cilium/tetragon

install/kubernetes/templates/_container_tetragon.tpl, install/kubernetes/templates/daemonset.yaml
It's not needed, there is nothing populating this directory.
=> helm: Don't mount /var/lib/tetragon/metadata

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/README.md, install/kubernetes/templates/_helpers.tpl, install/kubernetes/templates/clusterrolebinding.yml, install/kubernetes/templates/daemonset.yaml, install/kubernetes/templates/operator_clusterrolebinding.yaml, install/kubernetes/templates/operator_deployment.yaml, install/kubernetes/templates/operator_serviceaccount.yaml, install/kubernetes/templates/serviceaccount.yaml, install/kubernetes/values.yaml
I have added multiple configuration options for the Tetragon Operator Deployment, which are often crucial for enterprise-grade deployments that need to happen within certain security boundaries.
According to my current understanding, this should not break anything for existing users. The only chance I see a breakage happen is when somebody already configured `.Values.serviceAccount.name` in the past. The thing is, this value was never considered, and the SA was simply named `{{ .Release.Name }}` or `{{ .Release.Name }}-operator-service-account`. With this change, it would suddenly be considered for the actual SA naming.
- helm: Added extraVolumes support for the Tetragon Operator
- helm: Added extra labels for the Tetragon Operator Deployment and Pods
- helm: Added configurable …
=> Helm: Added various configuration options for the Tetragon Operator Deployment

.github/workflows/gotests.yml, .github/workflows/run-e2e-tests.yaml, contrib/verify/verify.sh
The CNCF signed a contract with Actuated to provide free arm64 runners
to CNCF project: see https://actuated.dev/blog/arm-ci-cncf-ampere.
After some trial and error we managed to compile a kernel for the
runners using Firecracker that works with BPF and especially Tetragon.
Only limitation is that they are running 5.10 for now and there is no
nested virtualization. But good news is that we can get more CPU and
more RAM for free!
Note: I know that I didn't change the buildjet runner for `Packages e2e Tests / standalone-tests (buildjet-2vcpu-ubuntu-2204-arm, arm64, arm64)`, but this should be eventually removed as `make tarball` now work with cross-compilation and we should not need a native runner here.
=> ci: replace buildjet arm64 runners with actuated ones

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/README.md, install/kubernetes/templates/operator_deployment.yaml, install/kubernetes/templates/operator_service.yaml, install/kubernetes/test.sh, install/kubernetes/values.yaml, operator/cmd/serve/serve.go
hey team, I'm new here so please correct me if I'm missing somewhere
This will fix the issue https://github.com/cilium/tetragon/issues/1778
```release-note
Add a Kubernetes service exposing Tetragon Operator metrics. Make the operator metrics port configurable via Helm values and change the default to 2113.
```
=> helm: adding optional to expose tetragon-operator metrics

.golangci.yml, pkg/btf/validation.go, pkg/reader/network/network.go, pkg/syscallinfo/syscallinfo.go
Makezero is a linter to ensure that slices are not initialized with non-zero length. Since in Go, we most of the time use append on the slice, initializing it with non-zero length can tend to create a slice full of zero that will clobber the beginning of the slice.
In the bug fixed here, we created a list with 300+ zeros and then append after them, only to skip the zero in the calling method. Usually we want to prealloc the slice with a capacity of len but a length of 0, i.e. replace make([]int, len(nums)) with make([]int, 0, len(nums)).  See more info here https://github.com/ashanbrown/makezero.
=> linters: add makezero and fix a related bug

.github/renovate.json5, .github/workflows/build-clang-image.yaml, .github/workflows/build-images-ci.yml, .github/workflows/build-images-releases.yml, .github/workflows/generated-files.yaml, .github/workflows/gotests.yml, .github/workflows/lint-codeql.yml, .github/workflows/podinfo-test.yaml, .github/workflows/run-e2e-tests.yaml, .github/workflows/static-checks.yaml, .github/workflows/vmtests.yml
This reverts commit https://github.com/cilium/tetragon/commit/dd5ddc26585820afd0e4b84a2675e482c8dae236.
This was a good idea but https://github.com/cilium/tetragon/pull/1748 impacts this as we no longer update the patch version in the go.mod directive. Thus the CI is running outdated Go versions.
=> workflows: add independent go-version for setup-go actions

pkg/bpf/detect.go, pkg/kernels/kernels.go, pkg/sensors/tracing/killer_test.go
currently we detect large programs with kernel version check (>=5.3.0)
but some kernels (rhel) have many backports on top of older versions
adding large program feature check and using it to load large programs
=> tetragon: Detect large program with feature check

.github/workflows/check-links-pr.yaml
Tries to fix #1858
PR link checker was checking the GitHub links against main which might not exist when the PR has not been merged on main yet.
Unfortunately `lychee --remap` just searched and replaced and could not just replace some part of the URL so I did good old find/sed commands.
=> workflow: fix PR link checker to check local branch links

pkg/kernels/kernels.go, pkg/kernels/kernels_test.go
=> pkg/kernels: Fix large patch numbers

pkg/testutils/path.go
We just need to skip the path on the right of vendor.
=> testutils: Fix RepoRootPath when Tetragon is vendored

pkg/fieldfilters/fields.go, pkg/fieldfilters/fields_test.go
We had a regression after some fieldfilter bug fixes and performance optimizations that caused top-level information to be missing from events when field filters are applied. The fix here is to make sure that we are setting non-event fields in the destination struct. Apply the fix and add a unit test to check for future regressions.
```release-note
Fix a regression related to field filters that could cause top-level information to be missing from events.
```
=> fieldfilters: fix regression with missing top-level info and add test

pkg/fieldfilters/fields.go, pkg/fieldfilters/fields_test.go
[upstream commit 651fcf1818a5271eef93a0a8e33104b778a22205]
We had a regression after some fieldfilter bug fixes and performance optimizations that caused top-level information to be missing from events when field filters are applied. The fix here is to make sure that we are setting non-event fields in the destination struct. Apply the fix and add a unit test to check for future regressions.
Backport of #1882.
```release-note
Fix a regression related to field filters that could cause top-level information to be missing from events.
```
=> backports/v1.0: fieldfilters: fix regression with missing top-level info and add test

docs/layouts/partials/hooks/head-end.html
In order to have visibility and improve our documentation, I would like to add an open-source analytic tool: GoatCounter (see https://www.goatcounter.com/) to the documentation website.
GoatCounter is an open source web analytics platform available as a free donation-supported hosted service or self-hosted app. It aims to offer easy to use and meaningful privacy-friendly web analytics as an alternative to Google Analytics or Matomo.
It's privacy-aware; it doesn’t track users with unique identifiers and doesn't need a GDPR notice. Fine-grained control over which data is collected.
For now we use the non-commercial free hosted solution but we can consider donating or self-hosting if this is useful for us in the future.
=> docs: add privacy-aware GoatCounter analytics

install/kubernetes/tetragon/templates/_container_tetragon.tpl, install/kubernetes/tetragon/templates/_extensions.tpl, install/kubernetes/tetragon/templates/daemonset.yaml, install/kubernetes/tetragon/templates/tetragon_configmap.yaml
The goal is to make it easy to build custom distributions of Tetragon Helm chart.
=> helm: Add extensions templates

bpf/process/bpf_exit.c, pkg/grpc/tracing/tracing.go, pkg/ksyms/ksyms.go, pkg/sensors/base/base.go, pkg/testutils/sensors/load.go
Adding support to use disassociate_ctty exit probe in case
acct_process is missing in kernel.
=> tetragon: Detect and use disassociate_ctty as exit probe if needed

.github/workflows/vmtests.yml
commit 8d35b43b3a680a3076108b9f573a3ccf7c386881 was trying to delete the artifact using a hack (uploading an empty artifact with the same name, overriding it). Action/upload-artifact v4 broke that, making impossible to override existing artifacts. Some GitHub actions exists for this particular need and are maintained to follow actions/upload-artifact updates, let's try them.
=> workflows/vmtests: delete artifacts if run was successful

tests/e2e/helpers/grpc/grpc.go
renaming ```waitForTracingPolicy``` to ```ensureTracingPolicy``` because that is what it does and the waiting part is done by ```WaitForTracingPolicy``` so we could import ```ensureTracingPolicy``` to other packages in future without confusions
```release-note
Rename a function in e2e test helpers.
```
=> chore: rename TracingPolicy function

Makefile, docs/content/en/docs/contribution-guide/development-setup.md
Compile all commands listed for kind setup into one make command via ```make kind-setup``` and updated docs accordingly and removes minikube setup as there is neglible chances that someone will use it over kind and we have to make our docs clean
Closes #1849
=> Improve local k8s developer experience

pkg/bpf/detect.go
We can outsource some of our detection code to ebpf/cilium,
some we need to keep so far, because there's no support for that yet.
=> tetragon: Use cilium/ebpf detection

.github/workflows/build-clang-image.yaml, .github/workflows/build-images-ci.yml, .github/workflows/build-images-releases.yml, .github/workflows/gotests.yml, .github/workflows/run-e2e-tests.yaml, .github/workflows/vmtests.yml
Temporary fix for https://github.com/cilium/tetragon/issues/1927.
This partially reverts commit eb4d9a2ba435f785c7f29d5f291eaa8d58ad22e6. Downgrade waiting for actions/download-artifact#249 being resolved.
=> Revert "chore(deps): update all github action artifacts to v4"

.github/workflows/build-clang-image.yaml, .github/workflows/build-images-ci.yml, .github/workflows/build-images-releases.yml
Fixes https://github.com/cilium/tetragon/issues/1894.
We experienced #1894, which made me create kubernetes-sigs/bom#385 only to fix the race condition and realize that it was already patched but no release existed.
=> workflows: bump bom version for race condition fix

pkg/observer/observer_stats.go
In Tetragon, we have maps ending with `_stats` that contain metadata about the main maps. An example is that we have `execve_map` and `execve_map_stats` that contain errors and other information related to the `execve_map` map.
Now when we fail to open the `_stats` map, we just stop the loop and we can possibly miss to check for other maps. This patch changes that and tries for the next map.
Additionally, we do not try to collect stats for maps that already end up with `_stats` as this would result in `_stats_stats` map names.
=> metrics: Do not return when we cannot find a _stats map

.github/workflows/vmtests.yml, cmd/tetragon-vmtests-run/conf.go, cmd/tetragon-vmtests-run/main.go, cmd/tetragon-vmtests-run/run_tests.go, contrib/tester-progs/Makefile, pkg/vmtests/list.go, pkg/vmtests/vmtests.go
This PR aims address the fact that our killer sensor tests were always skipped and we never noticed.
The reason was that our CI kernels were not configured with `CONFIG_BPF_KPROBE_OVERRIDE`. This was fixed in https://github.com/cilium/little-vm-helper-images/pull/286.
Adding the new kernel images  (https://github.com/cilium/tetragon/pull/1907) lead to some test failures that are meant to be addressed in this PR. This was because our CI did not have a ia32 libc: this is addressed by compiling the ia32 program statically
The only way to note that the tests were skipped using` t.Skip()` was to execute them manually and check the logs. This is not ideal, so  this PR adds support to the vmtests for providing detailed results that show what tests are actually skipped and what tests are not.
We …
=> killer sensor: improve testing

tests/e2e/tests/policyfilter/policyfilter_test.go, tests/e2e/tests/skeleton/skeleton_test.go
This pr will unload the policy that was loaded during the test which ultimately closes the issue #1771
=> chore: unloadpolicy after load

pkg/tracepoint/tracepoint_test.go
The TestTracepointLoadFormat test in pkg/tracepoint checks that the tracepoint format we can read matches what we expect. Unfortunately, in some cases the format of the comm field is unpredictable (within a few options).
This commit changes the test to allow the different formats we have observed.
=> Tracepoint tests: Fix comm signedness and length check

bpf/process/types/basic.h, docs/content/en/docs/concepts/tracing-policy/selectors.md, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/selectors/kernel.go, pkg/selectors/kernel_test.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Post actions can have a rateLimit argument that specifies how often identical events from the same hook and thread are generated. There is a use case to rate limit per process or generally.
This commit introduces the rateLimitScope argument, to be used with rateLimit, to specify whether the rate limiting should be limited to the same thread, the same process, or globally, using values "thread" (default), "process", or "global".
```release-note
Add rateLimitScope to control what rateLimit applies to.
```
=> Actions: add rateLimitScope

bpf/lib/bpf_task.h, bpf/lib/process.h, bpf/process/bpf_execve_event.c
Fix for https://github.com/cilium/tetragon/issues/1741
This PR changes how we read the binary path at `execve` time. We now read `exe` from the `task_struct` instead of relying upon the tracepoint argument that was just the path given to `execve` (thus possibly relative). This was an issue since `matchBinaries` could be avoided using relative links instead of absolute ones at `execve`.
In addition to this, we could also use this `exe` value for the binary path of the event. We also previously used the argument of `execve`, being possibly relative and corrected in userspace using `cwd`, but also possibly a symlink. This would thus introduce a user-facing change: tetragon events will now contain the canonical binary path while previously it could have been a symlink.
Without that user might …
=> bpf: read and copy proc exe at execve for matchBinaries

.github/workflows/bpf-unit-tests.yml, .github/workflows/gotests.yml, .github/workflows/vmtests.yml
Some workflows started to fail because the cache was invalid: some package was updated and it was still trying to install the previous one, then missing.
See [an example of workflow failing because of this](https://github.com/cilium/tetragon/actions/runs/7495570080/job/20405920129).
=> workflows: add apt-get update before installs

Dockerfile
This should fix #1606.
Previous version failed to build on old kernels, see issue libbpf/bpftool#17 for more information.
=> Dockerfile: bump bpftool revision to 7.3.0

docs/hugo.toml
User ioandr pointed out that those variables were not under the [params] section and thus not working in the shortcodes anymore.
Thanks a lot @ioandr! I messed up this.
=> docs: fix invalid site param in hugo.toml

pkg/eventcache/eventcache.go, pkg/grpc/exec/exec.go, pkg/metrics/errormetrics/errormetrics.go, pkg/metrics/eventcachemetrics/eventcachemetrics.go
This pr Closes #1787 .
Where I have considered the thershold to be ```CacheStrikes``` value to increment the metrics ```event_cache_process_info_failed``` && ```event_cache_parent_info_failed```  and not on all retries . On retries we will inc the values 
```event_cache_parent_info_retry``` and ```event_cache_process_info_retry```
=> handling metrics correctly

pkg/watcher/crd/watcher.go
When we update a tracing policy (i.e. apply a policy with the same name as an existing policy), we check if the new tracing policy has the same type (i.e. TracingPolicy or TracingPolicyNamespaced) as the old one.
Now we print the warning about type mismatch even if the types are the same. This patch fixes that by returing right after the actual update.
```release-notes
Do not print a warning during tracing policy updates when both old and new tracing policies have the same type.
```
=> crd: Fix type mismatch warning

bpf/Makefile, bpf/lib/bpf_task.h, bpf/process/bpf_killer.c, contrib/tester-progs/.gitignore, contrib/tester-progs/Makefile, contrib/tester-progs/go/getcpu/getcpu.go, pkg/bpf/detect.go, pkg/sensors/program/loader.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/killer.go, pkg/sensors/tracing/killer_amd64_test.go, pkg/sensors/tracing/killer_builder.go, pkg/sensors/tracing/killer_test.go, pkg/sensors/tracing/options.go
this PR is a followup to https://github.com/cilium/tetragon/pull/1948.
It adds `fmod_ret` support to the killer sensor and further improves testing.
```release-note
killer sensor: add fmod_ret support
```
=> killer sensor: add support for fmod_ret

pkg/observer/observer_stats.go
For the `tetragon_map_in_use_gauge` metric, we iterate through `sensors.AllMaps` to provide their size and errors.
Depending on the sensors that are loaded and the dependencies between them, `sensors.AllMaps` may have the same map name multiple times. This can cause errors like:
`collected metric "XXX" {...} was collected before with the same name and label values`
To avoid that we keep a map and process each map only once.
```release-notes
Process each map only once during the calculation of tetragon_map_in_use_gauge.
```
=> metrics: Do not process the same map multiple times

docs/content/en/docs/concepts/tracing-policy/selectors.md
This PR fixes wrong naming for `followForks`.
=> docs: fix property naming

.github/lychee.toml
Fixes #1995.
Broken link detector was trigger no the http://localhost:1313/docs link in the guide, which needs being excluded. On the other side we need to exclude only this explicit link since localhost:1313 base is used during local CI links checking.
=> docs: link checker config for docs contributor guide

cmd/tetragon/main.go, docs/content/en/docs/reference/helm-chart.md, docs/data/tetragon_flags.yaml, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/operator_configmap.yaml, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml, operator/cmd/common/common.go, operator/crd/crd.go, operator/option/config.go, pkg/option/config.go, pkg/option/flags.go
Fixes #1880
- new flag `enable-tracing-policy-crd` was added and enabled by default
- new flag `skip-tracing-policy-crd` was added and disabled by default
- two flags above were added into configmaps and values file
=> tetragon: run Tetragon without access to CRD

api/v1/README.md, api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go, api/v1/tetragon/tetragon.pb.go, api/v1/tetragon/tetragon.pb.json.go, api/v1/tetragon/tetragon.proto, bpf/lib/process.h, bpf/process/bpf_execve_bprm_commit_creds.c, bpf/process/bpf_execve_event.c, docs/content/en/docs/reference/grpc-api.md, pkg/api/processapi/processapi.go, pkg/process/process.go, pkg/sensors/exec/exec.go, pkg/sensors/exec/exec_test.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Detect execution of anonymous binaries, these are binaries that are not linked on a filesystem, where nlink is zero.
1. An anonymous shared memory file
https://man7.org/linux/man-pages/man7/shm_overview.7.html.
2. An anonymous file obtained with memfd API
https://man7.org/linux/man-pages/man2/memfd_create.2.html.
3. Or it was deleted from the file system.
```
"process_exec": {
"process": {
"binary_properties": {
"file": {
"inode": {
"number": "182698",
"links": 0
}
}
}
}
}
```
=> tetragon: detect execve of anonymous binaries

pkg/api/processapi/processapi.go, pkg/grpc/exec/exec.go, pkg/grpc/exec/exec_test_helper.go, pkg/grpc/process_manager_test.go, pkg/grpc/test/test.go, pkg/grpc/tracing/tracing.go, pkg/process/process.go, pkg/sensors/exec/cgroups_test.go, pkg/sensors/exec/exec.go, pkg/sensors/exec/exec_test.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/exec/threads_test.go, pkg/sensors/test/test.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/genericuprobe.go, pkg/sensors/tracing/kprobe_test.go, pkg/sensors/tracing/loader.go, pkg/sensors/tracing/policyfilter_test.go, pkg/testutils/perfring/perfring.go
Most sensors send data from kernel to user space via the perf ring buffer. They typically copy it into a struct, and copy it from that struct to another "Unix" struct. This series removes the second copy by replacing the duplicate members in the Unix struct with a pointer to the original struct. This should improve perf.
=> Perf: Remove extra copies of data from ring buffer

cmd/tetra/commands_linux.go, cmd/tetra/probe/probe.go, cmd/tetra/probe/probe_test.go, pkg/bpf/detect.go
This can typically be run in the context of Kubernetes with the following command:
```shell
kubectl run bpf-probe --image=quay.io/cilium/tetragon --privileged --restart=Never -it --rm --command -- tetra probe
```
=> tetra: add a probe command to probe BPF features 

.github/workflows/vmtests.yml, bpf/process/bpf_loader.c, pkg/sensors/tracing/loader.go
Making the loader sensor to send data for non excutable mmaps as well
to increase the chance that we might be able to read build id for the
binary at least from one of them.
As we can't sleep at the current loader probed function, we depend on
the page with build id being swapped-in, which might not be always the
case. By allowing to send build id data for mmap non executable mmap
events we increase the chance of getting the build id data for binary.
=> tetragon: Harden loader sensor

.github/workflows/packages-e2e-tests.yaml, Dockerfile.tarball, cmd/tetra/bugtool/bugtool.go, pkg/bugtool/bugtool.go, pkg/observer/observertesthelper/observer_test_helper.go
backport to v1.0 of https://github.com/cilium/tetragon/pull/2007/
=> backport/v1.0/: bugtool gops pprofheap

contrib/tester-progs/.gitignore
As agreed in PR #2031. W/o corresponding issue, because change is minor.
=> Git-ignore drop-privileges along with other binaries

.github/renovate.json5, Dockerfile.golangci-lint, Makefile
=> golangci-lint: remove Dockerfile.golangci-lint and update renovate config

.github/workflows/validate-crd.yaml
This pr Closes #1412  
If there is a change in the crd yaml files and if ```CustomResourceDefinitionSchemaVersion``` value is not updated accordingly in ```pkg/k8s/apis/cilium.io/v1alpha1/version.go``` or vice-versa . The CI will fail
How to test locally ?
follow this https://github.com/cilium/tetragon/pull/1919#pullrequestreview-1811074405 
for the event.json thing set it as 
```{
"pull_request": {
"head": {
"ref": "test-dev-2"
},
"base": {
"ref": "test-dev",
"sha":"58acf63b51238a93cb2d13cba90a80d6662d45bd"
}
}
}
```
you can replace the sha field by the latest commit on your base branch
here I added CustomResourceDefinitionSchemaVersion to ```pkg/k8s/apis/cilium.io/v1alpha1/version.go``` in both branches
and changed yaml files ```pkg/k8s/apis/cilium.io/v1alpha1/version.go``` and …
=> feat: validate crd versions

pkg/tracingpolicy/generictracingpolicy.go, pkg/tracingpolicy/generictracingpolicy_test.go
Callers of `tracingpolicy.FromFile()` no longer receive highly specific errors, but a generic error, which can also be presented to end users. Callers of `tracingpolicy.FromJSON()` still receive the specific errors, and any generic error wraps a specific one.
The implementation is along the lines suggested by @mtardy in #2022. (Thanks for that input.) Please indicate if my use of `Panicf()` in `pkg/tracingpolicy/generictracingpolicy_test.go` is unwelcome.
BTW, it seems to me that `drop-privileges` should be added to `contrib/tester-progs/.gitignore`. I could create another PR for that, if applicable (plus an issue, if necessary for the trivial change).
Fixes #2022
Signed-off-by: Christian Hörtnagl <christian2@univie.ac.at>
=> validation: improve error message when failing to load a TracingPolicy

docs/content/en/docs/concepts/tracing-policy/selectors.md
The yaml file in the Stack Traces section contained a typo that has been fixed.
=> Fix typo on TracingPolicy Selectors Stack Traces documentation

.github/workflows/validate-crd.yaml
This is a really small fix just to make renovate able to update that dep.
=> workflows: use defined actions/checkout version in validate-crd.yaml

bpf/process/types/basic.h, pkg/sensors/tracing/genericuprobe.go
after talking to ebpf/cilium maintainers, new release might still take a while,
so pushing at least the generic refactoring change from https://github.com/cilium/tetragon/pull/1914 so it won't get old 
Separating  uprobe sensor setup into addUprobe function, that creates and sets up uprobeEntry object and createSingleUprobeSensor that creates the actual sensor progs/maps arrays.
This way we can easily add multi uprobe sensor create function in following changes.
=> tetragon: Factor uprobe sensor setup

pkg/metrics/policyfiltermetrics/policyfiltermetrics.go
This is a breaking change but this metric is for internal use only so it should not be too bad.
=> pkg/metrics: fix a typo in `policyfilter_metrics_total`

README.md
This section was removed by #2097.
=> README: remove the link to the tutorials in docs

bpf/process/bpf_killer.c, contrib/tester-progs/killer-tester.c, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/killer.go, pkg/sensors/tracing/killer_test.go
Forcing fmod_ret method for secrity_* functions.
Allow multiple killer sensors.
=> killer: assorted fixes

bpf/libbpf/bpf_tracing.h
With the latest from
https://github.com/torvalds/linux/blob/master/tools/lib/bpf/bpf_tracing.h.
This mainly allows us to use BPF_PROG and BPF_KPROBE macros with more than 5 arguments.
=> chore: Sync bpf_tracing.h

pkg/server/server.go
The Exporter.Start() implementation uses a WaitGroup to wait until the exporter is ready after launching it in a goroutine. Unfortunately, this WaitGroup never gets set to Done when we encounter an error while starting the exporter. This ultimately causes the Tetragon process to hang indefinitely. Fix the issue by simply calling readyWG.Done() when we encounter an error here.
```release-note
Fix a hang when the event exporter fails to start.
```
=> exporter: fix hang when exporter fails to start

pkg/encoder/encoder.go
We seem to be accessing Args[1] without a proper check. Add the check to avoid the panic.
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/cilium/tetragon/pkg/encoder.(*CompactEncoder).EventToString(0xc0001e0ec0, 0xc000894240)
/home/kkourt/src/tetragon/pkg/encoder/encoder.go:413 +0x4438
github.com/cilium/tetragon/pkg/encoder.(*CompactEncoder).Encode(0xc0001e0ec0, {0x1c83480?, 0xc000894240})
/home/kkourt/src/tetragon/pkg/encoder/encoder.go:110 +0x9f
github.com/cilium/tetragon/cmd/tetra/getevents.getEvents({0x204cd20, 0xc000388840}, {0x205ba68, 0xc0007aec00})
/home/kkourt/src/tetragon/cmd/tetra/getevents/getevents.go:150 +0x4dd
github.com/cilium/tetragon/cmd/tetra/common.CliRunErr(0x1e4b3c8, 0x1e4b3c0) …
=> tetra: avoid panic in the decoder

.github/renovate.json5
Remove the restrictions on matching only some Makefiles in renovate, since it would be nice to auto update additional docker dependencies as we add them.
=> renovate: match all Makefiles

pkg/grpc/process_manager_test.go, pkg/reader/node/node.go
This enables node_name field in the standalone (non-k8s) mode.
```release-note
Set events node_name field to the hostname in the standalone (non-k8s) mode.
```
=> Set node_name to hostname if NODE_NAME envvar is not found 

cmd/tetragon/main.go, pkg/bench/bench.go, pkg/metrics/eventmetrics/collector.go, pkg/observer/observer.go, pkg/observer/observer_stats.go, pkg/observer/observertesthelper/observer_test_helper.go, pkg/observer/program.go, pkg/option/config.go, pkg/sensors/collection.go, pkg/sensors/exec/exec.go, pkg/sensors/exec/exec_test.go, pkg/sensors/handler.go, pkg/sensors/load.go, pkg/sensors/manager.go, pkg/sensors/manager_test.go, pkg/sensors/program/cgroup/cgroup.go, pkg/sensors/program/loader.go, pkg/sensors/sensors.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generickprobe_test.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/genericuprobe.go, pkg/sensors/tracing/killer.go, pkg/sensors/tracing/kprobe_test.go, pkg/sensors/tracing/loader.go, pkg/testutils/sensors/sensors.go
Removing MapDir as preparation for loader refactoring,
it's not used, BpfDir is enough.
Fixes: https://github.com/cilium/tetragon/issues/527
=> tetragon: Remove superfluous MapDir

pkg/grpc/process_manager_test.go, pkg/reader/node/node.go
upstream commit: b2540c98022a6cf229f7a450478ebc37f8bb92e1
This enables node_name field in the standalone (non-k8s) mode.
=> backports/v0.10: Set node_name to hostname if NODE_NAME envvar is not found

cmd/tetragon/main.go, pkg/bench/bench.go, pkg/exporter/exporter.go, pkg/exporter/exporter_test.go, pkg/observer/observertesthelper/observer_test_helper.go
In general, when Tetragon encounters an error in its initial configuration, we expect the agent to fail to start and return an appriate error explaining the configuration issue. This is the case for many aspects of initialization, except for the exporter which currently just logs an error message. This is perplexing behaviour because users who want to configure an exporter generally consume Tetragon events that way, so it makes no sense to simply refuse to export events and merrily hum along. Fix this issue by returning an appropriate error when the exporter fails to start so we can bubble it up.
```release-note
Fail with an error when the event exporter fails to start.
```
=> exporter: return err when exporter fails to start

cmd/tetragon/main.go
Create the /run/tetragon runtime directory of Tetragon early, as we have
code that tries to lookup for that directory early and could report
errors. One example is when we are looking for pidfile of tetragon.
On host install we always keep the cgroup2 mount inside /run/tetragon
which pins the runtime directory on the host forever. We do not have
strict unmount logic as there is no harm in keeping another mirror
of cgroup2 inside /run/tetragon, so on Tetragon restarts the runtime
will always be there. But on first ever start the directory won't be
there and errors will be reported.
Fix this by having the mkdir as early as possible before anything else.
=> tetragon:trivial: create run dir early to avoid errors

.github/workflows/build-deploy-docs.yaml, .github/workflows/check-links-pr.yaml
It doesn't make sense to run the links checker on old release branches, since we only deploy docs from main.
=> ci: only check docs on PR to main

cmd/tetra/tracingpolicy/tracingpolicy.go
Protobuf requires every enum values to be unique and thus good practice is to start them with their enum type name as prefix. But this information can be removed when outputing the state in human format.
=> cmd/tetra: remove tp_state_ prefix in state in tp list

docs/content/en/docs/troubleshooting/_index.md
Improved doc around tetra bugtool, demo how to run it for all different installation k8s, container or systemd host installation.
Fixes https://github.com/cilium/tetragon/issues/1974 second tick box.
=> docs: tetragon troubleshoot improve

.github/workflows/build-images-releases.yml, .github/workflows/packages-e2e-tests.yaml, Makefile
=> tetragon:tarball: docker oci tarball fix

docs/content/en/docs/use-cases/process-lifecycle/privileged-execution.md, testdata/specs/testpod.yaml
Fixes: https://github.com/cilium/tetragon/issues/705
Signed-off-by: janvi01 [janvibajo1@gmail.com](mailto:janvibajo1@gmail.com)
=> docs: Privileged execution - use nginx instead of test-pod image

contrib/tester-progs/.gitignore
=> tetragon: Move enforcer-tester to .gitignore

bpf/process/bpf_generic_tracepoint.c, bpf/process/types/basic.h, pkg/generictypes/generictypes.go, pkg/grpc/tracing/tracing.go, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/selectors/kernel.go, pkg/selectors/kernel_test.go, pkg/sensors/tracing/generictracepoint.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Tracepoint strings are typically presented as data_loc char buffers. This series provides support for these when they hold strings. The second commit in this series standardises on a global set of types that we support. The third commit adds support for sock and skb types.
```release-note
Add support for data_loc char buffers.
```
=> Tracepoints: Add support for data_loc params and sock and skb types

pkg/k8s/Makefile
When we run make generate (or make crds nowadays). we get the following error:
```
WARNING: generate-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
Generating deepcopy funcs
Generating defaulters
WARNING: generate-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
```
This patch fixes that.
=> pkg/k8s: fix use of deprecated scripts

.github/renovate.json5, .github/workflows/vmtests.yml, cmd/tetragon-vmtests-run/conf.go, cmd/tetragon-vmtests-run/main.go, cmd/tetragon-vmtests-run/qemu.go
Also, fix renovate to pick up the next rhel8 images.
```release-notes
Add rhel8 kernel in vmtests.
```
=> ci: Add rhel8 kernel in vmtests

cmd/tetra/policyfilter/policyfilter.go, pkg/cgroups/fsscan/fsscan.go
* add a command for troubleshooting in the CLI
* fix an issue with container scanning in the file-system
```release-note
policyfilter: fix issue in container fs scanning under cri-o
```
=> policyfilter fix

pkg/sensors/load.go, pkg/sensors/sensors.go
The loadInstance() function loads a BPF program. It checks its type against the list of registered types and calls the appropriate handler if there is a match. Otherwise it tries to match against some known types. If that fails, it attempts to load the program as a kprobe.
If a new probe type is created but isn't registered (due to a typo, bug, or some other error), then the program will silently attempt to load as a kprobe, instead of using the supplied handler.
This commit makes a list of inbuilt probe types, and checks the program type against it (calling the appropriate handler if it is in the list), then checks the program type against the registered probe types (again, calling the appropriate handler if it exists). If both of these fail, it returns an error instead of silently …
=> Loading: Check if probe type is registered

bpf/include/api.h, bpf/include/vmlinux.h
Update our headers to include some of the more recent helpers for dynptr, timers and ringbuf usage.
=> tetragon: update bpf func mappings and add dynptr_*, timer*, ring*

Makefile
Replace crdgen by crds in phony targets since that is the one used to rebuild crds.
=> make: fix make crds and generate targets

bpf/include/api.h
Ringbuf return actually returns a pointer. Fix it.
=> tetragon: update bpf func reserve mapping for proper return value

docs/content/en/docs/installation/verify.md
Cosign documentation was migrated to https://docs.sigstore.dev/ in sigstore/cosign#822 and the markdown files were removed in sigstore/cosign#3587. Tetragon documentation was linking to one of this files. Now it's linking to https://docs.sigstore.dev/.
While here, remove `COSIGN_EXPERIMENTAL=1` from the cosign command for verifying keyless-signed images. It's not required since cosign v2.0.0 (see https://blog.sigstore.dev/cosign-2-0-released/).
Fixes #2209
=> docs: Fix cosign instructions

bpf/process/types/basic.h
The generic tracepoint program does not seem to work on GKE kernel 5.15.133+. This patch, modifies read_call_arg to call copy_path only once. The goal is to reduce the complexity by having the code for copy_path() being inlined only once.
The error on the GKE kernel is:
> loadInstance: opening collection 'bpf/objs/bpf_generic_tracepoint_v511.o' failed: program generic_tracepoint_process_event: load program: operation not supported: stack depth 256 (3214132 line(s) omitted)"
As well as:
>         from 22 to 1547: safe
>         1563: R0=inv0 R6=ctx(id=0,off=0,imm=0) R9=map_value(id=0,off=0,ks=4,vs=24304,imm=0) R10=fp0 fp-176=mmmm????
>         ; return generic_process_event(ctx, (struct bpf_map_def *)&tp_heap,
>         1563: (b7) r0 = 0
>         1564: R0_w=inv0 R6=ctx(id=0,off=0,imm=0) …
=> bpf: read_call_arg, copy_path once

bpf/lib/bpf_task.h
[ Upstream main branch a2251c15d972c38956 ]
Use real_parent instead of parent in case parent is overwritten.
=> tetragon:backports:v0.10: bpf improve how to read parent

docs/content/en/docs/concepts/tracing-policy/selectors.md
* a first stab of what was discussed on w/ @kevsecurity , @mtardy [on Slack](https://cilium.slack.com/archives/C03EV7KJPJ9/p1710333769365779)
=> documentation: more detailed description re FollowFD/UnfollowFD

tests/e2e/helpers/grpc/grpc.go
When we check whether a policy is there, having it appear in the list is not enough. We need to check that its state is enabled and that there are no errors.
=> e2e: check policy state

pkg/bpf/perf_linux.go
We have ebpf.PossibleCPU for getting the number of possible cpus, let's use it.
=> tetragon: Implement bpf.GetNumPossibleCPUs through cilium/ebpf library

.github/workflows/check-links-pr.yaml
Fixes #2233 
Previously the PR link checker was checking any link, with this update it should just try the links added by the PR.
=> workflows: check only updated docs links in PRs

cmd/tetragon/main.go, pkg/bench/bench.go, pkg/observer/observer.go, pkg/observer/observertesthelper/observer_test_helper.go
Remove an unused field in the observer. It used to be the tracing policy file, which we now handle differently.
=> observer: remove unused field

cmd/tetragon/main.go, pkg/reader/proc/proc.go
=> tetragon: log current security context if any at startup

.github/workflows/static-checks.yaml
We've run into several instaces where binary files are accidentally checked into source control. Add a step to static-checks that will watch for this.
=> ci/static-checks: ensure no binary files are checked in

bpf/Makefile, bpf/process/bpf_generic_uprobe.c, docs/content/en/docs/concepts/tracing-policy/options.md, pkg/bpf/detect.go, pkg/option/flags.go, pkg/sensors/program/loader.go, pkg/sensors/program/program.go, pkg/sensors/tracing/genericuprobe.go, pkg/sensors/tracing/options.go, pkg/sensors/unloader/unloader.go
cilium/ebpf changes https://github.com/cilium/ebpf/pull/1269
=> tetragon: Add uprobe multi support

Makefile
On MacOS `uname -m` returns `arm64` whereas on Linux it returns `aarch64`.
Fixes https://github.com/cilium/tetragon/issues/2257
=> Makefile: add native build support for arm64 MacOS

examples/policylibrary/cves/cve-2024-3094-xz-ssh.yaml
Remove the new "message" field so users can run it on old versions
=> tracingpolicy: comment message field for older versions support

Makefile
It seems that it's a mistake from https://github.com/cilium/tetragon/commit/606aa9a67e77120e7968737ab51541da92692623#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R201. I was trying to rebase https://github.com/cilium/tetragon/pull/2175 and discovered the issue.
=> Makefile: fix a missing 'vendor' target in oci-hook

bpf/process/pfilter.h
My guess is some robot got carried away here. Lets optimize line breaks and spacing for humans. At least this human prefers to reduce line breaks and I love 80chars as much as the next person, but 81 chars is also fine.
=> tetragon: cleanup pfilter.h to make it readable

pkg/jsonchecker/jsonchecker.go, pkg/testutils/filenames.go
Some tests run JsonTestCheckExpect multiple times. Add a KeepExportFile
function to keep the export file and call it at the start of JsonTestCheckExpect.
=> jsonchecker: reset state of the export file

pkg/metrics/metricwithpod.go
This is done to prevent a memory leak in environments with a high pod churn or very long-running Tetragon agents.
Credits to Tam Mach for fixing a similar issue in cilium/cilium#31714.
=> metrics: Remove pod from the queue after deleting metrics

docs/content/en/docs/contribution-guide/development-setup.md
Fixes: #2293 
Current `docker run` doesn't work. ENTRYPOINT is set as `/usr/bin/tetragon` in [Dockerfile](https://github.com/cilium/tetragon/blob/86e210a6f9b818ef6e170f405bb19680ce63a2b5/Dockerfile#L83), so arguments for `docker run` are not needed.
Tetragon's container was created successfully via the new command:
```
$ docker run --name tetragon \
--rm -it -d --pid=host \
--cgroupns=host --privileged \
-v /sys/kernel/btf/vmlinux:/var/lib/tetragon/btf \
cilium/tetragon:latest
27016a8ee505aed876f9d7426e60d4ca347689ae56acd1f321192deae2b142f9
$ docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS          PORTS                       NAMES
27016a8ee505   cilium/tetragon:latest   "/usr/bin/tetragon"      3 seconds ago   Up 2 seconds …
```
=> docs: fix contribution-guide docker run

pkg/btf/validation.go
BTF validation fixes. See individual patches.
=> BTF validation fixes

docs/hugo.toml
Fixes: #2309
Current demo app url doesn't work in an ARM environment. It needs to be updated by following cilium repository's update: https://github.com/cilium/cilium/pull/31373. 
The new url worked in my ARM environment.
```
$ uname -a
Linux lima-tetragon-dev 5.15.0-101-generic #111-Ubuntu SMP Wed Mar 6 18:01:01 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
$ k create -f https://raw.githubusercontent.com/cilium/cilium/v1.15.3/examples/minikube/http-sw-app.yaml
service/deathstar created
deployment.apps/deathstar created
pod/tiefighter created
pod/xwing created
$ k get po
NAME                        READY   STATUS    RESTARTS   AGE
deathstar-b4b8ccfb5-kwz85   1/1     Running   0          12s
deathstar-b4b8ccfb5-z7pdj   1/1     Running   0          12s
tiefighter                  1/1 …
```
=> docs: update demo app url

pkg/server/server.go
[upstream commit: 44bd44c]
The Exporter.Start() implementation uses a WaitGroup to wait until the exporter is ready after launching it in a goroutine. Unfortunately, this WaitGroup never gets set to Done when we encounter an error while starting the exporter. This ultimately causes the Tetragon process to hang indefinitely. Fix the issue by simply calling readyWG.Done() when we encounter an error here.
```release-note
Fix a hang when the exporter fails to start.
```
=> backports/1.0: exporter: fix hang when exporter fails to start

.github/workflows/validate-crd.yaml
The previous version did not work with forks.
Use pull_request.{base,head}.sha for the diff of files to fix above issue.
Fixes: https://github.com/cilium/tetragon/issues/2255
=> validate-crd: use SHAs for diff

cmd/tetragon/main.go
Fix redaction filters log message to no longer log that an error occurred on success.
=> tetragon: fix redaction filters log message

pkg/filters/health_check.go, pkg/filters/health_check_test.go
This patch adds this by
1. filtering *.sh binaries in healthcheck filter
2. removing first argument in exec to correctly compare it to k8s pod's exec probe
Fixes: #2261
=> Filter out bash kubernetes healthchecks

Makefile
Using `$(MAKE)` will expand to the absolute path of `make` on the host, which can fail in docker if that path does not exist in the image.
Instead, just call `docker run ... make` without the $(MAKE) variable.
=> Makefile: Do not use $(MAKE) when calling make with `docker run`

pkg/k8s/Makefile, pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go
Commit a9c509f1f7c738bbeb1565f83eb9da70941a22ba replaced execution of deprecated scripts with
k8s.io/code-generator/kube_codegen.sh. However, kube_codegen.sh doesn't generate
code on its own, but rather defines helper functions. To migrate to
kube_codegen.sh we'll need to call these functions from another script.
Additionally, it'll change with version 1.30 of k8s libraries - that's why I
opted to simply revert the change for now. When k8s libraries are updated to
1.30, the code generation scripts should be updated too.
=> k8s: Fix CRDs Go code generation

docs/content/en/docs/use-cases/filename-access.md
Fixes: https://github.com/cilium/tetragon/issues/2334
A demo pod called `xwing` doesn't seem to have `vi` now. This may be because of the image update: https://github.com/cilium/tetragon/pull/2311, https://github.com/cilium/cilium/pull/31373.
So, I propose creating a new `busybox` pod instead of `xwing`.
=> docs: fix filename-access example

install/kubernetes/Makefile
Part of https://github.com/cilium/tetragon/issues/2234.
Update the following dockerfiles:
- docker.io/alpine/helm
- ghcr.io/yannh/kubeconform
- jnorwood/helm-docs
=> helm: use renovate to update dockerfiles in the Makefile

cmd/tetra/getevents/getevents.go
For some reason that I'm not sure I remember, I deprecated the singular
'--namespace', '--process' and '--pod' in https://github.com/cilium/tetragon/commit/23983ab2170650372558c2f73d78c80f77f37b3b. It's a bit annoying
to get those deprecation message when running the docs examples. Also, I
don't think that makes sense, especially when you are writing things
like:
tetra getevents --namespace value1 --namspace value2
We still keep both singular and plural working but advertize the
singular so that it's easier to type.
=> tetra: no longer show singular getevents cmd flags as deprecated 

.github/workflows/run-e2e-tests.yaml, Makefile
[E2e tests](https://github.com/cilium/tetragon/tree/main/tests/e2e/tests) currently have 3 packages that can run independently with each other
By split the test into 3 runners, we can reduce about ~50% CI time: https://github.com/Trung-DV/tetragon/actions/runs/8771741177
=> Tetragon e2e Test: Run e2e tests in parallel on multiple runners

cmd/tetragon/main.go, docs/content/en/docs/reference/metrics.md, pkg/exporter/exporter.go, pkg/exporter/metrics.go, pkg/metrics/metricsconfig/initmetrics.go
This is useful to figure out how much data is being exported and if the log pipeline is behind in processing the incoming events.
=> Add export metrics

install/kubernetes/tetragon/templates/operator_servicemonitor.yaml
Operator ServiceMonitor was defined as identical to the agent ServiceMonitor.
That's incorrect - it should have a different name and different selector, to
match operator Service, not the agent one. Let's fix it. While here, I also
changed the ServiceMonitor labels to match Tetragon operator.
=> helm: Fix name and selector in operator ServiceMonitor

.gitattributes, .github/workflows/lint-helm.yaml, docs/content/en/docs/reference/helm-chart.md, install/kubernetes/Makefile, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/crds-yaml/cilium.io_podinfo.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, install/kubernetes/tetragon/templates/crds.yaml, install/kubernetes/tetragon/templates/operator_configmap.yaml, install/kubernetes/tetragon/values.yaml
Introduce `crds.installMethod` Helm value which specifies how CRDs are installed: by Tetragon Operator (default), Helm, or not at all. Documented values are "operator", "helm" and "none", but any other value is treated as equivalent to "none". This also deprecates `tetragonOperator.skipCRDCreation` value which will be removed in Tetragon v1.2 release.
For Helm installation we don't use the Helm's "official" way of including CRDs in the crds directory, because this method:
* doesn't support upgrading CRDs
* enables CRDs creation by default
Instead, we opt to include CRDs alongside other resources if a Helm value is
set. A downside of this method is that when the chart is uninstalled, CRDs are
deleted too, leading to deletion of all Tetragon custom resources. To avoid
that, users can use …
=> helm: Add an option to install CRDs

Dockerfile.operator
It doesn't seem helpful, but it's being updated by Renovate, what causes extra PR and CI noise.
=> Dockerfile: Remove syntax annotation

.github/workflows/checkpatch.yaml
One issue checkpatch checks is whether the commit subject is not too long. Renovate commits tend to have long subjects for a reason (e.g. including the digest). Other checkpatch checks are either ignored or relevant only for BPF code, so it's fine to skip the entire workflow for Renovate PRs. If there are more checks added then we should revisit it (and maybe update cilium-checkpatch).
=> ci: Skip checkpatch for Renovate PRs

pkg/metrics/labelfilter.go, pkg/metrics/labels.go
LabelFilter.WithEnabledLabels behaved in the same way when passed nil or an empty slice - it disabled all labels. However, it's convenient to have a "no-op" option and just return a copy of the original filter. Let's do that when the passed slice is nil.
This change doesn't affect users. Currently the method is always called with a non-nil slice.
While here, I documented LabelFilter.WithEnabledLabels with edge cases. I also sneaked one convenience change - export fields in ProcessLabels struct.
=> metrics: Return a copy of LabelFilter in WithEnabledLabels(nil)

pkg/sensors/exec/procevents/proc_reader.go
Less confusion by unsetting auid of generated kernel pid 0.
=> proc: set auid to -1 for generated kernel pid 0

.github/workflows/run-e2e-tests.yaml, Makefile, api/vendor/github.com/cilium/tetragon/pkg/matchers/stringmatcher/stringmatcher.go, pkg/matchers/stringmatcher/stringmatcher.go, tests/e2e/tests/labels/labels_test.go
Migrate e2e labels test from `isovalent/jobs-app` to Opentelemetry demo app
- Update the labels checker
- remove `-p 1 -parallel 1` flags when running tests
Fixes: #1976, #2176
=> TestLabelsDemoApp: Replace isovalent/jobs-app by Opentelemetry demo app

bpf/lib/generic.h, bpf/process/bpf_execve_event.c
Users reported an issue on RHEL 9 with binary names being wrong.
Looking at the sched/sched_process_exec tracepoint we hook into:
```
$ cat /sys/kernel/debug/tracing/events/sched/sched_process_exec/format
name: sched_process_exec
ID: 310
format:
field:unsigned short common_type;       offset:0;       size:2; signed:0;
field:unsigned char common_flags;       offset:2;       size:1; signed:0;
field:unsigned char common_preempt_count;       offset:3;       size:1; signed:0;
field:int common_pid;   offset:4;       size:4; signed:1;
field:unsigned char common_preempt_lazy_count;  offset:8;       size:1; signed:0;
field:__data_loc char[] filename;       offset:12;      size:4; signed:1;
field:pid_t pid;        offset:16;      size:4; signed:1;
field:pid_t old_pid;    offset:20;      size:4; …
```
=> bpf: use CORE for execve hook

.github/workflows/run-e2e-tests.yaml
Currently, our six runners have to wait for Tetragon's images to be available before pulling. Therefore, I am moving this step to the preparation job to save time.
=> Wait for Tetragon's images exist before run test

operator/podinfo/podinfo_controller.go, operator/podinfo/podinfo_controller_test.go, vendor/k8s.io/apimachinery/pkg/util/rand/rand.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go, vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
Check if the pod has DeletionTimestamp field set before reconciling to avoid the situation where pod deletion gets stuck because Tetragon operator recreates PodInfo during pod deletion.
=> Don't create PodInfo if the pod is being deleted

pkg/sensors/tracing/kprobe_test.go
=> test: fix TestTraceKernelModule test

.github/renovate.json5
Some entries were missing from the v1.1 renovate config update (d7304ec722de2dae3fa558b213aeb95cdd06450b) and some unnecessary updates were showing up from renovate.
This should reduce by a lot the number of PRs created by renovate on v1.1.
Should we update the release checklist to make this more explicit?
=> renovate: add v1.1 in stable branches in config

pkg/testutils/sensors/load.go
I'm debugging some experimental code, but discovered that the utils code for testing map and prog bindings fails to work when maps and programs share maps. We will need this to resolve cases where we reload a new policy and want to do atomic updates using a shared map so lets just fix it now.
=> tetragon: debugging map duplication extending prog/map testers

.github/ISSUE_TEMPLATE/release_template.md
Releasing multiple modules from the same repo, requires tags for each. Add a tag for the api/ modules in the release process.
=> release_template: also tag API module

.github/pull_request_template.md
Fixes: #1929
Adds a pull request template to provide information on how to contribute to Tetragon.
=> Create a Pull Request Template for the project 

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/_container_tetragon.tpl, install/kubernetes/tetragon/values.yaml
Add tetragon.livenessProbe Helm value that overrides the default liveness probe for the tetragon container. For example, to use grpc probe, you can specify tetragon.livenessProbe Helm value like this:
tetragon:
livenessProbe:
grpc:
port: 54321
=> helm: Add tetragon.livenessProbe value

bpf/lib/generic.h, bpf/process/bpf_execve_event.c
[ upstream commit 8100230e93aa5d86b9a8ca863e1d1e165d06ce53 ]
Users reported an issue on RHEL 9 with binary names being wrong.
Looking at the sched/sched_process_exec tracepoint we hook into:
$ cat /sys/kernel/debug/tracing/events/sched/sched_process_exec/format
name: sched_process_exec
ID: 310
format:
field:unsigned short common_type;       offset:0;       size:2; signed:0;
field:unsigned char common_flags;       offset:2;       size:1; signed:0;
field:unsigned char common_preempt_count;       offset:3;       size:1; signed:0;
field:int common_pid;   offset:4;       size:4; signed:1;
field:unsigned char common_preempt_lazy_count;  offset:8;       size:1; signed:0;
field:__data_loc char[] filename;       offset:12;      size:4; signed:1;
field:pid_t pid;        offset:16;      size:4; …
=> [v1.1] backport: bpf: use CORE for execve hook

pkg/sensors/handler.go
This commit fixes the issue where the error
message was added to the status even if the
error was nil.
Please ensure your pull request adheres to the following guidelines:
description and a `Fixes: #XXX` line if the commit addresses a particular
GitHub issue.
Fixes: #issue-number
```release-note
```
=> TracingPolicyStatus: only add error if err not nil

bpf/include/api.h
Experimenting with different ways to get timestamps I figured rather than carry along a debug patch its easy enough to just add a bunch of helpers here.
Organize them slightly by type.
=> tetragon: organize bpf helpers and add a few time related helpers

.github/pull_request_template.md, docs/content/en/docs/contribution-guide/development-setup.md, docs/content/en/docs/contribution-guide/making-changes.md, docs/content/en/docs/contribution-guide/submitting-a-pull-request.md
Tetragon contribution guide consists of a few docs pages and a PR template,
each one containing a list of steps. Many of the steps (e.g. testing or commit
message guidelines) are duplicated between lists. This is hard to follow and
hard to maintain (different pages can easily become conflicting).
I refactored the contribution guide so that it's (hopefully) easier to follow:
* "Making changes" page has simplified build & test instructions. I added a step
about code generation and removed a step about commits.
* "Submitting a pull request" page covers everything related to commits (in
a dedicated section) and basic info about pull request review. I added a link
to the main contribution guide and removed other steps, which were
duplicating the previous guides
* Checklist in the PR template …
=> docs: Improve contribution guide & PR template

pkg/btf/validation.go
btf.TypeByName() could return ErrMultipleMatches if btf includes multiple matches.
=> btf: print original error returned by ebpf btf.TypeByName()

cmd/tetragon-vmtests-run/conf.go, cmd/tetragon-vmtests-run/image.go, cmd/tetragon-vmtests-run/main.go, cmd/tetragon-vmtests-run/qemu.go, tests/vmtests/fetch-data.sh
Deduplicate some codes shared between vmtests and LVH:
- inject LVH runner.RunConf into vmtests RunConf and reuse existing LVH configuration fields.
- use LVH runner.BuildQemuArgs along with custom vmtests logic.
- removes the support for HVF, we would need to put it in LVH to get this again but I don't think this is used nowadays.
This is mainly so that we benefit from the arm64 support as LVH was recently updated to support it.
=> vmtests: deduplicating code using LVH library for arm64 support

.github/renovate.json5
Since we now use the toolchain as the version we should use because of #2425, renovate need to pick up the toolchain version for its Go install fix.
Trying to fix the issue in https://github.com/cilium/tetragon/pull/2490.
=> renovate: switch to get Go version from toolchain directive

.github/ISSUE_TEMPLATE/release_template.md, .github/pull_request_template.md, contrib/update-upgrade-notes.sh, contrib/upgrade-notes/latest.md, contrib/upgrade-notes/template.md, contrib/upgrade-notes/v1.1.0.md, docs/content/en/docs/contribution-guide/release-notes.md
Documenting changes introduced in 1.1 release was not a trivial task, so here I'm attempting to improve the process around release & upgrade notes. There are two different aspects:
1. I documented the existing practices for `release-note` blurbs and labels in PRs (see `docs/content/en/docs/contribution-guide/release-notes.md`).
2. I want to introduce a practice of writing separate upgrade notes for changes that require attention when upgrading Tetragon. Initially I wanted to introduce a dedicated docs page, similar to the [one from Cilium](https://docs.cilium.io/en/latest/operations/upgrade/#version-specific-notes). However, I think keeping upgrade notes together with the regular release notes is a better solution, as many users at least skim through the release notes and Tetragon upgrade …
=> Document release notes process & introduce upgrade notes

contrib/update-upgrade-notes.sh, contrib/upgrade-notes/latest.md, contrib/upgrade-notes/template.md, contrib/upgrade-notes/v1.1.0.md
Backporting two commits from #2487 so that we can have upgrade notes for v1.1.x releases.
=> [v1.1] Introduce upgrade notes

pkg/btf/validation.go
[ OSS upstream 0636406b5f02afcc ]
TypeByName() can fail with ErrMultipleMatches if we have multiple candidates. If so, let's try again and take first match as it is.
This can help solve our immediate issue of having multiple definitions per system calls, however the long-term fix would be to iterate over all candidate, match their proto and arguments definitions, then attach to the corresponding ones.
Example output:
time="2024-05-31T15:53:17+01:00" level=info msg="BTF includes '2' matched candidates on call \"__x64_sys_init_module\", using first one"
=> backport:v1.1: btf: take first entry on multiple function matches

docs/hugo.toml
This PR fixes the path to `og:image` – open graph meta tags [preview](https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-2505--tetragon.netlify.app%2F)
=> fix: path to og:image

contrib/update-upgrade-notes.sh, contrib/upgrade-notes/latest.md, contrib/upgrade-notes/template.md
Backporting two commits from https://github.com/cilium/tetragon/pull/2487 so that we can have upgrade notes for v1.0.x releases.
=> [v1.0] Introduce upgrade notes

.github/renovate.json5
We recently switched to using the toolchain directive on the main which broke Go updates postUpgradeTasks on stable branches (see #2494 or commit bee5a74c9e233d379ff912f0db5182ac01f828af).
=> renovate: fix Go postUpgradeTasks for stable branches

docs/content/en/docs/resources/_index.md
More talks, blogs, labs and tutorials.
This patch updates the resources section of the docs by adding:
1. updated content around talks, blogs and video tutorials.
Fixes: #issue-number
```release-note
updates docs resources section with newer content
```
=> docs: updates resources section with newer content

.github/renovate.json5
Let's group the Go updates together regardless of the branch so that's it's applied to everything. And fix a mistake commited in f03102ca24c1172da539b31548d1ccba556a0d9e putting stables branches instead of main branch in a package rule.
=> renovate: group all go updates together and fix a rule

docs/content/en/docs/concepts/tracing-policy/selectors.md
Changed all occurrences of "killer" to enforcer in selectors.md
Fixes: #2517
=> Rename NotifyKiller to Enforcer in docs

pkg/sensors/program/map.go, pkg/sensors/tracing/enforcer.go, pkg/sensors/tracing/enforcer_test.go
When using fmod_ret, we need to load multiple programs -- one for each attach point we want to enforce.
In the current implementation, each program would use its own map which means that the enforcer notification worked only for a single program.
This patch fixes the code so that all programs use the same map. It also adds a test.
```release-note
enforcer: fix issue when using multiple calls with fmod_ret
```
=> enforcer: fix multiple prog issue with fmod_ret

pkg/sensors/program/map.go, pkg/sensors/tracing/enforcer.go, pkg/sensors/tracing/enforcer_test.go
backport of https://github.com/cilium/tetragon/pull/2524
```release-note
enforcer: fix issue when using multiple calls with fmod_ret
```
=> [v1.1] enforcer backport

.github/lychee.toml
=> docs: ignore some index.html link from link checker

Makefile
cf0a49dcbb6ddc6ab0617aef9e16a492d7804c5c introduced a tag for the api module. This, however, breaks the release process because the tarball image generation uses the api version and fails. Exclude the api tags from the version.
=> Makefile: exclude api tags from version

Makefile
=> [v1.1] Makefile: exclude api tags from version

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go
We stopped on a stack trace map that has a max_entries of 32768, which is 64 bits pointers * PERF_MAX_STACK_DEPTH (which is fixed at 127 for now), so 127*64/8=1016 bytes per entry + it's key_size of 32 bits (4 bytes) so 1020 bytes per entry. So 1020 * 32768 = 33,423,360 bytes. From bpftool, this map has a total bytes_memlock of 34,079,040 bytes. So for each stack trace map we load, we had 34MB of kernel memory, and it happened to be loaded many times when we were loading any tracing policy.
Since the map is used by the generic program, the loader will allocate the memory needed for the map even if we don't create a reference from the agent side and create an anonymous map. So we end up allocating a small map of max_entries 1 by default and resize it when the tracing policy actually …
=> pkg/sensors: reduce stack trace map memory footprint

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go
Backport of upstream commit 22510d98a16594b19b6ef8c68d3db5da5cb0a8cc
We stopped on a stack trace map that has a max_entries of 32768, which is 64 bits pointers * PERF_MAX_STACK_DEPTH (which is fixed at 127 for now), so 127*64/8=1016 bytes per entry + it's key_size of 32 bits (4 bytes) so 1020 bytes per entry. So 1020 * 32768 = 33,423,360 bytes. From bpftool, this map has a total bytes_memlock of 34,079,040 bytes. So for each stack trace map we load, we had 34MB of kernel memory, and it happened to be loaded many times when we were loading any tracing policy.
Since the map is used by the generic program, the loader will allocate the memory needed for the map even if we don't create a reference from the agent side and create an anonymous map. So we end up allocating a small map of …
=> [backport v1.1] pkg/sensors: reduce stack trace map memory footprint

bpf/process/bpf_rate.h, cmd/tetragon/main.go, pkg/observer/observertesthelper/observer_test_helper.go, pkg/sensors/base/base.go
It's not needed when the feature is disabled.
=> tetragon: Limit max entries of cgroup_rate_map when it's not used

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_test.go
For every ratelimit map loaded, we add ~10MB of kernel memory, and each kprobe added was adding a ratelimit map. We now only load that map if the user used the rateLimit field in a matchActions to reduce the memory footprint of this feature when unused.
```release-note
Reduce the kernel memory footprint (accounted by the cgroup memory controller) of the ratelimit feature when unused (around ~10MB per kprobe).
```
=> pkg/sensors: reduce ratelimit map memory footprint

pkg/syscallinfo/syscallnames_amd64.go
There seems to be a typo for SYS_OLDLSTAT. The name should be oldlstat rather than oldstat.
Looking at the i386/linux.go file:
```
$ grep -e 'OLDL\?STAT' ./pkg/syscallinfo/i386/linux.go
SYS_OLDSTAT                      = 18
SYS_OLDLSTAT                     = 84
```
Verified the number with:
```
$ cat oldlstat.c
int main(int argc, char **argv)
{
printf("SYS_oldlstat:%d\n", SYS_oldlstat);
return 0;
}
$ gcc -Wall -m32 oldlstat.c -o oldlstat
$ ./oldlstat
SYS_oldlstat:84
```
=> syscallinfo: fix typo for oldlstat

cmd/tetragon/main.go, pkg/cgrouprate/cgrouprate_test.go, pkg/observer/observertesthelper/observer_test_helper.go, pkg/sensors/base/base.go, pkg/sensors/load.go, pkg/sensors/program/loader.go, pkg/sensors/program/map.go, pkg/sensors/program/program.go, pkg/sensors/tracing/enforcer.go
Making it more straight forward to setup max entries for map shared between multiple programs.
=> tetragon: Factor the maps max entries setup

tests/e2e/install/tetragon/tetragon.go, tests/e2e/runners/runners.go
This PR uninstalls tetragon after each e2e test in order to remove any interference between tests.
```release-note
Uninstall Tetragon after each e2e test.
```
=> [ci/e2e] Uninstall Tetragon after each e2e test 

docs/content/en/docs/concepts/tracing-policy/hooks.md, docs/content/en/docs/policy-library/observability/_index.md
I made some improvements in the docs. Please let me know if any changes are required. I hope it helps, thanks!
1. Added missing closing quotes in some jq filter examples to correct syntax highlighting issues.
2. Fixed markdown syntax to eliminate warnings.
3. Fixed broken links for TrackSock and UntrackSock in hooks.md.
Fixes: #issue-number
=> docs: fix issues in jq filter examples and broken links

pkg/process/process.go
This field gets initialized but then never used. The variable is not exported so it does not impact other packages that depend on this package.
=> process: Remove ciliumState package variable

pkg/sensors/tracing/generickprobe.go
Commit 38ab0122a8d69368833457aad6d3d68858c0b561 pinned the ratelimit_map to the fs but used sensorPath instead pinPath since this is a per kprobe map and not a per sensor map.
=> pkg/sensors: fix for ratelimit_map wrong path pinning

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generictracepoint.go
~~The code is not great but it fixes the issue, maybe we can do it more elegantly idk~~
```release-note
Reduce the kernel memory footprint (accounted by the cgroup memory controller) of the ratelimit feature when unused (around ~11MB per kprobe).
```
=> pkg/sensors: reduce memory footprint of unused fdinstall maps and various fixes

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_test.go
Backport of https://github.com/cilium/tetragon/pull/2551 and https://github.com/cilium/tetragon/pull/2583
```release-note
Reduce the kernel memory footprint (accounted by the cgroup memory controller) of the ratelimit feature when unused (around ~10MB per kprobe).
```
=> [backport v1.1] pkg/sensors: reduce ratelimit map memory footprint

pkg/sensors/exec/exec.go
```release-note
tetragon:username: use login name instead of display name
```
=> backport:1.1:username: use login name instead of display name

api/v1/README.md, api/v1/tetragon/tetragon.pb.go, api/v1/tetragon/tetragon.proto, bpf/process/bpf_execve_event.c, contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto, docs/content/en/docs/reference/grpc-api.md, pkg/sensors/exec/exec_test.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Instead of reporting the real uid of the task that is the owner of the task, let's report the effective uid that is used to calculate the privileges of the current task when acting upon other objects. This allows to be compatible with 'ps' too.
See commits for further details.
=> process:bpf: report euid as the process.uid

api/v1/README.md, api/v1/tetragon/tetragon.pb.go, api/v1/tetragon/tetragon.proto, bpf/process/bpf_execve_event.c, contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto, docs/content/en/docs/reference/grpc-api.md, pkg/sensors/exec/exec_test.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
```release-note
tetragon: make uid equals euid fix
```
=> backport:1.1: tetragon: make uid equals euid fix

.github/workflows/build-images-releases.yml, .github/workflows/packages-e2e-tests.yaml, Makefile, api/v1/README.md, api/v1/tetragon/tetragon.pb.go, api/v1/tetragon/tetragon.proto, bpf/process/bpf_execve_event.c, contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto, docs/content/en/docs/reference/grpc-api.md, pkg/sensors/exec/exec_test.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
```release-note
tetragon: make uid equals euid fix
```
=>  backport:1.0: tetragon: make uid equals euid fix

docs/content/en/docs/reference/metrics.md, pkg/metrics/errormetrics/errormetrics.go, pkg/reader/namespace/namespace.go, pkg/reader/userdb/userdb.go, pkg/reader/userdb/userdb_test.go, pkg/sensors/exec/exec.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/exec/userinfo/userinfo.go, pkg/sensors/exec/userinfo/userinfo_test.go
```release-note
tetragon: resolve uid to username for exec events from /proc fs
```
=> tetragon:1.1: resolve uid to username for exec events from /proc fs

cmd/tetragon/main.go, pkg/option/flags.go
```release-note
tetragon: fail if --username-metadata receives invalid value
```
=> tetragon: fail if --username-metadata receives invalid value

docs/content/en/docs/reference/metrics.md, pkg/metrics/errormetrics/errormetrics.go, pkg/reader/namespace/namespace.go, pkg/sensors/exec/exec.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/exec/userinfo/userinfo.go, pkg/sensors/exec/userinfo/userinfo_test.go
```release-note
tetragon: resolve uid to username for exec events from /proc fs
```
=> tetragon: resolve uid to username for exec events from /proc fs

cmd/tetragon-metrics-docs/main.go, cmd/tetragon-metrics-docs/metricsmd/metricsmd.go
Introduce metricsmd package containing New function from cmd/tetragon-metrics-docs. This is done so that this function can be imported and reused by different commands.
=> tetragon-metrics-docs: Move New function to a separate package

Dockerfile
Now in the Dockerfile we do:
git clone --recurse-submodules https://github.com/libbpf/bpftool.git . && git checkout ${BPFTOOL_REV} which means that we fetch the libbpf submodule version of the main branch of bpftool and then we move to the appropriate commit that we need. After the checkout we also need to fetch the correct version of the submodules. This patch fixes that.
```release-note
Fix libbpf submodule checkout in bpftool when building the tetragon image.
```
=> Fix libbpf submodule checkout in bpftool

Dockerfile
[upstream commit 0235ed57252b9e03c68ea1dbc6ad0b1b6b5e6298]
Now in the Dockerfile we do:
git clone --recurse-submodules https://github.com/libbpf/bpftool.git . && git checkout ${BPFTOOL_REV} which means that we fetch the libbpf submodule version of the main branch of bpftool and then we move to the appropriate commit that we need. After the checkout we also need to fetch the correct version of the submodules. This patch fixes that.
=> [backport/v1.0] Fix libbpf submodule checkout in bpftool

Dockerfile
[upstream commit 0235ed57252b9e03c68ea1dbc6ad0b1b6b5e6298]
Now in the Dockerfile we do:
git clone --recurse-submodules https://github.com/libbpf/bpftool.git . && git checkout ${BPFTOOL_REV} which means that we fetch the libbpf submodule version of the main branch of bpftool and then we move to the appropriate commit that we need. After the checkout we also need to fetch the correct version of the submodules. This patch fixes that.
=> [backport/v1.1] Fix libbpf submodule checkout in bpftool

pkg/grpc/exec/kthread_init.go
When handling kthreads and we cannot find the parent, we print a warning, but we also call refinc on a nil parent which results in a panic in some cases.
This patch fixes that by avoiding the call of refinc in the case where we cannot find a kthread's parent.
Fixes: https://github.com/cilium/tetragon/issues/2614
```release-note
Do not increase the reference count when we cannot find a parent in kthreads.
```
=> [grpc/exec] Do not refinc on a nil parent

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go
[ upstream commit 22510d98a16594b19b6ef8c68d3db5da5cb0a8cc ] 
This is a slightly adapted version because #2145 was merged after v1.0
We stopped on a stack trace map that has a max_entries of 32768, which is 64 bits pointers * PERF_MAX_STACK_DEPTH (which is fixed at 127 for now), so 127*64/8=1016 bytes per entry + it's key_size of 32 bits (4 bytes) so 1020 bytes per entry. So 1020 * 32768 = 33,423,360 bytes. From bpftool, this map has a total bytes_memlock of 34,079,040 bytes. So for each stack trace map we load, we had 34MB of kernel memory, and it happened to be loaded many times when we were loading any tracing policy.
Since the map is used by the generic program, the loader will allocate the memory needed for the map even if we don't create a reference from the agent side and create an …
=> [backport v1.0] pkg/sensors: reduce stack trace map memory footprint

bpf/process/bpf_enforcer.h, pkg/sensors/tracing/enforcer.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/kprobe_maxentries_test.go, pkg/sensors/tracing/policyhandler.go, pkg/sensors/tracing/tracepoint_test.go
centralizing map entries configuration and adding tests
=> Reorg to factor mac entries setup and add a max entries test

bpf/process/bpf_execve_event.c, bpf/process/policy_filter.h, cmd/tetra/dump/dump.go, cmd/tetra/policyfilter/policyfilter.go, pkg/policyfilter/disabled.go, pkg/policyfilter/namespace.go, pkg/policyfilter/policyfilter.go, pkg/policyfilter/rthooks/rthooks.go, pkg/policyfilter/state.go, pkg/policyfilter/state_test.go, pkg/sensors/base/base.go, pkg/sensors/config/confmap/confmap.go, pkg/sensors/exec/config/config.go, pkg/sensors/tracing/policyfilter_test.go
Debugging BPF and some kernel functions I want to understand cgroup to namespace mappings at event side. This patch maintains a stable mapping between cgroups and human readable namespaces. The end goal is to filter out noisy namespaces from execs which will be follow up series. This is minimally useful as is.
To support this just extend the use of namespace filters from kprobe and tracepoints into a more general space where we can hook selectors.
=> tetragon: Add debug interface to track cgroups to workload/ns mappings

bpf/process/types/basic.h, pkg/sensors/tracing/kprobe_test.go
It's seems to me, that `case linux_binprm_type:` in [selector_arg_offset](https://github.com/cilium/tetragon/blob/main/bpf/process/types/basic.h#L1617) function is missing. [security_bprm_check.yaml](https://github.com/cilium/tetragon/blob/main/examples/tracingpolicy/security_bprm_check.yaml) from examples doesn't work.
=> bpf: fix missed linux_binprm_type in selector_arg_offset function

pkg/policyfilter/k8s_test.go, pkg/policyfilter/state.go, tests/vmtests/README.md
I've noticed a flake in the pkg.policyfilter.TestK8s
The test uses a fake k8s clientset, applies changes (e.g., adding or
removing pods), and then checks whether the policyfilter bpf map has the
expected contents.
We need to check the state after the pod informer callbacks have be
called. To do so, we maintain an operation count. We check that all
operations have been completed and then compare the contents of the
policyfilter map.
We seem to be increasing the counter first and then calling the
callback, however, which means that there is a small race where the
counts match but the bpf map contents have not been updated.
This patch increases the counters after the callback returns.
This seems to fix the issue in my local machine.
Also, two more minor updates.
Fixes: …
=> policyfiletr K8s test fix

contrib/k8s-get-tetragon-pod.sh
This is slightly modified script of https://raw.githubusercontent.com/cilium/cilium/main/contrib/k8s/k8s-get-cilium-pod.sh . This script helps user to identify tetragon pod running on the same node as a pod. 
Fixes: #issue-number
```release-note
```
=> identifies tetragon pod managing a pod

pkg/sensors/program/loader.go, pkg/sensors/program/program.go
This allows callers to re-write constants in eBPF programs before loading. Details on https://github.com/cilium/ebpf/discussions/795.
```release-note
Enable RewriteConstants for eBPF progs.
```
=> Provide a way to RewriteConstants in eBPF progs

docs/content/en/docs/reference/helm-chart.md, docs/content/en/docs/troubleshooting/_index.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml
Added a `debug` Helm flag for the Tetragon agent. Implemented via ConfigMap flag. The Tetragon DaemonSet will be restarted automatically after changing the debug value.
```release-note
helm, doc: Added debug Helm flag for the agent
```
=> helm, doc: Added debug Helm flag for the agent

Dockerfile, Dockerfile.dev, Dockerfile.operator, Dockerfile.rthooks, Dockerfile.tarball, Dockerfile.test
Silly changes to fix linter warnings:
```
FromAsCasing: 'as' and 'FROM' keywords' casing do not match
LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format
```
=> Fix linter warnings in Dockerfiles

docs/content/en/docs/use-cases/filename-access.md
This patch improves grammar, rewrites from passive to active voice, and fixes omissions and other snags in the filename access section of the docs.
(https://github.com/cilium/cilium/blob/main/USERS.md) in the Cilium repository.
This patch improves grammar, rewrites from passive to active voice, and fixes omissions and other snags in the filename access section of the docs.
=> docs: update filename access section of the docs

pkg/testutils/sensors/load.go
Adding some more tests discovered that its sometimes useful to explicitely list progs and maps for clarity. But, the testing utilities mark the test Fatal when this happens. Its not really an error to over specify a test so lets just allow it and have the merge logic skip it.
Without this its annoying to define tests for if multiple sensors work together. For example we have sensor tests with SensorX and another with SensorY if you want to test SensorX+SensorY looks good you get a Fatal just because logic doesn't know how to merge the  defintiion of Maps/Progs. Or you have to cut'n'paste it all over again.
=> tetragon: small improvement to testing merge sensors

docs/data/tetragon_flags.yaml, pkg/btf/btf.go, pkg/btf/validation.go, pkg/ksyms/ksyms.go, pkg/option/config.go, pkg/option/flags.go, pkg/sensors/program/loader.go, pkg/sensors/program/program.go, pkg/sensors/tracing/generickprobe.go
Now (as of 0.14.0) cilium/ebpf handles kmod BTFs natively (https://pkg.go.dev/github.com/cilium/ebpf#ProgramOptions.KernelModuleTypes).
Thus we can remove some duplicate code (i.e. mainly function AddModulesToSpec). This patch does this cleanup.
In Tetragon, we used kmod BTF in 2 places:
1. In order to attach to a function which is now handled automatically by cilium/ebpf.
2. In order to validate if the function name exists in the BTF and to check the argument types. In that case, we need to manually load the spec from the kmod that we care about. This is because cilium/ebpf checks (and loads the appropriate BTF) during the attach phase (i.e. …
=> [btf] Cleanup AddModulesToSpec 

pkg/sensors/program/loader.go
https://github.com/cilium/tetragon/commit/f44ce8cbb43d0ea3df532360a78328b863be85cf removed "github.com/cilium/tetragon/pkg/option" import from pkg/sensors/program/loader.go. This is merged without a rebase to latest master.
https://github.com/cilium/tetragon/commit/81a3e14f74cb1bcc02cfe5c503aa169d7e3b72dc adds a new dependancy on "github.com/cilium/tetragon/pkg/option" so removing that in the first commit breaks the build.
This patch fixes that.
```release-note
Fix a build issue in tetragon binary.
```
=> Fix tetragon build

.github/workflows/build-images-ci.yml, .github/workflows/build-images-releases.yml, .github/workflows/build-rthooks-images-releases.yml, Makefile
=> rthook images updates

install/kubernetes/tetragon/templates/operator_clusterrole.yaml
Don't give operator permissions to create CRDs if not needed 
Result of the change :
Reproduce the result:
create a local values.yaml file with CRD creation disabled:
```
tetragonOperator:
skipCRDCreation: true
```
and then run
and install Tetragon with using local Helm chart and your values.yaml file:
`./contrib/localdev/install-tetragon.sh --values values.yaml
`Then, check the operator ClusterRole using kubectl:
`kubectl get clusterrole tetragon-operator -oyaml`
Fixes: #2226
=> helm: Don't give operator permissions to create CRDs if not needed

Makefile
When generating Go code for proto API or k8s CRDs, we don't need to run vendoring for all modules before and after. It should be enough if we run vendoring only for the relevant module (api or pkg/k8s) before, and only for the main module after.
=> Makefile: Reduce the amount of vendoring calls

contrib/kind/install-tetragon.sh
1. Allow using custom Helm chart in install-tetragon.sh. A custom Helm chart can be passed via TETRAGON_KIND_HELM_CHART envvar. This is useful for testing released charts or custom distributions
2. Make install-tetragon.sh script runnable from anywhere. There were two issues when running script from a location different than the repo root:
- If running from a different git repo, the project root is detected incorrectly and the script fails to find config
- If passing a relative path to a values file, the script fails to find it
Ref https://github.com/cilium/tetragon/issues/1849
=> contrib/kind: Make install-tetragon.sh script more portable

docs/content/en/docs/installation/tetra-cli.md
Fix `tetra` CLI install directions for Windows
- Fix the `tetra` CLI install directions for Windows
=> Fix the `tetra` CLI install directions for Windows

pkg/multiplexer/multiplexer.go
We've occasionally been running into errors in e2e tests about invalid wire format messages and message size mismatches in protobuf. According to https://github.com/golang/protobuf/issues/1609, this is generally related to concurrency issues such as modifying a message during marshalling. Add a Clone() call before sending the event over the channel to mitigate this issue.
=> tests/e2e: clone proto event in rpcchecker

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_test.go, tests/vmtests/fetch-data.sh
Backport of https://github.com/cilium/tetragon/pull/2551 and https://github.com/cilium/tetragon/pull/2583
```release-note
Reduce the kernel memory footprint (accounted by the cgroup memory controller) of the ratelimit feature when unused (around ~10MB per kprobe).
```
=> [backport v1.0] pkg/sensors: reduce ratelimit map memory footprint

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generictracepoint.go
```release-note
Reduce the kernel memory footprint (accounted by the cgroup memory controller) of the fdinstall feature when unused (around ~11MB per kprobe).
```
=> [backport v1.1] pkg/sensors: reduce memory footprint of unused fdinstall maps and various fixes

bpf/process/bpf_fork.c, pkg/sensors/tracing/kprobe_threads_test.go
```release-note
store thread leader namespaces at fork and reduce false positives
```
=> tetragon: clone namespace improvements

bpf/process/bpf_generic_kprobe.c, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_maxentries_test.go
Some of the plumbing was already present. We now pin the map correctly.
```release-note
Reduce the kernel memory footprint (accounted by the cgroup v2 memory controller) of the override feature when unused (around ~3MB per kprobe).
```
=> pkg/sensors: reduce memory footprint of unused `override_tasks` maps

bpf/process/types/basic.h, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generictracepoint.go
```release-note
Reduce the kernel memory footprint (accounted by the cgroup memory controller) of the fdinstall feature when unused (around ~11MB per kprobe).
```
=> [backport v1.0] pkg/sensors: reduce memory footprint of unused fdinstall maps

bpf/process/bpf_fork.c, pkg/sensors/tracing/kprobe_threads_test.go
```release-note
store thread leader namespaces at fork and reduce false positives
```
=> backports:v1.1: clone ns fixes

bpf/process/bpf_fork.c, pkg/sensors/exec/exec_test.go, pkg/sensors/tracing/kprobe_threads_test.go
```release-note
store thread leader namespaces at fork and reduce false positives
```
=> backports:v1.0: clone ns fixes

bpf/process/bpf_generic_kprobe.c, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_maxentries_test.go
```release-note
Reduce the kernel memory footprint (accounted by the cgroup v2 memory controller) of the override feature when unused (around ~3MB per kprobe).
```
=> [backport v1.1] pkg/sensors: reduce memory footprint of unused `override_tasks` maps

bpf/process/bpf_generic_kprobe.c, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_maxentries_test.go
```release-note
Reduce the kernel memory footprint (accounted by the cgroup v2 memory controller) of the override feature when unused (around ~3MB per kprobe).
```
=> [backport v1.0] pkg/sensors: reduce memory footprint of unused `override_tasks` maps

pkg/sensors/tracing/policyhandler.go
For historic reasons, the tracing sensor has three different aspects: kprobes, tracepoints, and (recently) lsm hooks.
Also for historic reasons, we did not allow tracepoints and kprobes in the same policy.
With the addition of the LSM sensor
(8eb13e8abf2caddae083f09979adf5cebdc32e11), if a policy includes an lsm section together with either a kprobe section or a tracepoint section, the lsm section will be ignored.
This patch rejects policies that have more than one section of kprobes, tracepoints, and lsm hooks in the policy.
A better solution would be to decouple the tracing sensor, and create one sensor for kprobes, one for tracepoints, and one for lsm sensors. See: https://github.com/cilium/tetragon/issues/2706
CC: @anfedotoff
=> tracing: allow only one of kprobes/tracepoints/lsm

docs/content/en/docs/getting-started/execution.md, docs/content/en/docs/getting-started/install-docker.md, docs/content/en/docs/getting-started/install-k8s.md, examples/quickstart/docker-compose.yaml
Update Kubernetes install instructions to call out single node cluster assumption.
Update execution monitoring instructions to provide commands for using multi-node clusters.
Fixes #2680
=> fix(docs): update getting started instructions

docs/config/_default/hugo.toml, docs/config/production/hugo.toml, docs/layouts/partials/hooks/head-end.html, netlify.toml
Prevent development deployments of the documentation (preview on Netlify) to appear in search engines.
=> docs: use different config for development and production 

docs/content/en/docs/contribution-guide/development-setup.md
The Docker buildx plugin is required as part of make image - it may or not be installed by a users docker installation.
This commit adds it to the requirements.
Fixes https://github.com/cilium/tetragon/issues/2704
=> doc: Add docker-buildx to requirements

pkg/sensors/exec/exec.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/exec/userinfo/userinfo.go
tetragon: make resolving uid to username work with a processapi struct
=> tetragon: make resolving uid to username work with a processapi struct

.github/ISSUE_TEMPLATE/release_template.md
=> release_template: also push API tag

docs/content/en/docs/getting-started/execution.md
=> docs: use $POD env variable in multi node cmd

docs/content/en/docs/getting-started/enforcement.md, docs/content/en/docs/getting-started/file-events.md, docs/content/en/docs/getting-started/network.md, examples/quickstart/network_egress_cluster_enforce.yaml
This PR updates the Getting Started guide for consistency throughout all sections.
Here is the full changeset:
`execution.md`:
Remove language specifier for fenced codeblock.
`file-events.md`:
Add instructions for single-node and multi-node K8s clusters. Clean up Docker instructions.
Ensure consistent header levels.
Minor fixes in spelling and grammar.
`network.md`:
Add EKS, AKS instructions for getting service CIDR. Add instructions for single-node and multi-node K8s clusters. Ensure consistent header levels.
Minor fixes in spelling and grammar.
`enforcement.md`:
Reorganize content to improve flow.
Add EKS, AKS instructions for getting service CIDR. Add instructions for single-node and multi-node K8s clusters. Ensure consistent header levels.
Minor fixes in spelling and grammar.
No …
=> Update Getting Started guide

cmd/tetragon-metrics-docs/main.go, pkg/exporter/metrics.go, pkg/grpc/tracing/stats.go, pkg/metrics/cgroupratemetrics/cgroupratemetrics.go, pkg/metrics/errormetrics/errormetrics.go, pkg/metrics/eventcachemetrics/eventcachemetrics.go, pkg/metrics/eventmetrics/collector.go, pkg/metrics/eventmetrics/eventmetrics.go, pkg/metrics/kprobemetrics/kprobemetrics.go, pkg/metrics/labels.go, pkg/metrics/mapmetrics/mapmetrics.go, pkg/metrics/opcodemetrics/opcodemetrics.go, pkg/metrics/policyfiltermetrics/policyfiltermetrics.go, pkg/metrics/policystatemetrics/policystatemetrics.go, pkg/metrics/policystatemetrics/policystatemetrics_test.go, pkg/metrics/ratelimitmetrics/ratelimitmetrics.go, pkg/metrics/ringbufmetrics/ringbufmetrics.go, pkg/metrics/ringbufqueuemetrics/ringbufqueuemetrics.go, pkg/metrics/watchermetrics/watchermetrics.go, pkg/metricsconfig/healthmetrics.go, pkg/metricsconfig/initmetrics.go, pkg/observer/data_stats.go, pkg/observer/observer_stats.go, pkg/process/metrics.go, pkg/version/metrics.go
There are two things happening here:
1. Refactored custom collectors to use new helpers from pkg/metrics (commits 1-3). The main win here is simplifying how custom metrics are included in reference docs - we don't need to define a separate type and register it separately just for generating docs.
2. Defined a health metrics group (last commit). The idea is that in the future this group will have constrained cardinality and will be enabled by default (in contrast to another group with potentially high cardinality "debug" metrics). This commit only refactors the existing metrics initialization code to use the new framework. The health metrics group contains all metrics that were documented in the "health metrics" section, but in the future some of them will likely be moved to another group. …
=> Define health metrics group

contrib/kind/install-tetragon.sh
Fixes https://github.com/cilium/tetragon/issues/2731
When running `make kind-setup`, the tetragon images are not correctly pushed into kind, which leads to an error loopbackof in the cluster. It happens because of a formatting issue in the `./contrib/kind/install-tetragon.sh` with `yq`. Quotes are added and are unnecessary, which lead to this format in bash `"\"cilium/tetragon:latest\""`.
=> fix(install-tetragon.sh) fix 'kind load docker-image' in kind setup

pkg/encoder/encoder.go
Adding LSM events compact printing like it is done for kprobes in default case.
It seems that I forgot about `tetra` compact  printing for LSM events.  Maybe we can change ❓ symbol to something else to distinguish LSM hooks and kprobes.
=> tetra: LSM events compact print support

docs/content/en/docs/getting-started/enforcement.md, docs/content/en/docs/getting-started/file-events.md, docs/content/en/docs/getting-started/install-docker.md, docs/content/en/docs/getting-started/network.md
Users attempting to run docker-based commands from production images, eg. on the [Quick Local Docker Install](https://tetragon.io/docs/getting-started/install-docker/) page, will not have a local `:latest` copy, and will not be able to proceed through the getting started guide. This ensures that the latest tag available on quay.io is rendered in the docs
=> doc: use tag variable for docker-based commands

pkg/sensors/program/loader.go
https://github.com/cilium/tetragon/commit/0b090efc47f89f80336db39b365d54fa25979327 modifies LoadLSMProgram to be gelenic_lsm specific.
This patch adds LoadLSMProgramSimple that is generic enough to be used in other use cases.
```release-note
Add LoadLSMProgramSimple to load LSM programs.
```
=> Add LoadLSMProgramSimple

cmd/tetragon/main.go
This change will make Tetragon fail at startup if it finds out that another instance already created PID file and is still running. Previously it was only logging a warning.
Fixes #2672
=> tetragon: only allow single instance to run on a node

pkg/policyfilter/disabled.go, pkg/policyfilter/policyfilter.go, pkg/policyfilter/state.go
Debugging NSID/Pod mappings is a bit painful if something gets lost in BPF side. Provide a bit more data so we can lookup these entries and their human readable form at any point.
I'm using this to write a debug tool to show bpf maps and correlate with Tetragon data.
=> tetragon: extra debug info on nsid mappings

pkg/sensors/base/base.go, pkg/sensors/program/loader.go, pkg/sensors/program/program.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/genericlsm.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/genericuprobe.go
move tail call setup to the program layer and get rid of the tail call maps name checking
=> tetragon: Factor loader tailcall setup

bpf/include/compiler.h, bpf/lib/process.h, bpf/process/bpf_execve_event.c, bpf/process/bpf_process_event.h, bpf/process/types/basic.h, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/api/processapi/processapi.go, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/mbset/mbset.go, pkg/selectors/kernel.go, pkg/selectors/selectors.go, pkg/sensors/base/base.go, pkg/sensors/tracing/matchbinaries_follow_children_test.go, pkg/sensors/tracing/selectors.go, pkg/sensors/tracing/selectors_test.go, pkg/testutils/copyfile.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
This PR introduces a `FollowChildren:` attribute in `MatchBinaries`.
For now, only the `In` operator is supported but others can be added.
Another limitation is that only 64 of such sections are supported, but this number can also be increased.
```release-note
tracing: introduce FollowChildren attribute in MatchBinaries selector
```
=> matchBinaries: support followChildren

cmd/tetragon/main.go, docs/content/en/docs/reference/metrics.md, pkg/bpf/detect.go, pkg/metrics/kprobemetrics/collector.go, pkg/metrics/kprobemetrics/missed.go, pkg/metricsconfig/healthmetrics.go, pkg/sensors/base/base.go, pkg/sensors/load.go, pkg/sensors/program/loader.go, pkg/sensors/program/program.go, pkg/sensors/sensors.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_test.go
wip needs https://github.com/cilium/ebpf/pull/1295
=> Add missed probes metrics

.github/workflows/vmtests.yml, Makefile, bpf/lib/process.h, bpf/process/bpf_execve_event.c, bpf/process/bpf_process_event.h, bpf/tests/prepend_name_test.c, bpf/tests/prepend_name_test.go, pkg/sensors/tracing/kprobe_test.go
Fixes #2758
The matchBinaries Prefix operator fails to match a path longer than 256 chars because of the way we read the binary path. We use the exe of the process and walk the dentry from end to beginning. Thus if the path is too long, the buffer contains an incorrect start.
```release-note
Fix a bug related to the matchBinaries Prefix operator by increasing the buffer size used by our dentry walk. Now the matchBinaries Prefix operator can correctly trigger a match on any path above 255 chars.
```
=> bpf: bump prepend_name underlying buffer size 4096

pkg/metrics/kprobemetrics/collector.go
Some of the sensors do not set policy for program and it could
cause a problem with duplicate metrics values with empty policy.
Making the missed metrics groups by policy and attach point
values. Also storing only metrics that we managed to received
correctly (instead of storing them with zero values).
=> tetragon: Group missed metrics for policy and attach point

bpf/process/bpf_generic_retkprobe.c, bpf/process/bpf_generic_tracepoint.c, bpf/process/bpf_process_event.h, bpf/process/data_event.h, bpf/process/generic_calls.h, bpf/process/pfilter.h, bpf/process/types/basic.h
In some places, certainly because of copy-paste we use the inputs operands instead of the output operands section.
I also spotted some incorrect constraints, `r+` instead of `+r` for example.
=> bpf: fix incorrect inline asm output operands sections 

install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
55117f55586f26ee9a8fc5eca734456eb55faf54 Introduced a new field (followChildren), but it was not marked as optional which is a breaking change.
Make the field optional and false by default.
fixes: 55117f55586f26ee9a8fc5eca734456eb55faf54
Reported by @lambdanis https://github.com/cilium/tetragon/pull/2720#issuecomment-2278425729
=> crd: make followChildren optional

cmd/tetra/common/client.go, cmd/tetra/getevents/getevents.go
After commit 663a1e2ed51afa8590c07bac08822a98c0d12a43, we stop connecting to the server prior making the RPC. It creates a buggy situation when we are using streams: the connection get cancelled at timeout even if it's successfully streaming. Let's remove the timeout for the getevents command and only use the context based on the interrupt signals.
```release-note
Fix a bug where the tetra getevents command would timeout even if the connection was successful.
```
=> tetra: fix getevents cmd unexpected timeout

contrib/tetragon-rthooks/cmd/setup/main.go
For oci-hooks, the binary is copied twice. No need for that, remove the second copy.
Fixes: f9913836ec
=> rthooks: setup do not copy binary twice

contrib/upgrade-notes/latest.md, docs/content/en/docs/reference/metrics.md, go.mod, pkg/metrics/policyfiltermetrics/policyfiltermetrics.go, pkg/metricsconfig/healthmetrics.go
See commits.
```release-note
`tetragon_policyfilter_metrics_total` metric is renamed to `tetragon_policyfilter_operations_total`, and its `op` label is renamed to `operation`.
```
=> policyfiltermetrics: Refactor and rename metrics

cmd/tetragon/main.go
adding more checks on related options plus some more adding some more comments
=> tetragon: persistent monitoring fixes

pkg/metrics/kprobemetrics/collector.go
When collecting metrics from kernel, Tetragon needs to aggregate them in userspace maps to avoid duplicate labelsets, which cause metrics server errors. This was done incorrectly, using a pointer to missedKey struct as the aggregation key. Use missedKey struct directly.
=> kprobemetrics: Fix collecting missed metrics

bpf/lib/process.h, bpf/process/bpf_execve_event.c, bpf/process/types/basic.h, docs/content/en/docs/concepts/tracing-policy/selectors.md, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/api/processapi/processapi.go, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/selectors/kernel.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/tracing/kprobe_test.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Details can be found in #2679.
```release-note
Add the Postfix and NotPostfix operators to the matchBinaries selector.
```
=> Postfix operator for matchBinaries selector

.github/workflows/lint-helm.yaml
The 'lint Helm' GitHub workflow should also be triggered when its definition changes. Required for a follow up improvement of it.
```release-note
CI: Changed lint Helm CI trigger
```
=> CI: Changed lint Helm CI trigger

.clang-format, Dockerfile.clang, Dockerfile.clang-format
First half of https://github.com/cilium/tetragon/pull/2777.
=> Update Dockerfiles to build clang-18 images

docs/assets/scss/_styles_project.scss, docs/assets/scss/community-banner.scss, docs/assets/scss/header.scss, docs/assets/scss/home.scss, docs/content/en/_index.html, docs/layouts/_default/baseof.html, docs/layouts/partials/community-banner.html
Add banner before header and move slider section after community links at the homepage
=> feat: add banner to community meetings and move tetragon slides

docs/content/en/docs/reference/metrics.md, pkg/metricsconfig/initmetrics.go
It's a useful metric. From https://pkg.go.dev/runtime/metrics:
/sched/latencies:seconds
Distribution of the time goroutines have spent in the scheduler
in a runnable state before actually running. Bucket counts
increase monotonically.
=> metrics: Expose go_sched_latencies_seconds

docs/content/en/docs/reference/metrics.md, pkg/api/ops/ops.go, pkg/metrics/errormetrics/errormetrics.go, pkg/metrics/labels.go, pkg/metrics/opcodemetrics/opcodemetrics.go
`MsgOp*` constants were duplicating `MSG_OP_*`. There is no point in maintaining two lists, and `MsgOp*` constants weren't added for some new features. Let's keep `MSG_OP_*` for consistency with other types and bpf.
Also remove `MsgOpKfreeSkb` (not used and not existing in bpf) and update metrics docs with missing opcodes.
=> api/ops: Remove MsgOp* constants

docs/assets/scss/home/hero.scss, docs/assets/scss/social.scss, docs/content/en/_index.html, docs/static/svgs/linkedin-icon.svg
Signed-off-by: Anna Artemova <annartmva@gmail.com>
- Fix spacing for label in hero section for mobile
- Add LinkedIn link to the Community Section on the Tetragon [homepage](https://deploy-preview-2796--tetragon.netlify.app)
=> feat: add Linkedin to the Community Section

pkg/watcher/watcher.go
The pkg/reader/node package gets the value of the NODE_NAME environment variable (if the HUBBLE_NODE_NAME is empty). If it is empty, it gets the hostname and uses that. The pkg/watcher package just attempts to get the NODE_NAME environment variable and warns that it will not work as expected if it is empty or missing. This commit changes pkg/watcher so that it uses pkg/reader/node's function instead.
=> Watcher: fix NODE_NAME if missing

pkg/cgidmap/cgidmap.go
Fixes: 0227f5d0b3c6 ("process: resolve pods with cgidmap")
=> cgidmap: fix initialization bug

cmd/tetragon/main.go, docs/data/tetragon_flags.yaml, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, pkg/option/flags.go
Currently, there is no way to disable the gRPC server. this commit checks if the provided address is empty and, if so, does not start the server. It also updates the helm configmap template so that if gRPC is disabled, then an empty address is passed to the agent.
```release-note
Allow disabling gRPC either by selecting 'enabled:false' in the helm chart or by passing an empty address to the agent
```
Fixes: https://github.com/cilium/tetragon/issues/2477
=> allow to disable the gRPC server

.github/workflows/lint-helm.yaml, install/kubernetes/Makefile, install/kubernetes/Pipfile, install/kubernetes/Pipfile.lock, install/kubernetes/helm_lint_values_override.yaml, install/kubernetes/openapi2jsonschema.py, install/kubernetes/schemas/podinfo-cilium.io.json, install/kubernetes/schemas/tracingpolicy-cilium.io.json, install/kubernetes/schemas/tracingpolicynamespaced-cilium.io.json
- Improved Helm chart validation by using Kubeconformance with enabled CR validation.
- Added JSON schemas for the Tetragon CRDs as we might need them in the future to validate CRs from the Helm chart (TPs, etc.).
Follow up PR of https://github.com/cilium/tetragon/pull/2804
```release-note
CI: Improved K8s Kubeconformance validation
```
=> CI: Improved K8s Kubeconformance validation

install/kubernetes/tetragon/templates/servicemonitor.yaml
Prometheus Operator by default adds "pod" label, representing the metrics exporter pod, to all scraped metrics. However, Tetragon exposes events metrics with "pod" label, which represents the process that generated events, not Tetragon pod. This label is not overridden if using the default ServiceMonitor (with "honorLabels: true") - that's good. However, it still can be useful to know which Tetragon pod exported the metric. Let's add "tetragon_pod" label to metrics scraped via default ServiceMonitor.
=> helm: Add tetragon_pod label to metrics via ServiceMonitor

pkg/process/cache.go, pkg/process/metrics.go, pkg/process/process.go
tetragon_process_cache_size metric was increased on every add() and never decreased. This is incorrect - fix it, so that it's increased on add() only if there was no LRU eviction and it's decreased on remove().
=> Fix tetragon_process_cache_size metric

pkg/sensors/exec/fork_test.go
As described in issue 2691, TestFork has been flaky. The way this test works is that a child is forked, which then forks a second chlid, which exits and we are looking for the exit event of the second child.
My best guess on why the flake happens is that the pid filtering filters out the second exit event. This can happen, for example, if the pid cache of the pid filter has not yet seen an event with a known parent.
So if the exit event of the second child comes before the exit event of the first chilid, then the first child's pid will not be in the cache when we get the second child exit and the event will be filtered out.
Based on the above reasoning, this commit removes the pid filter for the test.
Fixes: #2691
=> fork_test: remove pid export filter

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/_container_rthooks.tpl, install/kubernetes/tetragon/values.yaml
Only use podSecurityContext for rthooks.
=> helm: use podSecurityContext for rthooks

contrib/verify/verify.sh
While taking a look at tetragon, I tried running verify.sh and
observed bpf_enforce and bpf_generic_kprobe* all fail because
bpf_override_return is not available. I also observed that this seems
be handled conditionally in tetragon via the
pkg.bpf.HasOverrideHelper() function.
This change updates verify.sh to check for bpf_override_return before
trying to load these programs. If it's not present, it will be skipped
cleanly since it's not expected to work.
A cleaner solution is to reuse the same check from the Go code.
Rewriting this script in Go is tracked in issue #229.
Signed-off-by: Russell Bryant <russell.bryant@gmail.com>
=> verify.sh: Handle when bpf_verride_return is unavailable

docs/content/en/docs/concepts/runtime-hooks.md
Align the displayed version with the one the link references, 1.7, for the introduction of NRI support within containerd.
=> docs: Fix the mentioned containerd version

.github/workflows/lint-helm.yaml
Only post the `Kubeconform Output` comment (on the affected GH PR) in case `kubeconform_min_k8s_version` OR `kubeconform_latest_k8s_version` is failed, not when they're `skipped` (e.g., in case a previous step fails).
I added write permissions to `pull-requests` because of https://github.com/cilium/tetragon/actions/runs/10580480940/job/29315446663#step:10:100.
```release-note
CI: Improve/stabilize lint Helm CI workflow
```
=> CI: Improve/stabilize lint Helm CI workflow

bpf/lib/process.h, docs/content/en/docs/reference/metrics.md, pkg/api/processapi/processapi.go, pkg/metrics/eventmetrics/eventmetrics.go
When testing I saw a bunch of "unknown" errors. To further investigate, let's split out ENOENT, E2BIG and EINVAL into separate label values. This should be almost all errors returned by perf_event_output, I left out only EOPNOTSUPP.
=> metrics: Expose more errors in tetragon_bpf_missed_events_total counter

contrib/upgrade-notes/latest.md, docs/content/en/docs/reference/metrics.md, pkg/metrics/errormetrics/errormetrics.go, pkg/process/cache.go, pkg/process/metrics.go
Stop reporting tetragon_errors_total metric with "type" label values:
`process_cache_miss_on_get`
`process_cache_evicted`
`process_cache_miss_on_remove`
Evictions and misses are not errors, this is just cache's life, sometimes you
hit, sometimes you miss, and sometimes you gotta evict a process.
They are now reported by more intuitive metrics:
`tetragon_process_cache_evictions_total`
`tetragon_process_cache_misses_total{operation=~"get|remove"}`
Part of #2785
=> Replace process cache evictions and misses metrics

contrib/upgrade-notes/latest.md, docs/content/en/docs/reference/metrics.md, pkg/metrics/errormetrics/errormetrics.go, pkg/metrics/eventmetrics/eventmetrics.go
Replace `tetragon_errors_total{type="event_missing_process_info"}` metric with `tetragon_events_missing_process_info_total`.
Part of #2785
=> Replace missing process info metric

bpf/lib/process.h
Using this function on 4.19 I hit:
```
loadInstance: opening collection '/host/bpf/objs/bpf_execve_event.o' failed:
program event_execve: load program: argument list too long
```
A switch seems more verifier friendly on 4.19 🤷
=> bpf: Fix perf_event_output_metric

bpf/lib/process.h
:face_palm:
Fixes: 4360b2826bd6 ("bpf: Fix perf_event_output_metric")
=> bpf: Fix perf_event_output_metric again

pkg/sensors/load.go, pkg/sensors/tracing/kprobe_test.go
=> tetragon: fixes

.github/renovate.json5
Also update target codegen to protogen and generate to crds.
=> renovate: add 'make metrics-docs' to post upgrade cmds

pkg/grpc/exec/exec.go, pkg/process/process.go
The `eventcache` API provides 2 handlers.
These are:
`RetryInternal` -> called to setup process information
`Retry` -> called to setup pod information
In the case of clone events, we used to have en empty implementation on the `Retry` handler. This results in an issue with missing pod information which is described in detail here: https://github.com/cilium/tetragon/issues/2902
This patch provides the proper `Retry` implementation to handle also those cases.
FIXES: https://github.com/cilium/tetragon/issues/2902
```release-note
Fix clone event eventcache retry handler when missing pod info.
```
=> Fix clone event caching due to missing pod info

pkg/grpc/exec/exec.go, pkg/process/process.go
[upstream commit 20bba351bd5dd0476315bfb8334189cc351ba1b2]
The eventcache API provides 2 handlers.
These are:
RetryInternal -> called to setup process information Retry -> called to setup pod information
In the case of clone events, we used to have en empty implementation on the Retry handler. This results in an issue with missing pod information which is described in detail here: https://github.com/cilium/tetragon/issues/2902
This patch provides the proper Retry implementation to handle also those cases.
FIXES: https://github.com/cilium/tetragon/issues/2902
=> [backport/v1.2][bugfix] Fix clone event caching due to missing pod info

pkg/process/cache.go, pkg/process/metrics.go, pkg/process/process.go
[ upstream commit: 9e35cbab946bf8c2d7d001dcf5a3b39b74768e8a ]
tetragon_process_cache_size metric was increased on every add() and never decreased. This is incorrect - fix it, so that it's increased on add() only if there was no LRU eviction and it's decreased on remove().
=> [v1.1] Fix tetragon_process_cache_size metric

.github/renovate.json5
This should fix the situation in https://github.com/cilium/tetragon/pull/2884 or https://github.com/cilium/tetragon/pull/2900.
=> renovate: run make vendor on any Go update

api/v1/README.md, api/v1/tetragon/tetragon.pb.go, api/v1/tetragon/tetragon.proto, bpf/process/types/basic.h, contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto, docs/content/en/docs/reference/grpc-api.md, install/kubernetes/schemas/tracingpolicy-cilium.io.json, install/kubernetes/schemas/tracingpolicynamespaced-cilium.io.json, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/api/tracingapi/client_kprobe.go, pkg/grpc/tracing/tracing.go, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/tracing_policy_types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go, vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/tracing_policy_types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Closes #2517
update docs to use NotifyEnforcer
```release-note
chore(docs): rename killer to enforcer
```
=> chore(docs): rename killer to enforcer

contrib/upgrade-notes/v1.2.0.md, install/kubernetes/tetragon/templates/operator_configmap.yaml
In this PR https://github.com/cilium/tetragon/pull/2498, the `tetragon.skipCRDCreation` key was removed from the `values.yaml` file; however, there is still a reference to it in the operator config map.
From what I understand, the operator expects a boolean value, and in case the installation method is `operator`, it should be set to `false`.
The patch makes the following changes:
1. Remove deprecated `tetragon.skipCRDCreation` from the operator config map and set `false` as the static value in `skip-crd-creation`.
2. Rename `tetragon.skipCRDCreation` to `tetragonOperator.skipCRDCreation` in the upgrade notes for Tetragon `1.2.0`.
```release-note
Remove deprecated `tetragonOperator.skipCRDCreation` from the operator config map and set "false" when `.Values.crds.installMethod` is …
```
=> helm: Remove deprecated tetragonOperator.skipCRDCreation value

bpf/include/api.h, bpf/lib/bpf_cgroup.h, bpf/lib/bpf_task.h
Newer kernels should not use probe_read so convert to probe_read_kernel. We have logic to revert to probe_read on older kernels. Further using probe_read instead of correct probe_read_{kernel|user} may fault on some architectures.
Convert probe_read to probe_read_kernel.
```release-note
Convert probe_read to probe_read_kernel to avoid possible runtime faults with probe_read on some architectures.
```
=> tetragon: probe_read usage may cause issues with newer kernels

contrib/upgrade-notes/v1.2.0.md, install/kubernetes/tetragon/templates/operator_configmap.yaml
Backport of #2907
(I also updated the published release notes, this was a silly mistake).
=> [v1.2] helm: Remove deprecated tetragon.skipCRDCreation value

docs/content/en/docs/reference/helm-chart.md, docs/data/tetragon_flags.yaml, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml, pkg/defaults/defaults.go, pkg/eventcache/eventcache.go, pkg/grpc/exec/exec_test_helper.go, pkg/jsonchecker/jsonchecker.go, pkg/option/config.go, pkg/option/flags.go
This PR makes the event cache tunable. This includes the number of retries and the delay between each retry. For this reason we introduce 2 new command line flags:
```
--event-cache-retries int                   Number of retries for event cache (default 15)
--event-cache-retry-delay int               Delay in seconds between event cache retries (default 2)
```
This PR does not change the default values of those.
We also export those values through the Helm Chart.
```release-note
Make eventCache number of retries and delay between them tunable.
```
=> Make event cache tunable

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/values.yaml
Set rthooks.podSecurityContext to empty by default to be consistent with the security context setting of Tetragon pods. Also note that "privileged" setting only applies to container security context [^1][^2].
[^1]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#podsecuritycontext-v1-core
[^2]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#securitycontext-v1-core
=> helm: Set rthooks.podSecurityContext to empty by default

pkg/jsonchecker/jsonchecker.go
In https://github.com/cilium/tetragon/commit/62957f104 we changed the Retries and RetryDelay from var to const. This patch reverst that change as we may need to adjust them based on the test needs.
=> [jsonchecker] Remove const from parameters

cmd/tetragon/main.go, docs/content/en/docs/reference/metrics.md, pkg/metrics/watchermetrics/watchermetrics.go, pkg/process/podinfo_test.go, pkg/watcher/deleted_pod_cache.go, pkg/watcher/watcher.go, pkg/watcher/watcher_test.go
Add a deleted pod cache for pod association. See commits.
=> podinfo: add a deleted pod cache

pkg/sensors/load.go
In case the map is shared we bailed out before we properly setup
map's PinPath, which is needed later on in loader code.
=> tetragon: Fix map PinPath setup in case the map is shared

pkg/bpf/detect.go, pkg/ksyms/ksyms.go, pkg/sensors/load.go, pkg/sensors/program/loader.go
Do not cache large objects like the BTF and ksyms. Reload them when needed.
Before:
After:
=> Memory optimizations: remove BTF and kallsyms caches

docs/content/en/docs/reference/metrics.md, pkg/observer/cache.go, pkg/observer/data.go, pkg/observer/metrics.go
Fixes #679 
This PR adds additional metrics around LRU data cache such as size, capacity, evictions and cache miss in order to have a same set of metrics collection across the board.
```
Add metrics for LRU data cache
```
=> Added metrics for LRU data cache

pkg/grpc/exec/exec.go, pkg/process/process.go
[upstream commit 20bba351bd5dd0476315bfb8334189cc351ba1b2]
The eventcache API provides 2 handlers.
These are:
RetryInternal -> called to setup process information Retry -> called to setup pod information
In the case of clone events, we used to have en empty implementation on the Retry handler. This results in an issue with missing pod information which is described in detail here: https://github.com/cilium/tetragon/issues/2902
This patch provides the proper Retry implementation to handle also those cases.
FIXES: https://github.com/cilium/tetragon/issues/2902
=> [backport/v1.1][bugfix] Fix clone event caching due to missing pod info

pkg/grpc/exec/exec.go, pkg/process/process.go
[upstream commit 20bba351bd5dd0476315bfb8334189cc351ba1b2]
The eventcache API provides 2 handlers.
These are:
RetryInternal -> called to setup process information Retry -> called to setup pod information
In the case of clone events, we used to have en empty implementation on the Retry handler. This results in an issue with missing pod information which is described in detail here: https://github.com/cilium/tetragon/issues/2902
This patch provides the proper Retry implementation to handle also those cases.
FIXES: https://github.com/cilium/tetragon/issues/2902
=> [backport/v1.0][bugfix] Fix clone event caching due to missing pod info

docs/content/en/docs/installation/runtime-hooks.md
=> Improve rthooks docs

bpf/process/types/basic.h, cmd/tetragon/main.go, docs/content/en/docs/reference/helm-chart.md, docs/content/en/docs/reference/metrics.md, docs/data/tetragon_flags.yaml, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml, pkg/defaults/defaults.go, pkg/eventcache/eventcache.go, pkg/grpc/exec/exec_test_helper.go, pkg/jsonchecker/jsonchecker.go, pkg/metrics/watchermetrics/watchermetrics.go, pkg/option/config.go, pkg/option/flags.go, pkg/process/podinfo_test.go, pkg/watcher/deleted_pod_cache.go, pkg/watcher/watcher.go, pkg/watcher/watcher_test.go
Backported PRs
* https://github.com/cilium/tetragon/pull/2928
* [Make EventCache configurable](https://github.com/cilium/tetragon/commit/62957f1042c56acac1e335d104b577c83d61f0e9)
* [Reduce the delay in GRPC gotests](https://github.com/cilium/tetragon/commit/aab03febf6abbb9bb22eb480d7b9e8185ab05108)
* [Export EventCache tunables in the Helm Chart](https://github.com/cilium/tetragon/commit/451f921b9947fa652afc641a8801bad769ded5c5)
* https://github.com/cilium/tetragon/pull/2930
* [watcher: refactor watcher](https://github.com/cilium/tetragon/commit/5c838d5fbb30e55d8bf5467831507b22808d69b7)
* [watcher: add a containerIDKey function](https://github.com/cilium/tetragon/commit/ebd7e4338585765ee487dc6a64a1aba0cc8f4469)
* [watcher: change FindContainer …
=> v1.2 backports

bpf/Makefile, bpf/process/bpf_map_test_p3.c, pkg/observer/observertesthelper/observer_test_helper.go, pkg/sensors/config/confmap/confmap.go, pkg/sensors/load.go, pkg/sensors/program/map.go, pkg/sensors/test/sensors_test.go
Adding the concept of owning map and splitting Map object to owners and others.
The idea is that the 'owned' Map object takes care of creating/overwriting the pin,
while the 'other' Map object is just a user, that can read/update map but can't create it.
I'm not really happy with the 'other' naming, so any ideas are welcome ;-)
=> tetragon: Add map ownership

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml
Fixes 
Implemented the possibility to disable gops server when installing tetragon via helm
```release-note
Add an "enabled" switch to enable/disable the gops server via the Helm chart. It is now disabled by default.
```
=> Implemented a possibility to disable gops via helm

Dockerfile
Minor UX improvement when troubleshooting inside the Tetragon container image:
```bash
77a8a8762616:/# tetra    # pressing <tab><tab>
bugtool          (Produce a tar archive with debug information)                probe            (Probe for eBPF system features availability)
completion       (Generate the autocompletion script for the specified shell)  stacktrace-tree  (Manage stacktrace trees)
cri              (connect to CRI)                                              status           (Print health status)
getevents        (Print events)                                                tracingpolicy    (Manage tracing policies)
help             (Help about any command)                                      version          (Print version from CLI and server)
loglevel         (Get and …
```
=> Enabled `tetra` bash autocompletion in the Tetragon image

cmd/tetra/debug/maps.go, pkg/bugtool/bugtool.go, pkg/bugtool/maps.go
Per request:
> Some questions; Is this part of bugtool? Should we make it?
>
> Can we have JSON output? JSON output helps if we want to write scripts to parse the data which will be useful if we run this via sysdmp/bugtool across the whole cluster.
_Originally posted by @kkourt in https://github.com/cilium/tetragon/pull/2959#pullrequestreview-2336465877_
=> tetra: add a JSON output format in debug map command and run it in bugtool

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml
I added `tetragon.enableKeepSensorsOnExit` to enable persistent enforcement of the sensors even when the Tetragon process is gone/exited. Let's make this flag (`--keep-sensors-on-exit`) a proper Helm value instead of having users specify it via extraArgs. We _should_ also set `--release-pinned-bpf=false` in case `--keep-sensors-on-exit` gets enabled. See https://github.com/cilium/tetragon/commit/64d620e4278ca59fc8666d60daf40b63600943fa.
https://tetragon.io/docs/concepts/enforcement/persistent-enforcement/
```release-note
helm: Added dedicated persistent enforcement flag
```
=> helm: Added dedicated flag for persistent enforcement

pkg/sensors/load.go, pkg/sensors/sensors.go, pkg/sensors/test/sensors_test.go
do better job on cleaning up after sensors is unloaded or fails to load
=> tetragon: sensor cleanup fixes

.github/workflows/vmtests.yml
vmtests needed nested virtualization, so they were using ubuntu-latest-4cores-16gb machines. Now, ubuntu-latest also supports nested virtualization so switch vmtest to ubnutu-latest.
=> vmtests: use ubuntu-latest

bpf/Makefile, bpf/include/api.h, bpf/include/vmlinux.h, bpf/process/bpf_prog_iter.c, cmd/tetra/debug/debug.go, cmd/tetra/debug/progs.go, pkg/sensors/tracing/enforcer.go, pkg/sensors/tracing/genericlsm.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/genericuprobe.go
Adding tetra debug progs command that enables bpf program stats and collects them for running programs.
The deault output looks like:
```
2024-10-01 11:42:28.181107151 +0000 UTC m=+5.061137969
Ovh(%)  Id      Cnt     Time            Name            Pin
22.17  5614    647635  886904962       generic_tracepo raw-syscalls/generic_tracepoint/raw_syscalls:sys_enter/prog
0.00  5606    1       8047            event_execve    __base__/event_execve/prog
0.00  5603    1       5910            event_wake_up_n __base__/kprobe_pid_clear/prog
0.00  5609    1       5255            tg_kp_bprm_comm __base__/tg_kp_bprm_committing_creds/prog
0.00  5601    1       3185            event_exit_acct __base__/event_exit/prog
```
It provides several options to control timeout and repetition, all should be described …
=> tetra: Add debug progs command

pkg/sensors/load.go, pkg/sensors/sensors.go, pkg/sensors/test/sensors_test.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generickprobe_test.go, pkg/sensors/tracing/genericlsm.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/genericuprobe.go, pkg/sensors/tracing/policyhandler.go, pkg/sensors/tracing/tracepoint_test.go
Make sure the bpffs hierarchy tree works properly with namespaced policies.
=> tetragon: Use namespace in sensor policy directory

pkg/sensors/program/map.go, pkg/sensors/test/sensors_test.go
John reported issue where user maps unpinned exisintg maps on unloading,
which is wrong, we just need to close the ebpf handle.
Reported-by: John Fastabend <john.fastabend@gmail.com>
=> tetragon: Unpin map only if you are owner

.github/workflows/vmtests.yml
All tests are failing with:
time="2024-10-15T15:35:54Z" level=warning msg="stderr> virt-customize: error: libguestfs error: passt exited with status 1\n"
time="2024-10-15T15:35:54Z" level=warning msg="stderr> \n" time="2024-10-15T15:35:54Z" level=warning msg="stderr> If reporting bugs, run virt-customize with debugging enabled and include the complete output:\n" time="2024-10-15T15:35:54Z" level=warning msg="stderr> \n"
time="2024-10-15T15:35:54Z" level=warning msg="stderr>   virt-customize -v -x [...]\n"
time="2024-10-15T15:35:54Z" level=error msg="error executing command" error="exit status 1" image=tetragon.qcow2
time="2024-10-15T15:35:54Z" level=warning msg="image file 'tests/vmtests/test-data/images/tetragon.qcow2' not deleted so that it can be inspected"
time="2024-10-15T15:35:54Z" …
=> vmtests: install dhclient

docs/content/en/docs/reference/metrics.md, pkg/metrics/policymetrics/policymetrics.go, pkg/metrics/policymetrics/policymetrics_test.go, pkg/policyfilter/policyfilter.go, pkg/sensors/manager.go, pkg/testutils/sensors/policyfilter.go, pkg/testutils/sensors/sensors.go
This fixes a metrics collection error that was occurring in case there were
multiple namespaced policies with the same name. The metrics collector is
iterating over all policies and reports tetragon_tracingpolicy_kernel_memory_bytes
metric for each of them. The metric used to be labeled only with the policy
name, so in case there was a second policy with the same name, the collector
reported a duplicate what causes the entire metrics collection job to fail.
Adding a policy_namespace label should prevent duplicates.
There is an underlying assumption that each policy returned by
ListTracingPolicies has a unique (name, namespace) tuple - if it's not the
case, then metrics collection might fail again. Also, I'm not sure if
per-policy memory metrics should be reported for policies in states …
=> Fix metrics collection in case of duplicate policy names

.github/workflows/packages-e2e-tests.yaml
=> ci:github: retry Test Tetragon on failure

pkg/eventcache/eventcache.go, pkg/grpc/exec/exec_test_helper.go, pkg/grpc/process_manager.go, pkg/server/server.go
Export the Notifier interface, and pass it to eventcache instead of passing the entire Server struct. Remove Server.NotifyListeners() method, which is simply a wrapper that calls NotifyListener() on the underlying Notifier.
=> Export the Notifier interface

pkg/eventcache/eventcache.go, pkg/exporter/exporter_test.go, pkg/grpc/exec/exec.go, pkg/grpc/process_manager.go, pkg/grpc/process_manager_test.go, pkg/grpc/test/test.go, pkg/grpc/tracing/tracing.go, pkg/process/process.go, pkg/ratelimit/ratelimit.go, pkg/reader/node/node.go, pkg/reader/node/node_test.go
Centralize the logic to set the NodeName field for events to avoid code duplication. Initialize the nodeName variable once in the node package init() function.
=> Centralize the logic to set node name

.github/workflows/build-images-ci.yml, .github/workflows/check-links-cron.yaml, .github/workflows/check-links-pr.yaml
A user could create a branch with a particular name that would trigger a command injection because we use this input directly in the shell scripts generation. See more details in
https://securitylab.github.com/resources/github-actions-untrusted-input/.
This also updates the lychee action that no longer need an explicit GITHUB_TOKEN env variable lycheeverse/lychee-action#195 and reduce the permissions needed by the token in both check links workflows.
Reported-by: Piergiorgio Ladisa <piergiorgio.ladisa@hotmail.it>
=> workflows: fix usage of untrusted input in check links

bpf/process/bpf_generic_lsm_core.c, bpf/process/bpf_generic_lsm_output.c, bpf/process/types/basic.h
There's recent kernel change forcing LSM bpf programs return value range [-4095, 0]. Making sure we follow that in generic lsm sensor.
[1] 5d99e198be27 bpf, lsm: Add check for BPF LSM return value
=> tetragon: Make sure lsm programs return bounded value

pkg/bpf/detect.go, pkg/ksyms/ksyms.go, pkg/sensors/load.go, pkg/sensors/program/loader.go
Backport in v1.2 of https://github.com/cilium/tetragon/pull/2937.
=> [v1.2 backport] Memory optimizations: remove BTF and kallsyms caches

pkg/sensors/tracing/kprobe_copyfd_test.go
Latest 5.10 kernel merged [1] change that removes __fd_install.
Making the test to check on __fd_install/fd_install function and use related spec accordingly.
[1] 89f9e529643a ("file: Merge __fd_install into fd_install")
=> tetragon: Fix TestCopyFd test on new v5.10 kernels

pkg/sensors/program/program.go, pkg/sensors/tracing/generickprobe_test.go
Fixes #3013 
Sensors that are disabled are not loaded and should not use memory, thus we clear the LoadedMapsInfo on unloading programs.
=> pkg/sensors: fix memory use of unloaded sensors

cmd/tetragon-metrics-docs/metricsmd/metricsmd.go, docs/content/en/docs/reference/metrics.md, pkg/version/metrics.go
Before this patch:
tetragon_build_info{commit="61b575c72b22aa8bb6d7ed8af2d3dbfee43f6307",go_version="go1.23.1",modified="true",time="2024-10-23T06:20:18Z"} 1
After:
tetragon_build_info{commit="61b575c72b22aa8bb6d7ed8af2d3dbfee43f6307",go_version="go1.23.1",modified="true",time="2024-10-23T06:20:18Z",version="v1.3.0-pre.0-216-g61b575c72"} 1
```release-note
metrics: add version to build information
```
=> version: add version string to metrics

docs/data/tetragon_flags.yaml, examples/configuration/tetragon.yaml, pkg/option/flags.go
- The --expose-kernel-addresses flag got deprecated in v1.1 [^1].
- The --pprof-addr flag got deprecated in v1.2 [^2].
[^1]: https://github.com/cilium/tetragon/commit/0d53eccaacf332a444c5073e88a58b8e77176fe9
[^2]: https://github.com/cilium/tetragon/commit/fe78328cf7a8c436a0335e734e609eb1d230750e
=> Remove --expose-kernel-addresses and --pprof-addr flags

docs/data/tetragon_flags.yaml, examples/configuration/tetragon.yaml, pkg/option/flags.go
Tetragon does not use this flag, so let's just remove it instead of deprecating it first.
=> Remove --enable-process-ancestors flag

pkg/filters/filters.go, pkg/filters/policies_test.go
In #1867, the `--policy-names` flag was added to filter events based on the tracing policy. However, the filter was only appled to `kprobe` events.
This patch extends the filter to support all events types: `kprobe`, `tracepoint`, `uprobe` and `lsm`.
=> tetra: fix `--policy-names` to apply all event types

contrib/tester-progs/.gitignore, contrib/tester-progs/Makefile, contrib/tester-progs/pause.c, pkg/grpc/exec/exec.go, pkg/sensors/exec/exit_test.go
The ProcessExit event returns a signal that the process received when it exited. However, core dumped signals (SIGSEGV, SIGILL, etc.) are not returned.
This patch fixes the issue by checking if the process exit code has the core dump bit set (7th bit, 0x80), and returns the correct signal. I used the kernel [code](https://elixir.bootlin.com/linux/v5.19/source/kernel/signal.c#L2076-L2078) as a reference to fix it.
Launch the `tetra` CLI with the following command:
```bash
tetra getevents --process "run" --output compact
```
Then launch a random program and terminate it using different signals:
```bash
./run &
kill -9 $!
./run &
kill -11 $!
```
**Expected Behavior:**
Before: the signal for core dumped processes is not displayed correctly.
After: the correct signal for core dumped processes …
=> tetragon: fix the process exit signal when core dumped

pkg/sensors/exec/exit_test.go
Exit events can be un ordered, make the test reflect that.
=> tetragon: Fix TestExitSignal test

install/kubernetes/tetragon/templates/_helpers.tpl
Also refactor the labels templates (deduplicate).
=> helm: Add part-of and component labels

cmd/tetra/debug/debug.go, cmd/tetra/debug/stats.go, docs/content/en/docs/reference/metrics.md, pkg/metrics/labels.go, pkg/metrics/overhead/collector.go, pkg/metrics/overhead/overhead.go, pkg/metrics/policymetrics/policymetrics.go, pkg/metricsconfig/healthmetrics.go, pkg/sensors/collection.go, pkg/sensors/delayed_sensor_test.go, pkg/sensors/manager.go, pkg/sensors/sensors.go
adding overhead metrics for loaded policies
at the moment we don't display base sensor stats, because that needs some code factoring and will come later
=> tetragon: Add overhead metrics

docs/data/tetragon_flags.yaml, pkg/option/flags.go
policyfilter is no longer beta, so remove comment from command line help. Note that policyfilter is mostly useful for k8s environments, where it is enabled by default via the corresponding helm option and we keep the default value as false in the agent for non-k8s installations.
=> policyfilter: do not mark as beta anymore

pkg/bpf/perf_linux.go
It's unused since switching to use cilium/ebpf functionality to get the number of possible CPUs in commit 582da32e11bd ("tetragon: Implement bpf.GetNumPossibleCPUs through cilium/ebpf library").
=> bpf: remove unused const PossibleCPUSysfsPath

.github/workflows/bpf-unit-tests.yml, .github/workflows/gotests.yml, .github/workflows/packages-e2e-tests.yaml, .github/workflows/run-e2e-tests.yaml, tests/e2e/tests/labels/labels_test.go
CNCF stopped funding actuated arm64 runners but GitHub now proposes their own runners part of the GitHub offering.
=> workflows: use GitHub arm64 runners instead of actuated

bpf/lib/bpf_cgroup.h, bpf/lib/environ_conf.h, bpf/process/bpf_process_event.h, pkg/cgroups/cgroups.go, pkg/cgroups/cgroups_test.go, pkg/sensors/config/confmap/confmap.go, pkg/sensors/exec/cgroups_test.go, pkg/testutils/confmap.go
kernel v6.11 introduced new CONFIG_MEMCG_V1 and CONFIG_CPUSETS_V1 [1]
that changed how userspace detects the compiled cgroup controllers,
if the new CONFIG_MEMCG_V1=n then memory and same for cpuset controller
will not be exported in /proc/cgroups.
In Cgroupv2 we automatically handle this with these changes. If your distribution
runs in Cgroupv1 then these changes also handle it assuming you have
both CONFIG_MEMCG=y and CONFIG_MEMCG_V1=y are set.  
[1] "af000ce85293b8e60" "cgroup: Do not report unavailable v1 controllers in /proc/cgroups"
Kernel v6.11 introduced a new CONFIG_MEMCG_V1 for legacy cgroup v1 memory controller which may affect Tetragon cgroup environment detection, process and container/pod association. Improve Tetragon so we handle the new configuration and allow process …
=> tetragon: improve how we handle cgroupv1 and cgroupv2

docs/content/en/docs/concepts/tracing-policy/selectors.md
The limitation of only having 4 values for `matchBinaries` doesn't apply anymore.
```release-note
doc: Removed old matchBinaries limitation
```
=> doc: Removed old matchBinaries limitation

.github/workflows/build-images-ci.yml
Follow security best practices for this sensitive pull_request_target workflow and simplify it for easy maintenance.
=> workflows: simplify build image CI

docs/content/en/docs/reference/metrics.md, pkg/metrics/overhead/collector.go, pkg/metrics/overhead/overhead.go, pkg/sensors/sensors.go
Let's assume the following example:
```
$ cat pol.yaml
metadata:
name: "file-monitoring-mmap"
spec:
kprobes:
- call: "security_mmap_file" syscall: false return: true args:
- index: 0 type: "file" # (struct file *) used for getting the path
- index: 1 type: "uint32" # the prot flags PROT_READ(0x01), PROT_WRITE(0x02), PROT_EXEC(0x04)
- index: 2 type: "nop" # the mmap flags (i.e. MAP_SHARED, ...) returnArg: index: 0 type: "int" returnArgAction: "Post" selectors:
- matchArgs:
- index: 0 operator: "Prefix" values:
- "/etc/" # filenames to filter for 
$ sudo ./tetragon --btf /sys/kernel/btf/vmlinux  --bpf-lib ./bpf/objs/ --metrics-server ':2112' --tracing-policy ./pol.yaml  --disable-kprobe-multi
```
After that, if we try to get the metrics …
=> [metrics] Fix overhead_program metrics for return probes

.github/renovate.json5
Include Chart.yaml to automatically bump dependencies in case we add some. Also
include all directories under install/kubernetes.
=> Renovate: Extend Helm files coverage

install/kubernetes/tetragon/crds-yaml/cilium.io_podinfo.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/tracing_policy_types.go, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/k8s/crdutils/register.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/tracing_policy_types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go, vendor/github.com/cilium/tetragon/pkg/k8s/crdutils/register.go
Let's slightly improve the Tetragon UX for lazy people like I am 😄.
- `podinfo` -> `tgpi`
- `tracingpolicy` -> `tgtp`
- `tracingpoliciesnamespaced` -> `tgtpn`
Furthermore, it's now possible to interact with user-relevant CRs (all besides `PodInfo`) at the same time via the `tetragon` category.
BTW, Cilium does the same for every Cilium CRD.
```release-note
crd: Added shortnames and catagory for Tetragon CRDs
```
=> crd: Added shortnames and catagory for Tetragon CRDs

.golangci.yml, go.mod, pkg/bugtool/maps.go, pkg/eventcache/metrics.go, pkg/metrics/eventmetrics/eventmetrics.go, pkg/metrics/policyfiltermetrics/policyfiltermetrics.go
Use the `maps` and `slices` packages from the Go standard library instead of the respective `golang.org/x/exp` packages.
Also add a linter check enforcing use of these packages.
=> Switch to Go 1.23+ stdlib `maps`/`slices` packages

cmd/tetragon/main.go, cmd/tetragon/main_test.go, pkg/bugtool/maps_test.go, pkg/observer/observer.go, pkg/observer/observertesthelper/observer_test_helper.go, pkg/sensors/exec/cgroups_test.go, pkg/sensors/exec/exec.go, pkg/sensors/exec/exec_test.go, pkg/sensors/exec/threads_test.go, pkg/sensors/tracing/enforcer_test.go, pkg/sensors/tracing/generickprobe_test.go, pkg/sensors/tracing/kprobe_test.go, pkg/sensors/tracing/policyfilter_test.go, pkg/sensors/tracing/selectors_test.go, pkg/testutils/sensors/sensors.go
We need to call procevents.GetRunningProcs after server is started observer listeners are configured.
Currently it's called within base sensor load, but it's now loaded before server is started, so we don't get any initial exec events.
=> tetragon: Move procevents.GetRunningProcs call from base sensor load

pkg/bugtool/maps.go, pkg/observer/observertesthelper/observer_test_helper.go, pkg/sensors/collection.go, pkg/sensors/delayed_sensor_test.go, pkg/sensors/exec/exec_test.go, pkg/sensors/handler.go, pkg/sensors/load.go, pkg/sensors/manager.go, pkg/sensors/program/loader.go, pkg/sensors/program/map.go, pkg/sensors/program/program.go, pkg/sensors/sensors.go, pkg/sensors/test/sensors_test.go, pkg/sensors/tracing/enforcer.go, pkg/sensors/tracing/enforcer_test.go, pkg/sensors/tracing/generickprobe_test.go, pkg/sensors/tracing/kprobe_test.go, pkg/sensors/unloader/unloader.go, pkg/testutils/sensors/sensors.go
factor sensors unpin-ing
fixes https://github.com/cilium/tetragon/issues/3033
=> tetragon: un/pin fixes

bpf/include/api.h, bpf/lib/bpf_cgroup.h, bpf/lib/bpf_task.h
Newer kernels should not use probe_read so convert to probe_read_kernel. We have logic to revert to probe_read on older kernels. Further using probe_read instead of correct probe_read_{kernel|user} may fault on some architectures.
Convert probe_read to probe_read_kernel.
```Convert probe_read to probe_read_kernel to avoid possible runtime faults with probe_read on some architectures.```
[Upstream PR: #2925]
=> Backports/v1.2: tetragon: probe_read usage may cause issues with newer kernels

.github/workflows/check-links-cron.yaml, .github/workflows/renovate.yaml
Fixes https://github.com/cilium/tetragon/issues/3107.
Avoid running cron jobs, especially renovate, on forks which would fail because of the absence of secrets.
=> workflows: only run cron jobs on main repo

pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_test.go, pkg/sensors/tracing/kprobe_validation_test.go
it's ok for non kprobe-multi specs and we retrn error in kprobe-multi mode
Fixes: https://github.com/cilium/tetragon/issues/2947
=> tetragon: Allow multiple symbol instances in kprobe spec

bpf/lib/process.h, bpf/process/bpf_execve_event.c, bpf/process/data_event.h, pkg/api/processapi/processapi.go, pkg/grpc/exec/exec_test_helper.go, pkg/sensors/exec/procevents/proc_reader.go
This was supposed to be a simple cleanup but ended up encountering complexity issues.
The second patch improves the complexity of the programs by moving error handling outside of the loops.
The PR ends up improving the complexity overall. See:  https://github.com/cilium/tetragon/actions/runs/11903505830?pr=3127.
Some sample numbers  from the link above:
| file | program | Insns (A) | Insns (B)    | Diff     |
|------|---------------|---------------| ---------------|--------- |
| `bpf_execve_event.o` | `event_execve` | 39760   |   25181 |  -14579 (-36.67%) |
| `bpf_execve_event_v53.o` | `event_execve` | 173713 |    144552 |  -29161  (-16.79%)  |
Loading time is also reduced which is nice.
=> bpf: remove unused fields in msg_k8s

cmd/tetragon/main_test.go
On slow server the test might fails to start exporter fast enough making the test fail, because events did not get stored.
Moving the tetragonExecuteCtx into separate process and adding extra 5 tries on checking up on the exported file.
=> tetragon: Unflake the TestGeneratedExecEvents test

.github/workflows/bpf-unit-tests.yml, .github/workflows/gotests.yml, .github/workflows/packages-e2e-tests.yaml, .github/workflows/run-e2e-tests.yaml, contrib/tester-progs/direct-write-tester.c, pkg/sensors/tracing/enforcer_test.go, tests/e2e/tests/labels/labels_test.go
Backport of #3034 for deps update to work (like https://github.com/cilium/tetragon/pull/3136).
=> [v1.1 backport] workflows: use GitHub arm64 runners instead of actuated

cmd/tetragon/main.go, docs/content/en/docs/reference/helm-chart.md, docs/data/tetragon_flags.yaml, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml, pkg/bench/bench.go, pkg/defaults/defaults.go, pkg/grpc/exec/exec_test_helper.go, pkg/grpc/process_manager_test.go, pkg/observer/observertesthelper/observer_test_helper.go, pkg/option/config.go, pkg/option/flags.go, pkg/process/cache.go, pkg/process/cache_test.go, pkg/process/process.go, pkg/sensors/exec/cache_test.go
The process cache delays removal of exited processes. The first time the garbage collector sees a process (marked deletePending), it changes it to deleteReady. The second time it sees the process, it deletes it from the cache. The garbage collector runs every 30s.
This PR makes the GC interval configurable with the --process-cache-gc-interval switch.
=> ProcessCache: Make GC interval configurable

bpf/Makefile, bpf/Makefile.defs, bpf/tests/Makefile
bpf makefile changes, hopefully making it more readable
=> tetragon: update bpf makefile

pkg/sensors/load.go, pkg/sensors/program/map.go, pkg/sensors/program/program.go
Currently, we emit a log line for every program and map loaded/unloaded in a policy. As policies, becomes more complicated, this makes logs very verbose.
This commit addresses this by moving the logging of the messages into Debug, and adding the information of what maps/programs are loaded in a single line that relates to the sensor.
An example using the base sensor can be found below.
Before:
Loading:
```
|  time="2024-11-29T14:34:24+01:00" level=info msg="Loading sensor" name=__base__
|  time="2024-11-29T14:34:24+01:00" level=info msg="Loading kernel version 6.8.12"
|  time="2024-11-29T14:34:24+01:00" level=info msg="tetragon, map loaded." map=execve_map max="{0 false}" path=/sys/fs/bpf/tetragon/execve_map sensor=__base__
|  time="2024-11-29T14:34:24+01:00" level=info msg="tetragon, map …
```
=> sensors: reduce the logs when {,un}loading policies

contrib/tester-progs/fork-tester.c, pkg/sensors/exec/fork_test.go
Fix https://github.com/cilium/tetragon/issues/3148
A nil pointer is returned by `ctx.Err()` because `ctx` is not done when the error is displayed.
On some distributions, like Archlinux, systemd run with the flag `--user`. Thus, makes the user manager process a child of systemd process 1. So when you search for PPID, it will always be this child process.
According to the documentation below, systemd expose an environnement variable to help finding this children. So if we compare the value of this environment variable with the ppid, we should get the same result as doing `ppid == 1` 
https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#%24MANAGERPID
=> fix(#3148) Update fork-tester.c replace systemd pid with parent process pid 

pkg/vmtests/skip.go
The TestProcessCacheInterval test is flaky in VMs, probably because it relies on timing. This commit disables the test in the vmtests.
=> ProcessCache: Disable interval test in VM

bpf/process/policy_filter.h, pkg/cgtracker/test/cgtracker_test.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/generictracepoint.go, pkg/testutils/perfring/perfring.go, pkg/testutils/progs/tester.go
This PR is a follow-up of https://github.com/cilium/tetragon/pull/3170.
#3170 added pod association using cgroup tracking.
This PR adds policy filtering using cgroup tracking.
This means that namespaced policies and policies with pod-label filters will work with nested cgroups (when cgtracker is enabled). 
See commits.
=> cgtracker: add policyfilter support

pkg/sensors/load.go, pkg/sensors/sensors.go
This will provide the ability to run sensor-specific code right after loading all maps/programs.
This can be used for cleanup etc.
=> [sensors] Add optional PostLoadHook

docs/content/en/docs/concepts/events.md
Correct a incorrect description of the `arguments_regex` filter in the documentation. This change is docs-only.
=> docs: Correct description of arguments_regex

bpf/Makefile
Keep just the dependency, the command is carried out by the default rule.
=> tetragon: Remove not needed rule commands

bpf/lib/process.h, bpf/process/bpf_execve_event.c, pkg/api/processapi/processapi.go
Setting up ability to match args as well as binary names. This is useful for matching 'java beaches.jar' or 'python palmTree.py' where the binary itself is an interpretor and the actual thing being called is what matters.
=> tetragon: setup to let match binary names use args as well

docs/content/en/docs/getting-started/network.md
Fixes #3182
Use `component=kube-apiserver` match in doc command for getting the SERVICECIDR on KinD clusters
Named KinD clusters will have kube-apiserver pods with the cluster name included--the format is `kube-apiserver-<CLUSTERNAME>-control-plane`.  The kube-system control-plane uses the label `component=kube-apiserver` on the apiserver pods regardless of the cluster name.
=> docs: use label match in SERVICECIDR command for KinD

pkg/metrics/overhead/collector.go, pkg/metrics/overhead/overhead.go, pkg/sensors/sensors.go
This is done to avoid duplicate metrics, that would cause the entire metrics collection job to fail.
=> Aggregate overhead metrics in userspace before reporting

docs/content/en/docs/contribution-guide/development-setup.md
deploy preview => https://deploy-preview-3231--tetragon.netlify.app/docs/contribution-guide/development-setup/#local-development-with-apple-silicon-mac
=> docs: Add dev setup instructions for Apple silicon Macs

cmd/tetragon-vmtests-run/image.go
Fixes broken vmtests in main branch (i.e. https://github.com/cilium/tetragon/actions/runs/12370210256/job/34524136468).
Details in the commit message.
=> [CI] Fix virt-customize issue in vmtests

docs/content/en/docs/contribution-guide/development-setup.md
See [preview](https://deploy-preview-3237--tetragon.netlify.app//docs/contribution-guide/development-setup/#local-development-with-apple-silicon-mac).
This uses the docs "warning" and "note" instead of custom cites and emojis.
=> docs: local dev with Apple Silicon small fixes

cmd/tetra/debug/progs.go, docs/content/en/docs/concepts/performance-stats.md, go.mod, pkg/bugtool/maps.go
Recent ebpf changes make ebpf.LoadPinnedProgram fail on opening link path. We want to open only programs, so failing on opening links/maps is fine ad we just want to continue scanning.
Fixes: https://github.com/cilium/tetragon/issues/3234
=> tetra: Fix tetra debug progs fail

cmd/tetragon-vmtests-run/image.go
Backport https://github.com/cilium/tetragon/pull/3232
=> [backport/v1.2][CI] Fix virt-customize issue in vmtests

docs/content/en/docs/concepts/tracing-policy/example.md
Doc update
docs: remove redundant  CLI command in tracing policy example
=> docs: remove redundance CLI command in tracing policy example

.github/workflows/build-images-releases.yml
This is the release workflow, so it won't be trigger unless we do a release next time.
=> ci: remove buildjet runners and use GitHub arm64 runners

.github/renovate.json5
Fix for 70ad4e78d5b4 ("renovate: disable digest update on Dockerfiles"), for some reason datasources works while managers doesn't.
I tested this one on a fork [a3f46d4df4ff07e829e604c68074ea78db4f80d3](https://github.com/mtardy/tetragon/commit/a3f46d4df4ff07e829e604c68074ea78db4f80d3) and it worked.
=> renovate: fix for config change 70ad4e78d5b4

bpf/cgroup/bpf_cgroup_events.h, bpf/lib/bpf_task.h, bpf/process/bpf_execve_event.c, bpf/process/bpf_fork.c
`curr->nspid` should be obtained from the child `task` arguments, not from the current `task_struct` (the parent process). 
This will lead to a mismatch between `pid` and `nspid`.
```c
__attribute__((section("kprobe/wake_up_new_task"), used)) int
BPF_KPROBE(event_wake_up_new_task, struct task_struct *task) {
struct execve_map_value *curr;
tgid = BPF_CORE_READ(task, tgid); 
curr->key.pid = tgid; // curr->key.pid is obtained from the task argument
// is not correct.
curr->nspid = get_task_pid_vnr(); // curr->nspid is obtained from the current task_struct (parent)!
}
```
for example. if we run in docker, we run a app which  fork process every second, the pid in container will be like this
```
Hello from child process (PID: 485), parent: 1
Hello from child process (PID: 486), parent: 1
Hello …
```
=> fix: nspid assign is not correct

bpf/process/bpf_process_event.h
Fixes 
cwd_read do not assign data->vfsmnt correctly. 
reproduce:
```
sudo mount -t nfs  x.x.x.x:/data/dev/nfs_dir /home/arthur/my_run
$ mount -t
x.x.x.x:/data/dev/nfs_dir on /home/arthur/my_run
/dev/nvme0n1p5 on /home type ext4 (rw,relatime)
```
and cat a file in my_run dir
```
cat /home/arthur/my_run/a.txt
```
in tetragon side, it will get a path : `/home/home/arthur/my_run/a.txt`, but  it should be `/home/arthur/my_run/a.txt`
```
cat-2152134 [003] d...1 3725192.671779: bpf_trace_printk: copy path: /home/home/arthur/my_run/a.txt
```
and in another production env, i found it will get path more than expected when i cat `/tmp/tetragon`. the prefix `/scon/containers/01J6HEV7R29R4WXXS1N2CS9ATP/rootfs/` should not be obtained.
```
/scon/containers/01J6HEV7R29R4WXXS1N2CS9ATP/rootfs/tmp/tetragon …
```
=> bug: fix assign vfsmnt correctly

pkg/sensors/manager_test.go, pkg/sensors/tracing/generickprobe_test.go, pkg/sensors/tracing/kprobe_test.go, tests/vmtests/fetch-data.sh
Panicking in tests is bad as it fails to tell the test handler that the test failed. Instead we should use t.Fatal(). This commit changes instances of panic in tests to t.Fatal().
[Upstream PR: #2685]
=> tests: replace panic with t.Fatal

bpf/process/pfilter.h, bpf/tests/Makefile, bpf/tests/pid_match_test.c, bpf/tests/pid_match_test.go
Fixes bug
In the code, the function next_pid_value(index, f, ty) is called multiple times to update the index, but the updated value is not written back to sel->index. This wil cause external callers to be unable to obtain the updated state.
matchPIDs only use first pid
```yaml
selectors:
- matchPIDs:
- operator: NotIn
values:
- 0
- 1
```
```
__u32 index = sel->index;
index = next_pid_value(index, f, ty);
FUNC_INLINE int next_pid_value(__u32 off, __u32 *f, __u32 ty)
{
return off + 4;
}
```
offset use selecttor_filter->index
```
FUNC_INLINE int
process_filter_pid(struct selector_filter *sf, __u32 *f,
struct execve_map_value *enter, struct msg_ns *n,
struct msg_capabilities *c)
{
__u32 sel, off = sf->index;  
__u64 flags = sf->flags;
__u64 pid;
if (flags & PID_SELECTOR_FLAG_NSPID) {
pid = …
```
=> [bug] matchPIDs is using first pid only

cmd/tetragon/main.go
improve error display when policy dir do not exist when starting tetragon.
Before the change，the error message is not clear to figure out what happens when custom tracing policy dir do not exist, the error message is 
```
time="2025-01-10T10:28:37+08:00" level=fatal msg="Failed to start tetragon" error="stat .: no such file or directory"
```
Now we check all directories upfront and provide better error context.
```
time="2025-01-10T10:38:06+08:00" level=fatal msg="Failed to start tetragon" error="Tracing Policies directory does not exist: /home/arthur/dev/tetragon/my_policy_dir"
```
```
Optimize directory existence check in loadTpFromDir
```
=> fix: improve error handling for tracing policies directory access

cmd/tetragon/main.go, pkg/sensors/program/loader.go
Currently we pin override program with -override suffix, like:
.../generic_kprobe/security_inode_mkdir-override
It's leftover from before we had the the bpffs directory structure, now we should pin it like:
.../generic_kprobe/security_inode_mkdir/prog_override
=> tetragon: Fix override program pin for fmodret and kprobe multi

cmd/tetra/getevents/getevents.go, cmd/tetra/getevents/getevents_test.go, pkg/filters/filters.go, pkg/filters/filters_test.go
Fixes https://github.com/cilium/tetragon/issues/3112
Integrate the existing CEL filtering capability into the CLI
=> tetra: Add CEL filter to the CLI

bpf/process/policy_filter.h, cmd/tetra/common/utils.go, cmd/tetra/debug/dump.go, cmd/tetra/policyfilter/policyfilter.go, cmd/tetra/tracingpolicy/tracingpolicy.go, docs/content/en/docs/reference/helm-chart.md, docs/data/tetragon_flags.yaml, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/tetragon_configmap.yaml, install/kubernetes/tetragon/values.yaml, pkg/option/config.go, pkg/option/flags.go, pkg/policyfilter/k8s_test.go, pkg/policyfilter/map.go, pkg/policyfilter/map_test.go, pkg/policyfilter/policyfilter.go, pkg/policyfilter/state.go, pkg/policyfilter/state_test.go
Add `tetra policyfilter listpolicies` to determine which Kubernetes Identity Aware policies should be applied on a specific container.
Example:
```
$ kubectl exec -it ds/tetragon -n kube-system -c tetragon -- tetra policyfilter -r "unix:///procRoot/1/root/run/containerd/containerd.sock" listpolicies ff433e9e16467787a60ac853d9b313150091968731f620776d6d7c514b1e8d6c
ID   NAME                    STATE     FILTERID   NAMESPACE   SENSORS          KERNELMEMORY
5    lseek-podfilter-usage   enabled   5          (global)    generic_kprobe   1.72 MB
1    lseek-podfilter-app     enabled   1          (global)    generic_kprobe   1.72 MB
```
Details on how this works can be found on specific commits.
=> Add tetra policyfilter listpolicies command

bpf/include/api.h
Add get_current_task_btf so we can reduce bpf_probe_read usage and start using BTF pointer walking on newer kernels.
=> tetragon: add get_current_task_btf

bpf/process/addr_lpm_maps.h, bpf/process/argfilter_maps.h, bpf/process/bpf_execve_event.c, bpf/process/bpf_generic_kprobe.c, bpf/process/bpf_generic_lsm_core.c, bpf/process/bpf_generic_retkprobe.c, bpf/process/bpf_generic_tracepoint.c, bpf/process/bpf_generic_uprobe.c, bpf/process/policy_filter.h, bpf/process/string_maps.h, bpf/process/types/basic.h
Using __type(key, type) instead of __uint(key_size, sizeof(type)), and similarly for value, adds BTF information on the map which can be useful. When using 'bpftool map dump' with the BTF information, the formatting is then correct according to the types.
This patch is the result of running:
find bpf -type f -exec sed -i -E 's/__uint\(value_size,\s*sizeof\(([^)]+)\)\)/__type(value, \1)/g' {} +
find bpf -type f -exec sed -i -E 's/__uint\(key_size,\s*sizeof\(([^)]+)\)\)/__type(key, \1)/g' {} +
Some __uint(value_size were kept because they did not use sizeof but literal integers.
=> bpf: declare maps with __type for key and value

AUTHORS, api/vendor/github.com/cilium/tetragon/AUTHORS
See: https://github.com/cncf/foundation/blob/main/copyright-notices.md#why-not-list-every-copyright-holder
CC: @tpapagian @mtardy @michaelhyatt @will-isovalent @ScriptSathi please have a look at the second patch and let me know if you have another preference for the email address in the AUTHORS file.
TODO: add a step in the release process to update the AUTHORS file.
=> Create an AUTHORS file for tetragon

docs/content/en/docs/getting-started/enforcement.md, docs/content/en/docs/getting-started/file-events.md, docs/content/en/docs/getting-started/network.md
Fixes https://github.com/cilium/tetragon/issues/3304
Fix typo "kubesystem".
=> docs: fix typo referencing kube-system as kubesystem

cmd/tetra/main.go
The grpc update to v1.70.0 and especially [1] requires retries to be > 1 in order to have a valid retry policy.
As we already do +1 later, let's set the default to 1.
[1] https://github.com/grpc/grpc-go/pull/7905
Suggested-by: Anastasios Papagiannis <anastasios.papagiannis@isovalent.com>
=> tetra: Set default for retries to 1

pkg/process/cache.go
When running comand "tetra debug dump processcache", we get sometimes the following error:
Error: failed to get process dump debug info: rpc error: code = Internal desc = grpc: error while marshaling: marshaling tetragon.GetDebugResponse: size mismatch (see https://github.com/golang/protobuf/issues/1609): calculated=1240, measured=1269
By checking the link provided in the error message, we can see that the most possible cause of the error is accidental sharing and concurrent mutation of a Protobuf message or submessage.
To avoid that issue, this patch clones mutable submessages.
We managed to reproduce that in a server with heavy load. This patch seems to solve that issue.
=> tetra/debug: Clone GetDebugResponse entries

cmd/tetragon-vmtests-run/image.go
Backport https://github.com/cilium/tetragon/pull/3232
=> [backport/v1.1][CI] Fix virt-customize issue in vmtests

pkg/process/cache.go
Backport of https://github.com/cilium/tetragon/pull/3343
=> [backport/v1.3] tetra/debug: Clone GetDebugResponse entries

pkg/process/cache.go
Backport of https://github.com/cilium/tetragon/pull/3343
=> [backport/v1.2] tetra/debug: Clone GetDebugResponse entries

pkg/observer/observertesthelper/docker/docker.go, pkg/observer/observertesthelper/observer_test_helper.go, pkg/sensors/exec/exec_test.go, pkg/sensors/exec/procevents/proc.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/exec/procevents/proc_reader_test.go, pkg/sensors/exec/procevents/proc_test.go
Recently we introduced the in_init_tree flag into execve map values to indicate whether
a process is a member of the initial process tree for a container. This worked well for
containers started after Tetragon, but broke for cases where the container was started
before Tetragon, since our procfs walk did not account for the in_init_tree flag. Fix this
behaviour by introducing logic in the procfs walk to account for this.
```release-note
Fix in_init_tree flag for processes started before Tetragon.
```
=> proc_reader: handle in_init_tree

pkg/process/cache.go, pkg/process/process.go
This will be used in follow-up PRs for creating tests check process cache entries.
=> Add the ability to get process cache entries

pkg/process/cache.go, pkg/process/process.go
[upstream commit 5e46dc7d2f4d4a28d6e3c5e044f2aecf2e953701]
This will be used in follow-up PRs for creating tests check process cache entries.
=> [backport/v1.3] Add the ability to get process cache entries

pkg/process/cache.go, pkg/process/process.go
[upstream commit 5e46dc7d2f4d4a28d6e3c5e044f2aecf2e953701]
This will be used in follow-up PRs for creating tests check process cache entries.
=> [backport/v1.2] Add the ability to get process cache entries

pkg/sensors/unloader/unloader.go
I'm really unfamiliar with this part of the code, do we need something similar for tc? Does it make sense to not detach on `unpin=false`?
```release-note
Fix a bug where unloading programs where detaching them even in the case of unpin false (i.e.) --keep-sensors-on-exit
```
=> pkg/sensors: RawDetachUnloader do not detach on unpin false

pkg/sensors/program/loader.go
Links were not pinned to the fs and thus --keep-sensors-on-exit was not working with program using such attach mechanism since they were garbage collected by the kernel on closing the file descriptor.
=> pkg/sensors: pin link in TracingAttach

bpf/lib/process.h, contrib/upgrade-notes/latest.md, docs/content/en/docs/reference/metrics.md, pkg/metrics/mapmetrics/mapmetrics.go, pkg/observer/observer_stats.go
Adding map_errors_update_total/map_errors_delete_total metrics, which replace current tetragon_map_errors_total.
=> tetragon: Add map_errors_update_total/map_errors_delete_total metrics

pkg/vmtests/skip.go
TestFastK8s was introduced in 7043d06fc5d79be8a9147e6fa98387739a0b41ba.
TestFastK8s has been flaky (see issue 2972). Not sure why this is the case. Maybe some timing issue with respect to the k8s controller and fake client initialization.
This commit disables it for vmtests since it does not load any bpf programs and so it is not kernel dependent.
Fixes: https://github.com/cilium/tetragon/issues/2972
=> vmtests: disable TestFastK8s

docs/content/en/docs/policy-library/observability/_index.md
Fixed the Example jq filter command in Observability Policies "Privileges Escalation via File Capabilities Execution".
=> docs: fix the Example jq filter in Observability Policies

.gitattributes
Since our generated files need to be updated via codegen targets after a rebase anyway, it makes no sense to manually resolve conflicts in them with mergetool. Therefore, let's have git automatically choose a dummy merge strategy for our generated files to streamline the process of making rebases.
=> gitattributes: auto resolve merge conflicts for generated files

.github/renovate.json5
Recently Renovate tried to to update google/cel-go to 0.23, but it turns out incompatible with k8s.io/apiserver 0.32. As Go dependencies are grouped, this is now blocking updates of other packages (cilium/tetragon#3290). Let's group cel-go together with k8s packages for now, so that it's not getting updated until we update to k8s 1.33.
=> renovate: Group cel-go together with k8s dependencies

bpf/lib/process.h, cmd/tetragon/main.go, docs/data/tetragon_flags.yaml, pkg/option/config.go, pkg/option/flags.go, pkg/sensors/base/base.go, pkg/sensors/exec/exec.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/load.go, pkg/sensors/program/cgroup/cgroup.go, pkg/sensors/program/loader.go, pkg/sensors/program/map.go, pkg/sensors/sensors.go, pkg/sensors/test/cgroups.go, pkg/sensors/test/sensors_test.go, pkg/sensors/tracing/enforcer.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/genericlsm.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/genericuprobe.go, pkg/sensors/tracing/loader.go
Adding execve-map-entries option to setup entries of execve_map map, plus related loader changes.
=> tetragon: map changes

pkg/sensors/base/base.go, pkg/sensors/exec/procevents/proc_reader.go
So it can serve as library function for others.
=> tetragon: Add GetExecveEntries function

docs/content/en/docs/concepts/tracing-policy/hooks.md, docs/content/en/docs/concepts/tracing-policy/selectors.md, examples/tracingpolicy/tcp-listen.yaml, pkg/bench/trace_bench_rw.go, pkg/sensors/tracing/kprobe_amd64_test.go, pkg/sensors/tracing/kprobe_test.go
Fixes https://github.com/cilium/tetragon/issues/3369
`.returnArg.index` was lacking.
In addition to the documentation, i also fix the examples and source code.
```release-note
```
=> fix: returnArg index of TracingPolicy is not specified

bpf/process/generic_calls.h, bpf/process/types/basic.h, docs/content/en/docs/concepts/tracing-policy/hooks.md, examples/tracingpolicy/lsm_track_grandparent.yml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/api/tracingapi/client_kprobe.go, pkg/btf/btf.go, pkg/btf/btf_test.go, pkg/generictypes/generictypes.go, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/sensors/tracing/generic.go, pkg/sensors/tracing/generic_test.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/genericlsm.go, pkg/sensors/tracing/genericuprobe.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
The discussion for this PR can be found here https://github.com/cilium/tetragon/issues/3142
Take this PR in the today state as a proof of concept for dynamic parameter extraction. I will continue to work on this PR until the below checks are done.
At the current state, the PR is able to
This PR introduce the dynamic extraction of a custom attribute
You can use the following config
```yaml
metadata:
name: "lsm"
spec:
lsmhooks:
- hook: "bprm_check_security"
args:
- index: 0
type: "string"
resolve: "file.f_path.dentry.d_name.name"
selectors:
- matchArgs:
- index: 0
operator: "Postfix"
values:
- "ls"
- "sh"
- "bash"
```
```release-note
Add attribute resolution
```
=> Add dynamic extraction of a parameter attribute

.github/renovate.json5
Go automatically removes the toolchain when the go version is equal to the toolchain version so let's do best effort: try to parse the toolchain directive, if it fails, parse the golang version directive directly.
=> renovate: more robust parser for Go version in go.mod

bpf/process/generic_calls.h
Moving extract code into separate function to simplify to generic_process_event function.
=> tetragon: Move extract code into separate function

.github/workflows/generated-files.yaml
Use `${{ github.ref_name }}` instead of `${{ github.ref }}` to hopefully finally fix an
issue with the branch name passed to buf.
=> ci: fixes for buf workflow

api/Makefile, contrib/scripts/repo-docker-run.sh
Currently, "make protogen" does not work with worktrees. Add a script and modify the Makefile to support it.
=> api/Makefile: make it work for worktrees

pkg/bpf/detect.go, pkg/sensors/tracing/genericlsm.go
Checking the contents of `/sys/kernel/security/lsm` file is redundant because later simple LSM program is loaded. File check makes problems when you trying to load LSM sensor in k8s cluster. We can remove this check without losing stability.
Fixes #3392 
Some discussion can be found here: #3404
=> pkg/bpf: remove redundant check from HasLSMPrograms

bpf/process/types/basic.h, examples/tracingpolicy/security_inode_follow_link.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/generictypes/generictypes.go, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/sensors/tracing/args.go, pkg/sensors/tracing/kprobe_test.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Adding support to extract dentry full path via new 'dentry' type,
which presents the data as as path_arg argument.
So following spec:
```
spec:
kprobes:
- call: "security_path_unlink"
syscall: false
args:
- index: 1
type: "dentry"
```
gives you:
`   args{"path_arg":{"path":"/tmp/TestKprobeDentryPath4036433650/001/dentry-unlink872807283", "permission":"-rw-------"}}
`
**Note** dentry type can extract path only to the first mount point.
Note this patch is based on work of David Windsor, adding his SOB.
=> add dentry type

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/values.yaml
This PR adjusts the default  `operator: Exists` toleration for the Tetragon Operator Deployment introduced in https://github.com/cilium/tetragon/pull/1817.
The Tetragon Operator deployment doesn't need that; it should usually only be scheduled when the node(s) are ready. It typically doesn't need to be running before (as it would be for a CNI, for example). Also, if specific tolerations for node taints are still required in some corner cases, the Helm default value can still be overridden.
The reason for this change is that an `operator: Exists` toleration can lead to situations where it conflicts with the [ContainerStatusUnknown admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaulttolerationseconds). For example, when a (single-)node …
=> helm: Removed default tolerations for the operator

.github/workflows/static-checks.yaml
git rev-list --reverse -1 [...] first truncate the result to one and then reverse the list. I initially thought it was in the other order.
=> workflow: fix a bug in build every commit

pkg/metrics/metricwithpod_test.go, pkg/metrics/syscallmetrics/syscallmetrics.go
Use syscall type to generate metrics. Now that we have a syscall-specific type, we can check for it across all arguments.
=> syscallmetrics: use syscall type

contrib/tetragon-rthooks/cmd/oci-hook/main.go
In https://github.com/cilium/tetragon/pull/3057 we tried to fix an issue with the rootDir in createRuntime hook. But this fix didn't seem to be enough.
The issue is that we compare configName with "config.json". But in https://github.com/cilium/tetragon/blob/e540d11870958a71be87bd29c9c0db47c8e8e035/contrib/tetragon-rthooks/cmd/oci-hook/main.go#L235-L237 the configName points to the full path of the config file. So this patch fixes the comparison to be with the full path instead of the file name.
=> rthooks: Fix rootDir in createRuntime hook

cmd/tetra/getevents/getevents.go
In certain situations (e.g., development) it's useful to have a tetra client constantly running as you are restarting the tetragon agent. Add a --reconnect option in the tetra getevents command to support this.
```release-note
tetra: add a --reconnect option to getevents command
```
=> tetra/getevents: add a --reconnect option

docs/content/en/docs/concepts/tracing-policy/options.md
The location of the link and description for Uprobe Options is unnatural.
https://tetragon.io/docs/concepts/tracing-policy/options/
=> docs: fix tracing policy options

docs/content/en/docs/concepts/events.md
We had some incorrect event types that erroneously made their way into our documentation examples. Let's remove and replace them with event types that are actually supported.
```release-note
docs: Remove incorrect event types from field filter docs examples.
```
=> docs: remove incorrect event types

install/kubernetes/tetragon/templates/tetragon_configmap.yaml
fixes 3b043f1f926b2cba93f4c4a34a1be786ada4556b
See: https://github.com/cilium/tetragon/issues/2639#issuecomment-2718853910
=> install/kubernetes: fix typo

bpf/process/generic_calls.h
We are facing issues when compiling bpf code with another clang version, adding the index bounds check fixes it.
=> tetragon: Add extra bounds check to extract_arg

install/kubernetes/tetragon/templates/_extensions.tpl, install/kubernetes/tetragon/templates/clusterrole.yaml, install/kubernetes/tetragon/templates/operator_clusterrole.yaml, install/kubernetes/tetragon/templates/operator_configmap.yaml
Add three more extensions points to the Helm chart. This is useful e.g. when extending the Helm chart with new CRDs.
=> helm: Allow extending clusterroles and operator configmap

cmd/tetragon/main_linux.go, pkg/watcher/watcher.go
Commit https://github.com/cilium/tetragon/commit/7dc13f82781ec6d0258e398281f847217d252513 ("crdwatcher: Reuse watcher.K8sWatcher to watch TracingPolicy")
reorganized the order of execution in the main function to start watching all
Kubernetes resources at once. In hindsight, this was a bit shortsighted. There
are two purposes Tetragon is watching Kubernetes API for:
1. retrieving Kubernetes metadata for processes
2. managing policies
These two should kick off at different times in the startup order. The former
should happen before the sensors are loaded, as otherwise events will be stuck
waiting for Kubernetes metadata. The latter should happen after the sensors are
loaded, as otherwise existing policies will fail to load on the first attempt.
To solve the problem, split informers used …
=> main: Split k8s watchers into process metadata and policy

.github/workflows/lint-proto.yaml, api/Makefile, docs/content/en/docs/reference/grpc-api.md
Commit https://github.com/cilium/tetragon/commit/eea39fd71e5b459675c048ede3160e2ec72ea4e5 ("api: build using buf") migrated proto API docs generation
to use buf, but also removed the script copying the generated README into the
docs directory from the Makefile. We still want API reference on the docs page,
so let's bring it back.
cc @will-isovalent
=> api: Copy API reference into docs 

contrib/upgrade-notes/latest.md, docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/operator_configmap.yaml, install/kubernetes/tetragon/templates/operator_deployment.yaml, install/kubernetes/tetragon/templates/operator_role.yaml, install/kubernetes/tetragon/templates/operator_rolebinding.yaml, install/kubernetes/tetragon/values.yaml, operator/cmd/serve/serve.go, operator/option/config.go
Required changes to leverage the already built-in `LeaderElection` support from https://github.com/cilium/tetragon/blob/main/operator/cmd/serve/serve.go. 
Added support to run multiple Tetragon Operator replicas. This also includes minor Helm adjustments regarding the rollingUpdate strategy and the affinity (podAntiAffinity). That's required to prevent situations where upgrades are stuck because of impossible-to-reach `maxUnavailable` values and both replicas are running on the same node.
> Besides installing CRDs, Tetragon Operator provides some functionality required to annotate events with additional metadata. If Tetragon Operator is disabled, some fields might be missing from generated events.
Hence, depending on how important this metadata is to somebody, the operator can still be …
=> Added support to run multiple Tetragon operator replicas simultaneously

pkg/watcher/fake.go, pkg/watcher/pod.go, pkg/watcher/pod_test.go
The K8sWatcher.FindPod method first tries to find a pod using index, then, if
unsuccessful, falls back to walking the entire pods list. This fallback was
incorrect - fix it.
I'm not sure how often or if ever this code path was being hit in the wild - it
would be hit only if the index got out-of-sync. It would be good to understand
it, but for now let's just fix the bug.
=> watcher: Fix K8sWatcher.FindPod

pkg/errmetrics/err_msg_windows.go, pkg/errmetrics/err_msg_windows_test.go
Add windows specific definition of GetErrorMessage() function to convert error code into string, using the sys/Windows package.
Added unit test to check strings related to common Windows errors.
```
Compile and run unit tests on the package pkg/errmetrics on Windows
```
=> tetragon/windows: Port package errmetrics to Windows

pkg/metrics/syscallmetrics/raw_syscall_name_windows.go
Adding stub function to compile metrics package on Windows
```
Compile the package pkg/metrics on Windows
```
=> tetragon/windows: Compilation only change for pkg/metrics/syscallmetrics

pkg/watcher/fake.go, pkg/watcher/watcher.go
=> [v1.2] watcher: Fix pod lookup if the index is out-of-sync

pkg/encoder/raw_syscall_enter.go, pkg/encoder/raw_syscall_enter_windows.go
Added windows specific stub of the function `rawSyscallEnter()` in `encoder/raw_syscall_enter.go` listing of encoder package to allow it to compile on Windows
```
Compile  the package pkg/encoder on Windows
```
=> tetragon/windows: Compilation only change to build encoder package 

pkg/kernels/kernels.go, pkg/kernels/kernels_common.go, pkg/kernels/kernels_windows.go
Adding windows specific kernel version retrieval via ntdll!RtlGetVersion Win32 API. 
The `kernels_common.go` file is added to convert string version to numeric across all OS.
kernels.go continues to be a //go:build !windows listing
```
Add windows implementation to kernels package.
```
=> tetragon/windows: Port pkg/kernels to Windows

pkg/cgroups/cgroups.go, pkg/cgroups/cgroups_linux.go, pkg/cgroups/cgroups_windows.go
Add windows specific stub function definitions to compile pkg/cgroups package on Windows. 
Common types and functions added in cgroups.go
```
Compile  the package pkg/cgroups on Windows
```
=> tetragon/windows: Compilation only change to compile cgroups package

pkg/multiplexer/multiplexer.go, tests/e2e/checker/rpcchecker.go, tests/e2e/helpers/grpc/grpc.go, tests/e2e/helpers/portforward.go, tests/e2e/state/state.go
Fix e2e tests port-forwarding issues.
See commits.
=> e2e: port forwarding fixes

pkg/pidfile/pid_alive_linux.go, pkg/pidfile/pid_alive_windows.go, pkg/pidfile/pidfile.go, pkg/pidfile/pidfile_test.go
pidfile package works well on windows, except readPidFile() function, which needs to access the proc filesystem. 
In Windows, we directly query the os to check if the pid is running.
This change results in compiled pidfile package in Windows and passed unit tests.
```
Compile and run unit tests on the package pkg/pidfile on Windows
```
=> tetragon/windows: Port pidfile package on Windows

pkg/procsyms/procsyms.go, pkg/procsyms/procsyms_linux.go, pkg/procsyms/procsyms_windows.go
Stubbing out the GetFnSymbol function on Windows to make sure pkg/procsysms compiles on Windows.
```
Compile the package pkg/procsyms on Windows
```
=> tetragon/windows: Compilation only Change for pkg/procsyms on Windows

pkg/constants/constants_windows.go, pkg/ktime/ktime.go, pkg/ktime/ktime_linux.go, pkg/ktime/ktime_test_windows.go, pkg/ktime/ktime_windows.go, pkg/sensors/exec/exec_windows.go, pkg/sensors/load.go, pkg/sensors/load_linux.go, pkg/sensors/load_windows.go, pkg/sensors/sensor_types_linux.go, pkg/sensors/sensor_types_windows.go, pkg/sensors/sensors.go, pkg/sensors/tracing/lists_windows.go, pkg/sensors/tracing/loader_windows.go, pkg/sensors/tracing/policyhandler.go, pkg/sensors/tracing/policyhandler_linux.go, pkg/sensors/tracing/policyhandler_windows.go, pkg/sensors/unloader/unloader.go, pkg/sensors/unloader/unloader_linux.go
This change attempts to port `ktime`, `constants` and `pkg/sensors` package to Windows following changes made via #3445. This is the strategy
1. Windows specific .go files are added in this PR for ktime, constants and sensors package
2. We bring back `pkg/sensors/unloader/unloader.go` , `pkg/sensors/tracing/policyhandler.go` and `pkg/sensors/sensors.go` and separate only platform specific code in these listings. 
3. Lot of code, we know not used on Windows is removed. Examples include LSM, multi kprobes etc. 
4. Functions required to build on Windows, but are not supported return "not supported on windows" error
This is a change to prepare for Windows build and port. This does not compile on Windows yet, as more changes to dependent packages will be added in subsequent PR. 
```
Add …
```
=> Windows: Build tetragon on Windows (Part -2)

pkg/metricsconfig/healthmetrics.go, pkg/metricsconfig/healthmetrics_linux.go, pkg/metricsconfig/healthmetrics_windows.go
Compilation-only change.
Add windows specific stub-function: `registerHealthMetricsEx` in an otherwise platform independent metricsconfig package This enables compilation of `pkg/metricsconfig` on Windows. 
```
Compile the package pkg/metricsconfig on Windows
```
=> tetragon/windows: Compilation only change for pkg/metricconfig package on Windows

pkg/multiplexer/multiplexer.go, tests/e2e/checker/rpcchecker.go, tests/e2e/helpers/grpc/grpc.go, tests/e2e/helpers/portforward.go, tests/e2e/state/state.go
Backported PRs
* https://github.com/cilium/tetragon/pull/3555
* [e2e tests: fix port-forwading race](https://github.com/cilium/tetragon/commit/b5962e4b432b54760a8398fe87af7b604befbd74)
* [e2e tests: use existing connections.](https://github.com/cilium/tetragon/commit/1365b31cb719ac064e05d002dcb739a850b732df)
=> v1.4 backports 20250326

pkg/multiplexer/multiplexer.go, tests/e2e/checker/rpcchecker.go, tests/e2e/helpers/grpc/grpc.go, tests/e2e/helpers/portforward.go, tests/e2e/state/state.go
Backported PRs
* https://github.com/cilium/tetragon/pull/3555
* [e2e tests: fix port-forwading race](https://github.com/cilium/tetragon/commit/b5962e4b432b54760a8398fe87af7b604befbd74)
* [e2e tests: use existing connections.](https://github.com/cilium/tetragon/commit/1365b31cb719ac064e05d002dcb739a850b732df)
=> v1.3 backports

install/kubernetes/tetragon/templates/_container_rthooks.tpl
extraHookArgs was wrong: we should use the value if the value is not null. Also, let's add -- to the options to make things easier to write.
```release-note
helm: fix extraHookargs in rthooks
```
=> helm: rthooks: fix extraHookArgs

bpf/lib/generic.h, bpf/process/bpf_generic_kprobe.c, bpf/process/bpf_generic_lsm_core.c, bpf/process/generic_calls.h, bpf/process/generic_path.h, bpf/process/heap.h, bpf/process/types/basic.h, docs/content/en/docs/concepts/tracing-policy/argument_types.md, pkg/generictypes/generictypes.go, pkg/selectors/kernel.go, pkg/sensors/tracing/generic.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/genericlsm.go, pkg/sensors/tracing/kprobe_test.go, pkg/sensors/tracing/lsm_test.go
adding support to retrieve full path from kprobe/lsm arguments from most kernels,
4.19 has still some limits, but it's better
=> tetragon: add support for path offload

install/kubernetes/tetragon/templates/_container_rthooks.tpl
Backported PRs
* https://github.com/cilium/tetragon/pull/3566
* [helm: rthooks: fix extraHookArgs](https://github.com/cilium/tetragon/commit/b9ed8ba4db94292ff2d86465f14e19bfa52a6fdf)
=> 1.4 backports

pkg/cgroups/cgroups_windows.go, pkg/constants/constants_windows.go, pkg/sensors/tracing/lists_windows.go, pkg/sensors/tracing/policyhandler_windows.go
Certain stub functions on Windows that are added for compilation support return an `errors.New("not supported on windows")` error which can be a package-level variable. This PR attempts to declare and use such a variable for packages that use that error more than once.
=> tetragon/windows: Use a package-level 'not supported' error variable

pkg/sensors/exec/procevents/proc.go, pkg/sensors/exec/procevents/proc_linux.go, pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/exec/procevents/proc_reader_linux.go, pkg/sensors/exec/procevents/proc_reader_windows.go, pkg/sensors/exec/procevents/proc_windows.go, pkg/sensors/exec/userinfo/userinfo_test.go
Port tetragon functions that use the proc-fs to query running processes or process properties into Windows to query the same using WIN32 APIs. The function to populate the exec map is stubbed out but not removed and will be implemented once the ebpf program on windows supports that.
```
Port the package sensor/exec into Windows. This allows Tetragon on Windows to load Windows based sensors.
```
=> tetragon/windows: port package sensors/exec/procevents into Windows

pkg/constants/constants_linux.go, pkg/constants/constants_windows.go, pkg/reader/network/inet_family_windows.go, pkg/reader/path/path.go
Two commits added to compile sub packages in reader package. 
1. pkg/reader/path can be compiled on Windows by using a platform dependent S_IFMT bitflag constant
2. pkg/reader/network can be compiled on Windows by adding correct values into the inetFamily map variables.
Both changes depend on constants package, added [here](https://github.com/cilium/tetragon/commit/0055bd6bd29a7e641bb124102932fd0e21aadb80)
=> tetragon/windows: Build reader/path and reader/network packages on Windows

pkg/defaults/defaults_windows.go
Moved over `defaults.go` to `defaults_linux.go` .
Added `defaults_windows.go` to add set of default paths and names for Windows. 
Some default definitions are stubbed out for compilation.
```
Port the package defaults to Windows
```
=> tetragon/windows: Add default definitions for Windows

pkg/reader/exec/signal_windows.go
Windows signal handler requires specific map to identify signal codes and convert into code and string. This PR adds that map and implements the signal code to string conversion
=> tetragon/widows: Add signal translation for Windows

pkg/bpf/bpffs.go, pkg/bpf/bpffs_linux.go, pkg/bpf/bpffs_windows.go, pkg/bpf/detect_windows.go, pkg/bpf/perf.go, pkg/bpf/perf_windows.go
This PR has commits that contribute to compiling and running pkg/bpf package into Windows. 
The bpffs and and kernel features checking functions are stubbed out in Windows specific go listings
The per event based functions stay the same, except the `UpdateElementFromPointers()` function which uses the `bpf()` function available in `ebpfapi.dll`. 
```
Compile pkg/ebpf package on Windows
```
=> tetragon/windows: Port bpf package into Windows

cmd/tetra/cgtracker/cgtracker_windows.go, cmd/tetra/debug/debug_windows.go, cmd/tetra/tracingpolicy/generate/all_syscalls.go, cmd/tetra/tracingpolicy/generate/all_syscalls_windows.go, cmd/tetra/tracingpolicy/generate/generate.go
Compilation changes so tetra binary could compile and  run on Windows. This accomodates changes made to various pkg/ packages in previous PRs Most changes just add stubs to windows specific listing, while keeping Linux and Darwin build unchanged
```
Compile and run tetra.exe on Windows 
```
=> tetragon/windows: Port cmd/tetra binary into Windows

pkg/process/process.go, pkg/process/process_id_linux.go, pkg/process/process_id_windows.go
This PR compiles and ports process cache into Windows. The only difference on Windows is how the pid for cache is computed. Currently on Windows, we are not using ktime as an input into process identifier.
The PID re-use is not a very big problem on Windows and the current bpf program does not communicate the parent's ktime to usermode. 
So the cache pid  on windows is based on numeric PID issued by kernel.
```
Compile and port the pkg/process package into Windows
```
=> tetragon/windows: Port process cache package on Windows

pkg/observer/observer.go, pkg/observer/observer_linux.go, pkg/observer/observer_windows.go
This PR lists observer side changes to support CreateProcess and ExitProcess events. 
Newly created processes are notified to user-mode via ring-buffer and their image path and command-line are queried via maps. 
The code casts the data received from ring-buffer in structures similar to Linux exec bpf program. This lets the event show up as a protobuf exec event.
```
Tetragon on Windows supports Create Process and Exit process events via bpf programs  specific to Windows.
```
=> tetragon/windows: Support Windows create and exit process - observer changes

.github/workflows/gotests.yml
To help debugging between arch, I think it is a great idea to upload the vmlinux file when this test fails
This will help fixing https://github.com/cilium/tetragon/issues/3492
`TestSpecs` uses `ksys_lseek`  symbol which is inlined (I think) on ARM but not on x86_64. If we upload the vmlinux, we can load the BTF spec and check what hooks are shared
https://github.com/cilium/tetragon/pull/3414#issuecomment-2733004356
Kprobes are not exactly the same between ARM and x86_64. To help understand why some tests fail on one architecture and not the other, it can be helpful to use the vmlinux file directly from the CI instead of deploying a specific VM with the same architecture for debugging.
=> ci: In "Tetragon Go Test" add vmlinux in artifact when test fails

bpf/Makefile, bpf/include/vmlinux.h, bpf/lib/bpf_cgroup.h, bpf/process/bpf_execve_event.c, bpf/process/bpf_exit.h, bpf/process/bpf_fork.c, bpf/process/bpf_process_event.h, contrib/verify/verify_test.go, pkg/config/config_linux.go, pkg/reader/namespace/namespace_linux.go, pkg/sensors/base/base.go, pkg/sensors/exec/procevents/proc_reader_linux.go
assorted changes to be able to run on rhel7
=> tetragon: rhel7 changes

pkg/sensors/base/base.go, pkg/sensors/base/base_linux.go, pkg/sensors/base/base_windows.go, pkg/sensors/config/confmap/confmap.go, pkg/sensors/load.go, pkg/sensors/load_linux.go, pkg/sensors/load_windows.go, pkg/sensors/program/loader.go, pkg/sensors/program/loader_linux.go, pkg/sensors/program/loader_windows.go
This PR lists sensor side changes to support CreateProcess and ExitProcess events. 
The program loader needs to load the entire collection of native Windows ebps program image using cilium/ebpf library. 
The specs for a native Windows bpf program is not available as it is not in ELF format 
This changes the order in which maps are loaded - collection is loaded first which loads maps and programs automatically.
```
Tetragon on Windows supports Create Process and Exit process events via bpf programs  specific to Windows.
```
=> tetragon/windows:  Support Windows create and exit process - sensor changes

bpf/Makefile, bpf/process/bpf_generic_rawtp.c, bpf/process/generic_calls.h, docs/content/en/docs/concepts/tracing-policy/hooks.md, examples/tracingpolicy/rawtp.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/grpc/tracing/tracing.go, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, pkg/sensors/tracing/generic.go, pkg/sensors/tracing/generic_test.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/genericlsm.go, pkg/sensors/tracing/generictracepoint.go, pkg/sensors/tracing/tracepoint_test.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
adding support for raw tracepoints, which allows to use raw tracepoint arguments, like:
```
metadata:
name: "rawtp"
spec:
tracepoints:
- subsystem: "sched"
event: "sched_process_exec"
raw: true
args:
- index: 2
type: "linux_binprm"
```
also there's support for argument resolve keyword
=> tetragon: add raw tracepoints

pkg/bpf/coll_windows.go, pkg/bpf/ringbuf_windows.go
This PR adds changes specific to Windows to support ring buffer reads from user-mode using synchronous APIS and also add a global ebpf collection object. 
Reading ringbuffer on Windows is implemented  using Windows device io control API. This is a transitory change as libbpf based implementation to read ringbuffer using Linux-style synchronous API is currently in the works.
The ringbuffer maps on Windows currently have some issues with pinning. As a result we do not pin maps after program load.
In order to read from those maps we need to keep a global collection object alive and use the FD in the collection object to read from those maps.
This is a transitory change till pinning issues is fixed on Windows.
After which, this global object will be removed and we will use pinned maps to read …
=> tetragon/Windows: Add support for process create and exit - ring-buffer 

pkg/exporter/exporter_test.go, pkg/grpc/process_manager_test.go, pkg/reader/node/node.go, pkg/reader/node/node_test.go, pkg/watcher/watcher.go
The HUBBLE_NODE_NAME env var is useful to add extra metadata to the "node_name" field for exported events. Often the Kubernetes node name is not very descriptive, and additional information is useful. This can be archived by eg. overriding the following helm values, where k8s will replace the $(NODE_NAME) with the existing NODE_NAME env var in the helm chart, populated from the actual node name.
```
tetragon.extraEnv=[{"name":"HUBBLE_NODE_NAME", "value":"$(NODE_NAME)-additional-info-here.domain.tld"}]
```
Prior to bcf9429 ("Watcher: fix NODE_NAME if missing") this worked as expected where the export events keep this value, and the Kubernetes pod watcher used the existing NODE_NAME. After that commit, the node watcher stated using the HUBBLE_NODE_NAME, resulting in it not receiving any pod …
=> Fix discrepancy between export and k8s node name

cmd/tetragon/main_test.go, pkg/constants/constants_linux.go, pkg/constants/constants_windows.go, pkg/testutils/filenames.go
Testcases in `cmd/tetragon/main_test.go` work on both OS - Windows and Linux except some constants like /tmp and the init process id, which are added in constants via this PR
=> tetragon/windows: Port Unit Tests in cmd/tetragon on Windows

pkg/alignchecker/alignchecker_test.go, pkg/bugtool/maps_test.go, pkg/cgrouprate/cgrouprate_test.go, pkg/metrics/metricwithpod_test.go, pkg/policyfilter/map_test.go, pkg/policyfilter/state_test.go, pkg/server/addr_test.go, pkg/tracepoint/tracepoint_test.go
This PR includes changes so that bpftool, cgrouprate, alignchecker, addr_test, tracepoint, and metricwithpod tests do not run on Windows.
Also excludes policyfilter/map_test and policyfilter/state_test on Windows due to difference in behavior on Windows,
=> tetragon/windows: Exclude some unit tests for Windows 

pkg/grpc/exec/exec_test.go, pkg/grpc/exec/exec_test_linux.go, pkg/grpc/process_manager_test.go, pkg/grpc/process_manager_test_linux.go, pkg/grpc/process_manager_test_windows.go
This PR changs the unit tests in grpc package to also run and succeed on Windows. Some exec based unit tests are excluded due to ktime not being present in Windows exec event.
=> tetragon/windows: Port unit tests in grpc package into  Windows

.github/workflows/static-checks.yaml
This PR adds a CI step to cross compile tetragon.exe for Windows on Linux.
=> tetragon/windows: Add windows compile as a ci step

docs/content/en/docs/concepts/events.md
Fixes #3570 
Filter spec has namespace with string list type as below, but document is written using just string, so submitting this PR to fix document.
https://github.com/cilium/tetragon/blob/d595559137b1c7b3104e857ba90e704e4312ee8c/api/v1/tetragon/events.proto#L40
=> doc: update export filtering example

bpf/process/types/basic.h
[ upstream commit ad5c2b02412136e2a095a889eab681e186e79cc8 ]
Currently we only store first byte of flags and mode from path retrieval, which ends up with wrong flags and permissions in all arguments that goes through path retrieval.
fixing it by properly storing the value in argument byte array.
=> tetragon: Fix storing of flags and mode for path

api/go.mod, api/vendor/modules.txt, contrib/tetragon-rthooks/go.mod, contrib/tetragon-rthooks/vendor/modules.txt
The top level go.mod uses the v0.0.0-00010101000000-000000000000 pseudo version for github.com/cilium/tetragon/{api,pkg/k8s} packages, and replaces them with local directories. IDEs like GoLand runs "go list -m" on all the go.mod files. It fails in api/ and contrib/tetragon-rthooks/ with an error like this:
% go list -m -mod=mod all
go: github.com/cilium/tetragon/pkg/k8s@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
because they don't replace indirect dependencies. Replace these indirect dependencies to get rid of the IDE warning.
=> go.mod: Consistently add replace directives

docs/content/en/docs/concepts/events.md
Provide event filter type information on document.
Following PR of https://github.com/cilium/tetragon/pull/3626#issuecomment-2801967868
=> doc: add events.proto link for event filters

pkg/watcher/deleted_pod_cache.go, pkg/watcher/pod.go, pkg/watcher/pod_test.go, pkg/watcher/watcher.go
2 commits:
- export DeletedPodCache so that controller-runtime can use it.
- refactor PodAccessor so that controller-runtime can re-use the common code with its pod informer.
=> Refactor Pod watcher

cmd/tetragon/main.go, pkg/manager/manager.go, pkg/watcher/crdwatcher/tracingpolicy.go
Let controller-runtime manage tracing policy informers to simplify the code a bit. Eventually we'll convert these informers to controllers.
=> Get tracing policy informers from controller-runtime manager

api/Makefile, contrib/scripts/repo-docker-run.sh
probably easier to review commit by commit.
=> Fix / clean up repo-docker-run.sh

.github/workflows/gotests.yml, Makefile, cmd/tetragon/main_test.go, pkg/grpc/process_manager_test_windows.go, pkg/sensors/exec/procevents/proc_reader_test.go
This PR enabled running unit tests on Windows on a windows-latest runner. Tests are run on cmd and pkg folders
=> tetragon/windows: Run unit tests on Windows

examples/README.md, examples/tracingpolicy/hardlink-observe.yaml, examples/tracingpolicy/hardlink-override.yaml, examples/tracingpolicy/openat_write.yaml, examples/tracingpolicy/symlink-observe.yaml, examples/tracingpolicy/symlink-override.yaml
Example policies are meant to illustrate the Tetragon features, and not to be used unmodified in for security. Clarify this in the README and in some of the policies that have TOCTU issues.
=> examples: use explicit wording about guarantees

.github/workflows/windows-build-smoke-test.yml, install/windows/README.md, install/windows/setup-windows.ps1
This CI action does the following actions:
1. Build the process_monitor.sys bpf program and the ntosebpfext.sys driver it depends on. These programs are uploaded as artifacts. 
2. Build tetragon.exe and tetra,exe on a Windows worker and uploads them as artifacts.
3. Downloads the artifacts and installs them, downloads the ebpf-for-windows build and installs it. Runs tetragon.exe and launches a process to see if an event is received.
=> tetragon/windows: Build windows bpf program and smoke test tetragon

.github/workflows/integration-test.yaml, cmd/tetragon/main.go, pkg/manager/manager.go, pkg/manager/manager_integration_test.go, pkg/watcher/deleted_pod_cache.go, pkg/watcher/pod.go, pkg/watcher/pod_test.go
- Use a pod informer from controller-runtime.
- Add a ControllerManager Implementation of the PodAccessor interface.
- Add integration tests for PodAccessor methods.
=> k8s: Let controller-runtime manage the pod informer

pkg/sensors/tracing/genericuprobe.go
this change allows uprobes to use actions like Sigkill with:
```
spec:
uprobes:
- path: ...
selectors:
- matchActions:
- action: Sigkill
```
=> tetragon: Allow uprobes to use actions

pkg/sensors/load_linux.go
Commit 8ce47efeab7a, introduced a cache for the program specs when loading maps. The go tests did not run in the corresponding PR (https://github.com/cilium/tetragon/pull/3685) and, as a result, we ended up with the following failure in main for some (rhel8.9, 5.15, 5.10, 5.3) kernels for the TestKproveOverideMulti test:
observer_test_helper.go:465: SensorManager.AddTracingPolicy error: sensor generic_kprobe from collection sys-openat-signal-override failed to load: failed prog /home/kkourt/src/tetragon/bpf/objs/bpf_generic_kprobe_v511.o kern_version 331700 loadInstance: opening collection '/home/kkourt/src/tetragon/bpf/objs/bpf_generic_kprobe_v511.o' failed: using replacement map override_tasks: MaxEntries: 32768 changed to 1: map spec is incompatible with existing map
The problem is …
=> loaderCache: copy map spec before using it

docs/content/en/docs/concepts/cgroup-rate.md
As title, fixed parameter explanation wrong.
=> doc: fix cgroup rate explanation not match the parameter

.github/workflows/windows-build-smoke-test.yml, bpf/windows/process_monitor.c, pkg/api/processapi/processapi_windows.go, pkg/bpf/coll_windows.go, pkg/bpf/ringbuf_windows.go, pkg/observer/observer_windows.go, pkg/sensors/exec/args_windows.go, pkg/sensors/exec/exec_windows.go, pkg/sensors/program/loader_windows.go
This PR has three commits:
1. Change the bpf program to use  `LIBBPF_PIN_BY_NAME` flag while creating ringbuf map in Windows. This lets the ringbuf map be re-usable across programs. 
2. While porting observer to windows, pkg/observer became dependent on event type and was highly specific to exec event. 
This PR fixes that by adding event specific parsing in sensor 
3. Fix the CI to match changes in bpf program
=> tetragon/windows: Fix observer to make it event independent

pkg/crdutils/crdutils_test.go, pkg/crdutils/testhelpers.go, pkg/eventcheckertests/yaml/yaml_test.go
This is done to improve reusability - the helpers can now be imported from
different packages.
=> crdutils: Move test helpers to dedicated file and export them

pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_test.go
Arguments are appended based on the index value,
so the argument printers need to follow that.
Fixes: https://github.com/cilium/tetragon/issues/3710
=> tetragon: Fix kprobe argument printers order

pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/kprobe_test.go
Running the following policy:
```
metadata:
name: "resolve-sockaddr"
spec:
kprobes:
- call: "security_socket_connect"
syscall: false
args:
- index: 1
type: "uint16"
resolve: "sa_family"
```
Leads to an event wih the wrong value. The issue is that when setting allBTFArgs we need to use the index in the function order rather than the index in the spec order.
This commit fixes the issue, and adds a test for it.
Fixes: https://github.com/cilium/tetragon/issues/3734
```release-note
tracingpolicy: fix issue in argument order with the resolve argument option
```
=> tetragon: fix resolve issue with argument order

pkg/manager/manager.go, pkg/manager/manager_integration_test.go
controller-runtime runs its own metrics server on port 8080 by default. It would be good if we can avoid running multiple metric servers. I need some time to think about how to consolidate Tetragon's metric server and controller-runtime metric server.
=> Temporarily disable controller-runtime metrics

pkg/sensors/program/loader_windows.go
Windows Loader had the process attach type hardcoded in the attach routine. This prevents us from loading other program types supported on Windows like cgroup/connect4 etc. This PR adds some more attach types.
=> tetragon/windows: Add Multiple program attach types

pkg/vmtests/list.go, tools/split-tetragon-gotests/main.go
The way the vmtest action works, is that it uses `./tools/split-tetragon-gotests` to create a list of tests to run.
Originally, this was used to speedup testing by running different tests in different GHA jobs (138bde54e8b5383fe19fab5b7661afe94a1103fc, 476ab862502c7a6ac92aebb1587e7c5a0b95c564), and, also, exclude some tests from being run.
We ended up moving away from the multiple groups approach (24c06e4c4274cbcaff786c140d1623db8ad62a74), but split-tetragon-gotests was still used for test exclusion in vmtests.
split-tetragon-gotests creates a file that specifies which tests to run. Currently, the file allows patterns that work similarly to how an argument to -test.run or -test.list would work.
The problem is that some tests are substrings of others, which results in some tests being …
=> vmtests CI: avoid running duplicate tests

.github/pull_request_template.md, docs/content/en/docs/concepts/tracing-policy/hooks.md
Fixes some reference links on Hook points page
Some links in the documentation are broken.
=> doc: fix some links in documentation

bpf/process/bpf_generic_tracepoint.c, bpf/process/generic_calls.h, bpf/process/types/basic.h, pkg/api/tracingapi/client_kprobe.go
We plan to increase number of supported arguments and it's more convenient with array size.
=> tetragon: Move some event_config values to arrays

bpf/windows/process_monitor.c, pkg/ktime/ktime_windows.go, pkg/ktime/ktime_windows_test.go, pkg/sensors/exec/procevents/proc_reader_windows.go
On Windows the exec/exit event timestamp was serialized incorrectly. All timestamps in Windows are 100 Nanoseconds from 1 Jan 1600. The protobuf serialization routine assumed nanoseconds wrt boot time or monotonic time, which were then converted to Linux Epoch.
This change converts the Windows Epoch based 100 Nanoseconds to Linux Epoch based time before Event is generated. Both existing and new processes are made to report time wrt to Windows Epoch.
=> tetragon/windows: Fix exec/exit event timestamp in event json

cmd/tetragon/main.go, pkg/manager/manager.go, pkg/manager/manager_integration_test.go, pkg/reader/node/node.go, pkg/reader/node/node_test.go
- Rename GetKubernetesNodeName() to GetNodeName()
- Rename SetKubernetesNodeName() to SetNodeName()
- Rename SetKubernetesNodeLabels() to SetNodeLabels()
One could imagine node name / labels might come from other sources outside Kubernetes in the future.
=> refactor: Rename functions in the node package

pkg/sensors/program/loader_linux.go
Currently, we check if btfSpec (BTF in non-normal location) is not nil and use that. If this fails to load, we then try to use user-provided load.KernelTypes. This has the issue that if we use the normal BTF file and the user also  provided load.KernelTypes. we tried that after a failed attempt which may result in missing features in loaded programs.
This patch fixes that issue by trying to load the user-provided load.KernelTypes in the first place if we use the BTF in the common location (i.e. /sys/kernel/btf/vmlinux).
=> btf: Use user-provided KernelTypes if the btfSpec is nil

tests/e2e/helpers/dumpinfo.go, tests/e2e/runners/runners.go, tests/e2e/state/state.go, tests/e2e/tests/labels/labels_test.go, tests/e2e/tests/policyfilter/policyfilter_test.go, tests/e2e/tests/skeleton/skeleton_test.go
fix e2e to call helpers.DumpInfo on setup / test failure. probably easier to review commit by commit. 
- test failure example: https://github.com/cilium/tetragon/actions/runs/15545804930?pr=3812
- setup failure example: https://github.com/cilium/tetragon/actions/runs/15545584308?pr=3812
=> e2e: Capture Tetragon state on failure

tools/protoc-gen-go-tetragon/common/common.go, tools/protoc-gen-go-tetragon/eventchecker/eventchecker.go, tools/protoc-gen-go-tetragon/helpers/helpers.go, tools/protoc-gen-go-tetragon/types/types.go
This is to make sure that we don't rely on import statement and generate the files in unintended directory.
For example, dummy import in bpf.proto, followed by `make codegen` will generate files into google/protobuf instead of `tetragon` dir
```diff
diff --git i/api/v1/tetragon/bpf.proto w/api/v1/tetragon/bpf.proto
index 486c4ed32..08629fac3 100644
--- i/api/v1/tetragon/bpf.proto
+++ w/api/v1/tetragon/bpf.proto
@@ -5,6 +5,8 @@ syntax = "proto3";
package tetragon;
+import "google/protobuf/duration.proto";
+
option go_package = "github.com/cilium/tetragon/api/v1/tetragon";
enum BpfCmd {
```
```bash
$  make protogen
... 
...
buf generate 
time="2025-06-12T03:27:25Z" level=info msg=google/protobuf/codegen/helpers/helpers.pb.go
time="2025-06-12T03:27:25Z" level=info …
```
=> tools: Avoid picking protoc file randomly

tests/e2e/flags/flags.go, tests/e2e/runners/runners.go
Add -tetragon.uninstall-tetragon flag to specify whether Tetragon is uninstalled after the test run. Sometimes I want to run E2E tests in a cluster with Tetragon already installed, and I want to keep Tetragon installed after the test run for debugging purpose like capturing sysdump and such.
=> e2e: Make uninstalling Tetragon optional

pkg/sensors/config/confmap/confmap.go
Use config.FindProgramFile() to load the program, so that compressed .o files work as expected.
Fixes: c66c93870f9f ("tetragon: support loading compressed (gz) .o files")
=> confmap: use config.FindProgramFile()

pkg/bpf/coll_windows.go, pkg/sensors/program/loader_windows.go
This PR changes the way programs are loaded on Windows in order to support loading multiple programs from a single collection. Earlier implementation assumed one program per collection.
In Windows, a collection can be loaded only once per process. In that light, if a sensor had two programs from the same sys file, the loading of the second program would fail, as loading the collection second time around fails.
In the PR, we cache loaded collections by path and check the cache before loading a new collection. The second run will use the cached collection object and load the passed in program.
=> tetragon/windows: Support multiple programs from a single collection

bpf/process/bpf_exit.h, pkg/testutils/sensors/load.go
As reported by Balasaheb we could pollute process cache by rate limiting exit events.
It makes more sense to let all possible exit events go through, because they won't eat much resources and eventually release process cache records.
Otherwise we could end up with hanging process cache records.
Reported-by: Balasaheb Salunke ...
=> RFC tetragon: Do not rate limit exit events

cmd/tetra/common/client.go
This method can be reused in different packages in future patches for configuring client with correct retry mechanism.
=> tetra: export common.RetryPolicy methods

pkg/sensors/load.go
Commit 04a1c6fa9dd2e49dba0ab112e34b97dffa2fc25c attempted to reduce logs by concentrating all the info in a single line. This is still too much information. This commit removes the sensors programs and maps from the loading/unloading log messages.
=> sensor: reduce logs in loading/unloading

pkg/constants/constants_linux.go, pkg/constants/constants_windows.go, pkg/pidfile/pid_alive_windows.go, pkg/pidfile/pid_alive_windows_test.go, pkg/process/process.go, pkg/sensors/exec/procevents/proc_reader_windows.go
In Windows, the ancestor list algorithm was broken due to multiple issues.
- One, on Windows, the ancestor enumeration needs to stop at pid 4, not pid 1.
- Two, Windows has true orphan processes. Which means that if a parent is terminated, it's parent is not automatically pid 4. This PR makes an adjustment to insert pid 4 as parent of orphaned processes. 
- Three, parent may be dead but still exist in kernel, allowing OpenProcess to succeed, even if the process is orphaned. This PR adds a robust process alive check.
=> tetragon/windows: Fix ancestor list

pkg/sensors/exec/procevents/proc_reader.go, pkg/sensors/exec/procevents/proc_reader_linux.go, pkg/sensors/exec/procevents/proc_reader_windows.go
8073fb2df erroneously removed the logic for handling inInitTree from proc events. Add that logic back here.
```release-note
Fix an issue where inInitTree was not properly accounting processes started before Tetragon.
```
=> procevents: fix in-init-tree

docs/content/en/docs/concepts/tracing-policy/hooks.md
Hi!
As discussed [in Slack](https://cilium.slack.com/archives/C03EV7KJPJ9/p1751961517515919?thread_ts=1751631795.554419&cid=C03EV7KJPJ9), one of the Tracing Policy examples in the docs is broken: hooking "security_inode_copy_up" requires the "syscall: false" clause, as this function is not a syscall.
This PR simply adds `syscall: false` to the example code.
=> fix "security_inode_copy_up" example in docs

pkg/filters/cel_expression.go
Based on some profiling, it seems that the call of helpers.ProcessEventMap is a bit heavy in terms of CPU cycles.
This patch changes EvalCEL function to call that outside of the loops.
=> cel: Move heavy operations outside of loops

pkg/bpf/detect_linux.go
Better late than never https://github.com/cilium/tetragon/issues/3317#issuecomment-2601893953
First commit explain why we reverted the patch https://github.com/cilium/tetragon/pull/3456#issuecomment-2695120756, https://github.com/cilium/tetragon/issues/3872#issuecomment-3058064606.
```release-note
Explain why LSM attach might fail on arm64 <6.0 kernels.
```
=> pkg/bpf: explain why LSM attach might fail on arm64 <6.0

docs/content/en/docs/concepts/events.md, docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/values.yaml
Fixes #3742
This PR clarifies the scope of `denylist` and `allowlist` export filters in the Tetragon documentation. Users were confused about why filtered events still appeared in `tetra` CLI output, not realizing these filters only apply to JSON file exports and not to gRPC streaming.
The changes add:
- A prominent caution note in `docs/content/en/docs/events.md` using the `{{< caution >}}` shortcode to clearly explain that export filters only affect JSON file sinks
- Concise inline notes in the Helm chart value tables in both `helm-chart.md` and `README.md` to indicate the filters are "for file sinks only"
These documentation updates will help users understand the intended behavior and avoid confusion when using the `tetra` CLI alongside export filters.
```release-note
docs: Clarify …
```
=> docs: Clarify export filter scope (JSON vs gRPC)

pkg/sensors/tracing/generickprobe.go
If we have a policy such as:
```
metadata:
name: "unload-module"
spec:
lists:
- name: "sys_delete_module" type: "generated_ftrace" pattern: "sys_delete_module" kprobes:
- call: "list:sys_delete_module" syscall: true args:
- index: 0  # module (user-space pointer, so unsafe) type: "string"
- index: 1  # flags type: "uint32"
```
The "syscall: true" is not respected when generating the calls. This commit fixes this.
```release-note
tracinpolicy: respect syscall attribute in lists
```
=> tracingpolicy: respect syscall attribute in lists

docs/content/en/docs/getting-started/network.md
Fixes #2724
Users were confused that the next step, enforcement, wasn't working until they found out that the tutorial didn't told them to remove the previous policy that was still applied.
Suggested-by: SimonB <simonb@kaizo.org>
=> docs: add instruction to cleanup getting started network policy

.github/workflows/build-images-ci.yml, Makefile
Push Helm chart to https://quay.io/repository/cilium-charts-dev/tetragon to make it easier to install Tetragon CI builds.
=> CI: Push OCI Helm chart

.github/workflows/packages-e2e-tests.yaml, pkg/bugtool/bugtool.go
[ upstream commit 15f723f34673b48640033d887d0bf88c2038579c ]
Collect pprof CPU profile as a part of the bugtool output. This makes the bugtool command 30 seconds slower, but I think it's still worth it to always collect CPU profile. Having access to CPU profile is immensely valuable for troubleshooting performance issues, and we often end up manually running 'gops pprof-cpu' to collect it anyways.
Bump the timeout for "Test Tetragon with a different tracing-policy-dir" step in Packages e2e Tests from 30 seconds to 60 seconds. This step runs tetra bugtool command.
=> bugtool: Collect pprof CPU profile

pkg/selectors/kernel.go
The bpf implementations for selectors have a limit of 4 values:
```
#define MAX_MATCH_VALUES 4
...
filter_64ty_selector_val(struct selector_arg_filter *filter, char *args)
{
__u64 *v = (__u64 *)&filter->value;
int i, j = 0;
#pragma unroll
for (i = 0; i < MAX_MATCH_VALUES; i++) {
...
filter_32ty_selector_val(struct selector_arg_filter *filter, char *args)
{
__u32 *v = (__u32 *)&filter->value;
int i, j = 0;
#pragma unroll
for (i = 0; i < MAX_MATCH_VALUES; i++) {
```
Current code just ignores the additional values.
Add a check to return an error in that case.
```release-note
tracingpolicy: return error on unsupported number of values 
```
=> selectors: error on vals larger than supported

install/kubernetes/tetragon/Chart.yaml
Hello, 🖖 
This PR adds icon section on chart.yaml file to make the CI happy with a green status 🟢 
Fixes : N/A
Currently, CI is issuing a warning about the helm linter because it wants to see the icon section in the Chart.yaml file.
My PR suggests adding the section to make the CI happy 👍 
Without icon section :
```
@HujinoKun ➜ /workspaces/tetragon (helm/add-icon-section-on-chart-file) $ make -C install/kubernetes lint
make: Entering directory '/workspaces/tetragon/install/kubernetes'
docker run --rm -u 1000:1000 -v /workspaces/tetragon/install/kubernetes/tetragon:/apps -v /workspaces/tetragon/install/kubernetes/helm_lint_values_override.yaml:/helm_lint_values_override.yaml docker.io/alpine/helm:3.18.3@sha256:afb4ca77e37c03fbf8009cbe29e5c014cfb2e5b1d4afff59c1b38bcd77e03845 lint . …
```
=> feat(helm): add icon section on Chart.yaml file

Makefile
After `make clean`, I got an error when trying to rebuild the tetragon-bpf target:
```
acam@lima-default:~/src/hubble-fgs/modules/tetragon-oss$ make -j3 tetragon-bpf
docker rm tetragon-clang || true
Error response from daemon: cannot remove container "tetragon-clang": container is running: stop the container before removing or force remove
```
This PR contains a simple change to force-remove the tetragon-clang container if it's already running.
=> fix: Force remove tetragon-clang container for the tetragon-bpf target in case it's still running.

bpf/lib/process.h
This is less brittle in the case where the struct's size is later modified.
=> fix: Refactor SIZEOF_EVENT constant to not be a hard-coded value.

docs/content/en/docs/installation/runtime-hooks.md
Fixes 
Line 200 fixed broken type kubecl to kubectl
=> Fix a typo in kubectl in the runtime hook documentation

.github/renovate.json5
After #3767, cilium/tetragon is no longer having cilium/cilium package dependency, so the manual step is no longer required.
Relates: #3767
=> renovate: Remove manual step for cilium/cilium dep

pkg/policyfilter/rthooks/rthooks.go
Move the container ID out of log messages so that they aggregate better.
=> rthooks: Log container ID as a key-value pair

.github/ISSUE_TEMPLATE/release_template.md
After merging https://github.com/cilium/charts/pull/187 we now have a kind (instead of a GKE) deployment to test Tetragon charts.
This patch updates release template to reflect that.
=> Update release template

pkg/sensors/config/confmap/confmap.go, pkg/testutils/confmap.go
This is to fix the the below failure by ignoring the condition check.
Failure run https://github.com/cilium/tetragon/actions/runs/16615955129/job/47008554004?pr=3967
```
pkg/sensors/config/confmap/confmap.go:88:5  staticcheck  SA4023: this comparison is always true
...
pkg/testutils/confmap.go:25:5               staticcheck  SA4023: this comparison is always true
```
=> lint: Ignore error check for cgroups.DiscoverSubSysIds call

.golangci.yml, cmd/tetragon/conf_test.go, go.mod, pkg/tracingpolicy/yaml.go
The project is unmaintained, and we regularly use the k8s package elsewhere, let's use it everywhere.
This will auto-close https://github.com/cilium/tetragon/pull/3436.
=> deps: remove direct gopkg.in/yaml.v2 dep

.github/workflows/run-e2e-tests.yaml, tests/e2e/flags/flags.go, tests/e2e/runners/runners.go, tests/e2e/tests/skeleton/skeleton_test.go
E2E no longer installs Cilium, so it's better to clean up the related flags. One benefit is to bump cilium version unnecessarily (even by renovate).
```release-note
e2e: Remove Cilium related flags
```
=> e2e: Remove Cilium related flags

install/kubernetes/tetragon/templates/tetragon_configmap.yaml
Kubernetes removes configmap entries if the value is null. Some GitOps systems (ArgoCD in my case) consider the configmap out of sync because the desired manifest contains:
enable-ancestors:
but the realized configmap doesn't contain this entry. Quote the Helm value tetragon.processAncestors.enabled so that the entry gets rendered as:
enable-ancestors: ""
instead so that Kubernetes does not remove the entry from the configmap.
=> helm: Quote tetragon.processAncestors.enabled

cmd/tetragon/main.go, pkg/manager/manager.go, pkg/option/config.go, pkg/watcher/crdwatcher/tracingpolicy.go
This commit is to enable non-k8s tetragon deployment to have k8s control plane i.e. tracing policy can be synced to the tetragon agent. A valid k8s config is required.
```release-note
k8s: Enable k8s control plane for non-k8s deployment
```
----
Testing was done locally by just running one kind cluster with tetragon installed, and then apply one TracingPolicy. 
```
$ sudo ./tetragon --bpf-lib bpf/objs --k8s-kubeconfig-path /home/tammach/.kube/config
level=info msg="Starting tetragon" version=v1.6.0-pre.0-67-g154c87ce7
level=info msg="Tetragon current security context" SELinux=unconfined AppArmor=unconfined Smack="" Lockdown=none
level=info msg="Tetragon pid file creation succeeded" pid=3668931 pidfile=/var/run/tetragon/tetragon.pid
level=info msg="BPF: successfully released pinned BPF …
```
=> k8s: Enable k8s control plane for non-k8s deployment

pkg/selectors/kernel.go, pkg/sensors/tracing/generickprobe.go, pkg/sensors/tracing/policyhandler_linux.go
Fixes #4007 
```release-note
```
This policy fails to load (it's missing `enforcers`):
```yaml
metadata:
name: "linux-ssh-key-config-deletion-detection"
annotations:
author: "Isovalent now part of Cisco"
spec:
kprobes:
- call: "security_path_unlink"
syscall: false
return: false
tags: [ "attack.T1070.004", "attack.T1485", "attack.defense_evasion", "attack.impact" ]
args:
- index: 0
type: "path"
selectors:
- matchArgs:
- index: 0
operator: "Prefix"
values:
- "/etc/ssh/ssh_host_"
- "/etc/ssh/sshd_config"
- "/etc/ssh/ssh_config"
matchBinaries:
- operator: "NotIn"
values: ["/usr/bin/ssh-keygen", "/usr/sbin/sshd", "/usr/bin/dpkg"]
matchActions:
- action: NotifyEnforcer
```
Failure to load due to missing `enforcers`:
```
level=error msg="Failed …
```
=> fix: reject NotifyEnforcer kprobe action without an Enforcer

install/kubernetes/tetragon/templates/_extensions.tpl, install/kubernetes/tetragon/templates/daemonset.yaml
Similar to initcontainers.extra function, containers.extra allows you to add extra containers to Tetragon daemonset.
=> helm: Add 'containers.extra' helper function

.github/renovate.json5, install/kubernetes/tetragon/Chart.yaml
Fixes #3941 
This PR ensures that the `version` and` appVersion` fields in Chart.yaml are kept in sync with the image tag from [quay.io/cilium/tetragon](https://quay.io/repository/cilium/tetragon?tab=tags&tag=latest).
A custom regex manager has been added in renovate.json, along with Renovate comments in Chart.yaml. These updates are grouped with changes to values.yaml, ensuring that all related Helm chart updates are applied together in a single Renovate PR.
=> renovate: sync helm chart version/appVersion update with image tag

pkg/selectors/kernel.go
[upstream commit 996d40f0907c17a9e914bd23911b01f03a11ed1d]
When tried to use the following tracing policy:
```yaml
metadata:
name: "lsm"
spec:
lsmhooks:
- hook: "bprm_check_security"
args:
- index: 0
type: "linux_binprm"
selectors:
- matchArgs:
- index: 0
operator: "Postfix"
values:
- "/true"
matchBinaries:
- operator: NotIn
values: []
```
I didn't get any events when running /usr/bin/true.
Removing the empty matchBinaries fixes that issue.
In order to fix that, this patch ignores empty (i.e. no values) matchBinaries selectors.
=> [backport/v1.5] selectors: Ignore empty matchBinaries

.github/workflows/gotests.yml, .github/workflows/windows-build-smoke-test.yml
Extracted from #4052 
Make sure to always use actions/setup-go after repo checkout.
=> chore(ci): always use `actions/setup-go` after repo clone.

cmd/tetragon/main.go, pkg/manager/manager.go, pkg/option/config.go, pkg/watcher/conf/conf.go
The below PR enables k8s cluster as control plane for non-k8s workload, however, the RBAC permission seems to be required unnecessarily for Pods, Nodes, and CRDs. This commit is to make sure that required RBAC is only limited to tetragon related resources
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: tetragon-vm
rules:
- apiGroups:
- cilium.io
resources:
- podinfo
- tracingpolicies
- tracingpoliciesnamespaced
verbs:
- get
- list
- watch
```
Relates: #4011
Testing was done with one dedicated Service account having only the above permission, and then run tetragon locally as per below
```shell
$ KUBECONFIG=./tetragon-vm.kubeconfig kg service
Error from server (Forbidden): services is forbidden: User "system:serviceaccount:default:tetragon-vm" cannot list …
```
=> k8s: Reduce RBAC permission for non-k8s deployment

docs/content/en/docs/concepts/tracing-policy/selectors.md
- fixes the invalid YAML file in docs/concepts/tracing-policy/selectors
Fix the YAML indent.
=> docs: fix the yaml indent in selector semantics

bpf/lib/policy_stats.h, bpf/lib/process.h, bpf/process/bpf_generic_tracepoint.c, bpf/process/generic_calls.h
perf_event_output_metric is defined in lib/process.h that is included from the code in the base sensor as well.
As a result, some programs from the exec sensor end up having private copies of the policy_stats map, which is just waster memory. Add some ifdefs to only enable the policy_stats map for the tracing (generic) sensors.
Fixes: b0e50ee7f3a1 ("bpf: policy stats")
=> policy_stats: use the map only for policy sensors

cmd/tetra/probe/config.go, cmd/tetra/probe/probe.go, pkg/bpf/detect_linux.go, pkg/kernels/config.go
1.Add `HasAuditLoginuid()` to check kernel support for `CONFIG_AUDIT` when auid is unavailable.
2.Add `DetectConfig()` ,in pkg/kernels/config.go, to detect kernel configuration status, enabling other detect functions(e.g., HasAuditLoginuid) to access configs of interest.
3.Add `audit_loginuid` field in `tetra probe`.
4.Add `tetra probe config` command to list availability of Linux kernel configuration options.
Fixes #2087
=> tetragon: add HasAuditLoginuid function

pkg/watcher/conf/conf.go
Similar to what controller-runtime is having (e.g. alias.go), this will help with testing and extension later. One of the use case is to support more auth methods to k8s.
Similar to what controller-runtime is having (e.g. alias.go), this will help with testing and extension later. One of the use case is to support more auth methods to k8s.
```release-note
k8s: Add alias for getting k8s config
```
=> k8s: Add alias for getting k8s config

bpf/process/generic_calls.h, bpf/process/types/basic.h, contrib/tester-progs/sdt-config.h, contrib/tester-progs/sdt.h, contrib/tester-progs/usdt.c, pkg/api/tracingapi/client_kprobe.go, pkg/elf/usdt.go, pkg/elf/usdt_args_amd64.go, pkg/elf/usdt_args_amd64_test.go, pkg/sensors/tracing/genericusdt.go, pkg/sensors/tracing/usdt_amd64_test.go
Borrowing changelog from kernel commit [1]:
On x86-64, USDT arguments can be specified using Scale-Index-Base (SIB)
addressing, e.g. "1@-96(%rbp,%rax,8)". The current USDT implementation
in libbpf cannot parse this format, causing `bpf_program__attach_usdt()`
to fail with -ENOENT (unrecognized register).
This patch fixes this by implementing the necessary changes:
- add correct handling for SIB-addressed arguments in `bpf_usdt_arg`.
- add adaptive support to `__bpf_usdt_arg_type` and 
`__bpf_usdt_arg_spec` to represent SIB addressing parameters.
Adding same change to our usdt parsing code.
[1] 758acb9ccfdb libbpf: Fix USDT SIB argument handling causing unrecognized register error
=> tetragon: allow to parse usdt sib argument

bpf/process/types/perfevent.h, pkg/api/tracingapi/client_kprobe.go
We have a hole in perf_event_info_type which results in wrong number in its go counterpart MsgGenericKprobePerfEvent which is aligned differently.
Make sure the C object does not have any holes.
Fixes: https://github.com/cilium/tetragon/issues/4119
=> tetragon: Fix struct perf_event_info_type layout

docs/content/en/docs/reference/tracing-policy.md, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml, install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, pkg/k8s/apis/cilium.io/v1alpha1/types.go, pkg/k8s/apis/cilium.io/v1alpha1/version.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go, vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Make ArgSelector::index/Args optional for k8s, so we can load policies through k8s validation.
=> tetragon: Fix k8s validation of ArgSelector fields

docs/data/tetragon_flags.yaml, pkg/manager/manager.go, pkg/option/config.go, pkg/option/flags.go, pkg/watcher/conf/conf.go
```Support ControllerManager retry logic.
```
Problem:
ControllerManager lacks support for retry. The retry option is required for projects where the on-prem controller can be delayed to come up.
Solution:
- Added retry support for ControllerManager. 
- The retry logic uses expontential backoff to avoid hammering the API Server.
- The retry logic uses Jitter, and logs retry attempt with time duration.
- Default for RetryCount is 1, where 1 means no retries,  just one execution of the connection attempt.
- Default for backoff is retry.DefaultBackoff
- This PR ensures the backward compatability for client's retry of ControllerManager is 1.
With this implementation, the Client's can set their desired values using the k8sConfigRetry alias to override.
Testing
1. Default behavior
``` …
```
=> k8s: Add retry support for ControllerManager

docs/content/en/docs/reference/helm-chart.md, install/kubernetes/tetragon/README.md, install/kubernetes/tetragon/templates/_helpers.tpl, install/kubernetes/tetragon/templates/rthooks-daemonset.yaml, install/kubernetes/tetragon/values.yaml
In [#3864](https://github.com/cilium/tetragon/pull/3864), support for nameOverride was introduced for the tetragon and tetragon-operator components. However, the tetragon-rthooks resources were not updated and still rely directly on the Helm release name.
This PR extends nameOverride support to tetragon-rthooks, ensuring consistent naming across all Tetragon components.
=> feat: add nameOverride support for tetragon-rthooks

examples/tracingpolicy/security-socket-connect-block-others.yaml, examples/tracingpolicy/tcp-listen.yaml, pkg/crdutils/crdutils.go, pkg/crdutils/crdutils_test.go, pkg/selectors/kernel.go, pkg/sensors/tracing/enforcer_test.go, pkg/sensors/tracing/kprobe_amd64_test.go, pkg/sensors/tracing/kprobe_net_test.go, pkg/sensors/tracing/kprobe_process_credentials_test.go, pkg/sensors/tracing/kprobe_test.go, pkg/sensors/tracing/kprobe_validation_test.go, pkg/sensors/tracing/tracepoint_amd64_test.go, pkg/sensors/tracing/usdt_amd64_test.go, testdata/specs/sigkill.yaml.tmpl, testdata/specs/sigkill_return.yaml.tmpl, testdata/specs/sigkill_tracepoint.yaml.tmpl
This fixes commit 29b76c402b68 ("Refactor CRD defaulting and validation as generic") that was enhancing commit a9c9a0bd83a8 ("pkg/tracingpolicy: add k8s validation for meta and spec").
I think it's a typo that was introduced because when do the validation of the object, we give the function two versions of that object, cr that is typed and was created by yaml.UnmarshalStrict the JSON object with K8s default, and unstr that is the unstructured object version of what was passed as input, but with K8s default. We need these two objects to do the validation respectively on the ObjectMeta and the Spec.
When Unmarshaling the JSON object to the GenericTracingPolicy (or others) types, all fields are set to their Golang defaults (!) in addition to the K8s default that were already applied. So some …
=> pkg/crdutils: fix standalone custom resources validation
