cilium/tetragon

README.md

Signed-off-by: Bill Mulligan <billmulligan516@gmail.com>

fix spelling and grammar

---

.github/workflows/build-images-default-branch.yml
.github/workflows/generated-files.yaml
.github/workflows/gotests.yml
.github/workflows/static-checks.yaml

We have a main branch (not a master branch)

---

.github/workflows/build-images-default-branch.yml

Build image for quay.io/cilium/tetragon:latest

---

.github/workflows/build-images-default-branch.yml
install/kubernetes/values.yaml

Fixing the build of images

---

install/kubernetes/README.md
install/kubernetes/values.yaml

Prepare for release v0.8.0

---

DEVELOP.md
contrib/localdev/bootstrap-kind-cluster.sh
contrib/localdev/conf
contrib/localdev/install-tetragon.sh
install/kubernetes/templates/_container_tetragon.tpl

See DEVELOP.md for example usage.

workflow: add scripts to make local development with kind easier

---

DEVELOP.md

Signed-off-by: Kornilios Kourtis <kornilios@gmail.com>
Fixes:  #26

DEVELOP.md: list requirements

---

README.md

README: Add GKE support

---

README.md

Signed-off-by: Marwan Nour <38836519+MarwanNour@users.noreply.github.com>

Added note for logging multiple tetragon pods

---

README.md

Signed-off-by: Raphaël Pinson <raphael@isovalent.com>

docs(README): add dark logo option

---

README.md

README.md: Install using Helm chart from helm.cilium.io

---

go.mod
go.sum
vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
vendor/github.com/cilium/cilium/pkg/metrics/metrics.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_go115.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector_pre_go115.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/expvar_collector.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_go116.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/process_collector.go
vendor/modules.txt

Release note: https://github.com/cilium/cilium/releases/tag/v1.9.16

vendor: Pick up cilium v1.9.16

---

README.md

Adding additional resources starting from 2020.

Add Additional Resources to README

---

README.md

Signed-off-by: Natalia Reka Ivanko <natalia@isovalent.com>

Format README: add missing `process_kprobe` JSON event

---

cmd/tetragon/main.go
pkg/bpf/bpffs_linux.go
pkg/defaults/defaults.go

bpf: use 'tetragon' as prefix for maps and progs on the bpffs

---

.github/workflows/checkpatch.yaml
.github/workflows/generated-files.yaml
.github/workflows/lint-helm.yaml

See individual commit messages for context.
- Rename checkpatch's static-checks job
- Add a job to lint our helm chart
- Add a help message to the generated-files job

ci: various improvements

---

operator/main.go

operator: fix tool name in log output

---

values.yaml

values.yaml was added by accident a couple weeks ago while I was testing a PR. Let's
remove it.

chore: remove accidentally checked in file

---

crds/README.md

Small typo in the README here 😄 
Signed-off-by: Tom Meadows <djw0bbl3@protonmail.com>

Update typo in README

---

crds/README.md

CRD docs referred to FGS
Signed-off-by: Liz Rice <liz@lizrice.com>

[docs] Correct name to Tetragon

---

pkg/data/data.go

Can be used in other places as well and reduce code duplication.

Export HandleData from pkg/data/data.go

---

cmd/tetra/tracingpolicy/tracingpolicy.go

It's as boring as it sounds but I spotted it when I discovered the project, so why not fix it!

Tetra: fix a typo in tracingpolicy command short description

---

Makefile

Some targets where not part of .PHONY target, add them and while in the process do some cleanups by inlining target definition with .PHONY inclusion.

make: add makefile targets to .PHONY targets

---

pkg/grpc/exec/exec_test.go

Both for in-order and out-of-order

Add unit-tests for clone events

---

.github/workflows/vmtests.yml

Signed-off-by: Kornilios Kourtis <kornilios@gmail.com>

vmtests: increase groups to 5

---

pkg/grpc/exec/exec_test.go

Add more unit-tests with OOO events and missing pod info

---

cmd/tetra/getevents/getevents.go
pkg/encoder/encoder.go
pkg/encoder/encoder_test.go

tetra cli: add more filters and a timestamps flag

---

.github/dependabot.yml

dependabot: Monitor Dockerfiles

---

.github/workflows/static-checks.yaml
Dockerfile.test

Remove hubble-libbpf repository

---

bpf/lib/bpf_events.h
bpf/process/bpf_exit.h
bpf/process/bpf_generic_retkprobe.c
bpf/process/generic_calls.h
bpf/process/pfilter.h
bpf/process/types/basic.h

tetragon: execve_map fixes

---

pkg/sensors/exec/exec_test.go

Add a test that checks that exec events contain the correct
Docker/container ID.

Add Exec Test For Docker/Container ID

---

.github/workflows/build-images-ci.yml

Push to tetragon-ci:latest on push to main

---

contrib/tester-progs/Makefile
contrib/tester-progs/sigkill-unprivileged-user-ns-tester.c
crds/sandbox/linux-namespaces/kill_unprivileged_user_namespace.yaml
crds/sandbox/linux-namespaces/kill_unprivileged_user_namespace_in_pid_namespace.yaml
pkg/sensors/tracing/kprobe_sigkill_test.go
testdata/specs/sigkill_unprivileged_user_namespace.yaml.tmpl
testdata/specs/sigkill_unprivileged_user_namespace_in_pid_namespace.yaml.tmpl

Add ability to sandbox access to unprivileged user namespaces.

sandbox: add crds to sandbox unprivileged user namespace

---

.github/ISSUE_TEMPLATE/release_template.md
contrib/update-helm-chart.sh

Add an issue template for the release process

---

install/kubernetes/Chart.yaml
install/kubernetes/README.md
install/kubernetes/values.yaml

Prepare for v0.8.2 release

---

pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
pkg/k8s/apis/cilium.io/v1alpha1/types.go
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go

We already support that, just added there for completeness.

Add Override type in ActionSelector

---

contrib/tester-progs/.gitignore
pkg/eventcache/eventcache.go
pkg/grpc/exec/exec.go

This PR does some fixes in the eventcache logic. Please check individual commits.

Fix parent reference counting in RetryInternal

---

Makefile

Signed-off-by: Bill Mulligan <billmulligan516@gmail.com>

Remove METADATA_IMAGE

---

bpf/lib/bpf_cgroup.h

RHEL kernels did a backport (I guess.) where they both have the kernfs_inode_id union defined, but instead of using it in the kernfs_inode struct definition they choose to use an anon union.
This breaks our code because when we find kernfs_inode_id union we try to walk through the union with pointer chasing like so, inode->kernfs_indoe_union->id. But, on these kernels the relocation lookup fails so relocation code at load puts a garbage call there to block verivier. And we get this error on load,
; if (!bpf_core_type_exists(union kernfs_node_id)) {
2150: (55) if r1 != 0x0 goto pc+44
last_idx 2150 first_idx 2146
regs=2 stack=0 before 2149: (b7) r1 = 1
; _(&vfsmnt->mnt_root));
2195: (85) call unknown#195896080
invalid func unknown#195896080
So to fix this we make the observation that we can …

hubble-fgs: Fix verifier error on non-upstreeam, non-LTS kernels

---

pkg/testutils/perfring/perfring.go

When waiting for events from the ring buffer we do not check if the context was canceled this may cause some tests to continue to run blocked at perfReader.Read() indefinitly until the go unit test timeout is reached.
Fix it by checking if the context is done, close the ring buffer and clean up related goroutines.

tests:perfring: allow to cancel context and close perfring buffer

---

.github/workflows/build-images-releases.yml

This job should require an approval from a maintainer.

draft-github-release: Use "release" environment

---

install/kubernetes/Chart.yaml
install/kubernetes/README.md
install/kubernetes/values.yaml

Prepare for v0.8.3 release

---

pkg/sensors/load.go

Log when loading BPF programs. I thought we already do that but it seems not.

pkg:sensors: log loading BPF programs

---

README.md

PR corrects a sentence in the 'Deploy Tetragon' session.  
/cc @pchaigno - https://cilium.slack.com/archives/C2B917YHE/p1666774588771809?thread_ts=1666774463.756319&cid=C2B917YHE
Signed-off-by: Dmitry Savintsev <dmitris@users.noreply.github.com>

correct a sentence in 'Deploy Tetragon'

---

pkg/sensors/sensors.go

Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>

Chore: registered probe types

---

cmd/tetragon-tester/init.go
pkg/bpf/bpffs_linux.go
pkg/eventcache/eventcache.go
pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
pkg/reader/node/node.go
pkg/selectors/kernel.go
pkg/sensors/test/checker.go
pkg/sensors/tracing/tracepoint_test.go
pkg/tracepoint/tracepoint.go
tests/e2e/runners/doc.go
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go

Just a make generate && make codegen && make format.

Update automatically generated files

---

bpf/process/bpf_generic_kprobe.c
bpf/process/bpf_generic_tracepoint.c
bpf/process/bpf_process_event.h
bpf/process/types/basic.h
pkg/reader/proc/proc.go
pkg/reader/proc/proc_test.go
pkg/sensors/exec/procevents/proc_reader.go

tetragon: improve how we read process info during startup

---

pkg/jsonchecker/jsonchecker.go
pkg/selectors/selectors.go
pkg/sensors/test/checker_test.go
pkg/sensors/tracing/kprobe_test.go
pkg/sensors/tracing/tracepoint_test.go
pkg/testutils/filenames.go
pkg/testutils/sensors/testrun.go
tests/vmtests/README.md

various fixes motivated by a failure of the raw syscall test

---

tests/vmtests/README.md

vmtests/doc: fix

---

pkg/cgroups/cgroups.go
pkg/cgroups/cgroups_test.go
pkg/sensors/config/confmap/confmap.go
pkg/sensors/exec/cgroups_test.go
pkg/testutils/sensors/sensors.go

tests:cgroups: add tests to emulate k8s hierarchies

---

cmd/tetragon/main.go

tetragon: fix cobra command line usage

---

Dockerfile

dockerfile: remove addgroup hubble

---

cmd/tetragon/main.go
go.mod
go.sum
vendor/github.com/cilium/lumberjack/v2/lumberjack.go
vendor/modules.txt

tetragon: logging improvements for non k8s deployment

---

cmd/tetragon/main.go
pkg/observer/observer.go

logging: allow users to know more about the overall status

---

pkg/sensors/program/loader.go

Using a log buffer that is too short causes the kernel to return ENOSPC and truncate verifier logs. This is annoying because 1) it masks the real errno, and 2) the truncated logs are pretty useless for our debugging purposes. So let's try to grow the log size until it works if we hit a verifier error.

loader: support larger verifier log sizes

---

pkg/encoder/encoder.go
pkg/encoder/encoder_test.go

Based on the original work in #444

encoder: pretty print bpf events

---

.github/workflows/build-images-releases.yml
.github/workflows/static-checks.yaml
Makefile

ci: add make tarball check and release

---

pkg/config/yaml.go

I forgot to add that and it would have helped me a lot to debug errors...

pkg/config: print name in validation error

---

bpf/Makefile

tetragon: bpf/Makefile fixes

---

bpf/process/bpf_exit.h
bpf/process/bpf_generic_kprobe.c
bpf/process/bpf_generic_retkprobe.c
bpf/process/bpf_generic_tracepoint.c
bpf/process/data_event.h
bpf/process/generic_calls.h
bpf/process/pfilter.h
bpf/process/retprobe_map.h
bpf/process/types/basic.h

tetragon: couple bpf fixes

---

Makefile

make:trivial: do sha256sum inside directory

---

docs/deployment/package/README.md
install/linux-tarball/uninstall.sh

deployment: minor tarball uninstall fixes

---

cmd/tetragon/main.go

Some users on k8s complained that we are spamming logs.
- Log only on non k8s environments where metrics are usually disabled.
- Log observer status only once 24h.
- For lost and error events we ratelimit to one status per 1 hour, and only if lost/error events keep increasing.

logging: log observer status only once 24h and for non k8s

---

.github/workflows/build-clang-image.yaml

Fix clang image build workflow SBOM step

---

netlify.toml

For some reasons, putting the same values from the Netlify dashboard in the config file did not work, let's remove the base and publish path from the config file and use the dashboard:
https://app.netlify.com/sites/tetragon/deploys/64130440d6c0ad0008912ede

Workflow: fix netlify deploy preview

---

.github/workflows/build-images-ci.yml
.github/workflows/build-images-releases.yml
Dockerfile
Makefile

This is part of https://github.com/cilium/tetragon/issues/487.
Very fun fact that I learned today, `tetra` requires CGO because it imports `tetragon/pkg/bpf`. I hope you are laughing now!

Cross-compile arm64 container images

---

.github/workflows/build-images-releases.yml
Dockerfile
Makefile

This will speedup the CI image building and add LLVM libs support for disassembler in bpftool.

Add conditional Dockerfile stage to build or download bpftool

---

api/go.mod
api/go.sum
api/vendor/github.com/stretchr/testify/assert/assertions.go
api/vendor/modules.txt
go.mod
go.sum
vendor/github.com/stretchr/testify/assert/assertions.go
vendor/modules.txt

build(deps): bump github.com/stretchr/testify from 1.8.1 to 1.8.2

---

cmd/tetragon/flags.go
cmd/tetragon/main.go
pkg/option/config.go

tetragon: move all cli flags to options.Config

---

netlify.toml

I did some testing on a fork and I hope this one will work better than the previous.

Fix Netlify ignore command to trigger build previews only on docs PR

---

.github/workflows/build-images-releases.yml
operator.Dockerfile

Set correct permissions to upload artifacts and switch to a different release action since our old one was archived.

ci: fixes for release automation

---

bpf/process/types/basic.h
pkg/selectors/kernel.go

fix default post action processing

tetragon: post action parsing fix

---

.github/workflows/generated-files.yaml
.github/workflows/gotests.yml
.github/workflows/run-e2e-tests.yaml
.github/workflows/static-checks.yaml
.github/workflows/vmtests.yml

ci: update setup-go@v3 to v4

---

cmd/tetragon/main.go
pkg/server/addr.go
pkg/server/addr_test.go

backports/v0.9: fixup server address when port is not present

---

Makefile

Backports/v0.9: Makefile: set GOARCH to TARGET_ARCH only if GOARCH is unset

---

cmd/tetragon/main.go
pkg/bugtool/bugtool.go
pkg/metrics/mapmetrics/mapmetrics.go
pkg/process/cache.go

Improvements in bugtool and metrics

---

.github/ISSUE_TEMPLATE/bug_report_template.yaml

bug-report-template: add an issue template for bug report

---

docs/content/en/docs/resources/_index.md

Also transform the list of conference talks in a table in the most recent to least recent order.
[Preview here](https://deploy-preview-993--tetragon.netlify.app/docs/resources/).

docs: add last two Tetragon KubeCon EU 2023 prez

---

docs/content/en/docs/faq/_index.md

This fixes #911.
cc @errordeveloper

docs: add an FAQ entry about BTF requirement

---

docs/assets/scss/sidebar.scss
docs/assets/scss/theme/main-container.scss
docs/assets/scss/theme/navbar.scss
docs/assets/scss/theme/sidebar-toc.scss
docs/assets/scss/theme/sidebar-tree.scss
docs/layouts/partials/sidebar-tree.html

This PR adds documentation style fixes and improvements

docs: fix sticky header, TOC scrolling and add search bar

---

.github/renovate.json5

This should pass checkpath.pl, I tested it.

renovate: fix author match with sign-off

---

cmd/tetra/getevents/getevents.go
cmd/tetra/getevents/getevents_test.go
cmd/tetra/main.go
cmd/tetra/tracingpolicy/tracingpolicy.go

Fix getevents `--output` flag

---

pkg/btf/btf.go

Nicholas reported that we don't take into account kernel option
when checking for BTF data, fixing that.

tetragon: Force configured kernel version in observerFindBTF

---

pkg/k8s/go.mod
pkg/k8s/vendor/modules.txt

tetragon: Remove unneeded custom cilium/ebpf dependency

---

.github/workflows/gotests.yml
.github/workflows/run-e2e-tests.yaml

Fix https://github.com/cilium/tetragon/issues/955

Add arm64 runners for go tests

---

pkg/sensors/tracing/generictracepoint.go

732087036a7180d1647ec5350c7f624e4ed9d36c introduced override tracepoint argument types by users.
The const_buf type, however, requires special information for its decoding that is only set during automatic type detection.
This results in the agent panicking when this happens. Fix this by disallowing const_buf being defined by users. In addition add a nil check before the dereference to avoid panics in the same code in the future if thigns change.
Fixes: https://github.com/cilium/tetragon/issues/1193

tetragon: do not allow users to set const_buf

---

.github/ISSUE_TEMPLATE/bug_report_template.yaml

Emphasize on the need for reproduction steps and remove the unnecessary tickboxes.

issue templates: improve bug report template

---

.github/renovate.json5
.github/workflows/build-clang-image.yaml
Dockerfile.clang
Makefile

Check individual commits for messages and changes.

Clang image Dockerfile and workflow improvements and renovate settings tuning

---

Makefile

A tiny patch, I'm just bothered that things get printed twice.

Makefile: Print messages only once

---

bpf/process/bpf_generic_tracepoint.c
bpf/process/types/basic.h
cmd/tetra/tracingpolicy/tracingpolicy.go
pkg/sensors/tracing/generickprobe.go

tetragon: kprobe fixes

---

pkg/bpf/map_linux.go

Couple fixes for map walking code and then a new map walking API to allow map walk to abort after some number of entries. This handles the case where map is being updated while we are walking it.

tetragon: bpf map handlers updates

---

bpf/process/types/basic.h
pkg/sensors/tracing/kprobe_test.go

Backport https://github.com/cilium/tetragon/pull/1301

[backport/v0.10] bugfix: Fix Prefix operator with file type in matchArgs

---

bpf/process/bpf_generic_tracepoint.c
pkg/grpc/tracing/tracing.go
pkg/sensors/tracing/generictracepoint.go
pkg/sensors/tracing/tracepoint_test.go

See commits.
```release-note
generic tracepoints: add support for string type
```

generic traceponts: add support for string type

---

cmd/tetra/commands_linux.go
tests/e2e/checker/rpcchecker.go

misc fixes

---

pkg/sensors/base/base.go
pkg/sensors/tracing/generickprobe.go

It's updated later in Sensor::Load function.

tetragon: Do not update sensors.AllPrograms in kprobe sensor

---

bpf/process/types/basic.h

The recent fix for socket tracking that stores the PID/TID/ktime against the cookie instead of just the PID/TID introduced a bug where sockets being freed in __sk_free after the process had exited weren't being removed from the socktrack map. This was because the fix required the PID to be looked up in the execve map and bailed if it wasn't there (which it wouldn't be after the process had exited).
This had a knock on effect of causing the old socket mapping to be used in the sk_alloc event, which would then be written back to the socktrack map on its return, meaning that subsequent calls to sk_alloc didn't fix the problem.
This commit moves the untrack deletion from the socket map to the earliest point possible, and certainly before the PID is looked up in the execve map. It should fix …

Sock/skb: fix untrack sock

---

bpf/process/types/basic.h
pkg/selectors/kernel.go
pkg/selectors/kernel_test.go

See commits.
Fixes: #1341.
```release-note
tracing: fix issues when multiple actions are specified in a selector
```

tracing: multiple action fixes

---

cmd/tetra/tracingpolicy/generate/generate.go
cmd/tetra/tracingpolicy/tracingpolicy.go
pkg/btf/validation.go
pkg/k8s/apis/cilium.io/v1alpha1/types.go
pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go
pkg/sensors/tracing/lists.go
pkg/sensors/tracing/policyfilter_test.go
pkg/sensors/tracing/selectors_test.go
pkg/tracingpolicy/generate/generate.go
pkg/tracingpolicy/generictracingpolicy.go
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go

improve tetra tracingpolicy generate

---

pkg/watcher/fake.go
pkg/watcher/fake_test.go

Implement FindServiceByIP and add accessor functions to make it easier to unit test.

watcher: Implement fake service functions

---

examples/tracingpolicy/list-syscalls-tracepoint.yaml
pkg/selectors/kernel.go
pkg/selectors/selectors.go
pkg/sensors/tracing/generickprobe.go
pkg/sensors/tracing/generictracepoint.go
pkg/sensors/tracing/genericuprobe.go
pkg/sensors/tracing/kprobe_amd64_test.go
pkg/sensors/tracing/kprobe_test.go
pkg/sensors/tracing/lists.go
pkg/sensors/tracing/policyhandler.go
pkg/sensors/tracing/selectors.go
pkg/sensors/tracing/tracepoint_amd64_test.go
pkg/sensors/tracing/tracepoint_test.go

We are going to use InMap operators for loading values from lists,
so moving the network port parsing code into separate function,
because not every possible map value is a port number ;-)

tetragon: Factor InMap operators

---

docs/assets/scss/footer.scss
docs/layouts/partials/footer.html

docs: fix footer

---

cmd/tetragon/flags.go
cmd/tetragon/main.go
examples/configuration/tetragon.yaml
install/kubernetes/templates/tetragon_configmap.yaml
pkg/bench/bench.go
pkg/observer/observer.go
pkg/observer/observertesthelper/observer_test_helper.go
pkg/option/config.go
pkg/sensors/collection.go
pkg/sensors/exec/exec_test.go
pkg/sensors/handler.go
pkg/sensors/load.go
pkg/sensors/manager.go
pkg/sensors/manager_test.go
pkg/sensors/program/cgroup/cgroup.go
pkg/sensors/sensors.go
pkg/sensors/tracing/kprobe_test.go
pkg/testutils/sensors/sensors.go

There is a rumor that Tetragon actually doesn't need to load Cilium BPF programs.

Remove cilium-bpf configuration parameter

---

cmd/tetra/common/client.go
cmd/tetra/common/flags.go
cmd/tetra/main.go

backports/v0.9: implement retries and exponential backoff in tetra cli

---

cmd/tetra/common/client.go
cmd/tetra/common/flags.go
cmd/tetra/main.go

Backport of https://github.com/cilium/tetragon/pull/1402

backports/v0.10: implement retries and exponential backoff in tetra cli

---

go.mod
go.sum
vendor/github.com/pelletier/go-toml/v2/.goreleaser.yaml
vendor/github.com/pelletier/go-toml/v2/LICENSE
vendor/github.com/pelletier/go-toml/v2/README.md
vendor/github.com/pelletier/go-toml/v2/ci.sh
vendor/github.com/pelletier/go-toml/v2/decode.go
vendor/github.com/pelletier/go-toml/v2/marshaler.go
vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
vendor/github.com/pelletier/go-toml/v2/unstable/parser.go
vendor/modules.txt

Fixes issues in https://github.com/cilium/tetragon/pull/1159

Update module github.com/pelletier/go-toml/v2 to v2.1.0

---

.github/renovate.json5

renovate: add both lvh-images/kind and kernel-images

---

pkg/btf/validation.go
pkg/btf/validation_test.go
pkg/selectors/kernel.go
pkg/sensors/tracing/generickprobe.go
pkg/sensors/tracing/kprobe_validation_test.go
pkg/sensors/tracing/lists.go

Adding more checks for list functions, so they have same checks as standard kprobes.

tetragon: Fix lists validation

---

docs/content/en/docs/faq/_index.md
docs/content/en/docs/getting-started/deployment/package.md

doc: add arm64 tarball install

---

.github/workflows/build-images-releases.yml

I messed up the indentation, and accidentally removed an if condition.
Fixes: 19e4a5ad512c ("Use 'go install' to install bom")

Fix build-images-releases.yml

---

.github/workflows/build-images-releases.yml

build-images-releases.yml: Fix indentation

---

contrib/bench-stat/graph.sh
contrib/bench-stat/run.sh

Adding helper scripts for stats benchmarks, they need to adjusted (set variables) to be usable.

tetragon: Add helper scripts for stats benchmarks

---

docs/content/en/docs/concepts/metrics.md

Update Metrics section to clarrify PACKAGE is about local installs. I at least was confused.

tetragon: docs, minor updates to metrics concepts

---

.github/workflows/build-images-ci.yml

Fixes: https://github.com/cilium/tetragon/commit/4765b0a95e9e1014a921d0d61bfb79afa3c2fc25

build-images-ci: fix GH action

---

docs/content/en/docs/reference/helm-chart.md
install/kubernetes/README.md
install/kubernetes/values.yaml

```release-note
helm: add PROCESS_TRACEPOINT to exported events
```

helm: add tracepoints to event set

---

.github/workflows/build-images-ci.yml

ci: fix branch name

---

docs/content/en/docs/reference/helm-chart.md
docs/hugo.toml
install/kubernetes/Chart.yaml
install/kubernetes/README.md
install/kubernetes/values.yaml

Prepare for v1.0.0 release

---

pkg/ftrace/ftrace.go
pkg/sensors/tracing/generickprobe.go
pkg/sensors/tracing/kprobe_test.go

Due to a popular demand, trying to make the kprobe sensor config code more structured.

tetragon: factor kprobes

---

.github/renovate.json5
Makefile.cli

renovate: add digest in Golang Docker image in Makefile.cli

---

docs/hugo.toml

This PR updates the site description

chore: site description update

---

tests/e2e/helpers/grpc/grpc.go

e2e: wait for tracing policy fixes

---

install/kubernetes/templates/daemonset.yaml

Fixing indents in Tetragon daemonset template.

backports/v1.0: helm: Fix templating securityContext and tolerations

---

pkg/selectors/kernel.go
pkg/sensors/tracing/kprobe_validation_test.go

Ensure that lt/gt operators are used in large kernels.

tetragon: Add LT/GT oerator checks

---

bpf/lib/generic.h
bpf/process/bpf_generic_kprobe.c
bpf/process/bpf_generic_tracepoint.c
bpf/process/bpf_generic_uprobe.c
bpf/process/generic_calls.h
bpf/process/pfilter.h
bpf/process/types/basic.h
pkg/selectors/kernel.go
pkg/sensors/tracing/generickprobe.go
pkg/sensors/tracing/generictracepoint.go
pkg/sensors/tracing/genericuprobe.go
pkg/sensors/tracing/kprobe_test.go
pkg/sensors/tracing/tracepoint_test.go
pkg/sensors/tracing/uprobe_test.go

Removing early binary filter and small tailcall index changes.

tetragon: Small filter fixes

---

.github/workflows/packages-e2e-tests.yaml

This makes the ARM tarball ci test cross compile then run it on an ARM machine
close https://github.com/cilium/tetragon/issues/1955

ci: cross compile the arm tarball for tests

---

bpf/process/bpf_execve_event.c

In execve events we have 2 tail calls. Now we call read_exe in the first one. The second seems to be more lightweight. So let's move it there to improve loading time.

bpf/exec: Move call to read_exe to tail call

---

docs/content/en/docs/contribution-guide/_index.md
docs/content/en/docs/contribution-guide/development-setup.md
docs/content/en/docs/contribution-guide/making-changes.md
docs/content/en/docs/contribution-guide/running-tests.md
docs/content/en/docs/contribution-guide/submitting-a-pull-request.md

See [preview here](https://deploy-preview-1980--tetragon.netlify.app/docs/contribution-guide/).

docs: improve contribution guide and add a running test page

---

docs/hugo.toml

Update hugo with point release.

tetragon: prepare for v1.0.2 release

---

pkg/sensors/exec/threads_test.go

It's possible we receive the origincal clone event out of order after the exec event, which will store wrong value to clonePID/cloneTID variables and mess up the test logic.
Making sure we skip the first clone event.

tetragon: Harden TestMatchCloneThreadsIDs test

---

docs/content/en/docs/installation/configuration.md
docs/content/en/docs/policy-library/observability/_index.md
testdata/demos/tools/exec-memfd.py

policylibrary: Privileges Escalation, unlinked and fileless binary execution

docs:policylibrary: more examples on privileges escalation and execution

---

pkg/observer/observertesthelper/observer_test_helper.go
pkg/sensors/test/cgroups.go
pkg/sensors/tracing/generickprobe.go

Adding several fixes before the loader sysfs refactor takes place.

tetragon: Assorted sensor fixes

---

contrib/rthooks/tetragon-oci-hook/cmd/hook/main.go

This patch improves logging in the tetragon-oci-hook program. It converts the program to use slog, while also fixing some instances of verbose messages (specifically, adding annotations to the messages).

tetragon-oci-hook: improve logging

---

docs/content/en/docs/concepts/events.md

Document export filters and field filters. Preview of the changes starts here: https://deploy-preview-2249--tetragon.netlify.app/docs/concepts/events/#export-filtering

docs: document export filters and fieldfilters

---

examples/policylibrary/cves/cve-2024-3094-xz-ssh.yaml

Lot of tools load liblzma even ps, but this one is just for OpenSSH

cves: add detection of XZ backdoor in OpenSSH

---

.github/workflows/run-e2e-tests.yaml
tests/e2e/helpers/dumpinfo.go
tests/e2e/helpers/portforward.go

e2e: fix bugs + dump operator logs

---

.github/renovate.json5
contrib/update-helm-chart.sh
install/kubernetes/Makefile

If I get a little ack @lambdanis, this is just a followup of the other renovate PRs, I didn't think the update would change the output of the `.md`.

renovate: run the Makefile after upgrading image deps

---

.github/renovate.json5
docs/hugo.toml

docs: update the latest version from the docs with renovate

---

operator/podinfo/podinfo_controller.go
operator/podinfo/podinfo_controller_test.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go

[ upstream commit be19aebaccbfc46217fc372e823a7c9ed925f92e ]
Check if the pod has DeletionTimestamp field set before reconciling to avoid the situation where pod deletion gets stuck because Tetragon operator recreates PodInfo during pod deletion.

Don't create PodInfo if the pod is being deleted

---

docs/content/en/docs/contribution-guide/making-changes.md

docs: Fix a link in contribution guide

---

pkg/reader/userdb/userdb.go

```release-note
tetragon:username: use login name instead of display name
```

tetragon:username: use login name instead of display name

---

docs/package-lock.json
docs/package.json

See https://github.com/cilium/tetragon/security/dependabot/52

docs: update docs dev deps for security fixes

---

docs/content/en/docs/concepts/tracing-policy/k8s-filtering.md

This patch improves the k8s filtering section of the docs by
1. Specifying the correct directory for installing the OCI runtime hooks in minikube.
2. Specifying the correct command for retrieving the tetragon operator logs.
3. A more specific name for tracing policy for filtering by container field.
4. General grammar improvements.

docs: improve k8s filtering docs

---

.github/workflows/check-links-pr.yaml

Fix this issue https://github.com/cilium/tetragon/actions/runs/10010537683/job/27742893906.
cc @scottslowe

workflows: fix the PR link checker script for `raw` GitHub links

---

pkg/sensors/exec/exec.go
pkg/sensors/exec/procevents/proc_reader.go
pkg/sensors/exec/userinfo/userinfo.go

tetragon: make resolving uid to username work with a processapi struct

tetragon: make resolving uid to username work with a processapi struct

---

docs/content/en/docs/troubleshooting/_index.md

Addressing @mtardy's remarks from https://github.com/cilium/tetragon/pull/2622#pullrequestreview-2163199358.
```release-note
doc: Minor style improvements in troubleshooting docs
```

doc: Minor style improvements in troubleshooting docs

---

pkg/cgroups/cgroups.go

```release-note
tetragon: improve systemd deployment detection
```

tetragon: improve systemd deployment detection

---

docs/content/en/_index.html

Fixes 
fixes grammar
```release-note
Grammar fix
```

fix: grammar

---

.github/lychee.toml
README.md
docs/config/_default/hugo.toml
docs/layouts/partials/footer.html

Fixes: https://github.com/cilium/cilium/issues/34043
Related pull requests:
https://github.com/cilium/cilium.io/pull/524
https://github.com/cilium/cilium/pull/34044

doc: update slack channel reference

---

docs/content/en/docs/installation/metrics.md

```release-note
doc: Improved Tetragon metrics guide
```

doc: Improved Tetragon metrics guide

---

docs/content/en/docs/concepts/tracing-policy/selectors.md

Docs for https://github.com/cilium/tetragon/pull/2720

docs for followChildren true

---

docs/content/en/docs/installation/runtime-hooks.md

docs: fix typo

---

install/kubernetes/tetragon/templates/tetragon_configmap.yaml

helm: Remove tcp-stats-sample-segs flag from ConfigMap

---

cmd/tetragon/main.go
pkg/bugtool/bugtool.go
pkg/bugtool/bugtool_test.go

```release-note
Add memory-related information to bugtool.
```

bugtool: add memory related information

---

docs/content/en/docs/installation/verify.md

Fixes #2914
```release-note
```

docs: Fix broken links

---

install/kubernetes/Makefile

* Remove deps target from Helm Makefile
* Remove openapi2jsonschema.py from default Helm Makefile target

Minor cleanup of Helm Makefile

---

pkg/observer/observer.go

Closes #2834
observer: Collect ring buffer metrics only once
```release-note
observer: Collect ring buffer metrics only once. The metrics values don't change, but we avoid keeping independent counters in the Observer struct.
```

observer: Collect ring buffer metrics only once

---

pkg/grpc/exec/exec_test_helper.go

Replace sleeps with waiting that can be interrupted by event delivery in notifier.
Adding bigger timeout to prevent flakes on slow machines.

tetragon: Factor grpc exec events test

---

bpf/process/types/basic.h

syscall64 type allows a bit to be set to distinguish between 32- and 64-bit syscalls. Currently, the only operators that work are InMap and NotInMap. This commit extends support for other operations as well: EQ, NEQ, MASK, GT, LT.
Using the MASK operator specifically, allows us to write policies for all 32-bit syscalls.
For example:
```yaml
metadata:
name: syscalls32bit
spec:
tracepoints:
- subsystem: raw_syscalls
event: sys_enter
args:
- index: 4
type: syscall64
selectors:
- matchArgs:
- index: 0
operator: Mask
values:
- "2147483648" # IS_32BIT
```
```release-note
bpf: support all operators (including Mask) for the syscall64 type
```

bpf: allow all operations for syscall64 type

---

examples/tracingpolicy/tcp-listen.yaml

Examples: Add TCP listen example tracing policy

---

pkg/sensors/tracing/enforcer.go

Enforcer fails to currently load for namespaced policies because it cannot find the `enforcer_data` map.  Add the policy namespace to the sensor.
Fixes: 2769f9b6efa1 ("tetragon: Add namespace to policy directory name")

enforcer: add policynamespace to sensor

---

cmd/tetragon/main.go
docs/data/tetragon_flags.yaml
pkg/cgrouprate/bpf.go
pkg/cgrouprate/cgrouprate.go
pkg/cgrouprate/sensor.go
pkg/observer/observertesthelper/observer_test_helper.go
pkg/option/flags.go
pkg/sensors/base/base.go
pkg/sensors/base/extensions.go

This PR introduces extensions for the base sensor. See commits.

base sensor extensions

---

pkg/grpc/exec/exec_test_helper.go

[upstream commit a0b0c2a8b4f2637de9529b9800f02a99652147d2]
Replace sleeps with waiting that can be interrupted by event delivery in notifier.
Adding bigger timeout to prevent flakes on slow machines.

[backport/v1.2] tetragon: Factor grpc exec events test

---

Makefile
bpf/Makefile
bpf/cgroup/bpf_cgtracker.c
bpf/lib/bpf_errmetrics.h
bpf/lib/fileids.h
bpf/process/bpf_execve_event.c
cmd/bpf-fileids/fileids.go
cmd/tetra/debug/dump.go
pkg/errmetrics/errmetrics.go
pkg/errmetrics/fileids.json
pkg/errmetrics/map.go
pkg/sensors/base/base.go

Introduce bpf error metrics. See commits.
```
sudo ./tetra debug dump errmetrics                                                   
Location                        Error       Count
bpf/cgroup/bpf_cgtracker.c:64   E2BIG (7)   8
```

BPF error metrics

---

.github/ISSUE_TEMPLATE/release_template.md
.github/renovate.json5
.github/workflows/validate-crd.yaml
pkg/k8s/apis/cilium.io/v1alpha1/version.go
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go

Starting v1.4 development cycle.
See patches.

start v1.4 development

---

cmd/tetragon-vmtests-run/image.go

Backport https://github.com/cilium/tetragon/pull/3232

[backport/v1.3][CI] Fix virt-customize issue in vmtests

---

docs/content/en/docs/resources/_index.md

This talk compares Tetragon with other popular security tools. Tetragon comes out on top in this comparison
I found this talk useful for understanding Tetragon and aided my choice in understanding the observability tool landscape. 
However, this talk is not explicitly focused on Tetragon and instead offers a comparison. 
I find tools that offer comparisons to be valuable to understand if they are worth pursuing. 
```release-note
Add link to Kubecon NA 2024 talk discussing Tetragon
```

Add Tetragon talk from Kubecon NA

---

pkg/observer/observertesthelper/observer_test_helper.go
pkg/server/server.go

See patches.
```release-note
tetragon: avoid the agent from hanging in some corner error conditions
```

fixes in server cleanup

---

docs/content/en/docs/troubleshooting/sysdump.md

The "System dump" page in troubleshooting has a description of log level. 
Delete it because it is a duplicate of the information on the "Log level" page.

fix: Troubleshooting documentation for System dump

---

pkg/cgroups/cgroups.go
pkg/sensors/config/confmap/confmap.go

Do not fail on deployment detection, just report errors if any
and set deployment to DEPLOY_UNKNOWN

cgroups: relax deployment detection logic

---

pkg/filters/cel_expression.go

Refactor the CEL filter code a bit, to make it more reusable.

filters: Minor CEL refactoring

---

pkg/sensors/handler.go
pkg/sensors/manager.go
pkg/server/fake_observer.go
pkg/server/server.go

Misc code cleanups. See commits.
```release-note
gRPC: the deprecated sensors API is now removed.
```

sensor cleanups

---

bpf/process/generic_calls.h
pkg/sensors/tracing/kprobe_test.go

We want to change the argument value, so we need to pass the value pointer.

tetragon: Pass argument pointer to extract_arg

---

bpf/process/types/basic.h
pkg/sensors/tracing/kprobe_test.go

adding missing code for dentry filtering and test

dentry fixes

---

bpf/process/generic_calls.h

bpf: verification fixes

---

cmd/tetra/main.go

```release-note:
tetra: increase connection timeout to 30'
```

tetra: increase connection timeout to 30s

---

bpf/process/types/skb.h

On a kernel compiled with fewer SKB extensions (e.g. CONFIG_XFRM is off), Tetra refuses to add the tracingpolicy `write.yaml`. The error message is:
```
Error: failed to add tracing policy: rpc error: code = Unknown desc = sensor generic_kprobe from collection sys-write failed to load: failed prog /usr/local/lib/tetragon/bpf/bpf_generic_kprobe_v61.o kern_version 393554 loadInstance: opening collection '/usr/local/lib/tetragon/bpf/bpf_generic_kprobe_v61.o' failed: program generic_kprobe_setup_event: load program: bad CO-RE relocation: invalid func unknown#195896080 (494 line(s) omitted)  
```
and the tetragon log is:
```
time="2025-02-24T12:39:46Z" level=warning msg="Server AddTracingPolicy request failed" error="sensor generic_kprobe from collection sys-write failed to load: failed prog …
```

Use BTF to access skb_ext

---

bpf/lib/bpf_d_path.h
bpf/process/bpf_generic_kprobe.c
bpf/process/bpf_generic_lsm_core.c
bpf/process/bpf_generic_retkprobe.c
bpf/process/bpf_generic_tracepoint.c
bpf/process/bpf_generic_uprobe.c
bpf/process/generic_calls.h
bpf/process/types/basic.h

pushing out some fixes to ease up upcoming path changes

assorted path related fixes

---

.github/renovate.json5

renovate config: automerge more

---

pkg/bpf/detect_linux.go

To check if lsm bpf is enabled /sys/kernel/security/lsm is used. Sometimes, securityfs is not mounted (eg. k8s, container deployments).
Detailed information in this [post](https://github.com/cilium/tetragon/pull/3485#issuecomment-2718236591).
```
docker run --name tetragon --rm -it                  \
--pid=host --cgroupns=host --privileged          \
-v /sys/kernel/btf/vmlinux:/var/lib/tetragon/btf -v /home/fedotoff/go/src/github.com/cilium/tetragon/examples/tracingpolicy:/tracingpolicy \
cilium/tetragon \
/usr/bin/tetragon --debug --tracing-policy /tracingpolicy/lsm_file_open.yaml
```

pkg/bpf: mount securityfs to check lsm bpf

---

cmd/tetragon-vmtests-run/image.go
cmd/tetragon/main_linux.go
pkg/api/tracingapi/client_kprobe.go
pkg/btf/btf.go
pkg/btf/btf_test.go
pkg/btf/validation.go
pkg/btf/validation_test.go
pkg/bugtool/bugtool.go
pkg/bugtool/bugtool_test.go
pkg/observer/observertesthelper/observer_test_helper.go
pkg/sensors/tracing/generic.go
pkg/sensors/tracing/generic_test.go
pkg/sensors/tracing/generickprobe.go
pkg/sensors/tracing/genericlsm.go
testdata/specs/lseek.yaml
testdata/specs/notasyscall.yaml
testdata/specs/wrongargindex.yaml
testdata/specs/wrongargtype.yaml

Fix https://github.com/cilium/tetragon/issues/3411

Remove `LoadBtf()` and add test wrapper for single btf use

---

install/kubernetes/tetragon/crds-yaml/cilium.io_podinfo.yaml
operator/podinfo/podinfo_controller.go
operator/podinfo/podinfo_controller_test.go
pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
pkg/k8s/apis/cilium.io/v1alpha1/types.go
pkg/k8s/apis/cilium.io/v1alpha1/version.go
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go

It could be useful to know which nodes pods are running on.

podinfo: Add spec.nodeName field

---

bpf/process/types/basic.h
pkg/sensors/tracing/kprobe_test.go

fixing path's permissions retrieval

tetragon: fix path permissions

---

cmd/tetragon/main_linux.go
install/kubernetes/tetragon/templates/clusterrole.yaml
pkg/watcher/namespace.go
pkg/watcher/namespace_test.go

This could be useful for selecting namespaces by labels.

watcher: Watch namespaces

---

bpf/lib/process.h
contrib/upgrade-notes/latest.md
docs/content/en/docs/reference/metrics.md
pkg/metrics/mapmetrics/mapmetrics.go
pkg/observer/observer_stats.go

backporting new stat map metrics

tetragon: backport v1.3 stat map metrics

---

pkg/observer/observertesthelper/observer_test_helper.go

This option is never set to true.

observertesthelper: Remove unused crd option

---

docs/content/en/features/capabilities-monitoring.md
docs/content/en/features/execution-monitoring.md
docs/content/en/features/file-integrity-monitoring.md
docs/content/en/features/kubernetes-identity-aware-policies.md
docs/content/en/features/network-observability.md
docs/content/en/features/operating-system-integrity.md
docs/content/en/features/privileges-monitoring.md
docs/layouts/features/single.html

This patch improves the features page copy and fixes typos

docs: improve features pages copy

---

docs/content/en/docs/policy-library/observability/_index.md

Fix Policy Library networking ssh anchor link

doc: fix policy-library sshd anchor link & title 

---

docs/content/en/docs/installation/runtime-hooks.md

- add instructions for kind
- use the helm repo rather than local helm files (since our released helm charts support this now)

docs: update rthooks installation

---

pkg/observer/observertesthelper/observer_test_helper.go

- Remove fakeK8sWatcher from observer_test_helper.go. Use the fake watcher defined in the watcher package.
- Use PodAccessor interface instead of K8sResourceWatcher. Observer only needs PodAccessor interface.
- Don't initialize a fake watcher in GetDefaultObserverWithWatchers. The default test options already initializes one [^1].
[^1]: https://github.com/cilium/tetragon/blob/8ce47efeab7accb69a5e6b901d8b1904a72d4de7/pkg/observer/observertesthelper/observer_test_helper.go#L192

test: Remove duplicate fake k8s watcher

---

contrib/tester-progs/sigkill-unprivileged-user-ns-tester.c

tetragon: Fix check_cap tester program call

---

docs/content/en/features/network-observability.md
docs/content/en/features/operating-system-integrity.md
docs/content/en/features/privileges-monitoring.md

Feature pages nits

---

tests/e2e/tests/policyfilter/policyfilter_test.go

In https://github.com/cilium/tetragon/issues/3732 we can see that we get an event from the ubuntu-l3 pod in TestContainerFieldRepoFilters. The intention is to check events from ubuntu-l3 pod in TestContainerFieldNameFilters and from ubuntu-l4 pod in TestContainerFieldRepoFilters.
An issue that may result to this issue is that we didn't remove the pod after finishing TestContainerFieldNameFilters test. So as a first thing, this patch deletes the test pod after the test.
To make sure that this cannot happen again in other cases, we also add a check in NextEventCheck to ignore events from other tracing policies.
FIXES: https://github.com/cilium/tetragon/issues/3732

policyfilter/e2e: Fix e2e tests

---

docs/content/en/_index.html

This patch adds new resources to updates and announcements section of the homepage.

docs: update homepage announcement section

---

docs/content/en/docs/concepts/tracing-policy/selectors.md

The file match_capability_changes.yaml was removed in the below PR.
Related: https://github.com/cilium/tetragon/pull/3491
```release-note
docs: Replace example file for matchCapabilityChanges
```

docs: Replace example file for matchCapabilityChanges

---

docs/content/en/docs/reference/helm-chart.md
install/kubernetes/tetragon/README.md
install/kubernetes/tetragon/values.yaml

helm: fix typo in `metricsLabelFilter` comment

---

.clang-format-ignore
bpf/Makefile
bpf/lib/bpf_helpers.h
bpf/lib/process.h
bpf/process/bpf_execve_event.c
bpf/process/bpf_execve_map_update.c
bpf/process/bpf_mbset.h
bpf/process/types/basic.h
contrib/tester-progs/Makefile
contrib/tester-progs/follow_children_1.c
pkg/api/processapi/processapi.go
pkg/config/config_linux.go
pkg/config/config_windows.go
pkg/mbset/mbset.go
pkg/policyfilter/map.go
pkg/sensors/base/base.go
pkg/sensors/base/base_linux.go
pkg/sensors/tracing/generickprobe.go
pkg/sensors/tracing/genericlsm.go
pkg/sensors/tracing/generictracepoint.go
pkg/sensors/tracing/genericuprobe.go
pkg/sensors/tracing/matchbinaries_follow_children_test.go

- add v6.12 objects
- add support to follow children of old process

tetragon: add support to follow children of old process

---

.github/workflows/run-e2e-tests.yaml
tests/e2e/tests/labels/labels_test.go

Relates: https://github.com/cilium/tetragon/pull/2345

ci: Re-enable label checker in ARM

---

bpf/process/bpf_generic_uprobe.c
bpf/process/bpf_generic_usdt.c
pkg/selectors/kernel.go
pkg/sensors/tracing/generickprobe.go
pkg/sensors/tracing/generictracepoint.go
pkg/sensors/tracing/uprobe_test.go
pkg/sensors/tracing/usdt_test.go

assorted fixes

---

pkg/sensors/tracing/kprobe_test.go

optimize kprobe rate limit tests with perfring framework
Fixes #2690 
```
Optimized kprobe rate limit tests with perfring framework
```

Optimize Kprobe Rate Limit Test Performance

---

.github/workflows/windows-build-smoke-test.yml

This fixes intermittent download failures of eBPF for Windows dependencies
Also uses GH actions cache

Fix flaky downloads of eBPF for Windows deps

---

docs/content/en/docs/contribution-guide/contributor-ladder.md

This PR improves the Cilium ecosystem contributing consistency by including a section in the contribution guide of the docs that outlines the contribution ladder. 
```release-note
```

doc: add contribution ladder section

---

docs/assets/scss/community-banner.scss
docs/layouts/partials/community-banner.html

Chore: Add KubeCon NA 2025 to Announcement banner
