cilium/tetragon

- .github/workflows/gotests.yml
- DEVELOP.md
Add a section to DEVELOP.md that covers how to run codegen, when it's necessary, and how
to modify the codegen output as part of a PR.
> docs/develop: document codegen and api generation

- pkg/grpc/exec/exec.go
- pkg/metrics/metrics.go
Missing parent warnings on exec events were producing noise, so hide them behind a debug
flag and add a metric for it.
> tetragon: silence missing parent warning + add metric

- README.md
Issue 1: the xwing pod uses busybox whoami which doesn't support --version, making the
exit code wrong. To fix this let's just remove the --version argument.
Issue 2: Grammar fix in examples.
Issue 3: "Incorrectly read, malicious altered" ->  "Incorrectly read, maliciously altered"
> readme: fix minor issues in quickstart

- pkg/selectors/kernel.go
- pkg/selectors/selectors.go
This PR fixes an issue revealed by the new codeql lints ci job.
We were parsing a 64-bit integer here and converting to a u32 without a bounds check. This
is obviously wrong, so drop the bit size on the ParseInt call down to 32 and make it
ParseUint. Additionally, split up signed and unsigned cases in parseMatchValues() so that
we can properly parse the signed/unsigned integer types.
> selectors: fix missing bounds check on int conversion

- README.md
- pkg/encoder/encoder.go
Rename tcp_connect/tcp_sendmsg/tcp_close to connect/sendmsg/close to
align them with other events, and change their emojis to make them look
slightly more interesting.
> encoder: Update TCP event format

- Vagrantfile
Currently `make` in the VM instance started from the included `Vagrantfile` fails with:
```
make -C contrib/capabilities-tester
make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/tetragon/contrib/capabilities-tester'
gcc -Wall test_caps.c -o test_caps -static -lcap
test_caps.c:11:10: fatal error: sys/capability.h: No such file or directory
11 | #include <sys/capability.h>
|          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:4: test_caps] Error 1
make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/tetragon/contrib/capabilities-tester'
make: *** [Makefile:208: contrib-progs] Error 2
```
The change should allow `make` to complete cleanly.
> Vagrantfile: install libcap-dev for Makefile

- pkg/grpc/exec/exec.go
- pkg/metrics/metrics.go
This counter is useful to help debug cases where process exec events are missing a parent.
Using the parent exec ID in the metric, we can determine the corresponding pid and cross
check against Tetragon event logs. This can help establish patterns and determine an
underlying root cause.
As a practical example, this counter recently helped me diagnose the underlying cause of
missing parents in kind deployments.
> metrics: add a per-exec-id counter for missing parents

- .github/workflows/static-checks.yaml
This is mainly to check commits are signed off, among other things.
Sample failure output: https://github.com/cilium/tetragon/runs/6462531785?check_suite_focus=true
Co-authored-by: Joe Stringer <joe@cilium.io>
> static-check: Run checkpatch.pl

- README.md
The TracingPolicy deletion command example in the Network Observability section was referred to the wrong manifest
> Fixed README command example

- Makefile
PR replaces the use of the literal `docker` in the `Makefile` with `CONTAINER_ENGINE` which has `docker` as the default value (but can be customized by the user - for example, to run `make tools-install CONTAINER_ENGINE='sudo podman'`).  For the "normal" invocations, nothing should change - `docker` still will be invoked.
Signed-off-by: Dmitry Savintsev <dsavints@gmail.com>
> use CONTAINER_ENGINE variable instead of literal 'docker'

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/process/process.go
- pkg/sensors/exec/exec.go
- pkg/sensors/tracing/generickprobe.go
There were some very verbose warnings that were inundating the logs. Let's silence them behind a debug flag and add a metric to help with debugging.
Best reviewed by commit.
> kprobe/process: silence verbose warnings + add metrics

- contrib/capabilities-tester/Makefile
- contrib/namespace-tester/Makefile
`-static` breaks the builds on RHEL8.  With this change 7aac0cc49df35320a867e3e5da63d31925766015, `sudo make test` runs fine in the Vagrant instance. 
Cumulative with https://github.com/cilium/tetragon/pull/43, can rebase when merged.
References:
* https://cilium.slack.com/archives/C03EV7KJPJ9/p1652902163455029?thread_ts=1652887764.380829&cid=C03EV7KJPJ9 
* https://access.redhat.com/articles/rhel8-abi-compatibility
* https://github.com/cri-o/cri-o/issues/2993
* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/developing_c_and_cpp_applications_in_rhel_8/index#static-and-dynamic-linking_using-libraries-with-gcc
> Remove -static flag

- install/kubernetes/README.md
- install/kubernetes/templates/tetragon_configmap.yaml
- install/kubernetes/values.yaml
This patch makes the gRPC address and port configurable in helm and adds a similar option
to configure the metrics address. Fixes #40.
> helm: make gRPC and metrics address/port configurable

- README.md
Currently, the installation instructions for the binary release of the
tetragon-cli hard-code GOOS=linux and GOARCH=386, but the tool is
provided for other platforms. Update the installation instructions
accordingly and also add commands to check the provided `.sha256sum`
file.
> README: fix tetragon-cli installation instructions

- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-default-branch.yml
- .github/workflows/build-images-releases.yml
- .github/workflows/build-images-stable-branches.yml
- Makefile
Above patch seems to break our builds, so revert it until things are
resolved.
This reverts commit 447404efe7043a990d8e509cfd3a510f99c2f3c3.
> Revert "Setup CI to build multi-arch images with arm64 support"

- api/v1/tetragon/codegen/eventcache/eventcache.pb.go
- cmd/protoc-gen-go-tetragon/eventcache/eventcache.go
- pkg/eventcache/eventcache.go
- pkg/execcache/execcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/process_manager.go
- pkg/metrics/consts/consts.go
- pkg/metrics/errormetrics/errormetrics.go
- pkg/metrics/eventcachemetrics/eventcachemetrics.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/eventmetrics/eventmetrics_test.go
- pkg/metrics/kprobemetrics/kprobemetrics.go
- pkg/metrics/mapmetrics/mapmetrics.go
- pkg/metrics/metrics.go
- pkg/metrics/opcodemetrics/opcodemetrics.go
- pkg/metrics/processexecmetrics/processexecmetrics.go
- pkg/metrics/ringbufmetrics/ringbufmetrics.go
- pkg/observer/observer.go
- pkg/observer/observer_stats.go
- pkg/process/cache.go
- pkg/process/process.go
- pkg/sensors/tracing/generickprobe.go
This PR splits the metrics into separate packages to make them easier to work with and reason about. It also adds some convenience helpers to avoid developer error when setting metric labels.
> metrics: split metrics into separate packages

- README.md
remove last \ so it can execute without waiting for another line/option.
Signed-off-by: Walter Lee <quietwalter@gmail.com>
> remove last \ in gcloud container clusters create

- README.md
This patch fixes the download URL outlined in README.md which earlier pointed to https://github.com/cilium/tetragon/releases/latest/download/tetragon-${GOOS}-${GOARCH}.tar.gz and that link rendered a "Not Found" for me in both GOOS=darwin and GOOS=linux.
With the patch I can reach the link on both platforms. 
Signed-off-by: Tony Norlin <tony.norlin@localdomain.se>
> Changed the download URL for tetragon-cli in README.md

- .github/workflows/checkpatch.yaml
- .github/workflows/static-checks.yaml
> ci: move checkpatch to its own job and add some exceptions

- bpf/process/bpf_exit.c
- bpf/process/bpf_exit.h
Separate the functionality of bpf_exit into a header file.
> Abstract bpf_exit

- api/v1/tetragon/codegen/eventcache/eventcache.pb.go
- cmd/protoc-gen-go-tetragon/eventcache/eventcache.go
- pkg/metrics/errormetrics/errormetrics.go
- pkg/metrics/eventcachemetrics/eventcachemetrics.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/eventmetrics/eventmetrics_test.go
- pkg/metrics/kprobemetrics/kprobemetrics.go
- pkg/metrics/mapmetrics/mapmetrics.go
- pkg/metrics/opcodemetrics/opcodemetrics.go
- pkg/metrics/processexecmetrics/processexecmetrics.go
- pkg/metrics/ringbufmetrics/ringbufmetrics.go
It's useful to export raw metric maps in case we need to do any more complex operations
that are not already exposed by helpers. So let's export them. This also matches the old
behaviour before bd4aada1.
> metrics: export raw metric maps

- .github/dependabot.yml
Let dependabot update Go modules and GH actions automatically. Exclude
cilium, hubble and the k8s Go modules though. These should be bumped in
lockstep, manually and explicitly because they likely also need
additional changes.
> .github: add dependabot configuration

- bpf/process/pfilter.h
- contrib/tester-progs/.gitignore
- pkg/sensors/tracing/kprobe_test.go
Add a test for `NotIn` operator in `matchCapabilities` selector and fix an issue with that. 
> Fix for NotIn operator in matchCapabilities selector

- bpf/process/pfilter.h
- pkg/sensors/tracing/kprobe_filterchange_test.go
- testdata/specs/capchanges.yaml.tmpl
Add a test for `NotIn` operator in `matchCapabilityChanges` selector and fix an issue with that.
```
- matchCapabilityChanges: 
- type: Effective
operator: NotIn
values:
- "CAP_SYS_ADMIN"
```
This will match if there is a change in any capabilities other than CAP_SYS_ADMIN.
Signed-off-by: Anastasios Papagiannis [tasos.papagiannnis@gmail.com](mailto:tasos.papagiannnis@gmail.com)
> Fix for NotIn operator in matchCapabilityChanges selector

- go.mod
- go.sum
- vendor/gopkg.in/yaml.v3/decode.go
- vendor/modules.txt
This fixes a potential panic when the library attempts to unmarshal invalid data.
See [this issue][0] for details.
[0]: https://github.com/go-yaml/yaml/issues/666
> vendor: upgrade yaml.v3 to v3.0.0

- pkg/sensors/tracing/kprobe_copyfd_test.go
- pkg/sensors/tracing/kprobe_filterchange_test.go
- pkg/sensors/tracing/kprobe_sigkill_test.go
> testing fixes.

- cmd/tetragon/main.go
When the config file is not specified a runtime panic occcured, as
we tried to dereference the nil config object.
Signed-off-by: Thomas Schubart <thomas@gitpod.io>
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17d16ca]
goroutine 1 [running]:
main.hubbleTETRAGONExecute()
/go/src/github.com/cilium/tetragon/cmd/tetragon/main.go:208 +0xa0a
main.execute.func1(0xc00011a780, {0x1d78f14, 0x1, 0x1})
/go/src/github.com/cilium/tetragon/cmd/tetragon/main.go:314 +0x8a
github.com/spf13/cobra.(*Command).execute(0xc00011a780, {0xc000132010, 0x1, 0x1})
/go/src/github.com/cilium/tetragon/vendor/github.com/spf13/cobra/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc00011a780) …
```
> Fix runtime panic when config file is empty

- install/kubernetes/templates/service.yaml
I've noticed that the service port as defined in `values.yaml` is not respected. As such I created a pull request to respect the value and, by doing so, noticed that the service is only used for metrics. Therefore the service can also be only templated if `prometheus.enabled` is `true`.
Let me know if anything is wrong.
> fix: (helm) service template now respects defined port and is only templated if prometheus is enabled

- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- cmd/protoc-gen-go-tetragon/eventchecker/eventchecker.go
Codegen under Go 1.18 was producing invalid code around Go generics. It seems like this is
fundamentally broken and needs to be totally redone, so let's just remove it for now and
fix it later.
> codegen: remove invalid generics

- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
Not entirely sure if I understood everything correctly, but based on the examples in the crds directory the current descriptions do not seem to reflect the expected input.
> Update description of CRD parameters

- Makefile
- bpf/test/bpf_lseek.c
- contrib/tester-progs/.gitignore
- contrib/tester-progs/Makefile
- contrib/tester-progs/trigger-test-events.c
- pkg/bpf/bpffs_linux.go
- pkg/observer/observer_test_json.go
- pkg/sensors/sync.go
- pkg/sensors/test/checker.go
- pkg/sensors/test/checker_test.go
- pkg/sensors/test/lseek_test.go
- pkg/sensors/test/test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/testutils/filenames.go
- pkg/testutils/sensors.go
Please review commit-by-commit
This PR contains a number of  improvements for testing. Most of them are small, but there is one which is notable: allowing testing without retries.
The idea is the following:
The typical structure of our tests is:
1. start observer
2. do some things on user-space
3. check that we get the expected events from tetragon
The above approach requires retries for step 3 if the events we are looking
for are not there. These retry counts are large so that we can deal with
worst case scenarios, and, subsequently, they induce a significant time cost
in failing tests. Furthermore, for some tests we also need to check for the
absence of events (e.g., when doing filtering), which also requires waiting
on timeouts.
This patch introduces the first steps to avoid having to …
> test improvements, and avoiding retries in event tests

- pkg/jsonchecker/jsonchecker.go
- pkg/jsonchecker/logcatpure.go
- pkg/observer/observer_test_helper.go
- pkg/sensors/exec/fork_test.go
- pkg/sensors/test/checker_test.go
- pkg/sensors/test/lseek_test.go
- pkg/sensors/tracing/kprobe_copyfd_test.go
- pkg/sensors/tracing/kprobe_filterchange_test.go
- pkg/sensors/tracing/kprobe_sigkill_test.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
JsonTestCheck is used widely by our unit tests, not just in pkg/observer. So let's split
this functionality out of the observer to make things more modular.
> tests: split json checker out of observer

- pkg/dns/dns_cache.go
Preparing to use Cilium to fetch DNS names (lost in conversion to OSS) we
have the dns pkg pulling in protobufs. This is a bit odd and not ideal
because Cilium certainly doesn't care about Tetragon protobufs and
importing them and using them in Cilium side is awkward.
For now do some simple refactoring to clean up the API.
> tetragon: extract protobuf from the dns cache

- bpf/include/vmlinux.h
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/generic_calls.h
- bpf/process/types/basic.h
- pkg/api/tracingapi/client_kprobe.go
- pkg/bpf/loader.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/kprobe_copyfd_test.go
Getting rid of extra configuration inside BTF and moving it to map.
The new internal config_map map is loaded for both tracepoints
and kprobes and loaded with config data at zero index.
Signed-off-by: Jiri Olsa [jolsa@kernel.org](mailto:jolsa@kernel.org)
> tetragon: Add event config map

- api/v1/tetragon/codegen/eventchecker/yaml/yaml.pb.go
- cmd/protoc-gen-go-tetragon/eventchecker/yaml.go
Define a private helper struct to replace the old eventchecker spec and use it to codegen
an UnmarshalJSON and MarshalJSON implementation for a wrapper struct around the
EventChecker interface. This enables seamless marshaling and unmarshaling of the
underlying interface and a much cleaner API.
It may be possible to do something similar for MultiEventChecker but details are TBD
around what might look like.
> eventchecker: simplify yaml spec for eventchecker

- pkg/reader/namespace/namespace.go
- pkg/sensors/exec/exec_test.go
Please see individual commit messages.
> add test for namespaces and fix bug on 5.4 and below

- install/kubernetes/templates/_container_export_stdout.tpl
Resolve https://github.com/cilium/tetragon/issues/118
Supports plugging in another exporter container.
> fix(helm): Support command override in exporter container #118

- pkg/ktime/ktime.go
Don't truncate Ktime to milliseconds and give a higher resolution. Fix for https://github.com/cilium/tetragon/issues/124.
> Don't truncate Ktime to milliseconds

- pkg/sensors/exec/exec_test.go
The longpath execve tests were relying on detecting a specific kernel feature that enables
longer tracepoint arguments. The checks are currently looking for 5.15+ kernels, however
this feature actually was not included until 5.16. This causes the longpath tests to fail
on 5.15 kernels.
Fix the problem by bumping the version check to 5.16.
> tests/exec: bump longpath version check to 5.16

- .github/workflows/gotests.yml
- Makefile
- contrib/verify/verify.sh
This commit adds a helper script that enables us to easily confirm whether Tetragon BPF
programs will pass the verifier. Uses bpftool under the hood.
Co-authored-by: Jussi Maki <jussi@isovalent.com>
> contrib/verify: touch verify.sh

- docs/security-observability-with-ebpf/04_chapter/01_cilium_tracing_policy/01_privileged_pod.yaml
- docs/security-observability-with-ebpf/04_chapter/01_cilium_tracing_policy/02_nsenter.yaml
1. Update `01_privileged_pod.yaml`: should block a privileged pod start
2. Update `02_nsenter.yaml`: should block nsenter coming from a container 
Working on: `04_deny_c2_connection.yaml`: need to get the destination addr from sockaddr
> Update Chapter 4 Prevention Policies

- bpf/process/bpf_execve_event.c
- pkg/sensors/exec/exec_test.go
Disabling long path/args retrieval for 4.19 kernels,
because it breaks probe loading at the moment with
program too long error.
> tetragon: Disable long path/args retrieval for 4.19 kernels

- bpf/process/bpf_generic_retkprobe.c
- bpf/process/types/basic.h
Fixing loading of retkprobe with moving args pointer initialization
closer to the user to workaround clang being smart and breaking
verifier.
> tetragon: Fix retkprobe loading on 4.19

- .dockerignore
- .github/workflows/build-clang-image.yaml
- .github/workflows/gotests.yml
- Dockerfile
- Dockerfile.clang
- Dockerfile.dev
- Dockerfile.test
- Makefile
- bpf/process/generic_calls.h
- contrib/tester-progs/.gitignore
Use an upstreamed version of clang (clang-13) instead of our forked version. We provide a Docker image for convenience, but any distribution's clang should work provided it is >= clang-13. See individual commits.
Fixes #142
> build: use upstream clang instead of forked version for BPF programs

- contrib/tester-progs/dup-tester.c
- pkg/sensors/tracing/kprobe_copyfd_test.go
- testdata/specs/copyfd.yaml.tmpl
TestCopyFd is failing in older kernels due to missing an event from dup.
`dup` system call is captured by hooking at `fd_install` in a similar way to `open` system call which is not actually the case in CopyFD.
Will fix temporary https://github.com/cilium/tetragon/issues/152 but we have to fix also the `dup` case.
> Remove dup() test from TestCopyFd

- README.md
We've tested the Tetragon deployment for the first time in our #EveryoneCanContribute cafe meetup: https://everyonecancontribute.com/post/2022-06-16-cafe-52-learned-at-kubecon-eu-coffee-chat/  
Some of the kubectl commands use relative paths which only work when you have the project cloned locally. 
This PR changes all kubectl commands to using raw URLs and help smoothen the first impression, allowing to deploy and play < 15 minutes.
> Docs: Use URLs for kubectl apply demo commands instead of relative paths

- go.sum
Vendoring got out of sync with static checks at some point, probably when I modified the
command we run in the static-checks job. Fix this by running the same command on the base
repo.
> chore: fix vendoring

- install/kubernetes/templates/clusterrole.yaml
Tetragon daemonset should be only allowed to get/list/watch TracingPolicy objects
Tetragon daemonset should be only allowed to create/update the TracingPolicy CRD definition
Signed-off-by: Natalia Reka Ivanko <natalia@isovalent.com>
> Update Tetragon Clusterrole

- cmd/tetragon/main.go
- pkg/exporter/exporter.go
- pkg/exporter/exporter_test.go
- pkg/grpc/process_manager.go
- pkg/grpc/process_manager_test.go
- pkg/observer/observer_test_helper.go
- pkg/server/server.go
We observed that rarely if we SIGTERM Tetragon (e.g. what pod restart and destroy do before SIGKILL it) that a corrupted json file might get left behind. The theory is this is do to writers being killed in the middle of an operation. 
To fix we do two things. First propagate a single context through the processManager and Server objects instead of just using context.Backgroun(). This allows the cancel() call from our SIGTERM handler to be handled by ctx.Done() in the respective go routines. Then we add a waitGroup to the signal handler to ensure it waits until the writer has exited.
I only fix the go routine responsible for writes here. We should audit the other routines as well.
And second I started thinking about how we nest the various objects, at the moment we pass a lot of input …
> tetragon: Teach file writer to exit gracefully

- bpf/process/generic_calls.h
- bpf/process/types/basic.h
> tetragon: Remove unused variables

- bpf/process/bpf_process_event.h
Please review commit by commit.
FIXES https://github.com/cilium/tetragon/issues/187
> Document better path resolution code introduced in PR #90 

- install/kubernetes/templates/clusterrole.yaml
According to the k8s RBAC documentation:
Note: You cannot restrict create or deletecollection requests by their resource name.
For create, this limitation is because the name of the new object may not be known at
authorization time.
This was causing our operator to fail because it the "create" verb was restricted in the
resource name which was not known ahead of time. To fix this, we need to split out the
"create" permission such that it is not restricted by resourceNames. We can keep the other
CRD permissions as-is.
Logs from operator before this change:
level=fatal msg="Unable to register CRDs" error="Unable to create custom resource
definition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User
\"system:serviceaccount:kube-system:tetragon\" cannot create resource …
> helm/rbac: split crd create permissions

- Makefile
- README.md
Add documentation to makefile as well as make vendor command. Also add an FAQ to the README.
> build/docs: simplify build process and add documentation

- install/kubernetes/templates/clusterrole.yaml
Tetragon daemonset should be only allowed to get/list/watch TracingPolicy objects
Tetragon daemonset should be only allowed to create/update the TracingPolicy CRD definition
Signed-off-by: Natalia Reka Ivanko <natalia@isovalent.com>
> Update the current clusterrole

- bpf/alignchecker/bpf_alignchecker.c
- pkg/alignchecker/alignchecker.go
- pkg/api/tracingapi/client_kprobe.go
Take the issue #108 . Have tested locally.
--- 
BTW, the alignment-checker reminds me that 
```
C and Go structs alignment check failed: execvemap.ExecveValue(48) size does not match execve_map_value(112)
```
Is this expected? I found that they are defined as 
```C
// bpf/lib/process.h
struct execve_map_value {
struct msg_execve_key key;
struct msg_execve_key pkey;
__u32 flags;
__u32 nspid;
__u32 binary;
__u32 pad;
struct msg_ns ns;
struct msg_capabilities caps;
} __attribute__((packed)) __attribute__((aligned(8)));
```
and 
```go
// pkg/sensors/exec/execvemap/execve.go
type ExecveValue struct {
Process processapi.MsgExecveKey
Parent  processapi.MsgExecveKey
Flags   uint32
Nspid   uint32
Buffer  uint64
}
```
Apparently, they are not the same...
And another related `ExecveValueL` struct in …
> chore: add event_config alignment check

- pkg/sensors/exec/exec.go
It can actually happen that there will be no arguments
or filename, in which case we need to check the data
length and api.EventErrorFilename flag.
> tetragon: Check the returned data length for exec arguments

- Makefile
PR is a workaround for the inconsistent behavior of `docker cp` and `podman cp` for the symlinks - docker copies the symlink itself but podman copies the target of the symlink, which leads to the missing symlinks and broken build.
Slack discusion: https://cilium.slack.com/archives/C2B917YHE/p1656948867647459
For reference - build and run with `podman` on rhel8 based on <https://github.com/cilium/tetragon/blob/main/docs/contributing/development/README.md#development-setup>:
```
CONTAINER_ENGINE='sudo podman' make tools-install
CONTAINER_ENGINE='sudo podman' LD_LIBRARY_PATH=$(realpath ./lib) make
sudo LD_LIBRARY_PATH=$(realpath ./lib) ./tetragon --bpf-lib bpf/objs
```
/cc @kkourt
> create symlinks for libbpf.so for podman

- api/v1/README.md
- api/v1/tetragon/tetragon.pb.go
- api/v1/tetragon/tetragon.proto
the invalid whitespaces in api/v1/tetragon.proto makes generated markdown document unreadable
remove invalid whitespaces in tetragon.proto and regenerate related files
Signed-off-by: Peihao Yang <peihao.young@gmail.com>
> doc: remove invalid whitespaces in proto file

- Makefile
`make test-compile` iterates all directories with Go code and calls go test to build the executable. In many of the directories there are no tests which introduces delays in the make process.
This commit calls go test only for directories that contain at least one test file (i.e. `*_test.go`).
Before the fix:
```
$ rm  -rf go-tests/ && time make test-compile > /dev/null
real	0m41.261s
user	2m10.735s
sys	0m24.337s
$ ls -la go-tests/ | wc -l
36
```
After the fix:
```
$ rm  -rf go-tests/ && time make test-compile > /dev/null
real	0m22.878s
user	1m16.238s
sys	0m10.950s
$ ls -la go-tests/ | wc -l
36
```
> Call go test only for directories that contain at least one test

- pkg/alignchecker/alignchecker_test.go
In order to run the aligncheker (i.e. compare the Go and C structs that are shared between user and kernel space) the user has to issue it manually:
```
$ sudo ./tetragon-alignchecker ./bpf/objs/bpf_alignchecker.o
OK
```
This commit adds a new unit test in `pkg/alignchecker/` that calls the alignchecker as part of the Go tests.
> Run alignchecker as part of unit tests

- pkg/sensors/program/map.go
It may be useful to directly perform operations on the inner cilium/ebpf map, so let's
expose it.
> map: expose inner map

- Makefile
Commit [1] broke libbpf-install target, which fails
if destination files exist:
$ make libbpf-install
mkdir -p ./lib
docker cp 9fb245cca6f49264e1ce716b5db5d6864e734e07b0d1558110880b37f5d0aa85:/go/src/github.com/covalentio/hubble-fgs/src/libbpf.so.0.2.0 ./lib
ln -s libbpf.so.0.2.0 ./lib/libbpf.so.0
ln: failed to create symbolic link './lib/libbpf.so.0': File exists
make: *** [Makefile:176: libbpf-install] Error 1
I need to fix this to get clean update eventhough I'm removing
the whole target in another libbpf remoal PR ;-)
[1] 7c22ff1af9bc create symlinks for libbpf.so for podman
> tetragon: Force libbpf link creation

- Makefile
- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/grpc/exec/exec.go
- pkg/grpc/process_manager.go
- pkg/grpc/process_manager_test.go
- pkg/grpc/tracing/tracing.go
- pkg/observer/observer_test_helper.go
- pkg/option/config.go
This simplifies Process manager and arg handling creating common pkg to handle getting/setting args. After this series ./pkg/option is also used for standard configuration options such as ProcessNS and ProcessCreds.
With this we can simplify Process Manager arg passing and avoid pushing args down through multiple layers of calls. And additionally logs can pretty print the args at any debug or info point we need them.
Finally fixes up cache init flow to only enable the eventCache when the K8s watcher is also enabled. This further simplifies bringing the ProcessManager up because we no longer need to pass the arg through. And finally, we can drop storing the cache in the process manager object. Caches are singular objects you can't have multiple caches of the same type. Historically, we …
> tetragon: Process Manager args cleanup

- pkg/execcache/execcache.go
There can be only one execCache add a getter for it so we can skip
holding a reference in process manager and implying we might have
many caches.
> tetragon: Add Get() execCache and allow only single cache

- pkg/grpc/exec/exec.go
- pkg/grpc/tracing/tracing.go
Exec sensor missed check for execcache != nil and attempts to query the
execcache even though its a nil pointer.
To fix simply check ptr for nil. Perhaps we should hide these behind a
fake interface, but not sure its worth it really.
This fixes the following,
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15835df]
goroutine 68 [running]:
testing.tRunner.func1.2({0x170cf40, 0x27c6850})
/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x170cf40, 0x27c6850})
/usr/local/go/src/runtime/panic.go:838 +0x207 …
> tetragon: avoid segfault of eventcache is disabled

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/observer/observer.go
- pkg/observer/observer_stats.go
- pkg/observer/observer_test_helper.go
- pkg/option/config.go
Dir variables are passed around and embedded in the observer even though
they are set once and fixed. Further they are not part of the observer
object at all. The fallout is then random pkgs reach into observer
just to lookup directories. This can then cause cycles and makes dev
work more difficult.
Lets skip passing them around and read them directly through the option
pkg.
> tetragon: Avoid passing dir options around and add them to option

- cmd/protoc-gen-go-tetragon/eventchecker/field.go
The logic for determining type names from protobuf maps was incorrect because we were
subbing in the FieldDescriptor rather than the underlying type. Fix this for now to get
codegen working. A subsequent commit will fix the eventchecker itself so arbitrary map
key/values will actually work.
> eventchecker: fix broken codegen for map checker

- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- cmd/protoc-gen-go-tetragon/eventchecker/field.go
- pkg/sensors/tracing/kprobe_copyfd_test.go
- pkg/sensors/tracing/kprobe_test.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
> eventchecker: fix type mismatch bug in argument checkers

- bpf/process/generic_calls.h
- bpf/process/types/basic.h
- pkg/observer/observer.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/testutils/sensors/testrun.go
In kprobes, we support `matchArgs` selector for `fd` and `file` types with `Equal`, `Prefix`, and `Postfix` operators.
This PR first introduces unit-tests for all of these cases. These tests show an issue in the case of `Postfix` operator and we also fix this issue.
Currently, `matchArgs` for `fd/file` types support up to 2 values. This PR also increases this number for newer kernels (5.3+) to 8. It keeps that to 2 for older kernels. 
Finally, we also update unit-tests to check these.
ps. Tested locally on 4.19, 5.4, 5.10, and 5.13.
> kprobes: matchArgs improvements (for fd/file)

- README.md
The default channel now comes with BTF file.
> README: Remove --release-channel GKE flag

- .github/workflows/checkpatch.yaml
This was flagging new files following our current convention for SPDX license tag. This is
annoying so turn it off.
> ci/checkpatch: remove SPDX warning

- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- cmd/protoc-gen-go-tetragon/eventchecker/field.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
This commit adds support to eventchecker for checking maps of string -> string. Note that
other kinds of maps are not supported for now as this would require a non-trivial refactor
to the existing code. But that should be fine for now. We can always revist this later if
needed.
> eventchecker: add support for checking map[string]string

- pkg/execcache/execcache.go
- pkg/grpc/exec/exec.go
After 4dac2750a, exec.go was adding events to the wrong cache. This was causing missing
pod info for essentially all events. Fix this by using the execCache again rather than the
eventCache.
> exec: fix cache for pod info

- pkg/sensors/exec/exec.go
- pkg/sensors/exec/procevents/proc_reader.go
GetRunningProcs() that reads process entries from procfs during startup
takes two boolean arguments which we always set to true, then it passes
these arguments down to how we send data to listeners and to write to the
execve_map.
Let's simplify this and remove these arguments as this makes reading code
easier.
Signed-off-by: Djalal Harouni <djalal@isovalent.com>
> pkg:sensors: simplify GetRunningProcs() when we read running processes

- bpf/Makefile
- bpf/include/vmlinux.h
- bpf/lib/bpf_helpers.h
- bpf/libbpf/bpf_tracing.h
- bpf/process/bpf_fork.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/generic_calls.h
- bpf/process/retprobe_map.h
1. add libbpf header bpf_tracing.h
2. replace probe_read to CORE macros on pt_regs
3. add a new configuration item in bpf/Makefile to assign arch
4. revise the definition `__VMLINUX_` in vmlinux.h to `__VMLINUX_H__`, which is the standard definition generated via bpftool
Signed-off-by: Peihao Yang <peihao.young@gmail.com>
> bpf: replace arch-specific pt_regs assumptions with bpf co-re macros

- .github/workflows/run-e2e-tests.yaml
- tests/e2e/runners/runners.go
Update the default runner config so that it only installs Cilium if it is not already
installed in the cluster.
> tests/e2e: only install cilium if it is missing

- pkg/sensors/tracing/kprobe_test.go
Before that tests that fail to create a new directory (i.e. already exists) just skipped.
FIXES: https://github.com/cilium/tetragon/issues/238
> Create temp directories for all tests in kprobes

- pkg/sensors/tracing/kprobe_test.go
mountPath was unused and our static checks were complaining. Let's get rid of it.
> tests/kprobe: remove unused const

- bpf/lib/data_msg.h
- bpf/process/data_event.h
FIXES: https://github.com/cilium/tetragon/issues/220
Tested over https://github.com/cilium/tetragon/pull/171 for clang-13 support.
> Fix for verifier issue in 5.4 with clang-13

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
Adding -cpuprofile option that allows to store go cpu profile
into provided file, like:
`  # ./tetragon --cpuprofile krava.prof`
Tetragon will show the start/stop messagein the log:
```
time="2022-07-28T13:39:12+02:00" level=info msg="Starting cpu profiling" file=krava.prof
...
time="2022-07-28T13:39:22+02:00" level=info msg="Stopping cpu profiling" file=krava.prof
```
you can display the profile in browser with:
` $ go tool pprof -http=:8080 krava.prof`
that should spawn new browser tab, go on 'VIEW' menu,
click on 'Flame Graph' and be amazed ;-)
> tetragon: Add -cpuprofile option

- bpf/process/bpf_generic_retkprobe.c
Renaming entry point of retkprobe function so it won't get
confused in bpftool stats output with the regular kprobe
program.
We used the 'generic_kprobe_event' to make things easier
in previous libbpf loader code. Now when it's gone we can
have unique name for retkprobe program.
> tetragon: Rename entry point of retkprobe function

- pkg/sensors/tracing/kprobe_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
> tests: use `T.TempDir` to create temporary test directory

- api/v1/README.md
- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- api/v1/tetragon/tetragon.pb.go
- api/v1/tetragon/tetragon.pb.json.go
- api/v1/tetragon/tetragon.proto
- bpf/process/types/basic.h
- bpf/process/types/bpfattr.h
- crds/examples/bpf_check.yaml
- pkg/api/tracingapi/client_kprobe.go
- pkg/btf/validation.go
- pkg/generictypes/generictypes.go
- pkg/grpc/tracing/tracing.go
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/reader/bpfattr/bpfattr.go
- pkg/sensors/tracing/generickprobe.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
This patch allows us to collect name, program type, and instruction
count of eBPF programs when they are verified.
Signed-off-by: Sarah Fujimori <sarah.fujimori@isovalent.com>
> add support for bpf_attr type

- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/exec/exec_test.go
- pkg/grpc/tracing/tracing.go
- tests/e2e/tests/skeleton/skeleton_test.go
An exec and exit event can be delivered out of order to the agent. For this reason, we have a cache that keeps the un populated events for a small period of time to wait for the exec event.
There are also other caches that deal with this situations.
This commit adds tests for pkg/grpc/exec. For now it only contains 2 different cases:
1. exec and exit events in order (TestGrpcExecInOrder)
2. exec and exit events out of order (TestGrpcExecOutOfOrder)
> Add tests for pkg/grpc/exec

- bpf/lib/process.h
Applying 'packed' attribute to structs causes clang to write to the
members byte-by-byte, as offsets may not be aligned. This is bad for
performance, instruction count and complexity, so don't apply this
attribute to structs where members are correctly aligned already
(e.g. by padding, layout).
> Remove 'packed' attribute where possible

- bpf/lib/bpf_helpers.h
relax_verifier() is used to cause the verifier to add a prune point that
can be helpful in reducing the overall complexity. It does this by
calling get_smp_processor_id(); in order to prevent the call from being
optimised out, its result is stored in a register and marked with the
unused attribute. This results in two assembler instructions, one for
the call and one to store the result. It also potentially causes a
register spill.
This commit changes relax_verifier() into a single assembler instruction
to call the helper. This reduces the overall instruction count and
reduces complexity.
> Make relax_verifier() into one instruction

- pkg/eventcache/eventcache.go
Currently, if eventcache.New() is called multiple times the old cache
will continue to be used. But, this is problematic if the caller is
trying to configure the cache with new parameters, such as duration
or exporter.
Specifically this is the case in the unit tests where each Test* is
creating a new process manager and exporter using a new file so that
we have specific logs for each test. But, the current behavior means
any events going through the eventcache (after the first test) are
then lossed because they attempt to export into the old filename.
To fix simply stop the old go() on New() and reconfigure it. When
I ran this locally forcing all events through the cache I am now
able to PASS multiple unit tests.
> tetragon: Update eventcache on New() call and cleanup old state

- tests/e2e/checker/multiplexer.go
- tests/e2e/tests/labels/labels_test.go
Some bug fixes for e2e framework on GKE clusters. See individual commits.
> e2e-framework: fix panic and bump event limit on demo app test

- .github/workflows/gotests.yml
From a failed test:
`level=info msg="Dumped bugtool info" file=/tmp/tetragon-bugtool.tar.gz test=TestKprobeObjectReadReturn`
So the the bugtool tarball is /tmp/tetragon-bugtool.tar.gz. The current action
uploads /tmp/tetragon-bugtool-* which does not match anything.
This commit fixes the action to upload the bugtool report.
> Fix bugtool upload

- bpf/process/bpf_process_event.h
The BPF_CORE_READ_INTO can help reduce unnecessary variables and simplify the logic
Signed-off-by: Peihao Yang <peihao.young@gmail.com>
> refactor: eliminate variables by BPF_CORE_READ_INTO

- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec_test.go
- pkg/jsonchecker/jsonchecker.go
- pkg/process/cache.go
- pkg/process/process.go
This unit-test emulates the case where we get an exit event but we miss the exec event. In that case, we should wait for the cache iterations to end and then produce an exit event with partial process info. In that case we only have the process start time and the process pid.
This PR also fixes https://github.com/cilium/tetragon/issues/285 and https://github.com/cilium/tetragon/issues/247. OOO events was related to these issues and thus I don't use a separate PR for them. To test this I have run 8 successful consecutive runs in the CI while before a kprobe flake appears every ~3 runs. 
> Add a unit test for missing exec event in the eventcache

- pkg/metrics/watchermetrics/watchermetrics.go
- pkg/watcher/watcher.go
This commit adds metrics for our k8s watchers so we can keep track of how many sucessful
watcher events we get as well as any errors.
> metrics: add watcher metrics

- contrib/mapdups.sh
This helper script is useful for parsing a bpftool map dump and determining whether or
not duplicate maps are loaded (as indicated by their map name). It's not a perfect
solution, but is helpful for rough debugging locally when something is not working right
in Tetragon.
When run on a file containing bpftool map output, the result will be a list of map names
and their respective counts, sorted by count. Numbers higher than 1 are considered
suspicious unless the map is OK to be duplicated (e.g. a "*heap" map in Tetragon.)
> contrib: introduce mapdups.sh

- .gitignore
- bpf/process/bpf_process_event.h
- bpf/process/types/basic.h
This PR does not change anything in the path resolution logic.
Tested with running `sudo ./contrib/verify/verify.sh ./bpf/objs/` in 4.19, 5.4, 5.10, 5.13, and 5.15. 
> Cleanup path resolution code

- pkg/eventcache/eventcache.go
- pkg/metrics/eventcachemetrics/eventcachemetrics.go
- pkg/reader/notify/notify.go
Minor fixes to event cache handlers so that they deal with missing pod info separately
from missing process info.
Also update the event cache to increment pod and process info errors by event type when we
hit our cache strikes limit.
> eventcachemetrics: fix eventcache and add error metrics

- pkg/eventcache/eventcache.go
It was rightly pointed out that event.internal not being nil is an invariant here. If this
ever changes accidentally we would probably want to know and in any case the panic would
happen much earlier in the code path. So let's remove the nil check here.
> eventcache: remove event.internal nil check for exec events

- .dockerignore
- .github/workflows/build-clang-image.yaml
- .github/workflows/gotests.yml
- .github/workflows/static-checks.yaml
- Dockerfile
- Dockerfile.clang
- Dockerfile.dev
- Dockerfile.test
- Makefile
This needs more testing on additional kernels before we merge. For example, while testing locally I noticed some verifier errors on 5.4 that we should fix first.
> build: use clang-13 to build bpf programs

- pkg/grpc/exec/exec.go
- pkg/grpc/exec/exec_test.go
This PR also include several cleanup, fixes, and optimizations in `pkg/grpc/exec` unit tests. 
> Add unit-test for parent and child process refcounts

- pkg/process/cache.go
We observed a panic from cache code when trying to print a log message. The issue
is the pkg has not been completely converted over to the new logging scheme. Seems
like we missed some bits when refactoring.
To fix remove log from Cache and use GetLogger() api.
> tetragon: Fix cache usage of logger

- Vagrantfile
- docs/contributing/development/README.md
Leftover documentation update after removing libbpf
and updating to clang-13.
> tetragon: Update development docs about tools

- pkg/grpc/exec/exec_test.go
This PR introduces 4 unit-tests that cover the following cases:
1. In-order exec and exit events
1. Pod info becomes available after both events
2. Pod info becomes available after first event (exec)
2. Out-of-order exit and exec events
1. Pod info becomes available after both events
2. Pod info becomes available after first event (exit)
> Add unit-tests for missing pod info events

- .github/workflows/vmtests.yml
With this change, force pushing or updating a job will cancel old runs, saving compute
resources.
> ci/vmtest: add concurrency groups

- Dockerfile
- Dockerfile.codegen
- operator.Dockerfile
Update used cilium-builder image to use go 1.18.3.
ref: https://github.com/cilium/cilium/commit/fa3cfa8bcb34bda17bdb3a299b1b09a54cb149f3
Signed-off-by: Kornilios Kourtis <kornilios@gmail.com>
> Dockerfille(s): use cilium-builder with go 1.18

- Dockerfile
- Dockerfile.test
Commit 8bd6295af79599489c8244faa75f64a2f04bd0a6 updated the image tags
of Dockerfile and Dockerfile.test but not the sha256 hashes. This meant
that the old version was used since the tag is ignored in the present of
the hash.
Add the correct hashes:
$ ~/src/cilium/images/scripts/get-image-digest.sh docker.io/library/golang:1.18.3-alpine3.15
sha256:f9181168749690bddb6751b004e976bf5d427425e0cfb50522e92c06f761def7
$ ~/src/cilium/images/scripts/get-image-digest.sh docker.io/library/golang:1.18.3
sha256:1650c170f3c55c158431cd35906cb6faf25f5c93b9d8850341c81e1236eaa745
fixes: 8bd6295af79599489c8244faa75f64a2f04bd0a6
> chore: use proper sha256 values for go images

- pkg/api/readyapi/readyapi.go
- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/test/test.go
- pkg/grpc/tracing/tracing.go
- pkg/reader/notify/notify.go
Some objects should never hit retry logic for internal process lookups. One
example here is the exec entries which are the source of the internal
process. But, the exec events can still be missing pod info. Another
example is the test and ready events. These should not be bounced through
the cache and if they are we should get an error. Current implementation
though does not split up internal retries from podInfo retries. Also it
does not allow msg types to specify type specific handlers and instead
did some hard coded exception for exec.
This patch pulls the retry logic into two methods: one to catch missing
internal process and then a second to catch other state such as the
podInfo. Then now that we have a method we can throw exceptions if we
ever catch a cache retry from a test or …
> tetragon: refactor eventCache retry logic

- docs/contributing/development/README.md
PR extends `docs/contributing/development/README.md` with instructions on using `podman` instead of `docker`.
> devel README.md: add podman instructions

- Makefile
PR adds the volume mount `:Z` option for the `docker run` (or `podman run`) command to work properly with SELinux.  This is to prevent the following error with the current code:
```
$ CONTAINER_ENGINE='sudo podman' make tetragon-bpf-container
/bin/sh: docker: command not found
sudo podman rm tetragon-clang || true
a53e97d50c0bd557ddaa234c835d62c5af982415688743fcff30d3022e1c5de4
sudo podman run -v /home/dmitris/dev/hack/gh/cilium/tetragon:/tetragon -u $(id -u) --name tetragon-clang quay.io/cilium/clang:7ea8dd5b610a8864ce7b56e10ffeb61030a0c50e@sha256:02ad7cc1d08d85c027557099b88856945be5124b5c31aeabce326e7983e3913b make -C /tetragon/bpf
make: *** /tetragon/bpf: Permission denied.  Stop.
make: *** [Makefile:71: tetragon-bpf-container] Error 2
```
`sealert` shows:
```
SELinux is preventing …
```
> add volume mounting ':Z' label

- .github/workflows/vmtests.yml
GA defaults to fail-fast on matrix strategies. This means that if one of our test groups
fails, it will cancel all the others. I think we really don't want this because 1. most of
the other jobs will probably be almost completed anyways so cancelling them is not worth
it and 2. more cancelled jobs means more jobs we need to re-run on flakes.
Let's disable fail-fast for the reasons stated above.
> ci/vmtest: disable fail-fast on test matrix

- .github/workflows/vmtests.yml
- cmd/tetragon-vmtests-run/image.go
- cmd/tetragon-vmtests-run/run_tests.go
- go.mod
- go.sum
- vendor/github.com/cilium/little-vm-helper/pkg/images/actions.go
- vendor/github.com/cilium/little-vm-helper/pkg/images/conf.go
- vendor/github.com/cilium/little-vm-helper/pkg/images/step_create_image.go
- vendor/modules.txt
> vmtests: address RCU stalls

- cmd/tetragon/main.go
- pkg/api/flags.go
- pkg/api/readyapi/readyapi.go
- pkg/bugtool/bugtool.go
- pkg/defaults/defaults.go
- pkg/observer/observer.go
- pkg/observer/observer_test_helper.go
- pkg/option/doc.go
- pkg/reader/proc/proc.go
There was a find and replace error in our initial release that caused a bunch of instances
of Tetragon to be capitalized like TETRAGON. Fix these up since it looks bad.
> chore: fix capitalization TETRAGON -> Tetragon

- .github/workflows/vmtests.yml
- cmd/tetragon-tester/init.go
- cmd/tetragon-vmtests-run/conf.go
- cmd/tetragon-vmtests-run/image.go
- cmd/tetragon-vmtests-run/main.go
- cmd/tetragon-vmtests-run/qemu.go
- pkg/vmtests/vmtests.go
> vmtests fixes and improvements

- api/v1/tetragon/tetragon_ext.go
- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/exec/exec_test.go
- pkg/grpc/tracing/tracing.go
- pkg/metrics/errormetrics/errormetrics.go
- pkg/process/process.go
- pkg/reader/notify/notify.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon_ext.go
When we bounce through the event cache its possible we never found the
parent process. In this case we also get a ref cnt imbalance because
the exit event will dec the ref but the exec does not.
To fix this update the Retry logic to also search for the parent
and if its missing populate it plus do refInc. And similarly
on exit check for parent and if its not handled yet similarly
go to the cache and wait, but this time do a refDec.
Now its still possible the dec happens before the inc in this
scenario,
```
exec -> cache ------------------> parentFound IncRef
exit -> decRef
```
But, in this case its OK that the ref briefly was incorrect because
the GC will wait for at minimum two iterations before removing it
to account for this eventually consistent logic.
Finally, there is the corner …
> Make events with missing parents go through eventcache

- cmd/tetragon/main.go
Before parsing environment variables we have to replace every "-" by "_"
in variable names.
> tetragon: before parsing environment vars replace "-" with "_"

- cmd/tetragon/main.go
- pkg/btf/btf.go
- pkg/btf/btf_test.go
- pkg/defaults/defaults.go
- pkg/sensors/load.go
- pkg/sensors/tracing/generickprobe.go
Users and even developers may get confused on why Tetragon is not working or did it find the appropriate BTF files. Improve logging and reduce confusion
> btf: improve logging around BTF files lookup

- pkg/sensors/exec/exec.go
- pkg/sensors/exec/exec_test.go
During execve events we try to lookup the container ID and fill up the
docker field, however since cgroups implementation has two separate
incompatible implementations, and container runtimes with k8s may use
different one according to their version, not to mention semantics
that change over time. Let's try to log the status of the Container ID
lookup.
Logging is at trace level, this will help debug our tests and even correlate
events with exec_id that have a missing docker field.
> exec: log results of docker or container ID lookup during execve events

- pkg/observer/observer_test_helper.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/program/coll.go
- pkg/sensors/program/loader.go
- pkg/sensors/program/program.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/testutils/sensors/load.go
- pkg/testutils/sensors/testrun.go
Adding CheckSensorLoad function that takes array of programs
and maps and checks they are loaded and share specified maps.
Plus related changes to allow that.
> tetragon: Add bpf program loader tests

- Makefile
- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- cmd/protoc-gen-go-tetragon/eventchecker/multichecker.go
- tests/e2e/checker/rpcchecker.go
- tests/e2e/helpers/dumpinfo.go
- tests/e2e/runners/runners.go
- tests/e2e/state/state.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
This PR makes two critical additions to the e2e test export. In particular, we will now dump a list of all events encountered by the checker in order as well as all unmatched checks from the event checker in JSON format. Combined, these two additions will help us debug failing tests by enabling us to match events 1:1 with the checker logs. See individual commits.
> tests/e2e: dump extra checker info

- Dockerfile
- Makefile
Currently, tetragon images do not incude the version. This is because we
generate the version using git, and .git is in .dockerignore so it will
not be copied over when we are bullding the image.
Fix this by passing an appropriate build argument to docker build.
Tested using:
$ make image
$ docker run -it  --entrypoint /bin/sh cilium/tetragon:latest
/ # /usr/bin/tetragon
time="2022-08-17T09:57:07Z" level=info msg="Starting tetragon" version=v0.8.0-478-g30eb03fbf
...
> Dockerfile: incude tetragon version in the image

- bpf/process/bpf_execve_event.c
Currently, we leak clone events into the procCache. The procCache is an LRU so not free'ing events correctly means after some uptime we have a bunch of unused memory around and LRU will free things. Nothing breaks but its unnecessary memory usage.
To fix ensure clone and execve events work together correctly see patch1. This issue was introduced with the clone event relatively recently.
> tetragon: handling clone events and exec events more correctly

- pkg/sensors/program/coll.go
Add program even with no maps.
> tetragon: Do not fail because of the empty map ids

- tests/e2e/checker/rpcchecker.go
We weren't dumping the checker type before which was making it difficult to discern which
checks were which in the dump. Add it to the dump here.
> tests/e2e: dump checker type along with event body

- Vagrantfile
https://lists.ubuntu.com/archives/ubuntu-announce/2022-July/000281.html indicates July 14, 2002 as the EOL date for ubuntu Impish release, therefore change it to Jammy Jellifish one https://lists.ubuntu.com/archives/ubuntu-announce/2022-April/000279.html.
> change Vagrant image to ubuntu/jammy64

- cmd/tetra/getevents/getevents.go
- pkg/encoder/color.go
- pkg/encoder/encoder.go
- pkg/encoder/encoder_test.go
> encoder: improve api to make it more generic

- .gitignore
PR adds `.vagrant/` to `.gitignore` for less spurious red on the `git status` command (after playing with vagrant in this repo).
Signed-off-by: Dmitry Savintsev <dsavints@gmail.com>
> gitignore .vagrant directory

- docs/contributing/development/README.md
- tests/vmtests/fetch-data.sh
PR changes the setting of `CONTAINER_ENGINE` in tests/vmtests/fetch-data.sh to allow overwriting the variable with for example `sudo podman` while keeping `docker` as the default.  It also adds a link to the vmtests README in the contributor guide.  
Based on the Slack conversation https://cilium.slack.com/archives/C2B917YHE/p1660856168376349?thread_ts=1660843012.876959&cid=C2B917YHE - thanks @kkourt!
> Podman-friendly CONTAINER_ENGINE setting

- pkg/multiplexer/doc.go
- pkg/multiplexer/multiplexer.go
- tests/e2e/checker/rpcchecker.go
The multiplexer previously lived inside the e2e-framework's checker package but it really
should exist independently of the e2e-framework, so let's move it out into its own
package.
> chore: move multiplexer into its own package

- .github/workflows/lint-codeql.yml
Ubuntu 18.04 is deprecated and is now being severely throttled by GA. So let's update the
runner to Ubuntu 20.04.
> ci/codeql: change runner version

- pkg/sensors/sensors.go
- pkg/sensors/sync.go
Some sensors need to perform additional work when unloaded, in order to
leave the system in a clean state, as part of facilitating the
capability to load and unload sensors repeatedly. A clear example would
be if a sensor installed a timer (an implementation of a stopable
ticker) in an enable function.
This commit adds an UnloadHook that can optionally be set by a sensor to
point to a function to call, prior to the programs and maps being
unloaded, when the sensor is being unloaded.
> Add UnloadHook to Sensors

- pkg/encoder/color.go
- pkg/encoder/encoder.go
Make ProcessInfo usable across packages. This should be useful in the future if we decide
to split color.go out of the encoder package. It also helps folks downstream who want to
write custom encoders.
> color: make ProcessInfo public

- bpf/include/api.h
- bpf/lib/bpf_events.h
- bpf/lib/bpf_helpers.h
- bpf/process/bpf_process_event.h
- pkg/bpf/bpffs_linux.go
- pkg/defaults/defaults.go
- pkg/sensors/load.go
- pkg/sensors/program/loader.go
This is a preparation PR to get some patches merged from #225 to easy review on it.
Only major change here is : support of raw tracepoints
> tetragon: cgroup rework preparation

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
Adding memprofile option that allows to store go memory profile
into provided file, like:
`  # ./tetragon --memprofile mem.prof`
Tetragon will show the start/stop messagein the log:
```
time="2022-08-22T23:19:17+02:00" level=info msg="Starting mem profiling" file=prof.mem
... 
time="2022-08-22T23:19:38+02:00" level=info msg="Stopping mem profiling" file=prof.mem
```
you can display the profile in browser with:
`  $ go tool pprof -http=:8080 mem.prof
`
that should spawn new browser tab with memory profile graph
with flamegraph as an option under 'VIEW' menu.
> tetragon: Add memprofile option

- pkg/cilium/monitor.go
- pkg/vmtests/vmtests.go
> remove time.After calls in for loops

- .github/workflows/gotests.yml
- Makefile
When we are using libbpf we had some issues with open fd when running
unit tests. By moving to cilium/ebpf this should not be still an issue.
> Do not increase open file descriptors limit

- cmd/tetragon/main.go
- pkg/sensors/load.go
- pkg/sensors/program/coll.go
- pkg/sensors/program/loader.go
- pkg/testutils/sensors/testrun.go
Adding -debug option to sensor tests and moving some of the loading messages to debug level.
> tetragon: Debug output fixes

- Dockerfile.clang
- Makefile
> chore: fix image-clang build issues

- pkg/grpc/exec/exec_test.go
- tools/split-tetragon-gotests/main.go
pkg.grpc.exec relies on sleep() calls in order to wait for the
eventcache to run. Running them on heavily loaded VM cause flakes.
As they are not kernel-dependant, let's run them only as part of
gotests.
> Remove pkg.grpc.exec from vmtests

- pkg/api/readyapi/readyapi.go
- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/test/test.go
- pkg/grpc/tracing/tracing.go
- pkg/process/process.go
- pkg/reader/notify/notify.go
The AddCloneEvent fails to add process the the cache if
the parent does not exist - there's no record of it. 
This can happen for example in TestFork test where fork events
can be delievered out of order and tetragon sees the child fork
event before the parent's one.
Adding retry logic for clone events, which will retry the fork
event processing and adding the hild process entry after the 
timeout. During the timeout the parent is updated and following
retry logic will add the child's entry properly.
> tetragon: Allow retry logic for clone events

- bpf/lib/bpf_events.h
- bpf/process/bpf_execve_event.c
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
Adding execve_map related fixes.
> tetragon: execve map related fixes

- pkg/metrics/errormetrics/errormetrics.go
- pkg/metrics/eventmetrics/eventmetrics.go
Add a new error metric that tracks events that are missing process info.
> metrics: add missing process info error metric

- Dockerfile.golangci-lint
hubble-libbpf is not needed since we moved to cilium/ebpf.
> Dockerfile.golangci-lint: remove hubble-libbpf use

- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
`InitKernelSelectors` and `InitTracepointSelectors` functions are almost the same. So we removed the second one.
> Cleanup in selectors/kernel.go

- tests/e2e/helpers/dumpinfo.go
- tests/e2e/helpers/gops/gops.go
- tests/e2e/helpers/portforward.go
- tests/e2e/runners/runners.go
- tests/e2e/state/state.go
This commit introduces the ability to dump gops debug information at the end of failed
end-to-end tests. We start by dumping memory statics as well as a heap profile for the
application. As with metrics, dumps occur every 30 seconds as well as at the end of
a test, and are discarded unless either the test fails or the user has passed
--tetragon.keep-export=true when running the test.
We also dump a copy of the Tetragon binary running in each Tetragon pod. Unlike the other
dumps, this happens only once at the beginning of a test as it is a costlier operation and
the binary is obviously not expected to change. This binary dump can be used in
cominbation with the heap dump to run it through `go tool pprof`, generating a call graph
that summarizes memory usage throughout Tetragon. …
> tests/e2e: dump gops information at the end of failed tests

- .github/workflows/run-e2e-tests.yaml
- Makefile
- tests/e2e/flags/flags.go
- tests/e2e/install/tetragon.go
- Add a -tetragon.btf flag to tests/e2e for easily using a custom BTF file in a KinD cluster
- Add some extra flags to the Makefile for more easily configuring test options, including a BTF file to use
> tests/e2e: improvements to testing workflow

- pkg/testutils/sensors/testrun.go
Remove an old verbosity-level flag in tests which is no longer used. Add a new flag -trace
which sets the log level to trace. Note that this conflicts with a similar argument to go
test so it must be passed after -args.
> tests: remove deprecated verbosity-level and add trace flag

- .github/workflows/build-images-ci.yml
They don't handle comments.
https://github.com/cilium/tetragon/runs/8213728526?check_suite_focus=true
> build-images-ci: Remove comments from tags section

- bpf/lib/bpf_helpers.h
- bpf/lib/generic.h
- bpf/lib/hubble_msg.h
- bpf/lib/process.h
- bpf/process/bpf_execve_event.c
- bpf/process/bpf_exit.h
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_process_event.h
- bpf/process/retprobe_map.h
- bpf/process/types/basic.h
Switching to BTF defined maps. This allows to dump map values nicely, like:
```
[{
"key": 431671,
"value": {
"key": {
"pid": 431671,
"pad": [0,0,0,0
],
"ktime": 171231811545404
},
"pkey": {
...
```
> tetragon: Switch to BTF defined maps

- bpf/include/vmlinux.h
- bpf/lib/bpf_cgroup.h
- bpf/lib/environ_conf.h
- bpf/libbpf/bpf_core_read.h
- bpf/process/bpf_process_event.h
- pkg/api/confapi/confapi.go
- pkg/cgroups/cgroups.go
- pkg/observer/observer.go
- pkg/sensors/base/base.go
- pkg/sensors/config/confmap/confmap.go
- pkg/sensors/exec/exec_test.go
This was part of https://github.com/cilium/tetragon/pull/225 , it was cleaned in order to improve our logic how we operate on cgroup hierarchies.
bpf:cgroups: pass subsys index when operating on cgroup_subsys_state set
Select which cgroup controllers to use at runtime by analyzing current machine
cgroup configuration and adapt the bpf helpers to use the best option.
We have experienced events that did not have the proper container ID 'docker' nor the pod fields set. The reason is due to:
In Cgroupv1 mode usually systemd only sets up by default the 'cpu, cpuacct, memory, devices and pids' controllers, cpuset which in normal cases indexed at 0 is not installed. Since some container runtimes and different environments may use systemd as a cgroup driver this can cause problems where we won't …
> cgroups: select which cgroup hierarchy and subsystem state to use

- pkg/observer/observer_test_helper.go
- pkg/sensors/tracing/kprobe_test.go
This reverts commit 2dc54da6a84df9346e8753d67c5219b504b4933c.
I sometimes pass a set of programs into observer test framework for running debug tests. I don't want to lose the capability so lets revert this for now and we can work to add some users. Or maybe improve the API so its not as clunky, but lets not just drop it.
> tetragon: Revert "observer_test_helper: do not pass the base sensor"

- pkg/btf/btf_test.go
- pkg/bugtool/bugtool_test.go
- pkg/cgroups/cgroups.go
- pkg/config/yaml.go
- pkg/kernels/kernels.go
- pkg/observer/observer_test_helper.go
- pkg/reader/caps/caps.go
- pkg/reader/namespace/namespace.go
- pkg/reader/proc/proc.go
- pkg/sensors/exec/procevents/proc.go
- pkg/sensors/exec/procevents/proc_reader.go
- pkg/sensors/sync.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
- tests/e2e/helpers/dumpinfo.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://pkg.go.dev/io/ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadDir` => `os.ReadDir` (returns a slice of `os.DirEntry` rather than a slice of `fs.FileInfo`)
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`
> refactor: move from io/ioutil to io and os packages

- pkg/observer/observer.go
Log errors from event handlers and use structured logging for opcode errors.
> logging: slight improvement to observer logging

- bpf/lib/generic.h
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/pfilter.h
- bpf/process/types/basic.h
`bpf/process/pfilter.h` implements several selectors for generic kprobes
and tracepoints. These include `matchPIDs`, `matchNamespaces`,
`matchNamespaceChanges`, `matchCapabilities`, and `matchCapabilityChanges`.
The main function `generic_process_filter()` gets as argument a pointer
to `msg_generic_kprobe`.
This commit changes this function in order to get more generic arguments
in order to be used for other use cases as well.
> Make pfilter.h more generic

- pkg/testutils/filenames.go
Subtests in Go have a path separator ("/") in their name. This breaks our export file creation since it is considered an error by os.CreateTemp(). Replace the path separator with a "-" here to correct this.
> testutils: fix export file when test name contains path separator

- pkg/selectors/kernel.go
- pkg/sensors/path.go
- pkg/sensors/program/loader.go
- pkg/sensors/test/test.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
This PR aims to sanitize pinning and meant as an intermediate step towards https://github.com/cilium/tetragon/issues/408. It also includes some simple (first 3) patches.
One of the immediate effects of this PR is that generic tracepoints have unique map names and collisions that may  cause problems are avoided.
See patches for more information.
> sensor pinning fixes (and misc updates)

- pkg/sensors/program/loader.go
This can be used to load tail call programs.
> Add a function to load (but not attach) an eBPF program

- .github/dependabot.yml
We want our releases to include important security updates for dependencies, so make these
PRs release-blockers.
> ci/dependabot: add release blocker label on dependabot PRs

- .gitignore
- Makefile
- cmd/tetragon-bench/bench.go
- go.mod
- pkg/bench/bench.go
- pkg/bench/bpfstats.go
- pkg/bench/cpuusage.go
- pkg/bench/summary.go
- pkg/bench/trace.go
- pkg/bench/trace_bench_custom.go
- pkg/bench/trace_bench_open.go
- pkg/bench/trace_bench_rw.go
Adding benchmark application to measure tracing workloads. 
The tetragon-bench application starts tetragon (or not for -baseline option)
for given CRD file and runs workload.
At the end it displays some stats, like:
```
Benchmark summary
-----------------
Test started:      2022-09-08 15:04:28.04513503 +0200 CEST m=+0.016539427
Test ended:        2022-09-08 15:04:38.268072909 +0200 CEST m=+10.239477312
Workload start:    2022-09-08 15:04:38.268072909 +0200 CEST m=+10.239477312
Arguments:         
Total duration:    10.222937885s
Setup duration:    1.743823005s
Workload duration: 8.479094472s
Test duration:     10.222937885s
Export duration:   0s
Export stats:      bytes=0, writes=0
FGS cpu usage:     system=15.170223s, user=17.522276s, rss=230504, ctxsw=1231909
Ring buffer: …
```
> tetragon: Add bench application

- .github/ISSUE_TEMPLATE/release_template.md
The commands in the issue template for the new releases were incorrectly formatted and we were missing a test.sh step for the helm chart. Fix both of these problems.
> release-template: fix command formatting + add test.sh

- README.md
- docs/contributing/development/README.md
PR adds a hint regarding vagrant/virtualbox fix - from https://stackoverflow.com/questions/18149546/macos-vagrant-up-failed-dev-vboxnetctl-no-such-file-or-directory.
See also
https://cilium.slack.com/archives/C03EV7KJPJ9/p1660806156966189?thread_ts=1660693909.096529&cid=C03EV7KJPJ9
PR is currently cumulative with (the tiny) #33, can rebase if/when #33 is merged.
/cc @kkourt
> Vagrant on MacOS fix information

- pkg/sensors/load.go
- pkg/sensors/program/cgroup/cgroup.go
- pkg/sensors/program/loader.go
Most program types have a verbose flag passed to the loader to indicate the level of output to provide for debugging purposes.
The loader used for CGroup programs passed a literal 0 instead of a configurable argument.
This commit adds the verbose int so that the CGroup program loader can provide verbose output.
> Add Verbose Value To Cgroup Program Loader

- cmd/tetragon-vmtests-run/image.go
A new rootfs image cauesd a couple of issues that prohibit the vmtests runner to build the test images. Fix them.
> tetragon-tester: fix issues caused by image update

- pkg/observer/observer.go
Flooding the logs with Warnings when a sensors have an error can be rather noisy. Instead these should be behind metrics that we can collected. Anyways lets make it Debug fow now and prode sensor owners to add proper error metrics for each type.
Signed-off-by: John Fastabend <john.fastabend@gmail.com
> tetragon: Warn on sensor bug can flood the logs make it debug

- bpf/process/bpf_generic_retkprobe.c
- bpf/process/generic_calls.h
- bpf/process/retprobe_map.h
- bpf/process/types/basic.h
- cmd/tetragon-bench/bench.go
- pkg/bench/bench.go
- pkg/bench/summary.go
- pkg/bench/trace_bench_rw.go
- pkg/metrics/kprobemetrics/kprobemetrics.go
- pkg/sensors/tracing/generickprobe.go
Fixing merging of kprobe events (returnCopy case) by adding 'ktime' to the merged key.
At the moment we merge kprobe events by matching the 'thread_id',
which can lead to wrong events in case we have LOST events like in
following sequence of received events:
```
-  read/kprobe
-  read/kreptprobe (LOST)
-  read/kprobe (LOST)
-  read/kretprobe
```
having 'ktime' part of the key eliminates such cases
This patchset:
- adds metrics for merged events
- adds support to 'rw' benchmark to generate case above
-  store events in tetragon-bench for post processing
- adds ktime to the key in kprobe merge map
With the fix and some post processing of the benchmark output data,
we can see more better numbers for correctly merged events:
We generated 'random sys_read' events and verified in the generated …
> tetragon: Fix merged kprobe events

- bpf/process/argfilter_maps.h
- bpf/process/types/basic.h
- bpf/process/types/operations.h
- pkg/idtable/idtable.go
- pkg/selectors/kernel.go
- pkg/selectors/selectors.go
- pkg/sensors/program/loader.go
- pkg/sensors/program/program.go
- pkg/sensors/sync.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/selectors.go
- pkg/sensors/tracing/selectors_test.go
- pkg/syscallinfo/syscallinfo.go
- pkg/testutils/sensors/testrun.go
Mainly, this PR adds an InMap (and NotInMap) argument operator for generic tracepoints and kprobes. InMap acts as a filter based on whether the value of an argument exists on a map or not. It works similar to the Equal operator, but it does not have the constrains on the number of values of the latter.
Secondly, this PR improves upon #415, by adding support for testing different selectors without reloading (and re-verifying) the program to generic kprobes.
Thirdly, it improves the implementation for both generic kprobes and tracepoints. Please review commit-by-commit.
> add InMap operator for filtering arguments, and improve eBPF unit testing for kprobes

- pkg/observer/observer.go
There is a mismatch between event numbers in userspace and their opcode numbers from the BPF side, so we can't log opcode names like we've been doing. In any case, the number would be more informative here so let's just do that everywhere.
> observer: log opcode number instead of name

- .gitignore
- Makefile
Adds a workflow for setting a compile-commands.json for the project to make it work better with the ccls language server. See commit messages.
> chore: support ccls language server with compile_commands.json

- api/v1/tetragon/types.pb.go
- cmd/protoc-gen-go-tetragon/types/types.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/types.pb.go
This commit adds a code generated UnwrapGetEventsResponse helper that returns the inner event type from a GetEventsResponse. This enables us to do type matching directly on the inner event, for example to see whether it implements a particular interface, thus avoiding the need for long and complex switch statements when we only care about one or two possible event types.
In subsequent patches, I will start to refactor existing parts of our codebase to use this new helper. But for now let's get this in as it should be useful in the future as well.
> codegen: implement UnwrapGetEventsResponse helper

- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/pfilter.h
- bpf/process/types/basic.h
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/sensors/tracing/selectors_test.go
While the kprobe and tracepoint tracing policies support multiple selectors, they do not work in practice. This PR adds a number of fixes and tests so that multiple selector policies will now work.
Fixes: https://github.com/cilium/tetragon/issues/423
> tracing: fix multiple selectors support

- docs/security-observability-with-ebpf/README.md
There are a separate set of example TracingPolicies in this directory associated with Natalia & Jed’s book. This README explains why they are separate from the other examples in the repo. 
Signed-off-by: Liz Rice <liz@lizrice.com>
> Add README explaining source of these examples

- bpf/lib/process.h
- bpf/process/bpf_execve_event.c
- pkg/sensors/base/base.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/program/loader.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/testutils/sensors/load.go
The execve is getting more complex and on 4.19 it's reaching
the maximum program size.
Splitting execve sensor into 2 (so far) tail called programs and
adjusting TestLoad* tests.
> tetragon: Separate execve sensor into taill called programs

- go.mod
- pkg/metrics/errormetrics/errormetrics.go
- pkg/metrics/opcodemetrics/opcodemetrics.go
- pkg/observer/observer.go
- pkg/testutils/perfring/perfring.go
This commit adds error metrics for event handler errors so we can tell when specific handlers are failing without flooding the logs with useless log messages. When more info is needed, debug logging can be enabled.
> metrics: add handler error metrics

- Makefile.cli
- cmd/tetra/common/client.go
- cmd/tetra/full_commands.go
- cmd/tetra/main.go
- cmd/tetra/standalone_commands.go
- pkg/syscallinfo/syscallnames_windows.go
- Add "standalone" build tag for only exposing version and getevents
subcommands in the standalone tetra CLI.
- Update make cli-local-release target to build linux arm64 and windows
amd64/arm64 binaries.
- Use syscall instead of unix for SIGINT and SIGTERM for windows build.
- Define an empty syscallNames for windows.
Ref: #438
> Build tetra CLI for linux arm64 and windows amd64/arm64

- .github/ISSUE_TEMPLATE/release_template.md
- .github/workflows/build-images-releases.yml
- Create a GitHub release draft as a part of the Image CI Releases workflow.
- Trigger the workflow when a tag with "test" prefix is pushed. It runs the Image CI Releases workflow for testing without actually pushing release images for testing.
> release: Add a job to create a release draft

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/observer/observer.go
- pkg/option/config.go
Adding new options to configure the size of perf ring buffer, which is used to get events from ebpf programs to user space.
Adding two new options:
`  --rb-size <BYTES>` specifies number of bytes to allocate for perf ring buffer for each cpu
`  --rb-size-total <BYTES>` specifies number of bytes to allocate for perf ring buffer in summary for all cpus
Adding new log message that displays how much memory is actually allocated for ring buffer:
for default case:
`  time="2022-10-17T15:53:04+02:00" level=info msg="Perf ring buffer size (bytes)" percpu=69632 total=278528`
for '--rb-size 128000' (on 4 cpu server):
`  time="2022-10-17T15:53:39+02:00" level=info msg="Perf ring buffer size (bytes)" percpu=135168 total=540672`
for  '--rb-size-total 128000' (on 4 cpus server):
` …
> tetragon: Add --rb-size/--rb-size-total options to setup perf ring buffer size

- docs/contributing/development/README.md
PR documents the `LOCAL_CLANG` make option in the developer documentation which currently is only in the `kind`-related part of the file. 
Signed-off-by: Dmitry Savintsev <dsavints@gmail.com>
> mention LOCAL_CLANG in contributor's dev docs

- pkg/grpc/exec/exec.go
There is a case where we have an OOO exec event and this will also try to add again a new entry in the eventcache that will cause a deadlock.
This commit fixes that by creating a goroutine for that case.
> Fix a deadlock in eventcache

- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/server/server.go
There was report about a deadlock when executing `tetra getevents` (issue #492 ).
After investigation, the issue seems to be that the notifier channel is full and the consumer is stuck trying to send a gRPC response. Since listeners use libraries for handling events that i) may block and ii) we do not control, the best option seems to be to drop events whenever the listener buffer is full. This is what this patch does. It also adds a metric to count these drops.
More details: looking at the stack trace, One goroutine seems to be stuck in Notify():
```
func (l *getEventsListener) Notify(res *tetragon.GetEventsResponse) {
l.events <- res
}
```
The events are consumed by function GetEventsWG which seems to be stuck in grpc land.
```
goroutine 82988 [select, 47 minutes]: …
```
> server: drop events if listener channel is full

- pkg/metrics/errormetrics/errormetrics.go
- pkg/process/cache.go
- pkg/process/cache_test.go
- pkg/process/process.go
pidMap holds mappings from PID to the most recent exec ID for the PID. This is used to find the parent of exec events that come after another exec event (i.e. not a clone). This can be racy as events can come OOO to the user space.
This information is also available in the execve_map inside the kernel where all events happen in-order.
https://github.com/cilium/tetragon/commit/45745a0a93c65811495f82deb9314a1c849e1403 introduced a new field in msg_execve_event (cleanup_key) that keeps the parent of the execve event. In that case this was needed for cleanup.
We can use the same information for the parent and remove entirely the pidMap. If there is a case where we cannot find the entry in the execve_map, we use as a parent the view of Linux (i.e. the process that clones the current process …
> Remove pidMap

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
- README.md
Implement container image signing using cosign in build images workflows. Leveraging image signing gives users confidence that the container images they got from the container registry were the trusted code that the maintainer built and published. This is part of efforts to improve the security posture of the Cilium family’s open source projects.
Signed-off-by: Sandipan Panda <samparksandipan@gmail.com>
> build: sign Tetragon container images

- crds/examples/fd_memfd_kill.yaml
Hi! I would like to validate about how detect memfd_call and use the file descriptor to execute.
More notes about the output of this policy and the image test, [here](https://hackmd.io/@krol/HJ3UiFSmi)
> chore: sample memfd_create rule

- cmd/tetragon/main.go
- pkg/observer/observer.go
Right now tetragon always exit with 1, let's fix this and improve graceful shutdown, so service monitors and container managers... won't treat Tetragon as it failed.
Some start up logic was re-ordered to improve how we cleanup things.
Also this change will make tetragonExecute() return up to callers, and allow Tetragon main to exit with 0.
> tetragon: fix graceful shutdown and exit code

- .github/workflows/run-e2e-tests.yaml
This commit fixes file exports on e2e test failure so that we actually upload the necessary artifacts.
> ci/e2e: fix test failure file exports

- bpf/include/api.h
- bpf/lib/common.h
- bpf/libbpf/bpf_tracing.h
Adding bpf_printk helper from bpf selftests that allows to use bpf_trace_vprintk helper and display more than 3 format arguments. This helper did not make it to 5.15 so it's available later on.
Up to 5.15 we can use bpf_printk with 3 format arguments, later versions can use up to 12 format arguments.
We need to use global data variable for format string for kernel versions < 5.2 (needs to be on stack), so I'm using __LARGE_BPF_PROG for that.
> tetragon: Add bpf_printk helper from libbpf

- pkg/process/process.go
https://github.com/cilium/tetragon/commit/ef0a4260f4be702ca31d5e1525e20c841647d6eb changes the behaviour of exec events that come after a clone event.
Before that commit we used to have:
```
process_clone with process pid 10 parent pid 9 // we cannot see that event as process_clone are not exported 
process_exec with process pid 10 parent pid 9  // will have as parent pid the clone's event parent pid 
process_exec with process pid 10 parent pid 10 // will have as parent the previous exec's pid
```
Now we have:
```
process_clone with process pid 10 parent pid 9 // we cannot see that event as process_clone are not exported 
process_exec with process pid 10 parent pid 10 // will have as parent pid the one from the clone event 
process_exec with process pid 10 parent pid 10 // will have as …
```
> Fix for execve events that come after clone

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/option/config.go
- pkg/server/server.go
The internal event queue had a fixed size of 100 events. If the event queue became full, additional events would be dropped. This commit raises the default size to 10000 events and makes the size configurable through a --event-queue-size command line flag.
> Make size of event queue configurable

- bpf/Makefile
- bpf/alignchecker/bpf_alignchecker.c
- bpf/cgroup/bpf_cgroup_events.h
- bpf/cgroup/bpf_cgroup_mkdir.c
- bpf/cgroup/bpf_cgroup_release.c
- bpf/cgroup/bpf_cgroup_rmdir.c
- bpf/lib/bpf_cgroup.h
- bpf/lib/environ_conf.h
- bpf/lib/msg_types.h
- pkg/alignchecker/alignchecker.go
- pkg/api/confapi/confapi.go
- pkg/api/ops/ops.go
- pkg/api/ops/ops_test.go
- pkg/api/processapi/processapi.go
- pkg/cgroups/cgroups.go
- pkg/cgroups/cgroups_test.go
- pkg/grpc/exec/exec.go
- pkg/logger/log.go
- pkg/observer/observer.go
- pkg/sensors/cgroup/cgrouptrackmap/cgrouptrackmap.go
- pkg/sensors/cgroup/cgrouptrackmap/cgrouptrackmap_test.go
- pkg/sensors/config/confmap/confmap.go
- pkg/sensors/exec/cgroups_test.go
- pkg/sensors/exec/exec.go
- pkg/sensors/test/cgroups.go
- pkg/testutils/confmap.go
- pkg/testutils/sensors/sensors.go
This PR introduce basic Cgroups tracking. It handles first task of issue: https://github.com/cilium/tetragon/issues/477
The main functionality is `cgroup_mkdir` and `cgroup_rmdir` where we register our bpf programs and expect events to be sent to user space. Note that these programs are not loaded into main Tetragon, we are babysitting them with tests for now, so no new functionality is introduced.
- The patches prefixed with bpf are bpf related parts.
- The following patches are user space handlers for the cgroup events.
- Then we have helpers to make tests easy, followed with tests including bpf unit tests.
> cgroups: add basic cgroups tracking and make it part of the testing framework

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/option/config.go
This adds a ReleasePinnedBPF option that will remove any and all pinned programs and maps in the tetragon directory. In normal use cases we should not require this Tetragon should clean up and reinit its state correctly.
However, some cases we hit recently require a bigger hammer. Specifically, when upgrading between versions and maps or programs are no longer in the new version. We would have to keep code to tear them down on the upgrade. We do this in some cases where we expect users will commonly upgrade through these paths. But, then there are always questions, such as how many versions do we need to maintain this code? For ever? What about downgrades with new maps that no longer exist? And so on.
To handle these cases the ReleasePinnedBPF option gives users that have no need to keep …
> tetragon: Add ReleasedPinnedBPF option to remove any old progs/maps

- bpf/Makefile
- bpf/include/api.h
- bpf/process/bpf_process_event.h
- contrib/verify/verify.sh
- pkg/kernels/kernels.go
- pkg/sensors/base/base.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
With clang 14 the prepend_path loop code does not pass verifier
on v6.x kernels, which can be fixed by using bpf_loop helper.
In order to use bpf_loop helper easily, I'm adding v6.0 version of
bpf objects, so we don't need to detect features and have specific
binary for each.
The v6.0 seems to be the latest stable, I'm not sure it will be longterm,
but with 5.19 EOL the other possibility is 5.15 which does not have
bpf_loop helper.. but I'm open to suggestions in here ;-)
Note I plan to move kprobe_multi objects into v60 in following changes.
> tetragon: Add v6.0 bpf objects and related fixes

- Makefile.cli
CLI builds have been failing with:
> addgroup: gid '123' in use
Fix this by redoing the addgroup, adduser command without a specific gid/uid.
> Makefile.cli: deal with {g,u}id collision

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
This PR adds support for pprof http endpoints.
Fixes: https://github.com/cilium/tetragon/issues/550
Signed-off-by: Andzej Maciusovic [andzej.maciusovic@gmail.com](mailto:andzej.maciusovic@gmail.com)
> tetragon: Add pprof http support

- cmd/tetragon/addr.go
- cmd/tetragon/addr_test.go
- cmd/tetragon/main.go
- install/kubernetes/README.md
- install/kubernetes/templates/_container_tetragon.tpl
- install/kubernetes/templates/tetragon_configmap.yaml
- install/kubernetes/values.yaml
- pkg/unixlisten/unixlisten.go
This PR adds support for using a unix socket for the gRPC agent interface.
> support for using unix socket for gRPC

- pkg/sensors/tracing/generictracepoint.go
tracepoint sensor creation not as expected.
[source code](https://github.com/cilium/tetragon/blob/3a3f8990503153b2ea63e15b3a62cbed6f8d1949/pkg/sensors/tracing/generictracepoint.go#L322)
use ```&conf``` cause all ```genericTracepoint.Spec``` as same as the last element in ```genericTracepointTable```, should use ```&confs[i]``` instead.
fix #569 
Signed-off-by: dechengyuan <dechengyuan@tencent.com>
> tetragon: fixup generic tracepoint sensor create

- cmd/tetragon/main.go
- pkg/server/server.go
There is a potential for a deadlock in the initialization case. This might happen if, for example, we pass a wrong filename for the config file.
We fix this by generating a new context which we can cancel without causing deadlocks.
The patch also adds comments to explain why this is needed so more details can be found there.
Reported-by:  Zhiyu Wang <zhiyuwang.newbis@gmail.com>
> tetragon: fix initialization deadlock

- pkg/sensors/load.go
- pkg/sensors/program/map.go
Following cilium/ebpf interface creates map from pin path
and checks if the pin is compatible with the map spec:
ebpf.NewMapWithOptions(spec, ebpf.MapOptions{PinPath: path, FullPath: true})
use that in the sensors map loading code
TODO split the cilium/ebpf change and push it separately 
> tetragon: Check and remove not compatible map pin paths on loading

- Makefile.cli
Initial fix for for this issue had the issue that the uid/gid of the generated artefact would not match the uid/gid of the `make` caller. Fix this using setpriv.
This approach was taken from 69822cd7789f368f280870429ba833005671316e in cilum/hubble, so copying the excellent message of above commit from Sebastian:
"""
The release build should run with the same numeric user and group id as the caller of the Makefile. This solves two problems:
1. The generated artefacts should be owned by the user who invoked the Makefile
2. `go build -buildvcs=true` (the default since Go 1.18) invokes git, and git requires that the .git folder is owned by the user invoking it.
Previously, we achieved this by creating a new user and group inside the container with the wanted uid/gid. The problem with that …
> Makefile: Fix potential uid/gid collision by using setpriv

- pkg/jsonchecker/jsonchecker.go
I ran into a corner case in CI a few times where it seems that the exporter is in the middle of writing an event when the jsonchecker decides to open the file and check it. In this case, the unmarshaller will bubble up either an EOF or UnexpectedEOF error which will fail the test. To handle this, let's just treat these errors the same way we treat regular JSON EOF: by retrying after a few seconds.
> jsonchecker: retry on EOF/UnexpectedEOF in unmarshaller

- tests/e2e/flags/flags.go
- tests/e2e/install/cilium/cilium.go
- tests/e2e/runners/runners.go
Make the installed version of Cilium configurable with a new command line flag: `-tetragon.cilium-version`.
> tests/e2e: make cilium version configurable

- .github/workflows/static-checks.yaml
- .golangci.yml
- Dockerfile.golangci-lint
- Makefile
- api/Makefile
- cmd/tetragon/addr.go
- pkg/k8s/Makefile
- pkg/unixlisten/unixlisten.go
Also bump the golangci-lint action to v3.3.1. Use the new `skip-cache` directive to disable caching instead of the more specific options. Remove `only-new-issues: false` given that `false` is the default value. Finally, remove `skip-go-installation` as this is an unknown config option to the linter which gives a warning.
> ci: bump golangci-lint to v1.50.1

- bpf/process/types/basic.h
The ```char_buf``` args obtained from ```kprobes``` or ```tracepoints``` events is sometimes not a useful value that can be used for analysis.
the ```size``` of ```bpf_probe_read(void *dst, u32 size, const void *unsafe_ptr)``` in ```__copy_char_buf``` used ```rd_bytes &= 0xfff```. when ```bytes``` , the meta size of char_buf args  is 4096, ```rd_bytes``` will be 0, then nothing can be read from arg.
[source code](https://github.com/cilium/tetragon/blob/c338a633b4818dba9ba327188531da4a1f76c9f7/bpf/process/types/basic.h#L524)
In this pr, when ```rd_bytes > 0xfff```, the right-shift operation is performed to reduce ```rd_bytes``` until it becomes a value in the range of 4096, so that a part of the data at the beginning of char_buf can always be read by ```bpf_probe_read```.
**Example**
if …
> tetragon: Make sure to read meaningful size data from char_buf args

- Makefile.cli
- cmd/tetragon/addr.go
- cmd/tetragon/addr_test.go
- cmd/tetragon/main.go
- install/kubernetes/README.md
- install/kubernetes/templates/_container_tetragon.tpl
- install/kubernetes/templates/tetragon_configmap.yaml
- install/kubernetes/values.yaml
- pkg/unixlisten/unixlisten.go
Backports:
* https://github.com/cilium/tetragon/pull/552
* https://github.com/cilium/tetragon/pull/557
* https://github.com/cilium/tetragon/pull/586
> [backport] unix socket for gRPC

- CODEOWNERS
- cmd/tetragon/main.go
- pkg/config/yaml.go
- pkg/exporter/exporter_test.go
- pkg/grpc/exec/exec_test_helper.go
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/sensors/collection.go
- pkg/sensors/exec/cgroups_test.go
- pkg/sensors/exec/exec.go
- pkg/sensors/load.go
- pkg/sensors/manager.go
- pkg/sensors/manager_test.go
- pkg/sensors/sensors.go
- pkg/sensors/sync.go
- pkg/sensors/test/lseek_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/server/fake_observer.go
- pkg/server/server.go
- pkg/testutils/sensors/sensors.go
- pkg/watcher/crd/watcher.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
This PR cleanups the sensor code as a preparation for subsequent patches.
It is split in small patches to ease reviewing.
The only user-visible change is that when a sensor in a tracing policy fails to load, we will unload all the sensors of said tracing policy.
Please review commit by commit.
> sensor cleanups

- tests/e2e/flags/flags.go
- tests/e2e/install/cilium/cilium.go
- tests/e2e/runners/runners.go
Backport of #591 
Make the installed version of Cilium configurable with a new command line flag: `-tetragon.cilium-version`.
> backports/v0.8: tests/e2e: make cilium version configurable

- pkg/eventcache/eventcache.go
There seems to be a typo where we update the ProcessInfoError metric even when the error ErrFailedToGetPodInfo.
> eventcache: update PodInfoError on pod error

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
- README.md
Add a Software Bill of Materials (SBOM) generated from source code and the image using the Kubernetes bom tool to the Tetragon image during image build.
Signed-off-by: Sandipan Panda <samparksandipan@gmail.com>
> build: Generate SBOM during image release

- install/kubernetes/templates/_container_tetragon.tpl
Use a specific directory for tetragon configmap.
Right now we are using /etc/tetragon/ as the base for configmap, however in future we want to put CRD rules under that same path /etc/tetragon/tetragon.rules.d/ .
So change the mountPath where tetragon-config points from:
/etc/tetragon/ => /etc/tetragon/tetragon.conf.d/
> helm: use a specific conf.d directory for --config-dir

- .github/workflows/vmtests.yml
Move away from the regular GitHub runner to a large one, which supports KVM acceleration.
This should significantly speed up test performance, so let's drop down to one group per
test and add a 5.15 test while we're at it.
> ci: use large github runner

- api/v1/README.md
- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- api/v1/tetragon/tetragon.pb.go
- api/v1/tetragon/tetragon.proto
- bpf/process/bpf_exit.c
- bpf/process/bpf_exit.h
- contrib/tester-progs/.gitignore
- contrib/tester-progs/Makefile
- contrib/tester-progs/exit-leader.c
- contrib/tester-progs/exit-tester.c
- pkg/grpc/exec/exec.go
- pkg/sensors/base/base.go
- pkg/sensors/exec/exit_test.go
- pkg/testutils/sensors/load.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Switching exit tracepoint to __put_task_struct kprobe, so we are sure not other thread is running.
The reason for this is that you can have application that spwns a thread which continues
running while the group leader thread exits. Tetragon sends EXIT event for the leader
but the process continues.
I initially checked the task->thread_group list, but I couldn't figure out way how to solve
the race between 2 finishing processes. There are no spin lock support for tracing programs yet.
You can check that change with trivial check in here:
https://github.com/olsajiri/tetragon/tree/exit_racy
I think it'd work most of the time, because hitting that race seems hard,
but in any case having the kprobe on __put_task_struct seems to serve
just as good without any race (that I know of ;-) ). …
> tetragon: Switch exit tracepoint to __put_task_struct kprobe

- bpf/Makefile
- bpf/alignchecker/bpf_alignchecker.c
- bpf/cgroup/bpf_cgroup_events.h
- bpf/cgroup/bpf_cgroup_mkdir.c
- bpf/cgroup/bpf_cgroup_release.c
- bpf/cgroup/bpf_cgroup_rmdir.c
- bpf/lib/bpf_cgroup.h
- bpf/lib/environ_conf.h
- bpf/lib/msg_types.h
- pkg/alignchecker/alignchecker.go
- pkg/api/confapi/confapi.go
- pkg/api/ops/ops.go
- pkg/api/ops/ops_test.go
- pkg/api/processapi/processapi.go
- pkg/cgroups/cgroups.go
- pkg/cgroups/cgroups_test.go
- pkg/grpc/exec/exec.go
- pkg/logger/log.go
- pkg/observer/observer.go
- pkg/sensors/cgroup/cgrouptrackmap/cgrouptrackmap.go
- pkg/sensors/cgroup/cgrouptrackmap/cgrouptrackmap_test.go
- pkg/sensors/config/confmap/confmap.go
- pkg/sensors/exec/cgroups_test.go
- pkg/sensors/exec/exec.go
- pkg/sensors/test/cgroups.go
- pkg/testutils/confmap.go
- pkg/testutils/sensors/sensors.go
This backports https://github.com/cilium/tetragon/pull/471 (all cherry picked)
https://github.com/cilium/tetragon/pull/471 includes some cgroup patches that enforce the notion of being compatible with both cgroupv1 and cgroupv2, and transparently detecting that. Beside that more fixes will come on top from upstream: https://github.com/cilium/tetragon/pull/541 and https://github.com/cilium/tetragon/pull/594
By merging this it will allow to nearly align this branch with current upstream in regards to cgroups, and make it easy to incorporate further fixes! the bpf cgroups programs still sit in testing. We can try to split this up, and just get the proper fixes, but it is a pain as original PR was explicitly split for such reasons bisecting... during review it was requested to pack it …
> Backports/v0.8: cgroups: add basic cgroups tracking and make it part of the testing framework

- bpf/process/bpf_exit.c
- bpf/process/bpf_exit.h
We can't use get_current_task in __put_task_struct, we need to use 
__put_task_struct task argument instead, otherwise we read wrong
task's exit_code.
Fixes: 1a37adf4bd40 ("tetragon: Switch exit tracepoint to __put_task_struct kprobe")
> tetragon: Use probe task instead of current in event_exit_send

- .github/workflows/build-images-ci.yml
- README.md
Fix CI build PR updates image digest output which was causing the `Sign SBOM Image` step introduced in 343e9f94c6eca025307cc5219638102c57c184c2 to fail.
Update cosign verify command flags used to verify cosign claims
and signing certificates on the Tetragon images
> Fix SBOM image signing and update image siganture verification docs

- cmd/tetragon/main.go
If empty do not start gops server.
In helm chart we explicitly pass the gops config since https://github.com/cilium/tetragon/pull/371
> tetragon: disable gops server by default

- Dockerfile
- cmd/tetragon/main.go
- go.mod
- go.sum
- pkg/observer/observer.go
- pkg/server/server.go
- vendor/github.com/cilium/lumberjack/v2/lumberjack.go
- vendor/modules.txt
This backport contains:
- https://github.com/cilium/tetragon/pull/565
- https://github.com/cilium/tetragon/pull/574
- https://github.com/cilium/tetragon/pull/582
- https://github.com/cilium/tetragon/pull/588
- https://github.com/cilium/tetragon/pull/590
Goes on top of https://github.com/cilium/tetragon/pull/629
> Backports/v0.8: tetragon: main agent and logging fixes

- bpf/alignchecker/bpf_alignchecker.c
Currently when compiling on Fedora37 with clang 15.0.4, the build fails because of the unused variable `iter` in bpf/alignchecker/bpf_alignchecker.c https://github.com/cilium/tetragon/blob/main/bpf/alignchecker/bpf_alignchecker.c#L30 (error below).  PR suggest to change the return statement of the (unused) main function to `return iter * 0` to avoid that error.  If there are better ways to make code compile on Fedora, please let me know! 
```
$ CONTAINER_ENGINE='sudo podman' LOCAL_CLANG=1 LOCAL_CLANG_FORMAT=1 make
/bin/sh: line 1: docker: command not found
make -C ./bpf
make[1]: Entering directory '/gh/cilium/tetragon/bpf'
clang -I. -Wall -Werror -Wno-address-of-packed-member -Wno-compare-distinct-pointer-types -Wno-unknown-warning-option -O2 -I ./libbpf/ -I ./include/ -I ./lib -target …
```
> bpf_alignchecker.c: avoid unused var error

- bpf/lib/generic.h
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/generic_calls.h
- bpf/process/types/basic.h
- pkg/sensors/tracing/kprobe_test.go
Currently we have 'id' and 'func_id' in struct msg_generic_kprobe keeping the same value. There's no need, we can use just the 'id' value for everything.
Also use __u32 as config_map key type.
> tetragon: Cleanup func_id/id mess in struct msg_generic_kprobe

- bpf/include/api.h
skb_adjust_room() allows skbs to be modified to different sizes.
> Add skb_adjust_room helper

- contrib/tester-progs/exit-tester.c
when trying to build on RHEL8 (with `CONTAINER_ENGINE='sudo podman' LOCAL_CLANG=1 LOCAL_CLANG_FORMAT=1 make`), I'm getting a build failure due to missing `gettid` function.  This seems to be a problem with glibc...  The suggested workaround gets the codebase to compile - would like you r(and CI builds' 😄 ) opinion whether this would generally work and be the right way to fix this.  NB: this is cumulative with #637, I'll rebase once that one is merged.
```
make -C "contrib/tester-progs"
make[1]: Entering directory '/home/dmitris/gh/cilium/tetragon/contrib/tester-progs'
gcc -Wall exit-tester.c -o exit-tester -lpthread
exit-tester.c: In function ‘thread’:
exit-tester.c:34:41: warning: implicit declaration of function ‘gettid’; did you mean ‘getgid’? [-Wimplicit-function-declaration] …
```
> gettid wrapper

- .github/workflows/gotests.yml
- Makefile
- Make explicit the implicit dependencies there were between `tetragon-bpf` and `tester-progs` for the target `test`. Also, run the tests as root with sudo using the `SUDO` variable.
- Simplify the associated GitHub action
> Update Makefile test target dependencies and run test as root

- tests/e2e/install/tetragon/tetragon.go
In some versions of helm, it complains when we try to add a repo that already exists. To prevent this, pass the `--force-update` flag.
> e2e-framework: force update when adding helm repo

- crds/examples/fd_install_cap_changes.yaml
- crds/examples/fd_install_caps.yaml
- crds/examples/fd_install_ns.yaml
- crds/examples/fd_install_ns_host.yaml
- crds/examples/hardlink-observe.yaml
- crds/examples/hardlink-override.yaml
- crds/examples/match_capability_changes.yaml
- crds/examples/match_namespace_changes.yaml
- crds/examples/symlink-observe.yaml
- crds/examples/symlink-override.yaml
- crds/sandbox/linux-namespaces/kill_unprivileged_user_namespace.yaml
- crds/sandbox/linux-namespaces/kill_unprivileged_user_namespace_in_pid_namespace.yaml
Many `metadata.name` of the `TracingPolicy` examples contained underscores in their name, and unfortunately, that makes it impossible to deploy them on Kubernetes. I assumed they were passed to Tetragon via flags using `--config-file` or similar. 
Maybe it would be interesting to implement the regex check in Tetragon to avoid this pitfall? 
Kubernetes objects names comply with lowercase RFC 1123 subdomain convention: they must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is `[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`)
> CRD examples: Replace invalid TracingPolicy names

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
Our image builder jobs were breaking due to incompaitibilies with a newer docker buildx version. Pin the version now to avoid breakages.
Original commit message from cilium/cilium:
GitHub recently rolled out Docker buildx version v0.10.0 on their
builders, which transparently changed the MediaType of docker images to
OCI v1 and added provenance attestations.
Unfortunately, various tools we use in CI like SBOM tooling and docker
manifest inspect do not properly support some aspect of the new image
formats. This resulted in breaking CI, with some messages like this:
level=fatal msg="generating doc: creating SPDX document: generating
SPDX package from image ref quay.io/cilium/docker-plugin-ci:XXX:
generating image package"
This could also lead CI to fail while waiting for image builds to …
> ci: pin docker buildx version to v0.9.1

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
[upstream commit: 7f9ac8a28f2f625184206b59f2cc85b7231f31f6]
Our image builder jobs were breaking due to incompaitibilies with a newer docker buildx version. Pin the version now to avoid breakages.
Original commit message from cilium/cilium:
GitHub recently rolled out Docker buildx version v0.10.0 on their
builders, which transparently changed the MediaType of docker images to
OCI v1 and added provenance attestations.
Unfortunately, various tools we use in CI like SBOM tooling and docker
manifest inspect do not properly support some aspect of the new image
formats. This resulted in breaking CI, with some messages like this:
level=fatal msg="generating doc: creating SPDX document: generating
SPDX package from image ref quay.io/cilium/docker-plugin-ci:XXX:
generating image package"
This …
> backports/v0.8: ci: pin docker buildx version to v0.9.1

- cmd/tetra/getevents/getevents.go
- cmd/tetra/getevents/getevents_test.go
- cmd/tetra/getevents/io_reader_client.go
Previously the field filters were used only in the server-side code:
https://github.com/cilium/tetragon/blob/cd96d7ca3d7556f0d44da7da0ab4cdf943d29957/pkg/server/server.go#L145-L149
> tetra: use field filters when reading via `io_reader_client`

- pkg/bench/trace_bench_open.go
- pkg/bench/trace_bench_rw.go
- pkg/config/yaml.go
- pkg/config/yaml_test.go
- pkg/sensors/tracing/kprobe_test.go
- testdata/specs/capchanges.yaml.tmpl
- testdata/specs/nschanges.yaml.tmpl
- testdata/specs/sigkill_unprivileged_user_namespace.yaml.tmpl
- testdata/specs/sigkill_unprivileged_user_namespace_in_pid_namespace.yaml.tmpl
This forces TracingPolicy to follow the same constraint on the metadata.name value when it is loaded directly as when it is added as a Kubernetes object.
I used the k8s package `validation` since it was already a dependency!
This is related to https://github.com/cilium/tetragon/pull/652.
> pkg/config: add k8s validation on `metadata.name`

- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- cmd/protoc-gen-go-tetragon/common/common.go
- cmd/protoc-gen-go-tetragon/eventchecker/eventchecker.go
- cmd/protoc-gen-go-tetragon/eventchecker/field.go
- cmd/protoc-gen-go-tetragon/eventchecker/message.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/exec/exit_test.go
- pkg/sensors/exec/fork_test.go
- pkg/sensors/test/lseek_test.go
- pkg/sensors/tracing/kprobe_amd64_test.go
- pkg/sensors/tracing/kprobe_copyfd_test.go
- pkg/sensors/tracing/kprobe_filterchange_test.go
- pkg/sensors/tracing/kprobe_sigkill_test.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/loader_test.go
- pkg/sensors/tracing/tracepoint_test.go
- tests/e2e/tests/labels/labels_test.go
- tests/e2e/tests/skeleton/skeleton_test.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
This commit implments eventchecker names for top-level checkers (i.e. checkers that check a process event). These names will show up in the error logs when a check fails. That should hopefully improve the readability of test logs (especially e2e tests) and help us diagnose why tests are failing.
Note that for most of the tests that have only one checker, I have opted to give them an empty name. This is because these are cases where disambiguation is (obviously) unhelpful. For some practical examples of why this construct is actually useful, please refer to the end-to-end tests.
> eventchecker: implement checker names

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/bench/bench.go
- pkg/observer/data.go
- pkg/observer/observer_test_helper.go
- pkg/sensors/exec/cgroups_test.go
- pkg/sensors/exec/exec.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/tracing/selectors_test.go
There's a chance that by losing events (in perf ring buffer)
we would never use data stored by data events. Adding the data
into lru cache so we eventually remove unused entries to make
space for new ones and don't grow endlessly.
> tetragon: Use lru.Cache for data events storage

- cmd/tetragon/main.go
- pkg/observer/observer.go
This logs the release bpf resources operation in case, and also before starting the bpf loading logic logs the current pinned ones if any.
For bpf developers some errors are easy to spot, for others let's add more logging.
Example:
time="2023-01-27T14:29:41+01:00" level=info msg="BPF: resources are empty" bpf-dir=/sys/fs/bpf/tetragon
Or:
time="2023-01-27T14:28:34+01:00" level=info msg="BPF: found active BPF resources" bpf-dir=/sys/fs/bpf/tetragon pinned-bpf="[event_execve event_exit execve_calls execve_map execve_map_stats kprobe_pid_clear names_map tcpmon_map tg_conf_map]"
> tetragon: log pinned bpf and maps status

- pkg/observer/data.go
The "Data message received" and "Data message used" log messages flood the Tetragon logs when debug logging is enabled, to the point that it obfuscates all other debug messages. Bump these messages up to the trace level so that they are less annoying.
> data: silence annoying debug log messages

- tests/e2e/install/tetragon/tetragon.go
[upstream commit: bd5c206c46a1994f1a52b0871e8e15a70178e0e0]
In some versions of helm, it complains when we try to add a repo that already exists. To prevent this, pass the `--force-update` flag.
> backports/v0.8: e2e-framework: force update when adding helm repo

- docs/contributing/development/README.md
PR fixes the URL in the "good tasks to get started" list, pointing to the list of issues with the parameters:
`is:issue is:open label:"good first issue" `
https://github.com/cilium/tetragon/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
> fix the URL for the "first good issue" list

- cmd/tetragon/main.go
When upgrading between minor versions of Tetragon, sometimes programs and maps can change enough that leaving the old ones kicking around can introduce bugs on the BPF side. We added the --release-pinned-bpf flag to help solve this issue by giving users a way to tell Tetragon that it should clear existing BPF programs and maps when it starts up.
While this flag was initially set to default false, there are currently no downsides to making it default to true since we typically clear remaining BPF programs and maps on termination anyway and any remaining ones would currently be considered bugs. Therefore, let's just set this flag to true by default and gives users the option to turn it off if they like. In the future, when Tetragon supports persisting policy between restarts, we can …
> tetragon: set default value of release-pinned-bpf to true

- pkg/encoder/encoder.go
- pkg/encoder/encoder_test.go
Signed-off-by: Natalia Reka Ivanko <natalia@isovalent.com>
> Changing bpf prog load, map create event names to be more descriptive

- .github/workflows/run-e2e-tests.yaml
- tests/e2e/flags/flags.go
- tests/e2e/helpers/cluster.go
- tests/e2e/install/tetragon/tetragon.go
Because KinD clusters run in nested containers, the Tetragon Helm Chart was not correctly mounting the host procfs into the Tetragon container. This was causing potential flakes in the end-to-end tests by making it impossible to correctly initialize data for already running processes on the host system. Since we're not interested in offering full support for KinD, let's just make the tests work by hacking them to mount the real host procfs into the Tetragon container.
To do this, we create the KinD cluster with an extra volume that mounts host procfs then link it up with Tetragon by adding an extra volume mount via the Helm chart and modifying Tetragon's startup arguments. Finally, we update the end-to-end CI job to make use of this by removing some logic to use a single shared cluster …
> tests/e2e: handle procRoot correctly in KinD clusters

- tests/e2e/checker/rpcchecker.go
- tests/e2e/tests/labels/labels_test.go
This should resolve a rare CI failure caused by the demo app failing to install correctly.
> tests/e2e: add ability to reset checker limits and retry demo app installation

- bpf/process/bpf_loader.c
Follow the standard way of including bpf/lib headers, so it won't mess the hubble sync.
> tetragon: Minor include headers changes in loader

- bpf/include/api.h
Currently we can't use bpf_printk macro with just single argument, like:
```
generic_kprobe_event(struct pt_regs *ctx)
{
+       bpf_printk("DEBUG\n");
return generic_kprobe_start_process_filter(ctx);
}
```
The reason is that for single string argument the __bpf_printk macro calls trace_printk helper without the 3rd argument, just the format string  and in this case the current __format__ attribute check will cause error:
__attribute__((__format__(__printf__, 1, 3)))
because there's no 3rd argument passed, but the format check expects it with '3' as in first-to-check index value.
Disabling the format arguments check by passing 0 instead. In this case the compiler only checks the format string for consistency.
As we use trace_printk just for debugging purpose I think it's safe to disable …
> tetragon: Fix bpf_printk for single string argument

- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/tracing/tracing.go
The event cache takes a timestamp via its Add method. This is used in two places: once in the RetryInternal method and again as the timestamp of the event. The RetryInternal method actually wants a process start time, and that is typically what functions give it. Using this as the event timestamp is therefore incorrect.
This commit adds a further parameter to the Add method and the event cache object: process start time. Functions will have to provide the event timestamp and the process start time in order to use the event cache, but this will solve the issue of the event being given the wrong timestamp.
> Add start time to event cache object

- README.md
- docs/tracingpolicy/README.md
Fixes https://github.com/cilium/tetragon/issues/179.
This PR:
- Add documentation on `TracingPolicy`
- Reorganize the main README
- Add a TOC and cleanup title ordering
- Add `tetra` homebrew installation instruction
- Add a link to last Tetragon KubeCon presentation
> Improve README and document tracing policies

- Dockerfile
- Dockerfile.codegen
- api/v1/tetragon/capabilities.pb.go
- api/v1/tetragon/events.pb.go
- api/v1/tetragon/tetragon.pb.go
- contrib/update-cilium-builder.sh
- operator.Dockerfile
- vendor/github.com/cilium/tetragon/api/v1/tetragon/capabilities.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
add a script to update cilium builder, and perform an update so that we can build with a new version of go.
> use  go 1.19.6

- bpf/lib/bpf_cgroup.h
- bpf/lib/process.h
- bpf/process/bpf_fork.c
- bpf/process/bpf_process_event.h
- pkg/sensors/exec/execvemap/execve.go
- pkg/testutils/sensors/load.go
Add cgrpid_tracker inside execve_map_value struct which will be used to track every process by its pinned Cgroup ID.
The cgrpid_tracker will be set to the cgroup ID of the tracking cgroup, could be a pod/container/systemd service, etc. Right now we set it to current cgroup ID. As we advance in next patches we will set it to the tracking cgroup ID.
Signed-off-by: Djalal Harouni <djalal@isovalent.com>
> tetragon: introduce Cgroup ID Tracker

- bpf/process/types/basic.h
- pkg/selectors/kernel.go
Kevin reported issue with longer selectors sending kprobes with
override action.
The problem is that we are masking action offset with wrong mask
bin(0xeff) == 0b111011111111, which was mangling offsets bigger
than 255, so the action code worked on top of wrong data.
Selector total length is 0x1000, so next longest mask to use here
is 0x7ff.
Note we should test longer selectors and make sure verifier is
happy with them.
Reported-by: Kevin Sheldrake <kevin.sheldrake@isovalent.com>
Fixes: https://github.com/cilium/tetragon/issues/462
> tetragon: Fix action offset masking

- bpf/process/types/basic.h
Now we ignore empty file argument only in the case of postfix operator.
This patch ignores empty file arguments also in equal and prefix operators.
> matchArgs: do not match on empty file

- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/tracing/tracing.go
The event cache takes a timestamp via its Add method. This is used in two places: once in the RetryInternal method and again as the timestamp of the event. The RetryInternal method actually wants a process start time, and that is typically what functions give it. Using this as the event timestamp is therefore incorrect.
This commit adds a further parameter to the Add method and the event cache object: process start time. Functions will have to provide the event timestamp and the process start time in order to use the event cache, but this will solve the issue of the event being given the wrong timestamp.
[Upstream commit: 88786e4]
> Backport:v0.8 Add start time to event cache object

- bpf/lib/generic.h
- bpf/process/types/basic.h
- pkg/api/tracingapi/client_kprobe.go
- pkg/api/tracingapi/client_tracepoint.go
- pkg/grpc/tracing/tracing.go
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/selectors_test.go
Currently we have experimental support for URL and DNS actions, which could be used to trigger Thinkst canaries. This experimental support incorrectly handles multiple selectors – it simply collects all the URLs in the kprobe and all the FQDNs in the kprobe into lists, and when a URL or FQDN action fires on it, it triggers everything in the corresponding list. This is obviously wrong.
This commit fixes this as follows. Each kprobe stores a table of URLs and FQDNs that it references, each entry with its own index. These indices are provided in the config to the match actions in the selectors, and the BPF program reports the matching index. In user space, the URL or FQDN is retrieved from the table using this index.
Note that only one URL and/or FQDN action is permitted per selector. It …
> Handle multiple URL and DNS selectors correctly

- bpf/lib/generic.h
- bpf/process/types/basic.h
- pkg/api/tracingapi/client_kprobe.go
- pkg/api/tracingapi/client_tracepoint.go
- pkg/grpc/tracing/tracing.go
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/selectors_test.go
Currently we have experimental support for URL and DNS actions, which could be used to trigger Thinkst canaries. This experimental support incorrectly handles multiple selectors – it simply collects all the URLs in the kprobe and all the FQDNs in the kprobe into lists, and when a URL or FQDN action fires on it, it triggers everything in the corresponding list. This is obviously wrong.
This commit fixes this as follows. Each kprobe stores a table of URLs and FQDNs that it references, each entry with its own index. These indices are provided in the config to the match actions in the selectors, and the BPF program reports the matching index. In user space, the URL or FQDN is retrieved from the table using this index.
Note that only one URL and/or FQDN action is permitted per selector. It …
> Backport:v0.8 Handle multiple URL and DNS selectors correctly

- bpf/lib/generic.h
- bpf/lib/process.h
- bpf/process/bpf_execve_event.c
- bpf/process/types/basic.h
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/selectors/selectors.go
- pkg/sensors/tracing/binaryentry.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/selectors.go
This PR fixes several issues regarding `matchBinaries` selector.
The first patch fixes some issues related to `matchBinaries` selector, but keeps the limit of 4 values. The second patch removes the limit of 4 values per `matchBinaries` selector. More details on the patches. 
Additionally, this PR adds support for NotIn operator in `matchBinaries` selector.
> matchBinaries improvements

- bpf/process/types/basic.h
This commit fixes a number of file match bugs:
* __filter_file_buf() was passing a length value of one less than the string length to cmpbytes() and as a result Equals and Prefix matches were testing one fewer bytes than required.
* ASM_RCMP (used in rcmpbytes()) was decrementing the string indices before testing if they were <1. This resulted in one fewer bytes being tested than required.
* ASM_RCMP50 comprisd of 2x ASM_RCMP20 and 1x ASM_RCMP5, totalling 45 iterations of ASM_RCMP, instead of 50.
* __filter_file_buf() tested failed postfix matches with a forward string match. This resulted in files that started with the postfix, but didn't end with it, matching when they shouldn't.
* cmpbytes() continued to loop to full number of iterations, even when the string length had been exhausted …
> Fix multiple file match bugs

- bpf/process/types/basic.h
This commit fixes a number of file match bugs:
__filter_file_buf() was passing a length value of one less than the string length to cmpbytes() and as a result Equals and Prefix matches were testing one fewer bytes than required.
ASM_RCMP (used in rcmpbytes()) was decrementing the string indices before testing if they were <1. This resulted in one fewer bytes being tested than required.
ASM_RCMP50 comprisd of 2x ASM_RCMP20 and 1x ASM_RCMP5, totalling 45 iterations of ASM_RCMP, instead of 50.
__filter_file_buf() tested failed postfix matches with a forward string match. This resulted in files that started with the postfix, but didn't end with it, matching when they shouldn't.
cmpbytes() continued to loop to full number of iterations, even when the string length had been exhausted …
> Backport:v0.8 Fix multiple file match bugs

- cmd/tetra/rthooks/rthook.go
Renaming --container-dir option to --container-id.
Also removing the setup for 2 extra arguments, because container id and dir are passed as argument values.
> tetra CLI: Fix rthook/create-container command arguments

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
Related to commit [`f1cbb5f`](https://github.com/cilium/cilium/commit/f1cbb5f8a908659817e5c0e6a3692424fa647ab9) on cilium/cilium.
GitHub recently rolled out Docker buildx version v0.10.0 on their builders, which transparently changed the MediaType of docker images to OCI v1 and added provenance attestations.
Unfortunately, various tools we use in CI like SBOM tooling and docker manifest inspect do not properly support some aspect of the new image formats. This resulted in breaking CI, with some messages like this:
level=fatal msg="generating doc: creating SPDX document: generating
SPDX package from image ref quay.io/cilium/docker-plugin-ci:XXX:
generating image package"
This could also lead CI to fail while waiting for image builds to complete, because the command we use to test whether …
> Unpin buildx version in CI

- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
This patch makes selector functions public in order to be used in other (than kprobes and tracepoints) places.
This will allow use to define a different selector with different actions.
> Make functions in pkg/selectors/kernel.go public

- .github/workflows/build-clang-image.yaml
- .gitignore
- Makefile
- bpf/Makefile
Add multi-arch build for clang image to support both amd64 and arm64,
see https://docs.docker.com/build/ci/github-actions/multi-platform/.
To test, you can try on a platform that has the QEMU emulation thing: `docker buildx build --platform linux/arm64,linux/amd64 --tag mytag/clang . --file=Dockerfile.clang`, it works.
Occasionally adds `.DS_Store` files to .gitignore.
> clang image: add support for arm64 and detect arch for BPF compilation

- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
In https://github.com/cilium/tetragon/pull/686/commits/84e71d2777f43b53fcb8b53caa01431d4640ffa6 we introduced the implementation of NotIn operator in matchBinaries selector. We missed to add this in the tracing policy definition.
This patch fixes that.
> matchBinaries: Add NotIn in tracing policy

- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/generic_calls.h
Getting rid of generic_process_event* functions, one is enough.
> tetragon: Get rid of generic_process_event* functions

- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generickprobe_test.go
This fixes https://github.com/cilium/tetragon/issues/751.
If kprobe call is a syscall, we try to detect if the user specified a prefix in the form of "__x64" or "__arm64", and if not, transparently add it based on runtime.GOARCH.
```
// Note that cilium/ebpf, retries to attach to an arch specific version of the
// symbol after a failure thus making possible to attach to "sys_listen" which
// will fail and retry with the corrected "__arm64_sys_listen" if you are
// running on arm64. See https://github.com/cilium/ebpf/pull/304.  However, this
// causes Tetragon users to believe that two symbols exist (following the same
// example) "__arm64_sys_listen" and "sys_listen", which results in differents
// events.  Because we actually know if a call is a syscall, we can pre-format
// the symbol …
```
> kprobe: detect and add missing syscall arch prefix

- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
This patch makes selector ops public in order to be used in other modules.
> Export selector ops from pkg/selectors/kernel.go

- pkg/process/podinfo.go
- pkg/process/process.go
- pkg/sensors/exec/procevents/proc_reader.go
When constructing Pod information we want to have the PID inside the related container that triggered events. To achieve this we read the nspid from the container view then pass it back to GetPodInfo().
This does not introduce any code change.
> trivial:doc: add code documentation for nspid when getting Pod info

- .github/workflows/build-clang-image.yaml
Fixes https://github.com/cilium/tetragon/issues/750 since other workflows `build-image-ci.yml` and `build-images-releases.yml` are already acting differently in the case of push on main and PRs.
- Add a path addition to allow for the workflow to be tested when we modify it in a PR.
- Add a boolean condition in quay login step and at pushing step to only push on commit on main.
- Remove the environment since the workflow can run without approval now. We will still need the credential from the environment to login to quay thought.
**Warning**: I need external action on the repo for this PR to work when merged:
```yaml
username: ${{ secrets.QUAY_CLANG_RELEASE_USERNAME }}
password: ${{ secrets.QUAY_CLANG_RELEASE_PASSWORD }}
```
These secrets must be moved from the `environment: release-clang` …
> clang image: rework workflow to dry run on PR

- bpf/process/types/basic.h
- pkg/sensors/tracing/selectors_char_buf_test.go
Got the patch from @Y-dc (see https://github.com/cilium/tetragon/pull/576) and added a test for it.
> fix char buff matchargs

- bpf/include/vmlinux.h
- bpf/libbpf/bpf_tracing.h
- pkg/arch/arch.go
- pkg/arch/arch_test.go
- pkg/bench/trace_bench_open.go
- pkg/bench/trace_bench_rw.go
- pkg/config/yaml_test.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/kprobe_copyfd_test.go
- pkg/sensors/tracing/kprobe_filterchange_test.go
- pkg/sensors/tracing/kprobe_sigkill_test.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/selectors_test.go
- pkg/tracepoint/tracepoint_test.go
- testdata/specs/capchanges.yaml.tmpl
- testdata/specs/copyfd-__fd_install.yaml.tmpl
- testdata/specs/copyfd-fd_install.yaml.tmpl
- testdata/specs/nschanges.yaml.tmpl
- testdata/specs/sigkill.yaml.tmpl
- testdata/specs/syslseek.yaml
- testdata/specs/syswrongargindex.yaml
- testdata/specs/syswrongargtype.yaml
Thanks to the work done previously (see https://github.com/cilium/tetragon/issues/487), it is pretty straightforward to build Tetragon on arm64 and it seems to mostly work out of the box. The exec probes seem to be working, and I tried to load some TracingPolicy with kprobe hooks that just worked.
~~The makefile assumes that we are building using the clang docker image by default, and this one is built only for amd64 at the moment. I saw there was previously a PR attempt https://github.com/cilium/tetragon/pull/50 that was unfortunately reverted https://github.com/cilium/tetragon/pull/55 because it might have been really too early to build every images for arm64 (including the Tetragon one). It would simplify the workflow to build a multi-arch image and use it in the Makefile.~~ …
> Add support for arm64 for building, running and testing

- .github/workflows/build-deploy-docs.yaml
- README.md
As we are waiting for tetragon.cilium.io, let's use the cilium.github.io/tetragon subdirectory.
> Doc: temporary hugo baseURL fix to serve website

- .github/workflows/build-deploy-docs.yaml
- README.md
It seems that CNCF managed to set up the DNS correctly, so we should be able to use the `tetragon.cilium.io` subdomain for now.
> docs: use tetragon.cilium.io domain for website

- pkg/podhooks/podhooks.go
- pkg/policyfilter/state.go
- pkg/watcher/watcher.go
This patch allows different modules to register custom functions to watch the creation/deletion/update of pods.
> tetragon: Export podInformer

- .github/workflows/check-links-cron.yaml
- .github/workflows/check-links-pr.yaml
- README.md
- docs/content/en/docs/contribution-guide/development-setup.md
- docs/content/en/docs/faq/_index.md
- docs/content/en/docs/getting-started/deployment/package.md
- docs/content/en/docs/getting-started/explore-security-observability-events.md
- docs/content/en/docs/reference/tracing-policy.md
Please appreciate how painful it was to make that work like a charm:
```yaml
- name: Search for existing issue number
id: search-issue
run: |
encoded_issue_name=$(echo "$ISSUE_NAME" | sed 's/ /%20/g')
response=$(curl -s -X GET "https://api.github.com/search/issues?q=$encoded_issue_name+repo:cilium/tetragon+state:open+label:automated-issue&type=Issues")
issue_number=$(echo "$response" | jq -r '.items[0].number // empty')
echo "issue_number=$issue_number" >> $GITHUB_OUTPUT
- name: Create or update issue with report
if: env.lychee_exit_code != 0
uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f
with:
title: ${{ env.ISSUE_NAME }}
content-filepath: ./lychee/out.md
issue-number: ${{ steps.search-issue.outputs.issue_number }}
labels: automated-issue
```
> Documentation: add a links checker to the CI

- docs/content/en/docs/reference/tracing-policy.md
I found some missing indent in document
> docs: missing space indent

- netlify.toml
In order to avoid notification spam on our PRs preview on non-docs related PRs, we need to add a ignore command.
> Docs: add netlify config file to ignore non-docs related PRs

- .github/workflows/build-images-ci.yml
I accidentally added a run line here:
https://github.com/cilium/tetragon/blob/540a7bd4d5bd2d3df306a1b0244406efbaf249d5/.github/workflows/build-images-ci.yml#L175-L184
And it broke the workflow (which not triggered an alert in the checks since it was a `pull_request_target`) https://github.com/cilium/tetragon/pull/816#issuecomment-1472545789 it was in plain sight here. Anyway, here's a patch.
> Workflow: fix syntax of build image CI

- pkg/sensors/tracing/generickprobe.go
The MultiKprobeAttach expects pointer to attach, but we are passing poitner to pointer.
> tetragon: Fix multi kprobe attach data

- contrib/dependabot-fail
Apparently, the login for dependabot changed to app/dependabot. Let's check this as well. There seems to also be a is_bot flag now in the "author" field, but we want to look for dependabot specifically in this script.
> dependaboit-fail: check app/dependabot login

- bpf/process/types/basic.h
- contrib/tester-progs/.gitignore
- pkg/selectors/kernel.go
- pkg/selectors/selectors.go
- pkg/sensors/tracing/genericuprobe.go
- pkg/sensors/tracing/selectors.go
Using the following tracing policy:
```
kprobes:
- call: "fd_install"
syscall: false
args:
- index: 0
type: int
- index: 1
type: "file"
selectors:
- matchBinaries:
- operator: "In"
values:
- "/usr/bin/cat"
matchArgs:
- index: 1
operator: "Equal"
values:
- "/etc/passwd"
- matchBinaries:
- operator: "In"
values:
- "/usr/bin/tail"
matchArgs:
- index: 1
operator: "Equal"
values:
- "/etc/shadow"
```
we expect to get events if:
`[ binary == /usr/bin/cat AND arg1 == /etc/passwd ] OR [ binary == /usr/bin/tail AND arg1 == /etc/shadow ]`
By running:
`/usr/bin/cat /etc/passwd && /usr/bin/cat /etc/shadow && /usr/bin/tail /etc/passwd && /usr/bin/tail /etc/shadow`
We get events for all of these. Which is not the expected behavior.
The issue is that in https://github.com/cilium/tetragon/pull/686 we use …
> bugfix: matchBinaries in multiple selectors

- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- cmd/protoc-gen-go-tetragon/eventchecker/message.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
It's nice to be able to see checker names in event type mismatches in the checker logs. This makes it easier to see which outstanding checks haven't passed when the targeted event type is no longer coming in (e.g. at the end of an e2e test).
> eventchecker: output checker names in event mismatches

- docs/README.md
see: https://github.com/cilium/tetragon/pull/694#discussion_r1149189671
> docs: add link to kubernetes style guide

- pkg/btf/validation.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/policyhandler.go
- pkg/server/server.go
kprobes: pre-validate kprobe semantics
This adds a pre-validate kprobe semantics phase in order to:
1. Separate kprobe semantics errors from BPF related ones.
2. Fail early without probing BPF on some errors and avoid loading BPF resources
3. Reduce user confusion if a policy was loaded or not
Before:
```
time="2023-03-22T12:48:47+01:00" level=debug msg="Received an AddTracingPolicy request" request="yaml:\"apiVersion: cilium.io/v1alpha1\\nkind: TracingPolicy\\nmetadata:\\n name: \\\"fake\\\"\\nspec:\\n kprobes:\\n - call: \\\"sys_fake\\\"\\n   syscall: true\\n\""
time="2023-03-22T12:48:47+01:00" level=warning msg="invalid or old kprobe spec: kprobe spec validation failed: call __x64_sys_fake not found"
time="2023-03-22T12:48:47+01:00" level=debug msg="Kprobe spec pre-validation …
```
> kprobes: add a prevalidate kprobe semantics phase

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- examples/tracingpolicy/sys_write_sigkill.yaml
- pkg/btf/validation.go
- pkg/kernels/kernels.go
- pkg/option/config.go
Adding --force-large-progs option to force loading of large bpf
programs.
It's usefull in situations where kernel contains backports and
its version does not reflect actual features.
> tetragon: Add --force-large-progs option to force large bpf programs

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
This reverts commit eceacc854304748cc19f115277b0342381788626 (https://github.com/cilium/tetragon/pull/771).
Reverting this dependabot change because it breaks the build.
> Run cosign sign quay.io/cilium/tetragon-operator-ci@sha256:32851e6980638f3cd364fd52174b041de3e4bf433b3b49c57f58c0f2dc341970 | Generating ephemeral keys...
>  Retrieving signed certificate...
>  Successfully verified SCT...
> 
> 	Note that there may be personally identifiable information associated with this signed artifact. | 	This may include the email address associated with the account with which you authenticate. | 	This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later. |
> By typing 'y', you attest that you grant (or have permission to …
> Revert "build(deps): bump sigstore/cosign-installer from 2.8.1 to 3.0.1"

- pkg/sensors/tracing/policyfilter_test.go
- pkg/sensors/tracing/selectors_char_buf_test.go
Resolves in part https://github.com/cilium/tetragon/issues/776.
Fix a test that was recently introduced by https://github.com/cilium/tetragon/pull/694.
> Fix tests to run on arm64

- cmd/tetragon/main.go
> tetragon: load tracing policy provided by command line via sensor manager

- Makefile
This fixes a bug where we currently build an amd64 binary in the arm64 layer of the tetragon-operator image 😞 . See https://github.com/cilium/tetragon/issues/487#issuecomment-1495605010.
TARGET_ARCH in Makefile makes more sense for the Tetragon and BPF build because it regroups the target architecture for the Go program and the BPF code. However for pure Go programs like tetragon-operator, it makes less sense that you have to set TARGET_ARCH and that GOARCH will be overridden. This patch allows you to use both TARGET_ARCH to set everything or just GOARCH for certain pure Go program use cases.
> Makefile: set `GOARCH` to `TARGET_ARCH` only if `GOARCH` is unset 

- examples/tracingpolicy/fd_memfd_kill.yaml
- examples/tracingpolicy/hardlink-observe.yaml
- examples/tracingpolicy/hardlink-override.yaml
- examples/tracingpolicy/match_capability_changes.yaml
- examples/tracingpolicy/match_namespace_changes.yaml
- examples/tracingpolicy/names.yaml
- examples/tracingpolicy/open_kill.yaml
- examples/tracingpolicy/symlink-observe.yaml
- examples/tracingpolicy/symlink-override.yaml
- examples/tracingpolicy/sys_clock_settime.yaml
- examples/tracingpolicy/sys_mount.yaml
- examples/tracingpolicy/sys_pivot_root.yaml
- examples/tracingpolicy/sys_ptrace.yaml
- examples/tracingpolicy/sys_setuid.yaml
- examples/tracingpolicy/sys_write_follow_fd_etc_pwd.yaml
- examples/tracingpolicy/sys_write_follow_fd_prefix.yaml
- examples/tracingpolicy/sys_write_sigkill.yaml
- examples/tracingpolicy/write.yaml
This patch includes the change done by this command: 
```shell
find . -type f -name '*' -print0 | xargs -0 sed -i 's/call: "__x64_sys_/call: "sys_/g'
```
Apart from that, it highlights the issue that for the user, the symbol declared `sys_write` will be different than the symbol he can see from the logs `__x64_sys_write` or `__arm64_sys_write`. Should we do something about it? We could:
- retranslate `__x64_sys_write` to `sys_write` at the agent level so that all logs contain this symbol name;
- just provide a translation in `tetra`;
- nothing.
> TracingPolicy examples: use portable symbols for syscalls

- docs/assets/scss/_styles_project.scss
- docs/content/en/docs/reference/tracing-policy.md
- docs/i18n/en.toml
- docs/layouts/shortcodes/caution.html
- docs/layouts/shortcodes/note.html
- docs/layouts/shortcodes/warning.html
- netlify.toml
Fix partially https://github.com/cilium/tetragon/issues/872.
Deploy preview [available here](https://deploy-preview-884--tetragon.netlify.app/docs/reference/tracing-policy/).
Mostly add details about kprobes and tracepoints, change all the architecture-specific syscall symbols to generic ones, add a few note and caution blocks and fix some typos.
This PR also addresses a small issue in the Netlify config since it's used by the docs Makefile and adds the note, caution and warning blocks with some styles taken from kubernetes/website.
> Docs: update the TracingPolicy reference for arm64

- Dockerfile.operator
> fix: injecting Git version into tetragon-operator binary fails

- bpf/lib/common.h
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_generic_uprobe.c
- bpf/process/bpf_loader.c
- bpf/process/types/basic.h
- pkg/api/tracingapi/client_kprobe.go
- pkg/selectors/kernel.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/genericuprobe.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/sensors/tracing/uprobe_test.go
The matchBinary filter des not have any selector record, so we can do that as a first thing in probe.
> tetragon: Move matchBinaries filter to be executed earlier

- install/kubernetes/templates/daemonset.yaml
After the helm upgrade with new configmap changes. the daemonset pod is not recreated to retrieve the new configmap.
The readconfig function only read on pod start https://github.com/cilium/tetragon/blob/main/cmd/tetragon/main.go#L542
to make Tetragon restart and retrieve the new configuration. Kubernetes annotation helps determine whenever the pod needs to be recreated.
> helm: recreate daemonset pod when configmap changes

- pkg/ksyms/ksyms.go
- pkg/ksyms/ksyms_test.go
Use binary search to optimize performance in pkg/ksyms/ksyms.go
> use binary search to optimize performance

- contrib/tester-progs/.gitignore
- contrib/tester-progs/Makefile
- contrib/tester-progs/exit-code.c
- pkg/sensors/exec/exit_test.go
test for retrieving exit code
Fixes: #634
> test for retrieving exit code

- cmd/tetragon/main.go
- pkg/server/addr.go
- pkg/server/addr_test.go
Some recent changes to the way we input the address string in Helm have introduced an
unfortunately compatibility breakage with the old default values which did not include
a port number in the address string. To provide backward compatibility here, let's just
assume a default of `:54321` when the port is not present.
> fixup server address when port is not present

- bpf/process/types/basic.h
- pkg/btf/validation.go
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/selectors/selectors.go
Support multiple filters in matchArgs
Fix path argument type
[John: resolved conflicts on original PR here, https://github.com/cilium/tetragon/pull/827]
> matchArgs improvements

- Dockerfile
- Dockerfile.operator
- docs/content/en/docs/getting-started/deployment/container.md
- install/kubernetes/templates/_container_tetragon.tpl
ENTRYPOINT should be used instead of CMD to declare the main program of the Dockerfile. CMD should be used for default parameters to the entrypoint binary if any.
It's still possible to modify the entrypoint with the `--entrypoint` flag, to execute a bash in the container for example and it makes the image "ready to consume", i.e. you can directly pass args and flags to the image.
See this example where we simulate the ENTRYPOINT this patch would add with the `--entrypoint` flag, to understand the convenience: 
```
docker run --rm --entrypoint /usr/bin/tetragon quay.io/cilium/tetragon:v0.9.0 --help
```
This will become:
```
docker run --rm quay.io/cilium/tetragon:vTDB --help
```
> Dockerfiles: use ENTRYPOINT instead of CMD

- pkg/arch/arch.go
- pkg/encoder/encoder.go
- pkg/encoder/encoder_test.go
Also rename the output for fd_install to fd_install instead of open and change the default emoji for unrecognized symbols since previous emoji was shifting alignment.
> pkg/encoder: make customized syscalls printers portable and add open/openat

- .github/dependabot.yml
The cilium/alpine-curl dependency has tags beginning with `v` and some without, which means that for dependabot, 1.1 < v1.6.0. Let's ignore the first tags without the `v` letter. See more information here: https://github.com/cilium/tetragon/pull/909#pullrequestreview-1378642231
> Dependabot: update config for alpine-curl dep and new label name

- examples/tracingpolicy/raw_syscalls.yaml
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/syscallmetrics/syscallmetrics.go
This patch adds system call metrics. It looks for raw_syscall/sys_enter events and updates metrics.
It is expected to work with the examples/tracingpolicy/raw_syscalls.yaml custom resource. We can also update the code to work with kprobes, but this is left as future work.
The patch also updates the above yaml, so that it can be applied via kubectl.
> pks/metrics: add syscall metrics

- pkg/grpc/tracing/tracing.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/eventmetrics/eventmetrics_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/genericuprobe.go
- pkg/sensors/tracing/policyhandler.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/tracingpolicy/tracingpolicy.go
This patch adds metrics for tracing policy events. It uses the policy name and a hook name as labels.
As an example, with this policy:
```
metadata:
name: "kubectlexec-net"
spec:
kprobes:
- call: "tcp_connect"
syscall: false
args:
- index: 0
type: "sock"
selectors:
- matchPIDs:
- operator: NotIn
followForks: true
isNamespacePID: true
values:
- 1
- call: "tcp_close"
syscall: false
args:
- index: 0
type: "sock"
selectors:
- matchPIDs:
- operator: NotIn
followForks: true
isNamespacePID: true
values:
- 1
- call: "tcp_sendmsg"
syscall: false
args:
- index: 0
type: "sock"
- index: 2
type: int
selectors:
- matchPIDs:
- operator: NotIn
followForks: true
isNamespacePID: true
values:
- 1
```
We will see the following events:
``` …
```
> pkg/metrics: add event for tracing policy metrics

- pkg/sensors/program/loader.go
Cgroup SKB programs can be attached using the program.RawAttach method. This method sets the attach flags to 0. If multiple Cgroup SKB programs are to be attached to the same attachment point, then the BPF_F_ALLOW_MULTI flag needs to be passed. This patch adds a program.RawAttachWithFlags method that can be used to pass this. The program.RawAttach method has been rewritten to reuse this new method, but passing 0 as the flags.
> Add Flags To Raw Attach

- cmd/tetragon/main.go
- pkg/bench/bench.go
- pkg/observer/observer.go
- pkg/observer/observer_test_helper.go
- pkg/sensors/manager.go
- pkg/sensors/manager_test.go
- pkg/testutils/sensors/sensors.go
We have some reports of sensors using the wrong tcpmon_map. Specifically, we observe sensor programs using a different tcpmon_map than the execve program.
Below is an analysis of what may cause this, and a description of the solution implemented in this patch.
The intialization order in cmd/tetragon/main.go:
1. initialize sensor manager (InitSensorManager)
2. create k8s watcher (getWatcher)
3. start gRPC server (Serve)
4. load base sensor (directly)
The intention behind the sensor manager is to serialize all concurrent requests for loading programs/creating maps/etc. Hence, all sensors are loaded via the sensor manager except the base sensor (this is partly for historic reasons, but there are also some assumptions in the code that the base sensor is loaded first).
There are two ways that …
> tetragon: deal with duplicated tcpmon_map issue

- pkg/observer/observer_test_helper.go
- pkg/sensors/tracing/kprobe_test.go
Our tests used to silently ignore parse errors when loading tracingpolicies. This would lead to confusing failures and make it difficult to debug exactly why a test was failing in the presence of a subtly invalid tracingpolicy. Fix this issue by correctly propagating the error in observer_test_helper.
> tests: fail test when tracingpolicy parsing fails

- docs/content/en/docs/reference/tracing-policy.md
Adding documentation for Signal and NoPost actions.
> tetragon: Add documentation for Signal and NoPost actions

- bpf/process/data_event.h
Kornilios suggested the fallback for get_current_pid_tgid in data_event for reason explained in retprobe_map_get_key comment.
The fallback to frame pointer in here is fine, because we are looking for unique id and it will be stored to both struct data_event_desc and struct msg_data data.
Suggested-by: Kornilios Kourtis <kornilios@isovalent.com>
> tetragon: Add fail path for data events get_current_pid_tgid call

- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_generic_uprobe.c
- bpf/process/generic_calls.h
- bpf/process/types/basic.h
- docs/content/en/docs/reference/tracing-policy.md
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/kprobe_test.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
Adding support to specify 'maxData: true' flag for char_buf argument
type to retrieve maximum data.
Using data events (same as for exec sensor) to retrieve and send
data to the user space from bpf program.
It's available for large kernels. Kernels < 5.3 won't load the 
generic kprobe with data events due to verifier size limit.
It's possible to use the maxData flag like:
```
- call: "__x64_sys_write"
return: false
syscall: true
args:
- index: 0
type: "int"
- index: 1
type: "char_buf"
sizeArgIndex: 3
maxData: true
- index: 2
type: "size_t"
```
The data events are used only if the data won't fit into standard
event size.
There's no return kprobe support at the moment. I'm adding this
for terminal sniff, where it's not needed.
The maximum size for char_buf argument with maxData flag is …
> tetragon: Allow to use data events for char_buf data

- docs/content/en/docs/faq/_index.md
- docs/content/en/docs/getting-started/configuration.md
- docs/content/en/docs/getting-started/deployment/_index.md
- docs/content/en/docs/getting-started/explore-security-observability-events.md
- docs/content/en/docs/getting-started/kubernetes-quickstart-guide.md
- docs/content/en/docs/getting-started/try-tetragon-linux.md
- docs/hugo.toml
- docs/layouts/shortcodes/latest-version.html
Preview [here](https://deploy-preview-899--tetragon.netlify.app/docs/getting-started/try-tetragon-linux/)
The goal is to make people discover Tetragon features quickly and easily. Avoiding getting too technical or into the details.
> Docs: add a try Tetragon on Linux getting-started tutorial 

- api/v1/README.md
- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- api/v1/tetragon/tetragon.pb.go
- api/v1/tetragon/tetragon.proto
- bpf/lib/process.h
- bpf/process/bpf_execve_event.c
- bpf/process/bpf_exit.h
- bpf/process/bpf_fork.c
- contrib/tester-progs/Makefile
- contrib/tester-progs/threads-tester.c
- pkg/api/processapi/processapi.go
- pkg/grpc/exec/exec.go
- pkg/grpc/exec/exec_test_helper.go
- pkg/process/cache.go
- pkg/process/cache_test.go
- pkg/process/process.go
- pkg/sensors/exec/exec.go
- pkg/sensors/exec/procevents/proc_reader.go
- pkg/sensors/exec/procevents/proc_reader_test.go
- pkg/sensors/exec/threads_test.go
- pkg/testutils/threadevents.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
This PR adds the TID the thread ID to Process object and then it adds support to clone and process_exec|exit events.
The TID makes more sense in kprobe and tracepoints, however since we share the Process object with process_exec, let's reuse it here and ensure that the TID is not zero during process_{exec|exit}
For more details, see commits.
> tetragon: handle process threads in clone and process_{exec|exit} events

- pkg/btf/btf.go
Creating BTF obj consumes 30MB of data we really only need to find the file to feed to cilium/ebpf.
> tetragon: we only need to find the BTF file skip creating it

- pkg/observer/observer.go
To load programs we use a good chunk of memory 30MB or more just to pull in BTF, lookup attach function and so on. In many cases all the needed programs will be loaded on start. So this patch calls the GC to cleanup any memory and return it to the system.
When running with memory limits this helps Tetragon stay below max mem usage limits in k8s.
> tetragon: release memory used for loading programs

- .github/dependabot.yml
Partially reverts commit a05a988523c68eacd4ea3bad4f541560b0441f4c and fix by ignoring the latest tag.
> dependabot: fix a tag issue with alpine-curl image

- tests/e2e/helpers/dumpinfo.go
- tests/e2e/helpers/gops/gops.go
- tests/e2e/runners/runners.go
- tests/e2e/state/state.go
- tests/e2e/tests/labels/labels_test.go
- tests/e2e/tests/skeleton/skeleton_test.go
This PR introduces some refactors to tests/e2e to improve image dumps, reduce their size, and avoid duplicated information. Best reviewed by commit.
> e2e-framework: minor refactors to improve image dumps

- bpf/process/types/basic.h
- bpf/process/types/operations.h
- docs/content/en/docs/reference/tracing-policy.md
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/sensors/tracing/kprobe_test.go
Adding support and operator for kernel selector operation.
It's now possible to use it in matchArgs selector like:
```
selectors:
- index: 2
operator: "And"
values:
- 1  # O_WRONLY
- 2  # O_RDWR
```
Rebased on top of  https://github.com/cilium/tetragon/pull/885
Fixes: #933
> tetragon: Add support for and filter operation

- pkg/policyfilter/k8s_test.go
- pkg/policyfilter/podhelpers.go
- pkg/policyfilter/state.go
As things stand now, we pass all containers to the policyfilter code. As a result, we get log warnings for containers that are not running because we are unable to find their cgroup ids.
This patch fixes this issue by only dealing with containers that have a running status.
> policyfilter: only deal with running containers

- docs/content/en/docs/reference/tracing-policy.md
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
> Add documentation in the CRD for `maxData` and `returnCopy` flags and update doc

- examples/tracingpolicy/openat_write.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/kprobe_test.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
Adding support for LessThan/GreaterThan (LT/GT) operators for matchReturnArgs,
so we can use following selector:
```
matchReturnArgs:
- index: 0
operator: "GT"
values:
- 0
```
that checks return value is > 0
The filter is done in user space at the moment, still it's useful to ensure syscalls like openat returned valid fd.
> tetragon: Add support for LT/GT operators for matchReturnArgs

- cmd/tetra/common/client.go
- cmd/tetragon/main.go
- docs/content/en/docs/getting-started/configuration.md
- pkg/bugtool/bugtool.go
- pkg/defaults/defaults.go
Make tetra cli guess the best configuration to use when connecting to daemon. This saves users from explicitly specifying the server address in case it is a unix socket, as it works in localhost context anyway.
Since the client cli is run remotely, check if the server address was set
* If yes: use it directly, users know better.
* If no: then try the daemon tetragon-info.json file to find the best address
if possible (could be unix socket). This also covers the case that default
address is localhost so we are operating in localhost context anyway.
If that address is set try it, if it fails for any reason then retry last
time with the server address.
> tetra: transparently handle unix or tcp gRPC socket

- .github/ISSUE_TEMPLATE/feature_request_template.yaml
I recently saw [people using the bug template for feature requests](https://github.com/cilium/tetragon/issues/970), so here is a template for feature requests.
> github: add feature request issue template

- pkg/btf/btf.go
- pkg/observer/observer.go
Couple fixes to reduce memory consumption on startup as a few folks have complained we use too much memory.
> v0.9: tetragon backports to reduce memory limits

- bpf/process/bpf_exit.c
- bpf/process/bpf_exit.h
- pkg/sensors/base/base.go
- pkg/sensors/exec/exit_test.go
- pkg/testutils/sensors/load.go
Previously, we moved the exit hook from a `tracepoint` to `kprobe/__put_task_struct` because of some issues (more details in https://github.com/cilium/tetragon/pull/558).
On the other hand, with the new kprobe we have seen cases where the kprobe is interrupted (and aborted) which means that we missed close events.
As a first step, we revert https://github.com/cilium/tetragon/commit/1a37adf4bd400733292900335bf246f4263622bf until we find a better hook point.
This commit also disables `TestExitLeader` and `TestExitZombie` due to failures from reverting the previous commit.
> Revert: tetragon: Switch exit tracepoint to __put_task_struct kprobe

- docs/content/en/docs/faq/_index.md
Preview [here](https://deploy-preview-981--tetragon.netlify.app/docs/faq/#go-compiler-is-complaining-about-missing-symbols-in-pkgbpf).
> docs: add FAQ entry about CGO related issues in pkg/bpf

- pkg/testutils/logcapture.go
The inner logrus logger is already taking care of formating, meaning that when we have an actual % character inside the resulting string,
we end up with potential formatting issues by attempting to use that string as a format string once again. This was causing some strange bugs in tests, such as the following:
logcapture.go:23: time="2023-05-11T10:57:30-04:00" level=info msg="BPF events statistics: 72 received, 0%!e(MISSING)vents loss"
To fix this, we can use the plain T.Log() function instead of T.Logf() when writing to the LogCapturer.
> logcapture: use T.Log instead of T.Logf

- install/kubernetes/templates/daemonset.yaml
'with' already test if the values is empty so it's useless to add an extra 'if' around the 'with'
> fix[helm]: remove useless 'if' around a 'with'

- docs/content/en/docs/getting-started/configuration.md
- docs/content/en/docs/getting-started/install-tetra-cli.md
I know the guide is overlapping with the existing https://tetragon.cilium.io/docs/getting-started/explore-security-observability-events/ page, but this will be revamped (and the part about tetra CLI will be removed).
[Preview here](https://deploy-preview-991--tetragon.netlify.app/docs/getting-started/install-tetra-cli/)
> docs: add a "install tetra CLI" guide to getting started

- bpf/process/bpf_exit.c
- bpf/process/bpf_exit.h
- pkg/sensors/base/base.go
- pkg/sensors/exec/exit_test.go
- pkg/testutils/sensors/load.go
[upstream commit: fbeb302fd684a5652714049aaa48c8bcc594ad33]
Previously, we moved the exit hook from a tracepoint to kprobe/__put_task_struct because of some issues (more details in
https://github.com/cilium/tetragon/pull/558).
On the other hand, with the new kprobe we have seen cases where the kprobe is interrupted (and aborted) which means that we missed close events.
As a first step, we revert https://github.com/cilium/tetragon/commit/1a37adf4bd400733292900335bf246f4263622bf until we find a better hook point.
This commit also disables TestExitLeader and TestExitZombie due to failures from reverting the previous commit.
> backports/v0.8: Revert: tetragon: Switch exit tracepoint to __put_task_struct kprobe

- bpf/cgroup/bpf_cgroup_events.h
- bpf/process/bpf_execve_event.c
- bpf/process/bpf_fork.c
- bpf/process/bpf_process_event.h
- pkg/testutils/sensors/load.go
hunt for execve_map leak showed few places that use 
execve_map_get instead of execve_map_get_noinit.
Even though it did not turn out to be the source of the leak,
we should use execve_map_get_noinit calls.
The execve_map_get is used only by fork sensor to create the 
stat record.
> tetragon: Use execve_map_get_noinit cgroup related code

- api/Makefile
- api/export-docs.sh
- docs/content/en/docs/reference/grpc-api.md
So that the reference is integrated into the docs website and we don't have to put an external link there.
[Preview here](https://deploy-preview-1009--tetragon.netlify.app/docs/reference/grpc-api/).
> docs: add a script to export the generated API doc to references

- Makefile
To speed up the build, stolen from perf tool makefiles.
By default the bpf build is now parallel with -j<nr_cpus> option.
It's possible to specify -j argument with JOBS variable, which can be also used to switch it off with 'make JOBS=1'.
> tetragon: Enable parallel build for bpf objects

- bpf/lib/generic.h
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_generic_uprobe.c
- bpf/process/generic_calls.h
- bpf/process/types/basic.h
- contrib/tester-progs/Makefile
- contrib/tester-progs/threads-tester.c
- pkg/api/tracingapi/client_kprobe.go
- pkg/api/tracingapi/client_tracepoint.go
- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/test/test.go
- pkg/grpc/tracing/tracing.go
- pkg/process/process.go
- pkg/sensors/exec/threads_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/genericuprobe.go
- pkg/sensors/tracing/kprobe_threads_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/sensors/tracing/uprobe_test.go
- pkg/testutils/threadevents.go
This PR adds the TID the thread ID to kprobe and tracepoint events
> tetragon: handle process threads in kprobes and tracepoints

- .github/dependabot.yml
This kinda revert 22c9d55afb899aa5fbdfdbebbd0a154b428f749a.
Dependabot cannot ignore tags on Docker images, it only works on semantic version numbers. It is not documented but the GitHub support provided us the information. We could not patch dependabot behavior via configuration so we bumped the image tag itself.
> dependabot: remove ignore on tag name

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- install/kubernetes/README.md
- install/kubernetes/templates/tetragon_configmap.yaml
- install/kubernetes/values.yaml
- pkg/metrics/opcodemetrics/opcodemetrics.go
- pkg/observer/observer.go
- pkg/option/config.go
Example:
```
tetragon_handling_latency_bucket{op="23",le="50"} 3613
tetragon_handling_latency_bucket{op="23",le="100"} 4126
tetragon_handling_latency_bucket{op="23",le="500"} 4130
tetragon_handling_latency_bucket{op="23",le="1000"} 4130
tetragon_handling_latency_bucket{op="23",le="+Inf"} 4131
tetragon_handling_latency_sum{op="23"} 106430
tetragon_handling_latency_count{op="23"} 4131
tetragon_handling_latency_bucket{op="24",le="50"} 3572
tetragon_handling_latency_bucket{op="24",le="100"} 3608
tetragon_handling_latency_bucket{op="24",le="500"} 3610
tetragon_handling_latency_bucket{op="24",le="1000"} 3610
tetragon_handling_latency_bucket{op="24",le="+Inf"} 3610
tetragon_handling_latency_sum{op="24"} 56959
tetragon_handling_latency_count{op="24"} 3610 …
```
> metrics: Show the latency needed to handle a msg per op

- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/test/test.go
- pkg/grpc/tracing/tracing.go
We set tid for process part of the event to the tid value
we received from kprobe/uprobe/tracepoint event.
We missed it in HandleGenericEvent which is called from
Retry eventcache callback.
> tetragon: Adding missing tid setup to HandleGenericEvent

- bpf/process/bpf_exit.c
- bpf/process/bpf_exit.h
- contrib/tester-progs/exit-leader.c
- pkg/sensors/base/base.go
- pkg/sensors/exec/exit_test.go
- pkg/testutils/sensors/load.go
Hooking on do_task_dead kernel function, which is the last one the 
task would execute after exiting. It's stable since v4.19, so it's
safe to hook for us. 
To find out if we are the last thread of execution in the task we
use current->signal->live counter (thanks Djalal! ;-) )
It's initialized for thread leader:
```
clone {
copy_process
copy_signal
atomic_set(&sig->live, 1); 
}
```
Incremented for each new thread:
```
clone {
copy_process
atomic_inc(&current->signal->live);
... 
wake_up_new_task
}
```
Decremented for each exiting thread:
```
do_exit {
atomic_dec_and_test(&tsk->signal->live);
... 
do_task_dead
__schedule
BUG 
}
```
If task->signal->live == 0 we are the last thread of execution and we
won't race with another clone, because there's no other thread to call
it (current thread …
> tetragon: Use do_task_dead probe for exit sensor

- cmd/tetra/getevents/getevents.go
- cmd/tetra/tracingpolicy/tracingpolicy.go
- pkg/bugtool/bugtool.go
- pkg/metrics/policyfilter/policyfilter.go
- pkg/policyfilter/rthooks/rthooks.go
- pkg/policyfilter/state.go
- pkg/sensors/collection.go
- pkg/sensors/handler.go
- pkg/sensors/manager.go
- tests/e2e/checker/rpcchecker.go
- tests/e2e/helpers/grpc/grpc.go
- tests/e2e/runners/runners.go
- tests/e2e/tests/policyfilter/policyfilter_test.go
- tests/e2e/tests/skeleton/skeleton_test.go
This PR includes several improvements for polcyfilter.
* fix an issue where we did not removed policies from the policyfilter state
* add e2e tests for namespaced policies and pod label filters
* list policies in bugtool
* adds some (simple for now) metrics
There were some modifications needed in the e2e tests for the second bullet. Please review patch-by-patch.
> policyfilter improvements

- .gitignore
- api/v1/README.md
- api/v1/tetragon/events.pb.go
- api/v1/tetragon/events.proto
- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- contrib/tester-progs/.gitignore
- docs/content/en/docs/reference/grpc-api.md
- pkg/filters/filters.go
- pkg/filters/filters_test.go
- pkg/filters/pidSet.go
- pkg/observer/observer_test_helper.go
- pkg/option/config.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/exec/exit_test.go
- pkg/sensors/exec/fork_test.go
- pkg/sensors/exec/threads_test.go
- pkg/sensors/test/checker_test.go
- pkg/sensors/tracing/kprobe_amd64_test.go
- pkg/sensors/tracing/kprobe_copyfd_test.go
- pkg/sensors/tracing/kprobe_sigkill_test.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/loader_test.go
- pkg/sensors/tracing/uprobe_test.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Fix pidSet filter so that it properly accounts for children of children. Update observer_test_helper to support adding export filters on protojson and update existing tests to filter by PID with a pidSet filter.
> tests: filter unit tests by PID + fix pidSet bugs

- .github/renovate.json5
- .github/workflows/lint-helm.yaml
- .github/workflows/renovate-config-validator.yaml
- .github/workflows/renovate.yaml
- install/kubernetes/test.sh
- run renovate self-hosted on GitHub action with a workflow in order to use PostUpgradeCommands to commit generated files in deps update PRs.
- install docker CLI plugin buildx in the renovate container in order for our PostUpgradeCommands to work.
- use 'cilium-renovate' GitHub application in order to generate a fine grain permissions token.
- group some deps update together in a single PR.
- add a workflow to validate configuration change in PRs.
I had to merge https://github.com/renovatebot/github-action/pull/749 to make our commands work in the renovate container.
This will provide us a lot more control over our deps update bot, and a lot more configuration settings (since we are running it ourselves on top of changing from dependabot to renovate).
When the renovate deployment works, …
> deps: add renovate to replace dependabot

- bpf/process/types/basic.h
- docs/content/en/docs/reference/tracing-policy.md
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
Some hooks can generate the same events many times repeated. This can
fill logs and doesn't always provide useful information. This series
adds rate limiting so that events with the same data are not generated
until a specified time limit has passed.
This is implemented by building a hash key out of the function ID,
action, and the first 16 bytes of each of the arguments that are
retrieved. This key maps to the last time that the event with this key
was sent. Each new event is checked to see if it is new (in which case
it is sent and an mapping created to the current time), if it is a
repeat but long enough ago (event is sent and mapping is updated to
current time), or if it is a recent repeat, in which case nothing
happens.
> Add rate limiting to events

- examples/tracingpolicy/datagram.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/selectors/kernel.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
In the previous commit, the rate limit parameter to matchActions was incorrectly specified as argRateLimit (but was correct in documentation). This commit changes that parameter to the correct rateLimit. No releases have occurred since the commit. This change shouldn't have a detrimental or regressive effect. Also, updated the example datagram.yaml tracing policy to include the rateLimit parameter.
Also fixes a potential overflow in the rateLimit argument.
> Rename argRateLimit to rateLimit

- pkg/exporter/exporter.go
- pkg/observer/observer_test_helper.go
- pkg/process/cache.go
We are leaking goroutines in testing.
This was reproduced via running the tests with a small timeout:
```
$ sudo $(which go) test ./pkg/sensors/tracing -test.v -test.failfast -bpf-lib $(pwd)/bpf/objs -test.timeout 1m
```
And observing the resulting stack traces.
Before the patch:
```
1         /home/kkourt/src/tetragon/pkg/eventcache/eventcache.go:155 +0x112
18         /home/kkourt/src/tetragon/pkg/exporter/exporter.go:63 +0xca
19         /home/kkourt/src/tetragon/pkg/process/cache.go:149 +0x30
19         /home/kkourt/src/tetragon/pkg/process/cache.go:46 +0x105
19         /home/kkourt/src/tetragon/pkg/sensors/manager.go:57 +0xea
1         /home/kkourt/src/tetragon/pkg/server/server.go:156 +0x727
```
After the patch:
```
1         /home/kkourt/src/tetragon/pkg/eventcache/eventcache.go:155 …
```
> fix goroutines leaking in tests

- cmd/tetragon/main.go
- docs/content/en/docs/tutorials/debugging-tetragon.md
- pkg/logger/log.go
- pkg/tgsyscall/tgsyscall.go
Allow to change log level dynamically which is handy for debugging problems.
sudo kill -s SIGRTMIN+20 $(pidof tetragon)
sudo kill -s SIGRTMIN+21 $(pidof tetragon)
sudo kill -s SIGRTMIN+22 $(pidof tetragon)
sudo kill -s SIGRTMIN+22 $(pidof tetragon)
output:
time="2023-06-02T13:14:31+02:00" level=info msg="Listening for events..."
time="2023-06-02T13:14:33+02:00" level=info msg="Received signal SIGRTMIN+20: switching from LogLevel 'info' to 'debug'"
time="2023-06-02T13:14:37+02:00" level=info msg="Received signal SIGRTMIN+21: switching from LogLevel 'debug' to 'trace'"
time="2023-06-02T13:14:40+02:00" level=trace msg="process_exec: no container ID due to cgroup name not being a compatible ID, ignoring." cgroup.id=13750 cgroup.name=vte-spawn-5c6c92b1-0631-48d7-855c-bc00f4b70255.scope …
> logging: change log level dynamically

- Dockerfile
- Dockerfile.codegen
- Dockerfile.operator
> Update cilium-builder image

- bpf/include/vmlinux.h
- bpf/process/types/basic.h
- cmd/tetra/common/flags.go
- cmd/tetra/getevents/getevents.go
- examples/tracingpolicy/tty.yaml
- examples/tracingpolicy/tty_419.yaml
- pkg/encoder/encoder.go
- pkg/generictypes/generictypes.go
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/sensors/tracing/generickprobe.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
Adding way to monitor terminals, with following crd:
```
```
run on monitored terminal:
```
/dev/pts/1
...
```
on another terminal:
```
...
```
you should see data from monitored terminal.
Works on 6.x kernels so far.
> tetragon: tty monitoring

- .github/workflows/gotests.yml
- Makefile
- bpf/process/types/basic.h
- pkg/sensors/tracing/kprobe_test.go
Testing fixes. Please see patches.
> update_pid_tid_from_sock: add always_inline attr

- pkg/bpf/map_linux.go
- pkg/observer/observer_stats.go
- pkg/observer/observer_test_helper.go
This PR includes a bug that fixes a memory corruption bug, and it includes some other minor patches as well. Please review patch-by-patch.
Fixes: https://github.com/cilium/tetragon/issues/1083
Fixes: https://github.com/cilium/tetragon/issues/193
> Fix memory corruption bug

- .github/renovate.json5
- fix label priority/release-blocker
- remove digest updates to only create updates on released versions and
not on the latest commit of the main branch.
- use same git author as GitHub app
- only rebase on conflict to avoid noise
> renovate: various fixes and tuning

- Dockerfile.clang
- Makefile
Switching to clang-15 in Dockerfile.clang, the new version is 1:15.0.7-0ubuntu0.22.04.1.
> tetragon: Switch to clang-15 in Dockerfile.clang

- pkg/grpc/tracing/tracing.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/tracepoint_test.go
The syscall enter/exit tracepoints exports all arguments as 8 bytes
values (unsigned long). This might lead to problems when interpreting
smaller integers like for unsigned int for 'fd' values.
Adding a way to force type for given argument with 'Type' field.
And adding support for [u]int32 types.
> tetragon: Allow to override tracepoint argument type

- pkg/kernels/kernels.go
add check to length of versionStrings
fix: #1086
> pkg: fix versionStrings out of bound

- bpf/Makefile
- bpf/process/bpf_process_event.h
- bpf/process/types/basic.h
- contrib/verify/verify.sh
- pkg/kernels/kernels.go
- pkg/sensors/base/base.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/genericuprobe.go
The new stable is v6.1, so let's have 'latest' objects based on that.
> tetragon: Switch v60 object defines to v61

- .github/renovate.json5
This will reduce the number of PRs created by the bot.
> renovate: group Go updates except for major updates

- docs/content/en/docs/tetragon-events/generic-tracing/file-access.md
- examples/tracingpolicy/file_monitoring.yaml
- examples/tracingpolicy/file_monitoring_filtered.yaml
- pkg/encoder/encoder.go
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
This PR updates the file access use case. We use 3 new hooks to provide better visibility and remove the need to have `followfd` actions. This is done by using more appropriate hooks deeper in the kernel stack. 
These hooks are responsible to monitor read/write accesses (including different ways to do I/O), mmap calls to files that we care about, and `truncate` system calls. 
This PR also updates the encoder to pretty print these new hooks and also updates the documentation.
> tracing: Add policy for file monitoring

- Dockerfile
- Bump to building with golang 1.20.5 to placate CVE scanners
- Tweak to use a less complex image version so that Renovate will pick this up in the future.
> Bump and tweak Alpine image version

- examples/tracingpolicy/datagram-with-selectors.yaml
- examples/tracingpolicy/datagram.yaml
- examples/tracingpolicy/tcp-connect-with-selectors.yaml
- examples/tracingpolicy/tcp-connect.yaml
The tcp-connect.yaml and datagram.yaml examples include selectors that match on components of the sock and skb data structures, notably DAddr. The current release does not yet support these selectors, unintentionally breaking their use with the latest release. They should, however, work with latest main, should that be compiled from source.
This commit moves the current examples to new file names and replaces the existing examples with versions that should work with the current release.
> Fix connect and datagram tracingpolicy examples

- .github/workflows/digestcheck.yaml
- Dockerfile
- contrib/digestcheck.sh
Add a shell script and its workflow to automatically detect when we use arch-restricted Docker images when we could use multi-arch ones.
> contrib: add a Docker images digest checker

- bpf/process/types/basic.h
- cmd/tetragon/main.go
- pkg/bpf/map_linux.go
- pkg/observer/observer_stats.go
Backports:
Commits for  https://github.com/cilium/tetragon/pull/564:
*  18d0775f7b5b6f3f02928ec33b890b25f46e5209 tetragon: ensure char_buf args copy size
Commits for  https://github.com/cilium/tetragon/pull/689:
* 4af9c7fafde69771e6039ef4781ce5a4875f83ce tetragon: set default value of release-pinned-bpf to true
Commits for https://github.com/cilium/tetragon/pull/1090:
* 590a5244555c56b0e9384f1782b2ff075c03eac4 bpf: OpenMap do not leak fd
* 2df044e2fd2e55c855803b43c7946f9f4c263da3 observer_stats: use GetNumPossibleCPUs()
* 0ffc6c636150d6efc42b9bbc681fb0239d3f40b1 updateMapMetric: close maps on errors
* ~8f19ada3e1f48cded023088fb5eb24fe5d4c4cdd testObserverOptions: remove unused pretty field~ (:x: had a conflict and was not backported)
> v0.8 backports 20230627

- bpf/alignchecker/bpf_alignchecker.c
- bpf/cgroup/bpf_cgroup_events.h
- bpf/cgroup/bpf_cgroup_mkdir.c
- bpf/cgroup/bpf_cgroup_release.c
- bpf/cgroup/bpf_cgroup_rmdir.c
- bpf/include/vmlinux.h
- bpf/lib/bpf_cgroup.h
- bpf/lib/bpf_event.h
- bpf/lib/bpf_events.h
- bpf/lib/bpf_task.h
- bpf/lib/common.h
- bpf/lib/generic.h
- bpf/lib/hubble_msg.h
- bpf/lib/process.h
- bpf/process/bpf_execve_event.c
- bpf/process/bpf_exit.h
- bpf/process/bpf_fork.c
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_generic_uprobe.c
- bpf/process/bpf_loader.c
- bpf/process/pfilter.h
- bpf/process/types/basic.h
- bpf/test/bpf_globals.c
- bpf/test/bpf_lseek.c
Pushing cleanups in extra PR to make the following PR small.
> tetragon: Header file and other cleanups

- pkg/generictypes/generictypes.go
Kprobe and tracepoint arguments can be specified with a type. In some cases some common types – int64, int32, long, unsigned long and long – were missing from the mapping from their string representations to the internal type enum. This caused warnings to be displayed if these types were used in a CRD to specify the types of arguments.
This commit adds these common types.
> Add common types to CRD argument parsing

- Makefile.cli
Fixes https://github.com/cilium/tetragon/issues/1194.
> tetra: add .exe suffix for Windows binaries

- .github/renovate.json5
Too many minor updates have issues to be merged to group them together. Also group patch and minor updates for GitHub actions.
In the state, this is impossible to merge: https://github.com/cilium/tetragon/pull/1176.
> renovate: ungroup Go minor updates

- .github/renovate.json5
Run of renovate showed a warning to migrate the configuration for deprecated fields. Indeed v36 has a few breaking changes https://docs.renovatebot.com/release-notes-for-major-versions/#version-36.
See https://github.com/cilium/tetragon/actions/runs/5517954322/jobs/10061268126#step:8:77.
> renovate: migrate config for v36 release

- pkg/grpc/tracing/stats.go
- pkg/metrics/consts/consts.go
- pkg/metrics/errormetrics/errormetrics.go
- pkg/metrics/eventcachemetrics/eventcachemetrics.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/kprobemetrics/kprobemetrics.go
- pkg/metrics/mapmetrics/mapmetrics.go
- pkg/metrics/opcodemetrics/opcodemetrics.go
- pkg/metrics/policyfilter/policyfilter.go
- pkg/metrics/processexecmetrics/processexecmetrics.go
- pkg/metrics/ringbufmetrics/ringbufmetrics.go
- pkg/metrics/syscallmetrics/syscallmetrics.go
- pkg/metrics/watchermetrics/watchermetrics.go
This is a non-functional change.
> Pass Namespace in metrics options instead of prefixing metric names

- pkg/filters/fields.go
- pkg/filters/fields_test.go
Protobuf does not support snake case in the JSON representation of FieldMasks. This is a problem for us because our canonical representation of fields is in snake_case and we don't want to create confusion. To make things consistent, this patch introduces a hack to perform the snake case to camel case conversion just before we unmarshal from JSON.
```release-note
Field filters for masking event export fields now support path names defined in snake_case as well as camelCase.
```
> pkg/filters: make field filters work with snake case fields

- pkg/bench/summary.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/ringbufmetrics/ringbufmetrics.go
- pkg/observer/observer.go
- pkg/server/server.go
The following metrics:
* tetragon_notify_overflowed_events
* tetragon_ringbuf_perf_event_received
* tetragon_ringbuf_perf_event_lost
* tetragon_ringbuf_perf_event_errors
are conceptually counters, not gauges, so I changed the metric type to reflect
that. Also added a `_total` suffix to all of them, for compatibility with the
OpenMetrics standard. This is a breaking change, but it shouldn't be painful - the semantics of the metrics doesn't change, only the names.
Admittedly, it's also not super necessary - using plain Prometheus you can scrape and query existing metrics just fine. Maybe there are/will be other systems that are pedantic about the standard, then this change will bring some benefits, but otherwise it's kinda compatibility for its own sake. Please shout if you think it's not …
> metrics: Switch from gauges to counters

- pkg/metrics/errormetrics/errormetrics.go
- pkg/metrics/eventcachemetrics/eventcachemetrics.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/kprobemetrics/kprobemetrics.go
- pkg/metrics/mapmetrics/mapmetrics.go
- pkg/metrics/processexecmetrics/processexecmetrics.go
- pkg/metrics/syscallmetrics/syscallmetrics.go
- pkg/metrics/watchermetrics/watchermetrics.go
For compatibility with the [OpenMetrics standard](https://github.com/OpenObservability/OpenMetrics/blob/v1.0.0/specification/OpenMetrics.md#suffixes). This is a breaking change, but it shouldn't be painful - the semantics of the
metrics doesn't change, only the names.
While here, I renamed a few metrics to follow common naming conventions:
* event_cache_count -> tetragon_event_cache_accesses_total
* tetragon_policy_stats -> tetragon_policy_events_total
* tetragon_syscall_stats -> tetragon_syscalls_total
Admittedly, it's also not super necessary - using plain Prometheus you can scrape and query existing metrics just fine. Maybe there are/will be other systems that are pedantic about the standard, then this change will bring some benefits, but otherwise it's kinda compatibility for its own …
> Add _total suffix to counter metrics that didn't have it 

- .github/workflows/static-checks.yaml
- Makefile
- pkg/selectors/selectors.go
- pkg/sensors/load.go
- pkg/sensors/program/loader.go
- pkg/sensors/program/map.go
- pkg/sensors/program/program.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/selectors.go
- pkg/sensors/tracing/selectors_test.go
When setting multiple inner maps in argfilter_maps of different sizes,
loading the data into the maps fails for 5.4 and 4.19 kernels.
We attribute this failure to these kernels not having
https://lore.kernel.org/bpf/20200828011800.1970018-1-kafai@fb.com/,
which allows the outer map to be updated with an inner map of different
sizes. This change was introduced in 5.9
This PR:
1. Introduces a MaxEntriesInnerMap filed in the programs, which allows
us to override the max entries defined in the bpf code. We follow
this approach since there is already a MaxEntries field for a similar
purpose.
2. Sets this field using SetMaxEntries in both generic kprobes and
tracepoints. For this to work, we had to move the parsing of the
kernel selectors earlier. This happens only for
kerrnels < 5.9
3. …
> selector fixes

- bpf/process/addr_lpm_maps.h
- bpf/process/types/basic.h
- bpf/process/types/operations.h
- docs/content/en/docs/concepts/tracing-policy.md
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/selectors/selectors.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/selectors.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
This series adds functionality to socket matching for sock and skb types. Previously, ports and CIDRs could be specified, but only a limited number would be accepted, due to complexity issues surrounding checking members of lists. This series uses an argfilter map to specify ports so that theoretically any number could be specified, and a new addr4filter map to specify IPv4 CIDRs, that are matched using a longest prefix match TRIE map.
In addition, ports can now be specified as ranges using the 'min:max' format, and new operators SPortPriv and DPortPriv were added to specify the range of privileged ports, from 0 to 1023 inclusive. On top of that, all port and address operators now can be prefixed with the Not keyword to create an inverse match, e.g. NotSAddr, and these can be combined …
> Infinite ports and CIDRs

- .github/workflows/vmtests.yml
- cmd/tetragon-vmtests-run/main.go
- cmd/tetragon-vmtests-run/run_tests.go
- pkg/sensors/tracing/loader_test.go
- pkg/vmtests/skip.go
- pkg/vmtests/vmtests.go
- tests/vmtests/fetch-data.sh
Update the gh action for vmtetss to use the latest version for each kernel, which is designated as "-main".
> gh/vmtests: use -main for latest version and add bpf-next

- .github/renovate.json5
- .github/workflows/generated-files.yaml
- .github/workflows/gotests.yml
- .github/workflows/run-e2e-tests.yaml
- .github/workflows/static-checks.yaml
- .github/workflows/vmtests.yml
- Dockerfile
- Dockerfile.operator
- Makefile.cli
Fixes #1169.
It was way more complicated than initially thought and it took me something like 2 days asynchronously to debug/test on the fork. The result should be as fancy as this PR on the fork https://github.com/mtardy/tetragon/pull/63/files.
> Let renovate update Go toolchain in a single PR

- pkg/sensors/tracing/kprobe_test.go
- pkg/vmtests/skip.go
The TestKprobeSkb test in pkg/sensors/tracing/kprobe_test.go uses a hook that doesn't appear to be hit by sent/received TCP/UDP datagrams in bpf-next. As such, this test fails.
This commit replaces the hook in the test with ip_send_skb that gets hit for IPv4 UDP datagrams. This causes the test to succeed on kernels 4.19, 5.4, 5.10, 5.15 and (current at time of writing) bpf-next.
Fixes #1249
> Fix SKB test

- bpf/lib/data_msg.h
- bpf/process/data_event.h
- pkg/api/dataapi/data.go
- pkg/observer/data.go
- pkg/observer/data_stats.go
- pkg/sensors/exec/exec.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/tracing/generickprobe.go
Adding size check on receiving side of data event to make
sure we won't use incomplete data.
Also adding stats for data events to keep track of what's
happening in there.
> tetragon: Check final size for data event

- pkg/sensors/program/loader.go
- pkg/sensors/tracing/generickprobe.go
Making the loader more configurable through opts and moving override
code loading out of the loader core into kprobe opts callbacks,
plus other small fixes.
> tetragon: Loader fixes

- .github/renovate.json5
- .github/workflows/renovate.yaml
- .github/workflows/static-checks.yaml
- Makefile
- pkg/k8s/Makefile
> Renovate: let renovate update golangci-lint and various fixes

- pkg/eventcache/eventcache.go
- pkg/grpc/exec/exec.go
- pkg/grpc/tracing/tracing.go
GetProcessCopy is required when we need to modify the Process info. This is done primarily to update the Tid to reflect the caller of a system call or kprobe.
Most other cases shouldn't need to get a fully copy of the process object. The reason a copy is needed in the modification case is to avoid having a writer updating the object while the GRPC stream handler or JSON writer are marshalling the data which can corrupt the streaming logic. This results in either broken messages in JSON export file or the GRPC stream failing.
> tetragon: remove unnecessary GetProcessCopy()

- bpf/process/bpf_generic_kprobe.c
- pkg/sensors/program/loader.go
- pkg/sensors/program/program.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/kprobe_test.go
Adding support to load override helper for kprobe.multi attached
kprobes.
> tetragon: Add support for multi kprobe override

- pkg/grpc/tracing/tracing.go
- pkg/sensors/exec/exec.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/loader.go
- pkg/strutils/strutls.go
> Handle non-utf8 strings in protobuf structures

- pkg/grpc/tracing/tracing.go
- pkg/sensors/exec/exec.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/loader.go
- pkg/strutils/strutls.go
Backported PRs
* https://github.com/cilium/tetragon/pull/1282
* [exec event: deal with non-utf8 strings](https://github.com/cilium/tetragon/commit/cba6fc7d89357ba0be0900903374e690295b386d)
* [tracing: refactor handleGenericKprobeString](https://github.com/cilium/tetragon/commit/c32895c6fc28abc043008a129a2fb347cadc0660)
* [tracing: use handleGenericKprobe](https://github.com/cilium/tetragon/commit/43db99bac6c7e126b3205d9ab3836795f0e5a32c)
* [tracing: ensure strings are valid utf-8](https://github.com/cilium/tetragon/commit/7c7ed6a19eb4be0b6b6480c8a2dec47c14e79476)
* [grpc/tracing: remove unused type in HandleMessage](https://github.com/cilium/tetragon/commit/eebb6bac3496acc91195ccb141c9c7dda56c4cf9)
> v0.10 backports

- pkg/grpc/tracing/tracing.go
- pkg/sensors/exec/exec.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/loader.go
- pkg/strutils/strutls.go
Backported PRs
* https://github.com/cilium/tetragon/pull/1282
* [exec event: deal with non-utf8 strings](https://github.com/cilium/tetragon/commit/cba6fc7d89357ba0be0900903374e690295b386d)
* [tracing: refactor handleGenericKprobeString](https://github.com/cilium/tetragon/commit/c32895c6fc28abc043008a129a2fb347cadc0660)
* [tracing: use handleGenericKprobe](https://github.com/cilium/tetragon/commit/43db99bac6c7e126b3205d9ab3836795f0e5a32c)
* [tracing: ensure strings are valid utf-8](https://github.com/cilium/tetragon/commit/7c7ed6a19eb4be0b6b6480c8a2dec47c14e79476)
* [grpc/tracing: remove unused type in HandleMessage](https://github.com/cilium/tetragon/commit/eebb6bac3496acc91195ccb141c9c7dda56c4cf9)
> v0.9 backports

- .github/workflows/packages-e2e-tests.yaml
- Dockerfile
- Dockerfile.dev
- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- docs/content/en/docs/getting-started/deployment/container.md
- docs/content/en/docs/getting-started/deployment/package.md
- docs/content/en/docs/reference/tetragon-configuration.md
- examples/sandbox/linux-namespaces/kill_unprivileged_user_namespace_in_pid_namespace.yaml
- examples/tracingpolicy/bpf.yaml
- examples/tracingpolicy/open_geturl.yaml
- install/linux-tarball/install.sh
- pkg/defaults/defaults.go
- pkg/option/config.go
- pkg/tracingpolicy/generictracingpolicy.go
Load tracing policies from /etc/tetragon/tetragon.tp.d/
Allow to use 1 depth directory to organize tracing policies, example: file access, network access, etc...
> tetragon: load tracingpolicies from directory

- contrib/localdev/bootstrap-kind-cluster.sh
- contrib/localdev/install-tetragon.sh
Using `helm upgrade --install` instead of `helm install` makes it possible to use the same script for both installing and upgrading Tetragon in a Kubernetes cluster.
Also added a timeout for `kubectl rollout status` command to prevent the script from handing forever.
> contrib: Support upgrade in install-tetragon.sh

- .github/workflows/static-checks.yaml
Also remove make tarball since it now has its own workflow file: packages-e2e-tests.yaml.
This speeds up static checks feedback a lot.
> workflows: split static checks to parallelize jobs

- pkg/sensors/tracing/generickprobe.go
Allow to override security_ hooks, there are probably other hooks that have other naming pattern, but let's start simple and maybe later we add those case by case
> kprobes: allow to override security_ hooks

- examples/tracingpolicy/cves/cve-2023-2640-overlayfs-ubuntu.yaml
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2640
Prevents copying up security.capability xattr on overlayfs from a user namespace, making it a nop.
> cves:exploit: prevent cve-2023-2640 overlayfs exploit on ubuntu

- bpf/process/types/basic.h
- pkg/sensors/tracing/kprobe_test.go
The tracing policy provided in https://raw.githubusercontent.com/cilium/tetragon/main/examples/tracingpolicy/file_monitoring.yaml does not work as expected. 
The matchArgs filter with file type and Prefix operator results in events with filenames with different prefixes as what we expected. This means that expect from the events that we care about, we also get a bunch of unrelated events. 
More details on commit messages.
```release-note
Fix Prefix operator with file type in matchArgs.
```
> bugfix: Fix Prefix operator with file type in matchArgs 

- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generickprobe_test.go
Initially found this issue by trying to fuzz parts of the handler. You can run the fuzzer with the following command:
`go test -fuzz=Fuzz_parseString -run=Fuzz_parseString ./pkg/sensors/tracing/` Also added some unit test cases under `Test_parseString`.
Previous parsing had flaws that could make Tetragon panic or be OOM killed in certain circumstances. In reality, the string size was already bound by BPF copy_string function to 1024 but it could have theoretically returned a size of -2 as an error code which would have made it panic.
Also remove some code duplication that was rewriting the string parsing instead of using the common function.
> sensors: harden string parsing from BPF events

- examples/tracingpolicy/dns-only-specified-servers.yaml
- examples/tracingpolicy/tcp-connect-only-local-addrs.yaml
- examples/tracingpolicy/tcp-connect-only-private-addrs.yaml
1. Only permit port 53 to specified DNS servers.
2. Only permit TCP connect to private addresses and loopback (enforce in-cluster communciation only) for specified processes.
3. Only permit TCP connect to loopback (enforce side car access only) for specified processes.
More details in the descriptions of each policy. Note these will require v0.11 or later.
> Add three network policies

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/btf/btf.go
- pkg/option/config.go
- pkg/sensors/program/loader.go
- pkg/sensors/tracing/generickprobe.go
Adding a kprobe hook to a function that defined inside a module is not currently supported.
This commit adds support for that.
The user can use a command line argument --kmods to define the desired modules. Adding --kmods overlay,tls will search for btf files in /sys/kernel/btf/overlay and /sys/kernel/btf/tls.
> btf: Add support to load symbols from kernel modules

- .github/renovate.json5
This partially reverts commit 9e6f21093791e9078c109e5ad7d05ca4343d759e.
I was wrong, most of the settings of renovates are not regexes and this breaks glob matching.
> Revert "renovate: fix usage of dot in regexes"

- bpf/lib/process.h
- pkg/metrics/mapmetrics/mapmetrics.go
- pkg/observer/observer_stats.go
Maps have an associated _stats map that is used to keep total number of entries values. Lets use the stats maps to also store any errors that map updates/deletes may have encountered.
> tetragon: Add stats support for errors

- cmd/tetragon/conf.go
- pkg/option/config.go
Move readConfig{Dir,File} to the option package. I'd like to use these functions to read tetragon operator configurations.
Ref: #794
> refactor: Move readConfig{Dir,File} to the option package

- pkg/bench/trace_bench_rw.go
- pkg/observer/observer.go
- pkg/observer/observer_test_helper.go
- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/exec/exit_test.go
- pkg/sensors/exec/fork_test.go
- pkg/sensors/exec/threads_test.go
- pkg/sensors/test/checker_test.go
- pkg/sensors/test/lseek_test.go
- pkg/sensors/tracing/kprobe_amd64_test.go
- pkg/sensors/tracing/kprobe_copyfd_test.go
- pkg/sensors/tracing/kprobe_filterchange_test.go
- pkg/sensors/tracing/kprobe_sigkill_test.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/kprobe_threads_test.go
- pkg/sensors/tracing/loader_test.go
- pkg/sensors/tracing/selectors_char_buf_test.go
- pkg/sensors/tracing/selectors_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/sensors/tracing/uprobe_test.go
I hit an import cycle in `observer_test_helpers.go` when working on #1304, so I re-implemented `metrics.EnableMetrics()` there instead of importing the metrics package. Then I hit the same import cycle when working on #1279, so here I moved `observer_test_helpers.go` to a separate package.
It's a pretty straightforward refactoring, see commits for details. Technically it is a breaking change, but only developer-facing.
> Move observer_test_helpers.go to a separate package

- docs/content/en/docs/reference/helm-chart.md
- install/kubernetes/README.md
- install/kubernetes/templates/_container_tetragon.tpl
- install/kubernetes/templates/daemonset.yaml
- install/kubernetes/templates/operator_configmap.yaml
- install/kubernetes/values.yaml
- operator/flags.go
- operator/main.go
- operator/option/config.go
- Add tetragon-operator-config ConfigMap.
- Add tetragonOperator.skipCRDCreation Helm value.
- Mount the ConfigMap to /etc/tetragon/operator.conf.d/ and load the
config from the directory.
- Log the config at the startup.
Ref: #794
sample log output:
```
level=info msg="Loaded config from directory" config-dir=/etc/tetragon/operator.conf.d/ subsys=tetragon-operator
level=info msg="Starting Tetragon Operator" config="&{SkipCRDCreation:false KubeCfgPath: ConfigDir:/etc/tetragon/operator.conf.d/}" subsys=tetragon-operator version=v0.10.0-145-g8b2a7e8f
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=TracingPolicy/v1alpha1 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=TracingPolicyNamespaced/v1alpha1 subsys=k8s …
```
> Add tetragon-operator-config ConfigMap

- bpf/process/types/basic.h
- bpf/process/types/operations.h
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- pkg/selectors/kernel.go
- pkg/sensors/tracing/kprobe_test.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
FIXES: https://github.com/cilium/tetragon/issues/1310
> matchArgs: Add Not{Equal, Prefix, Postfix} in fd, file, path types

- pkg/sensors/tracing/kprobe_test.go
We didn't rebase https://github.com/cilium/tetragon/pull/1325 after merging
https://github.com/cilium/tetragon/commit/822e2da104233a546765f399b0ba3877a8c7d1fc so this makes TestKprobeMatchArgsNonPrefix introduced in that PR to broke builds in main branch.
This patch fixes that issue.
> Fix TestKprobeMatchArgsNonPrefix test

- operator/crd/crd.go
- operator/main.go
We'll introduce a proper operator deployment in #794. Once the operator deployment is available, we can move the CRD registration logic there instead of calling it from an init container in the Tetragon daemonset. This commit moves the CRD registration logic to a separate package so that it can be called from outside the main package.
> operator: Move the CRD registration logic to a separate package

- README.md
- docs/content/en/docs/tutorials/verify-tetragon-image-signatures.md
https://docs.sigstore.dev/cosign/installation/ is returning 404 now. Let's use https://docs.sigstore.dev/system_config/installation/ instead.
> docs: Update the link to the cosign installation page

- docs/content/en/docs/reference/helm-chart.md
- install/kubernetes/README.md
- install/kubernetes/templates/clusterrole.yaml
- install/kubernetes/templates/operator_clusterrole.yaml
- install/kubernetes/templates/operator_clusterrolebinding.yaml
- install/kubernetes/templates/operator_configmap.yaml
- install/kubernetes/templates/operator_deployment.yaml
- install/kubernetes/templates/operator_serviceaccount.yaml
- install/kubernetes/values.yaml
In this PR:
- Added service account, role bindings and cluster roles for the tetragon operator deployment.
- This is disabled by default, to enable it, set the podWatcher.enabled field to true.
> Add tetragon operator deployment into the helm chart

- bpf/process/generic_calls.h
It's leftover from latest refactoring [1].
[1] 8d8af6d7907d tetragon: Refactor generic_process_event* functions
> tetragon: Remove unnecessary computation line

- examples/tracingpolicy/datagram_518.yaml
The datagram examples only work up to and including kernel version 5.17. This is because an extra check was placed in front of the hook in 5.18.
This commit moves the hook points to before the checks such that they should all work on recent kernels.
> sock/skb: Add datagram example for kernel 5.18+

- bpf/process/addr_lpm_maps.h
- bpf/process/types/basic.h
- bpf/process/types/skb.h
- bpf/process/types/sock.h
- bpf/process/types/tuple.h
- docs/content/en/docs/concepts/tracing-policy.md
- pkg/api/tracingapi/client_kprobe.go
- pkg/reader/network/network.go
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/selectors/selectors.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/selectors.go
The sock and skb types currently support IPv4 addresses and CIDRs, and in fact the whole subsystem assumes network operations are only IPv4 or AF_INET.
This commit adds IPv6 support by allowing IPv6 addresses and CIDRs to be specified for arg matching for sock and skb types; collects IPv6 addresses from sockets and datagrams where the family is AF_INET6; and reports said addresses correctly in user space.
> sock/skb: Add IPv6 Support

- docs/content/en/docs/concepts/tracing-policy.md
The override on security_ hook is available starting from 5.7, so check before loading the policy.
https://lore.kernel.org/all/20200304191853.1529-5-kpsingh@chromium.org/
> bpf: fmodret override on security_ hooks is available from 5.7

- contrib/rthooks/minikube-containerd-install-hook.sh
Build `tetradon-oci-hook` statically-linked binary. It ensures binary is exected in minikube environment without linking errors.
> tetragon-oci-hook: statically linked binary

- install/kubernetes/templates/clusterrole.yaml
- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/watcher/fake.go
- pkg/watcher/watcher.go
- pkg/watcher/watcher_test.go
Cache k8s services and index them by IP addresses when --enable-k8s-api
flag is specified. This allows Tetragon to associate IP addresses with
k8s services in network events.
> Watch k8s services

- .github/workflows/packages-e2e-tests.yaml
Just noticed this check started in https://github.com/cilium/tetragon/pull/1377.
> Ignore `docs/**` in packages-e2e-tests.yaml

- .github/workflows/static-checks.yaml
- .golangci.yml
Caching was disabled for stuff that might not apply anymore: golangci/golangci-lint-action#153
We were timing out on the analysis so this might help.
> golangci-lint: increase timeout and enable caching

- docs/content/en/docs/use-cases/linux-process-credentials/monitor-changes-at-kernel.md
- docs/content/en/docs/use-cases/security-profiles/_index.md
- docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
- examples/tracingpolicy/process-credentials/creds-capability-usage.yaml
Depends on https://github.com/cilium/tetragon/pull/888
Made this into new sub section inside doc security profiles: https://deploy-preview-1189--tetragon.netlify.app/docs/use-cases/security-profiles/   if it doesn't feel right, can move it back to linux process credentials section
> use case:credentials: record Linux capability usage

- docs/assets/scss/page-info.scss
- docs/content/en/docs/concepts/k8s-filtering.md
- docs/content/en/docs/concepts/tracing-policy/_index.md
- docs/content/en/docs/concepts/tracing-policy/example.md
- docs/content/en/docs/concepts/tracing-policy/hooks.md
- docs/content/en/docs/concepts/tracing-policy/selectors.md
- docs/content/en/docs/getting-started/try-tetragon-linux.md
Now the Tracing Policy documentation splits into three pages:
- an example of policy, shortly explained
- a hook point page about how to use kprobes, tracepoints, etc.
- a selector page about filters and actions
See [preview](https://deploy-preview-1377--tetragon.netlify.app/docs/concepts/tracing-policy/).
> docs: split Tracing Policy concept page into subpages

- cmd/tetragon/main.go
- pkg/bench/bench.go
- pkg/grpc/process_manager.go
- pkg/grpc/process_manager_test.go
- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/process/process.go
- Remove ciliumState field from ProcessManager
- Delete GetProcessEndpoint()
> refactor: Clean up unused stuff

- pkg/process/process.go
Add a function that returns K8sResourceWatcher. This makes it easier for users of the process package to associate process information with Kubernetes resources.
> process: Add a function to access K8sResourceWatcher

- .github/workflows/pr-validation.yaml
This action validates PRs based on labels.
It blocks PRs that have a dont-merge/* label, and blocks PRs that do not have a release-note/* labe.
> gha: add pr-validation GH action

- pkg/grpc/exec/exec.go
- pkg/grpc/process_manager_test.go
- pkg/process/podinfo.go
- pkg/process/podinfo_test.go
- pkg/process/process.go
The return value is always ignored, and it's only being used by unit tests.
> process.GetPodInfo: Don't return Cilium endpoint

- cmd/tetra/common/client.go
- cmd/tetra/common/flags.go
- cmd/tetra/main.go
This PR adds two new command line options:
- `--timeout` allows the user to configure the desired gRPC connection timeout, instead of hard coding it at 10 seconds
- `--retries` sets the number of attempts we should make to connect to the gRPC server with exponential backoff
> cmd/tetra: retry failed gRPC connections with exponential backoff

- cmd/tetragon/main.go
- pkg/metrics/config/initmetrics.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/metrics/syscallmetrics/syscallmetrics.go
- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/podhooks/podhooks.go
Some of the exposed metrics have "pod" label, which contains the name of the
monitored pod. So far when a pod got deleted, Tetragon kept exposing stale
metrics for it. This was causing continuous increase in memory usage in
Tetragon agent as well as in the metrics scraper.
This PR fixes the issue. Now if metrics and k8s API are both enabled then
an additional pod hook gets registered that on pod deletion deletes metrics
associated with it.
```release-note
When a pod gets deleted, Tetragon stops exposing metrics associated with it.
```
> Delete metrics for deleted pods

- pkg/selectors/selectors.go
We need to update theselector's newBinVals even in case the binary is in the global cache. The selector's newBinVals data is used to update the data in names_map map.
> tetragon: Add missing selectors newBinVals setup

- docs/content/en/docs/concepts/tracing-policy/hooks.md
Adding documentation for lists.
> tetragon: Adding lists documentation

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/metrics/config/initmetrics.go
- pkg/metrics/ringbufqueuemetrics/ringbufqueuemetrics.go
- pkg/observer/observer.go
- pkg/option/config.go
Adding extra layer between perf ring buffer reader and event
processing by sensor code.
This way we keep the perf reader fast and we won't get lost events
if sensor processing code have a hiccup and takes longer.
> tetragon: Add buffer between perf reader and events processing code

- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/testutils/filenames.go
- pkg/testutils/logcapture.go
The testing package supports additional test types, such as fuzzing and bench testing. However, our existing observer test helpers were designed only to work with unit tests. To support additional test types, modify the observer test helpers to use the generic testing.TB interface instead of testing.T. This should facilitate writing fuzz tests and benchmarks for Tetragon in the future.
> observer_test_helper: make helpers generic over TB

- .github/renovate.json5
See https://github.com/cilium/tetragon/pull/1384#issuecomment-1704986391 and https://github.com/cilium/tetragon/pull/1384#issuecomment-1705460667.
Already created this label https://github.com/cilium/tetragon/labels/release-note%2Fdependency (but renovate creates if needed anyway).
Should this be plural `release-note/dependencies`?
> renovate: add release-note/dependency label to PRs

- cmd/tetra/getevents/io_reader_client.go
- pkg/server/server.go
As we keep them in the process cache, removing fields may affect the correctness of the process cache. In order to fix that, we create a copy of the event and apply fieldFilters only on the copy.
FIXES: https://github.com/cilium/tetragon/issues/1428
> Use a message copy to apply fieldFilters in exec events

- install/kubernetes/templates/operator_clusterrolebinding.yaml
this commit:
- changes the name of operator cluster role to match the name in cluster role binding.
> Modify Operator cluster role

- .github/CODEOWNERS
- Fix paths, indeed `path/` means that it will select `/path/` but also `/something/path/`. So I explicitely mentioned `/path/` for the entries.
- Exclude myself from some auto-generated docs files that are often modified.
- Add @cilium/tetragon owner to `/.github/workflows/` to ping William on workflow changes without blocking PRs.
- Move file into `/.github` since it's tied to GitHub and will reduce the amount of files in the root.
cc @willfindlay, tell me if you are satisfied with the changed I did to your line.
> CODEOWNERS: multiple fixes and move file in `.github`

- install/kubernetes/templates/_container_tetragon.tpl
We noticed issues in testing where gRPC queries would sometimes spuriously time out, causing our livenessProbe to fail and the Tetragon pod to restart. 7f2edda4 and 4f4feb8c introduced new configuration values in our CLI to allow it to re-attempt the connection in case of failure. Update our livenessProbe in helm to use these new configuration values so that we can re-attempt the connection.
> helm: update livenessProbe to retry 5 times before failing

- pkg/metrics/config/initmetrics.go
- pkg/metrics/ratelimitmetrics/ratelimitmetrics.go
- pkg/ratelimit/ratelimit.go
Tetragon can set a maximum rate limit to push events. And when this is done we also track the number of events that were dropped due to a rate limit. When drops occur we generate a summary event to report how many drops happened. This adds a metric for this as well so it can be tracked easily from prometheous.
> tetragon: Add metric to report rate limited events

- bpf/process/string_maps.h
- bpf/process/types/basic.h
- examples/tracingpolicy/hardlink-observe.yaml
- examples/tracingpolicy/hardlink-override.yaml
- examples/tracingpolicy/openat_write.yaml
- examples/tracingpolicy/symlink-observe.yaml
- examples/tracingpolicy/symlink-override.yaml
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/selectors/selectors.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/selectors.go
Currently string, char buf, file, fd, and path matchers (equal, prefix, postfix, plus the 'not' equivalents for file, fd and path) are all written in BPF using loops to inspect (potentially) every character in the strings to be matched.
This series (see commits for details) converts all these matchers to hash map look ups, using a set of 6 hash maps of varying sizes for equal matches, and LPM TRIE maps for prefix and postfix look ups. In addition, the 'not' equivalents are implemented for string and char buf.
The default string lengths for the matches has been set at 128 bytes, but could be increased to an arbitrary size for equals, and up to 256 bytes for prefix and postfix. For small programs (<5.3), the postfix limit (which is bounded by a byte-by-byte reverse copy) has been raised …
> Convert string and char_buf matches to hash look ups

- bpf/process/data_event.h
This patch fixes a verification error in a 4.18.0-477.21.1.el8_8.x86_64 kernel.
The error was reported in issue #1442.
The patch simplifies the code: it eliminates a common expression, and it changes some values from int to long to avoid generated code for the implicit casting.
It also fixes a issue. bpf_probe_read_str may return 0, and in this case the old code will underflow. And even though we mask the size, the size value would have been wrong in this case:
(gdb) printf "0x%zx\n", (0-1) & 0x7fff
0x7fff
> bpf: fix verification error in bpf_execve_event

- README.md
- docs/content/en/docs/use-cases/process-lifecycle/advanced-process-execution.md
Extremely 😇 PR.
Busybox website has proven to be unreliable and has been generating noise on the link detector:
- https://github.com/cilium/tetragon/issues/1374
- https://github.com/cilium/tetragon/issues/1360
- https://github.com/cilium/tetragon/issues/1338
> docs: fix link in README and remove unreliable link to busybox

- examples/tracingpolicy/cves/cve-2023-2640-overlayfs-ubuntu.yaml
- examples/tracingpolicy/datagram-with-selectors.yaml
- examples/tracingpolicy/datagram-with-sock-tracking.yaml
- examples/tracingpolicy/datagram_518.yaml
- examples/tracingpolicy/dns-only-specified-servers.yaml
- examples/tracingpolicy/openat_write.yaml
- examples/tracingpolicy/sys_write_sigkill.yaml
- examples/tracingpolicy/tcp-accept.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- pkg/k8s/apis/cilium.io/v1alpha1/register.go
- pkg/k8s/apis/cilium.io/v1alpha1/types.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/register.go
- vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
This PR fixes all example tracing in https://github.com/cilium/tetragon/tree/main/examples/tracingpolicy to load in k8s.
> Small fixes in example tracing policies

- go.mod
- go.sum
- vendor/github.com/pelletier/go-toml/v2/.goreleaser.yaml
- vendor/github.com/pelletier/go-toml/v2/LICENSE
- vendor/github.com/pelletier/go-toml/v2/README.md
- vendor/github.com/pelletier/go-toml/v2/ci.sh
- vendor/github.com/pelletier/go-toml/v2/decode.go
- vendor/github.com/pelletier/go-toml/v2/marshaler.go
- vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
- vendor/github.com/pelletier/go-toml/v2/unstable/parser.go
- vendor/modules.txt
This reverts commit 8d27aec379cabd2dc81c0ad21155bb7288fa7f66. This commit bumped the indirect dependency and not the direct project dependency.
> Revert "Update module github.com/pelletier/go-toml/v2 to v2.1.0"

- install/kubernetes/templates/clusterrole.yaml
- install/kubernetes/templates/clusterrolebinding.yml
- install/kubernetes/templates/daemonset.yaml
- install/kubernetes/templates/operator_clusterrole.yaml
- install/kubernetes/templates/operator_clusterrolebinding.yaml
- install/kubernetes/templates/operator_configmap.yaml
- install/kubernetes/templates/operator_deployment.yaml
- install/kubernetes/templates/operator_serviceaccount.yaml
- install/kubernetes/templates/service.yaml
- install/kubernetes/templates/serviceaccount.yaml
- install/kubernetes/templates/tetragon_configmap.yaml
> helm: Allow multiple installations of the Tetragon Helm chart

- .github/renovate.json5
- .github/workflows/vmtests.yml
Adapt the regex used in the workflows to work with both use cases.
Along I migrate the renovate config because it was needed.
> lvh: allow renovate to update kernel images instead of using main

- .github/renovate.json5
In the last patch, I changed the image name in the workflow comments but forgot to reflect that change in the config.
> renovate: rename correctly the lvh image name in config

- docs/content/en/docs/concepts/tracing-policy/example.md
Made minor edits to remove commas where they were not needed and fixed two small grammar changes.
> docs(tracing-policy) - Grammar and punctuation

- bpf/process/types/basic.h
See commits.
First commit fixes a couple of (pseudo?) bugs in the in-BPF rate limit code. It worked before, but it wasn't optimal.
Second commit adds support for IPv6 tuples so that rate limiting isn't just limited to IPv4.
> Add IPv6 support to BPF rate limit

- install/kubernetes/templates/operator_clusterrole.yaml
- install/kubernetes/templates/operator_deployment.yaml
- operator/cmd/common/common.go
- operator/cmd/root.go
- operator/cmd/serve/serve.go
- Refactor the CRD registration logic to a separate common package so that both the root and serve commands can call it.
- Mount tetragon-operator-config configmap for the operator deployment.
> operator: Call crd.RegisterCRDs() from operator deployment

- Makefile
- bpf/Makefile
- bpf/lib/common.h
The bpf_printk() helper is sometimes useful for debugging but we don't want to include it in production code since it makes programs incredibly slow. However, it's nice to have a consistent set of debugging messages we can lean on when it's time to investigate an issue on the BPF side.
This commit introduces a new DEBUG macro that is a NOP unless we set DEBUG=1 in the BPF Makefile, in which case it turns into a bpf_printk() call. This will enable us to over time build up and check in a suite of debugging statements for diagnosing problems during the development cycle without impeding performance in production contexts.
> bpf: add DEBUG() macro

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
According to the code comments the `--config-file` flag should have been removed in the v0.11 release, but it hasn't been. Let's remove it before the next release.
Ref #651
> cmd: Remove deprecated --config-file flag

- install/kubernetes/templates/operator_clusterrolebinding.yaml
There are other issues in the Helm chart that I'd like to fix but let's start small.
> helm: Don't create operator ClusterRoleBinding if podWatcher is disabled 

- .github/workflows/podinfo-test.yaml
- docs/content/en/docs/reference/helm-chart.md
- install/kubernetes/README.md
- install/kubernetes/templates/_container_tetragon.tpl
- install/kubernetes/templates/daemonset.yaml
- install/kubernetes/templates/operator_clusterrole.yaml
- install/kubernetes/templates/operator_clusterrolebinding.yaml
- install/kubernetes/templates/operator_configmap.yaml
- install/kubernetes/templates/operator_deployment.yaml
- install/kubernetes/templates/operator_serviceaccount.yaml
- install/kubernetes/values.yaml
- operator/cmd/serve/serve.go
- Remove tetragonOperator.enabled. Tetragon daemonset won't start if
this value is set to false.
- Rename podWatcher.enabled to tetragonOperator.podInfo.enabled to
better indicate this enables PodInfo CRD.
- Always run Tetragon operator deployment. We are planning to remove the
init container, so the operator needs to run unconditionally to create
CRDs.
- Rename skip-tetragon-pod-crd to skip-pod-info-crd in tetragon-operator
configmap. The operator is expecting skip-pod-info-crd flag.
- Don't start the PodInfo controller if tetragonOperator.podInfo.enabled
is set to false.
> operator: Clean up Helm values

- pkg/grpc/exec/exec.go
- pkg/metrics/errormetrics/errormetrics.go
- pkg/process/process.go
When caching process, report if pid and tid mismatch so we are aware of any bug that may affect BPF or userspace caching logic.
> metrics: report metric errors when caching pids

- docs/assets/scss/theme/content.scss
This PR fixes anchor links in docs. [Preview](https://deploy-preview-1516--tetragon.netlify.app/docs/getting-started/try-tetragon-linux/#start-tetragon)
> docs: fixes anchor links

- bpf/process/bpf_exit.c
- contrib/tester-progs/Makefile
- contrib/tester-progs/threads-exit.c
- pkg/sensors/base/base.go
- pkg/sensors/exec/exec_test.go
Djalal and Anastasios found another way we could race in exit
event hook, so we could receive multiple exit events with same
pid value.
Anastasios suggested to hook acct_process instead, which is
called only for the last task in the thread group.
The acct_process depends on CONFIG_BSD_PROCESS_ACCT config
option but it seems to be present on all supported kernels.
> tetragon: Hook exit sensor on acct_process

- pkg/sensors/tracing/generickprobe.go
If returnArg is empty, but return is true, the agent will crash with a sigsegv. This patch adds a check and returns an error.
Fixes: https://github.com/cilium/tetragon/issues/1490
```release-note:
fix segfault when return is specified without returnArg in a tracing policy
```
> tracing: check for empty returnArg

- cmd/tetragon/flags.go
- docs/content/en/docs/reference/helm-chart.md
- install/kubernetes/README.md
- install/kubernetes/templates/tetragon_configmap.yaml
- install/kubernetes/values.yaml
- pkg/metrics/config/initmetrics.go
- pkg/metrics/consts/consts.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/eventmetrics/eventmetrics_test.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/metrics/syscallmetrics/syscallmetrics.go
- pkg/option/config.go
Currently, metrics are all-or-nothing.
Certain labels may cause cardinality issues.
This patch introduces a new configuration option - MetricsLabelFilter. It is an allow-list for configuring namespace, workload, pod, and binary. Labels that utilize these fields will only add them if configured for it.
Fixes: #1037
> metrics: Add metrics label filter configuration

- Dockerfile.clang
I boldly assert that it's sufficient to specify the clang version by
using clang-15 package. This way we can pick up the latest security
release automatically. Otherwise this Dockerfile keeps breaking when
there is a new security release and the old package gets deleted.
Ref: https://github.com/cilium/tetragon/actions/runs/6355442579/job/17263533977#step:6:239
Ref: https://packages.ubuntu.com/jammy/clang-15
> Dockerfile.clang: Don't pin clang patch version

- .github/workflows/packages-e2e-tests.yaml
Docker Hub keeps rate limiting buildjet runners. Set fail-fast to false so that ubuntu-22.04 runners can finish the job, and then we can re-trigger the failed buildjet job later.
Ref: https://github.com/cilium/tetragon/actions/runs/6355863531/job/17264805755?pr=1530
Ref: https://github.com/actions/runner-images/issues/1445#issuecomment-714832439
> packages-e2e-tests: Don't fail fast

- .github/workflows/generated-files.yaml
- .github/workflows/gotests.yml
- .github/workflows/podinfo-test.yaml
- .github/workflows/run-e2e-tests.yaml
- .github/workflows/static-checks.yaml
- .github/workflows/vmtests.yml
> setup-go: Get Go version from go.mod

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
Use 'go install' to compile and install bom using the same Go version as
Tetragon to avoid getting this error:
invalid go version '1.21.1': must match format 1.23
> Use 'go install' to install bom

- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/kprobe_validation_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/sensors/tracing/uprobe_test.go
Several observer related cleanups.
> tetragon: Several observer related cleanups

- api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
- cmd/protoc-gen-go-tetragon/eventchecker/multichecker.go
- vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
Avoid using the word "failure" for pending checks to make it easier to locate actual failures in the log.
> event checker: Don't use the word "failure" for pending checks

- pkg/btf/validation.go
- pkg/sensors/tracing/kprobe_validation_test.go
fix crash in kprobe validation
> tetragon: fix crash in kprobe validation

- cmd/tetragon/main.go
- pkg/bench/bench.go
- pkg/observer/observer.go
- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/observer/sensor_manager.go
- pkg/sensors/base/base.go
- pkg/sensors/exec/cgroups_test.go
- pkg/sensors/exec/exec_test.go
- pkg/sensors/handler.go
- pkg/sensors/load.go
- pkg/sensors/manager.go
- pkg/sensors/test/lseek_test.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/kprobe_validation_test.go
- pkg/sensors/tracing/policyfilter_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/sensors/tracing/uprobe_test.go
- pkg/testutils/sensors/sensors.go
The change loading and unloading sensors to be on the sensors level,
so instead of removing separate programs, we remove complete sensors.
This has benefit of triggering sensors' unload hooks.
> tetragon: Remove sensors on exit not programs

- cmd/tetra/dump/dump.go
- cmd/tetragon/main.go
- contrib/localdev/bootstrap-kind-cluster.sh
- contrib/localdev/install-tetragon.sh
- contrib/localdev/kind-config.yaml
- docs/content/en/docs/reference/helm-chart.md
- install/kubernetes/README.md
- install/kubernetes/templates/daemonset.yaml
- install/kubernetes/values.yaml
- pkg/checkprocfs/checkprocfs.go
> check if procfs is the actual host procfs

- docs/content/en/docs/reference/helm-chart.md
- install/kubernetes/README.md
- install/kubernetes/templates/operator_deployment.yaml
- install/kubernetes/values.yaml
imagePullPolicy for the operator deployment can be now set in tetragonOperator.image.pullPolicy value, and defaults to IfNotPresent. Previously it defaulted to Always and couldn't be changed, what was problematic for example in local development.
```release-note
imagePullPolicy for the operator deployment can be set in tetragonOperator.image.pullPolicy Helm value and defaults to IfNotPresent.
```
> helm: Make operator imagePullPolicy configurable

- pkg/sensors/exec/procevents/proc_reader.go
In some cases, we try to get the docker of pid=0, which fails and produces the following warning:
time="2023-10-04T10:27:14Z" level=warning msg="Procfs execve event pods/ identifier error" error="open /procRoot/0/cgroup: no such file or directory"
This warning is confusing, so avoid it by not calling the relevant code for pid=0.
> proc_reader: avoid warning for pid=0

- .github/renovate.json5
Renovate is configured to ignore minor and major updated of k8s dependencies, because they need to be bumped together with Cilium. However, some k8s dependencies (`k8s.io/kube-openapi`) are not tagged with a version, but pinned by digest. Their updates are incompatible with other k8s deps, what's blocking updates of other Go dependencies, see #1372. This PR updates the Renovate config to ignore digest updates for k8s deps too.
> Renovate: Ignore digest updates for k8s dependencies

- cmd/tetragon/flags.go
- cmd/tetragon/main.go
- pkg/metrics/consts/consts.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/metrics/metricsconfig/initmetrics.go
- pkg/metrics/metricsconfig/labelfilter.go
- pkg/metrics/metricwithpod.go
- pkg/metrics/metricwithpod_test.go
- pkg/metrics/policyfiltermetrics/policyfiltermetrics.go
- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/policyfilter/rthooks/rthooks.go
- pkg/policyfilter/state.go
This PR contains a bunch of developer-facing breaking changes. See commits for details. I figured that it's worth doing them, as they will make future development easier and Tetragon is still before 1.0 release. But feel free to call me out if I shouldn't break package structure so freely :)
Initially I wanted also to merge the `pkg/metrics/consts` package into `pkg/metrics`, but I'm hitting import cycles. So I left this idea for now, I might revisit it when iterating on #1548 (although it doesn't seem that changes introduced there make it any simpler).
```release-note
Reorganize code under pkg/metrics. There are no functional changes, but it's a breaking change for developers.
```
> Misc changes to the packages structure under pkg/metrics

- go.mod
- operator/podinfo/podinfo_controller.go
- pkg/ftrace/ftrace.go
- pkg/metrics/metrics.go
Tetragon uses slices and maps functions from `golang.org/x/exp`. In Go 1.21 they
are a part of the Go standard library, so let's import them from there instead.
> Use Go stdlib instead of golang.org/x/exp

- .github/renovate.json5
- api/go.mod
- contrib/rthooks/tetragon-oci-hook/go.mod
- go.mod
- pkg/k8s/go.mod
PR #1536 broke "renovate update Go toolchain in a single PR" from #1259 because in the actual state it could only bump the go directive from minor versions, not bumping the patch needed by the workflows github actions reading that version.
From cilium/cilium@2f7e2f33659776a1c2adcf80111f69d6debdd850: According to [1] as of Go 1.21 we either need to specify the full toolchain version in the `go` directive or add a `toolchain` directive with the concrete toolchain version. Opt for the former and make sure it's kept up to date by renovate bot.
[1] golang/go#62278 (comment)
> renovate: fix renovate upgrade of Go toolchain

- .github/renovate.json5
This is a follow-up of https://github.com/cilium/tetragon/pull/1579 because https://github.com/cilium/tetragon/pull/1577 is broken.
This simplifies a49c4bc2ce6128800ca9b00825954f6b6d6bc0f4 that causes issues in the case of the new Go toolchain feature. It was manually installing a version off-by-one, like 1.21.2 for 1.21.3 present in the just updated go.mod and thus triggering the automatic download of the 1.21.3 toolchain. But in the renovate container env, GOSUMDB is set to off for some reason which blocks the download of the toolchain.
This simplifies the manual install by reading the go.mod file to determine the correct version, allowing to remove the bump of the number in the renovate config itself.
> renovate: fix the way we manually install Go inside the runner

- pkg/btf/validation.go
This fixes warnings for struct/pointer-based types (e.g. file) that the spec type doesn't align with the BPF-identified type.
This issue was previously identified (with a fix written) in https://github.com/cilium/tetragon/pull/850. However, that fix was never merged, and changes validation logic instead of just type identification.
> Reconstruct BTF types more accurately in getKernelType

- contrib/tester-progs/.gitignore
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/selectors/selectors.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/genericuprobe.go
- pkg/sensors/tracing/kprobe_test.go
This PR first introduces a test showing that we have a bug in the case of kprobe-multi, which uses matchArgs where both use maps to do string operations.
The problem is due to overriding string maps after processing each kprobe. To fix that we use shared maps for all selectors for all attach points in the case of kprobe-multi.
Non kprobe-multi cases and tracepoints/uprobes work exactly as before.
> bugfix: Use shared string maps in kprobe-multi

- bpf/lib/bpf_cgroup.h
- bpf/lib/process.h
- bpf/process/bpf_fork.c
- bpf/process/bpf_process_event.h
- bpf/process/policy_filter.h
- pkg/grpc/exec/exec.go
- pkg/sensors/exec/execvemap/execve.go
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/testutils/sensors/load.go
There is an issue with the cgroup tracker id (details can be found below). This issue causes policyfilter to misbehave. Furthermore, the original intention behind the cgroup tracker id was never implemented and so it currently serves no purpose. Its only user is the policyfilter.
This patch removes the cgroup tracker id, and, instead, computes the cgroup id at the time of the policyfilter check. For most common setups (cgroupv2) the overhead of doing so is negligible. Computing the cgroup id at the time of check is more reliable and also simplifies the code.
More details can be found below.
We have a namespaced policy installed that mathes connect() calls to 8.8.8.8, and execute the following on a pod in the same namespace:
`kubectl exec -it nonqos-demo -- curl 8.8.8.8`
We observe two …
> bpf: remove cgrpid_tracker

- cmd/tetragon/main.go
- pkg/observer/observer.go
- pkg/option/flags.go
- pkg/strutils/strutls.go
- pkg/strutils/strutls_test.go
Adding support to set and display rb sizes with size suffixes.
```
...
time="2023-10-13T20:18:51Z" level=info msg="Perf ring buffer size (bytes)" percpu=64M total=256M
...
time="2023-10-13T20:18:27Z" level=info msg="Perf ring buffer size (bytes)" percpu=16M total=64M
...
time="2023-10-13T20:17:42Z" level=info msg="Perf ring buffer events queue size (events)" size=976K
```
> tetragon: Allow to specify rb-* size options with size suffix

- pkg/eventhandler/eventhandler.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generickprobe_test.go
- pkg/sensors/tracing/generictracepoint.go
- pkg/sensors/tracing/policyhandler.go
- pkg/sensors/tracing/tracepoint_test.go
> custom event handling

- .github/renovate.json5
Let's agree on what it's reasonable to enable auto-merge! I propose:
```json5
{
"matchPackageNames": [
"go", // golang version directive upgrade in go.mod
],
"matchPackagePrefixes": [
"docker.io/library/", // official Docker images
"github.com/golang/", // Golang official org
"golang.org/x/", // Golang official experimental org
"google.golang.org/", // Google official repo for api/genproto/grpc/protobuf
"github.com/google/", // Google official github org
"k8s.io/", // Kubernetes official repo
"sigs.k8s.io/", // Kubernetes official SIG repo
],
"matchUpdateTypes": [
"patch",
"pin",
"pinDigest"
],
"automerge": true
},
```
> renovate: enable automerge for pin/pinDigest and patch 

- pkg/sensors/collection.go
- pkg/sensors/exec/cgroups_test.go
- pkg/sensors/handler.go
- pkg/sensors/load.go
- pkg/sensors/sensors.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/generickprobe_test.go
- pkg/testutils/sensors/testrun.go
Backport for #1562 
[upstream commit 5b315444c93b4db09aa8e95fc87c1ae7d30331af]
Commit 310846e44ca1830f8a3f4890a8338bb17a8a1fbb introduced a cleanup of the kprobe table entry on unload, which introduced some issues because unload is using when disabling sensors (that might be re-enabled later). Previous pre and post-hooks are still useful for resources management on unload.
The kprobe table entry is added on creation (not load) and then it must be cleaned up on deletion introducing the new sensor.Destroy() method. 'Destroy' expresses the idea that the sensor is not usable past this point and must be recreated to be loaded.
```release-note
Fixes a regression on enable/disable sensors that would prevent a sensor from being enabled.
```
> pkg/sensors: cleanup kprobe entry from table on destroy

- .github/workflows/build-images-ci.yml
We don't want to run `make version` in the context of a PR branch, so run it from master before checking out the PR branch.
> ci: minor refactor to build-images job

- api/go.mod
- api/vendor/modules.txt
We had `../../tetragon` as the go mod replacement for the api module. But what happens when the directory name of the git repo isn't `tetragon`? We should handle this case, so change it to `..` directly.
> vendor: fix cilium/tetragon replacement in api

- .github/workflows/veristat-compare.yaml
- .github/workflows/veristat.yaml
Fixes #892
We can restrict the run to PRs touching the `/bpf` folder.
Take a look at [this](https://github.com/cilium/tetragon/actions/runs/6561516593?pr=1610#summary-17821372896) and [that](https://github.com/cilium/tetragon/actions/runs/6561516598?pr=1610#summary-17821373428). More comparison examples [here](https://github.com/mtardy/veristat-action/actions/runs/6560133222#summary-17817130029).
> Add veristat in the CI

- docs/content/en/docs/getting-started/enforcement.md
- docs/content/en/docs/getting-started/execution.md
- docs/content/en/docs/getting-started/file-events.md
- docs/content/en/docs/getting-started/install-k8s.md
- docs/content/en/docs/getting-started/network.md
mostly small mix of fixes to docs quickstart.
> tetragon: doc cleanup and fixes

- install/kubernetes/templates/operator_deployment.yaml
Use tetragon-operator.selectorLabels instead of tetragon-operator.labels for selector labels. tetragon-operator.labels contains the helm.sh/chart label which differs among different versions (e.g. tetragon-1.0.0-rc.1). Helm upgrade fails because spec.selector field is immutable.
> helm: Fix selector labels for the operator deployment

- cmd/tetra/commands_linux.go
- cmd/tetra/dump/dump.go
- cmd/tetra/policyfilter/policyfilter.go
- pkg/policyfilter/map.go
Add a new policyfilter tetra command.  We add two sub-commands:
dump (which is the same as tetra dump policyfilter) and add to add
entries to the map. This is strictly for development/debugging, so we
mark the command hidden.
> tetra policyfilter command

- bpf/process/bpf_generic_kprobe.c
- cmd/tetragon/main.go
- examples/tracingpolicy/override-security.yaml
- pkg/bpf/detect.go
- pkg/observer/observertesthelper/observer_test_helper.go
- pkg/sensors/program/loader.go
- pkg/sensors/program/program.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/kprobe_test.go
Adding support to override 'security_' kernel functions with
fmod_ret override program.
The fmod_ret program is specific and differs to kprobe override
program in following ways:
1) it needs to be loaded with BTF ID of function it's attached to
2) it's invoked from BPF trampoline which is executed as direct call
after the ftrace trampoline is done
The 1) prevents us to have single program for multiple functions we
want to override, hence for this moment we allow to fmod_ret override
only in non kprobe_multi mode (--disable-kprobe-multi option).
This could be changed in future, but might imply some performance hits.
The 2) adds extra code paths execution compared to invoking kprobe override
program, so we are using fmod_ret override only for 'security_' functions
and kprobe override for …
> tetragon: Add support to override security_ functions

- .github/workflows/packages-e2e-tests.yaml
One of our CI jobs recently started relying on a repo secret to log into Docker Hub. This is not strictly necessary, but was done to make the job less flaky, since we were hitting rate limits on Docker's API server. However, this actually broke the workflow for external contributors, since forks do not have access to repo secrets.
It would be a significant security challenge to make this work for external contributors, so I'm leaving this as future work for now. Instead, let's fix the more immediate problem by simply only attempting a login when the PR comes from within the Cilium org.
> ci: fix CI for external contributors

- docs/content/en/docs/reference/helm-chart.md
- install/kubernetes/README.md
- install/kubernetes/templates/servicemonitor.yaml
- install/kubernetes/values.yaml
This commit was related to the service monitor scrape interval option.
I made a change to allow options to be injected via the values.yaml file.
fix: #1633
> helm: add service monitor scrape interval config

- docs/content/en/docs/reference/helm-chart.md
- docs/hugo.toml
- install/kubernetes/Chart.yaml
- install/kubernetes/README.md
- install/kubernetes/values.yaml
Fixes: https://github.com/cilium/tetragon/pull/1655 (typo, forgot the '.' after -rc)
> Prepare for v1.0.0-rc.2 release

- README.md
There are dead links in the Getting Started section of the README. 
This patch fixes this by:
1. Replacing all the dead links with the corresponding updated link in the documentation. 
Fixes: #1653
> doc: replace dead links in README.md

- .github/workflows/vmtests.yml
The action was timing out: taking around 11min to build, 2min to create the archive, upload was more than 6/7min thus triggering the 20min limit.
> vmtests: bump timeout and start multiple job for builds

- docs/content/en/docs/getting-started/install-k8s.md
- docs/content/en/docs/use-cases/linux-process-credentials/monitor-changes-at-kernel.md
- docs/content/en/docs/use-cases/linux-process-credentials/syscalls-monitoring.md
- docs/content/en/docs/use-cases/process-lifecycle/advanced-process-execution.md
- docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
- docs/hugo.toml
- docs/layouts/shortcodes/demo-app-url.html
> Update the Star Wars demo app URL

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
Cosign is broken in `main`, which means that our CI is also broken.
Try to fix it.
error:
```
Run sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b
Run #!/bin/bash
INFO: Downloading bootstrap version 'v1.13.1' of cosign to verify version to be installed...
https://storage.googleapis.com/cosign-releases/v1.13.1/cosign-linux-amd64
ERROR: Unable to validate cosign version: 'v1.13.1'
Error: Process completed with exit code 1.
```
> gh: update cosign installer

- docs/content/en/docs/overview/_index.md
- docs/layouts/partials/footer.html
> Minor docs changes for 1.0 messaging

- .github/lychee.toml
- .github/workflows/check-links-cron.yaml
- .github/workflows/check-links-pr.yaml
This commits adds a new config for the link checker lychee. This should reduce the noise from some false negatives or un-reliable websites. It also makes the config less different between PR and main branch checks.
> ci: check docs links fixes and configuration

- docs/content/en/docs/policy-library/observability/_index.md
The module link had a typo so it created a 404 fix it.
> tetragon: docs, fix modules policy library CRD link

- bpf/alignchecker/bpf_alignchecker.c
- bpf/cgroup/bpf_cgroup_events.h
- bpf/lib/msg_types.h
- bpf/lib/process.h
- bpf/process/bpf_execve_event.c
- bpf/process/bpf_exit.h
- bpf/process/bpf_fork.c
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_generic_uprobe.c
- bpf/process/bpf_loader.c
- bpf/process/data_event.h
- bpf/process/types/basic.h
- contrib/tester-progs/.gitignore
- pkg/alignchecker/alignchecker.go
- pkg/api/processapi/processapi.go
- pkg/metrics/eventmetrics/collector.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/metricsconfig/initmetrics.go
- pkg/sensors/base/base.go
Example:
```
$ curl localhost:2112/metrics 2> /dev/null | grep 'sent_events_total\|missed_events_total\|ringbuf_perf_event_lost_total\|ringbuf_queue_lost_total\|msg_op_total\|ringbuf_queue_received_total'
tetragon_missed_events_total{msg_op="13"} 73300
tetragon_missed_events_total{msg_op="23"} 28
tetragon_missed_events_total{msg_op="24"} 606
tetragon_missed_events_total{msg_op="5"} 20
tetragon_missed_events_total{msg_op="7"} 22
tetragon_msg_op_total{msg_op="13"} 4.268532e+06
tetragon_msg_op_total{msg_op="23"} 12444
tetragon_msg_op_total{msg_op="24"} 2110
tetragon_msg_op_total{msg_op="5"} 11908
tetragon_msg_op_total{msg_op="7"} 12447
tetragon_ringbuf_perf_event_lost_total 73976
tetragon_ringbuf_queue_lost_total 0
tetragon_ringbuf_queue_received_total 4.307441e+06
```
This PR adds an eBPF …
> Add a metric to provide missed events per type

- pkg/filters/fields.go
- pkg/grpc/exec/exec.go
- pkg/grpc/tracing/tracing.go
- pkg/metrics/eventcachemetrics/eventcachemetrics.go
- pkg/server/server.go
Commit 1 fixes the bug, commit 2 adds a nil check and a metric to catch if a similar situation happens in the future.
```release-note
Fix a segmentation fault related to filtering out pid information with field filters
```
> server: fix another segfault related to field filters

- docs/content/en/_index.html
- docs/hugo.toml
This PR updates the docs site to include the tetragon tagline in the title
> docs: update tetragon.io title

- bpf/alignchecker/bpf_alignchecker.c
- bpf/cgroup/bpf_cgroup_events.h
- bpf/lib/msg_types.h
- bpf/lib/process.h
- bpf/process/bpf_execve_event.c
- bpf/process/bpf_exit.h
- bpf/process/bpf_fork.c
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_retkprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_generic_uprobe.c
- bpf/process/bpf_loader.c
- bpf/process/data_event.h
- bpf/process/types/basic.h
- pkg/alignchecker/alignchecker.go
- pkg/api/processapi/processapi.go
- pkg/metrics/eventmetrics/collector.go
- pkg/metrics/eventmetrics/eventmetrics.go
- pkg/metrics/metricsconfig/initmetrics.go
- pkg/sensors/base/base.go
[upstream commit d5a7ee210e64885fb4cd7eb8a42ba368f132e24e]
Example:
$ curl localhost:2112/metrics 2> /dev/null | grep 'sent_events_total\|missed_events_total\|ringbuf_perf_event_lost_total\|ringbuf_queue_lost_total\|msg_op_total\|ringbuf_queue_received_total' tetragon_missed_events_total{msg_op="13"} 73300
tetragon_missed_events_total{msg_op="23"} 28
tetragon_missed_events_total{msg_op="24"} 606
tetragon_missed_events_total{msg_op="5"} 20
tetragon_missed_events_total{msg_op="7"} 22
tetragon_msg_op_total{msg_op="13"} 4.268532e+06
tetragon_msg_op_total{msg_op="23"} 12444
tetragon_msg_op_total{msg_op="24"} 2110
tetragon_msg_op_total{msg_op="5"} 11908
tetragon_msg_op_total{msg_op="7"} 12447
tetragon_ringbuf_perf_event_lost_total 73976
tetragon_ringbuf_queue_lost_total 0 …
> backports/v1.0: Add a metric to provide per-event missed events

- cmd/tetra/getevents/io_reader_client.go
- pkg/filters/fields.go
- pkg/filters/fields_test.go
- pkg/server/server.go
We need to deep copy the event here to avoid issues caused by filtering out information that is shared between events through the event cache (e.g. process info). This can cause segmentation faults and other nasty bugs. Avoid all that by doing a deep copy here before filtering. This is not pretty or great for performance, but it at least works as a stopgap until we're able to refactor things so that it's no longer necessary.
```release-note
Fix a number of segmentation faults related to field filters.
```
> filters/fields: do a deep copy before filtering

- docs/content/en/docs/reference/daemon-flags.md
- examples/configuration/tetragon.yaml
- pkg/option/flags.go
The commit is to add the missing metrics-label-filter flag.
fix: #1667
> pkg/option: add metrics-label-filter flags

- pkg/bench/bpfstats.go
- pkg/bench/trace.go
Turning on BPF stats collection causes overhead, so it makes sense to turn it off at the end of benchmarking. On newer kernels we can use ebpf.EnableStats as a safer interface.
> pkg/bench: disable BPF stats collection at the end of execution

- .github/renovate.json5
- api/go.mod
- api/vendor/modules.txt
- contrib/rthooks/tetragon-oci-hook/go.mod
- contrib/rthooks/tetragon-oci-hook/vendor/modules.txt
- go.mod
- pkg/k8s/go.mod
- vendor/modules.txt
Port of https://github.com/cilium/cilium/pull/28686. We are seeing issues in the CI as well https://github.com/cilium/tetragon/actions/runs/6853112156/job/18633190187?pr=1747.
> Avoid requiring the latest Go toolchain patch version to build

- .github/renovate.json5
I finally understood that the allowedVersion was broken, restricting <1.22. Docker does not have version semantics because of tags so it was using a fallback to npm and thus filtering out any version with the -alpine suffix. Explaining the missing updates on stable 1.0.
> renovate: fix allowed version for Go upgrades in 1.0 branch

- cmd/tetra/common/client.go
- cmd/tetra/common/flags.go
- cmd/tetra/getevents/getevents.go
- cmd/tetra/main.go
That PR is the one that changes viper.BindPFlags.
Fixed #1108
> Issue 1108/replace the use of viper.bind flags with variables binding

- cmd/tetragon/main.go
There has been a longstanding bug where if Tetragon encounters an error inside of tetragonExecute, the process will hang instead of exiting as expected. When looking at the goroutine stacktrace dump provided by the runtime on SIGABRT, we can immediately see the problem. The main thread is stuck on a channel send inside of observer.RemoveSensors(). Further investigation reveals that the channel is never opened because InitSensorManager() is waiting on the waitChan to be closed, which does not happen until we have loaded the base sensor.
To fix this issue, we simply need to move the defer call into observer.RemoveSensors() to after we indicate that InitSensorManager() is cleared to run. This patch does exactly that. Since we haven't loaded any BPF progs yet until the base sensor has been …
> tetragon: fix hang on error in tetragonExecute

- operator/podinfo/podinfo_controller.go
Sometimes creating a podinfo fails with AlreadyExists error even though the previous call to get the podinfo returned NotFound because of a timing issue. Requeue without returning the error when this happens to prevent the controller from logging an unnecessary error.
> podinfo: Handle an expected error gracefully

- docs/content/en/docs/faq/_index.md
Updated 'Can I run Tetragon on Mac computers?' FAQ as newer Docker Desktop versions now come with BTF support and CONFIG_DEBUG_INFO_BTF enabled.
> doc: Clarified Docker Desktop on MacOS FAQ

- bpf/process/string_maps.h
- pkg/selectors/selectors.go
- pkg/sensors/tracing/selectors.go
The file prefix limit was originally 256 characters. When the code was converted to use LMP TRIE maps, the limit was set to 128 characters.
This commit changes the prefix limit from 128 to 256 characters.
```release-note
Increases the character limit for prefix matches from 128 to 256.
```
> String: Increase prefix size from 128 to 256 chars

- bpf/process/bpf_generic_retkprobe.c
- bpf/process/types/basic.h
- pkg/selectors/kernel.go
- pkg/selectors/kernel_test.go
- pkg/selectors/selectors.go
- pkg/sensors/program/loader.go
- pkg/sensors/tracing/generickprobe.go
- pkg/sensors/tracing/kprobe_test.go
Assorted fixes as preparation for return kprobe filtering support.
Sending self contained fixes first, so the final PR is not too big.
> tetragon: Assorted fixes

- pkg/btf/validation.go
Kprobe arguments of type "sock" and "skb" are valid but fail BTF validation because the function prototypes report "struct sock *" and "struct sk_buff *" types.
This commit adds validation to remove warnings that these types in the policy don't match the types in the function prototypes.
```release-note
Adds validation for sock and skb types
```
> Arg validation: Add mappings for sock and skb

- bpf/process/bpf_exit.c
- contrib/tester-progs/Makefile
- contrib/tester-progs/threads-exit.c
- pkg/sensors/base/base.go
- pkg/sensors/exec/exec_test.go
backport of https://github.com/cilium/tetragon/pull/1509
> tetragon: another exit fix

- .github/workflows/build-clang-image.yaml
- .github/workflows/build-images-ci.yml
- .github/workflows/build-images-releases.yml
CI is broken on 0.9, due to cosign.
This will fail, so we need to merge to check that it actually works.
Backports of:
* https://github.com/cilium/tetragon/commit/20bd368b10d1614140ec5237b7600e0d9aaf7eb7
* https://github.com/cilium/tetragon/commit/3fff37afdfc7927f21143166b5513317cc7bcbb7
See the same for 0.10: https://github.com/cilium/tetragon/pull/1694
> [v0.9] update cosign

- bpf/lib/generic.h
- bpf/process/bpf_generic_kprobe.c
- bpf/process/bpf_generic_tracepoint.c
- bpf/process/bpf_generic_uprobe.c
- bpf/process/generic_calls.h
- bpf/process/types/basic.h
- pkg/sensors/tracing/kprobe_test.go
- pkg/sensors/tracing/tracepoint_test.go
- pkg/sensors/tracing/uprobe_test.go
There's no need for having separate programs for generic_kprobe_filter_arg* and 
generic_kprobe_process_event* function, we can have just one instance called
recursively by tail jump.
b4:
```
14
32411: kprobe  name generic_kprobe_process_event3  tag 75d7c429743eb535  gpl
32412: kprobe  name generic_kprobe_filter_arg1  tag 9279987579ba117c  gpl
32413: kprobe  name generic_kprobe_process_event2  tag bf3fbe433d43e592  gpl
32414: kprobe  name generic_kprobe_output  tag 9e772542ab44369a  gpl
32415: kprobe  name generic_kprobe_filter_arg3  tag dbdb3573c7575198  gpl
32416: kprobe  name generic_kprobe_filter_arg4  tag c23b95feefd79e4b  gpl
32417: kprobe  name generic_kprobe_actions  tag dc8cb05c20800b5e  gpl
32418: kprobe  name generic_kprobe_process_filter  tag e003f29c78cce2e5  gpl
32419: …
```
> tetragon: get rid of some programs

- contrib/tester-progs/fork-tester.c
- pkg/sensors/exec/fork_test.go
Connecting to 8.8.8.8, might cause the test to fail. Instead, just print a message.
There was a `TestFork` failure on `main`: https://github.com/cilium/tetragon/actions/runs/7008794565/job/19066214778#step:6:1164
> ❌	pkg.sensors.exec.TestFork						9.772s	(1m25.943s)
Looking at the logs, the problem was that the connect operation failed:
>     cmd.go:100: stdout>: parent: (pid:1607, ppid:1601) starts
>     cmd.go:100: stdout>: child 1 (pid:1608) exits
>     cmd.go:100: stdout>: parent: (pid:1607, ppid:1601) starts
>     cmd.go:100: stdout>: child 2 (pid:1609, ppid:1) connecting to 8.8.8.8:53
>     cmd.go:100: stdout>: parent: (pid:1607, ppid:1601) starts
>     cmd.go:100: stderr>: connect: Network is unreachable
>     cmd.go:100: stdout>: parent: (pid:1607) child (1608) exited with: 0 …
> fork-tester: remove connect to 8.8.8.8

- go.mod
- go.sum
- tests/e2e/runners/runners.go
- vendor/github.com/go-logr/logr/README.md
- vendor/github.com/go-logr/logr/SECURITY.md
- vendor/github.com/go-logr/logr/funcr/funcr.go
- vendor/github.com/go-logr/logr/logr.go
- vendor/github.com/go-logr/logr/slogr/sloghandler.go
- vendor/github.com/go-logr/logr/slogr/slogr.go
- vendor/github.com/go-logr/logr/slogr/slogsink.go
- vendor/k8s.io/klog/v2/.golangci.yaml
- vendor/k8s.io/klog/v2/internal/buffer/buffer.go
- vendor/k8s.io/klog/v2/internal/clock/clock.go
- vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
- vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go
- vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go
- vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go
- vendor/k8s.io/klog/v2/internal/verbosity/verbosity.go
- vendor/k8s.io/klog/v2/k8s_references_slog.go
- vendor/k8s.io/klog/v2/klog.go
- vendor/k8s.io/klog/v2/klog_file.go
- vendor/k8s.io/klog/v2/klogr.go
- vendor/k8s.io/klog/v2/klogr_slog.go
- vendor/k8s.io/klog/v2/textlogger/options.go
- vendor/k8s.io/klog/v2/textlogger/textlogger.go
- vendor/k8s.io/klog/v2/textlogger/textlogger_slog.go
- vendor/modules.txt
In e2e tests we can see the following error:
```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed. Detected at:
>  goroutine 1 [running]:
>  runtime/debug.Stack()
>  	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x5e
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>  	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:60 +0xcd
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc00027f740, {0x1ef22f6, 0x14})
>  	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:147 +0x45
>  github.com/go-logr/logr.Logger.WithName({{0x2208298, 0xc00027f740}, 0x0}, …
```
> e2e: Fix logger in e2e tests
